### ISSUE TITLE
swith doc infra to hugo or docusaurus

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1006]
what about switch from sphinx to [hugo](https://gohugo.io/getting-started/usage/) or [docusaurus](https://docusaurus.io/)?

cc @Xunzhuo @danehans @arkodg

**Comment by arkodg** [comment]
@zirain curious why ?

**Comment by zirain** [comment]
IMO, they are wildely used in cncf community, AND have a lot of modern themes, with better visuals.
