### ISSUE TITLE
Add Status Sub Resource to EnvoyProxy API

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#1007]
Currently, EnvoyProxyStatus is not implemented. It would be helpful if status surfaced the following:
- A list of resources that reference the EnvoyProxy.
- An "Accepted" status condition indicating that the resource contains valid params and is being managed by an instance of EG.
- Others?

**Comment by arkodg** [comment]
currently Gateway API provides a `InvalidParameters` reason https://github.com/kubernetes-sigs/gateway-api/blob/e1f652e00d85060ffc76154127e0280c447dc5a3/apis/v1beta1/gatewayclass_types.go#L172 to surface any issues with ParametersRef (EnvoyProxy in this case). We are currently setting `InvalidParameters` reason (with `Accepted=False`) when the `EnvoyProxy` config is invalid.
@AliceProxy curious if you can think of any case when the status would be required specifically on `EnvoyProxy`

**Comment by arkodg** [comment]
closing for now, since the validation of `EnvoyProxy` reflects in the `GatewayClass` status
