### ISSUE TITLE
Investigate Gateway/HTTPRouteObservedGenerationBump Test Flakes

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#1016]
HTTPRouteObservedGenerationBump seems to be flaky.

xref: https://github.com/envoyproxy/gateway/pull/1014#issuecomment-1423668703

**Comment by arkodg** [comment]
@Xunzhuo I tagged you because I thought these were related to the `GatewayClassObservedGenerationBump` Test, but they are tied to `Gateway` and `HTTPRoute`, my bad, unassigning you

**Comment by AliceProxy** [comment]
Should be able to un-skip these with the release of Gateway API 0.6.2 next week.
