### ISSUE TITLE
Decision: Should Kube and Non Kube Be Two Separate Builds

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#103]
This issue comes from @youngnick comments in 6/9/21 [community meeting](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing):

"Should we consider building two version of EG, one for Kubernetes and one for non-Kubernetes? (With code reuse between them, of course). I’m writing a doc about what the install experience should look like for both options, and I’m worried that trying to serve both with one thing may make them too complex."

**Comment by shaneutt** [comment]
As someone who's interested in this project and would like to contribute I have honestly been left wishing for this kind of distinction (in fact I was almost kinda hoping that these efforts would even be separate repositories, perhaps sharing some libraries, but that's taking it to another level I suppose). I don't have any need of the non-kube use case (at least for the moment) so the thought had occurred to me that separations of these concerns would help at least reduce noise and complexity.

**Comment by arkodg** [comment]
hey @shaneutt supporting all [environments](https://github.com/envoyproxy/gateway/blob/main/GOALS.md#all-environments) is a core goal of the project with an initial focus on kube. The outcome of this issue should help add more clarity on internal k8s specific tasks and components as well as end user UX and arch.

from an end user intent perspective, the user could either specify the platform they can running on via the BootstrapConfig as suggested [here](https://github.com/envoyproxy/gateway/pull/95#discussion_r890674588) or `envoy-gateway` can have distinct subcommands - `kubernetes` & `local/stand-alone/docker` . 
from a project perspective would prefer if everything lives in the same repo initially to speed up development.

**Comment by shaneutt** [comment]
> hey @shaneutt supporting all [environments](https://github.com/envoyproxy/gateway/blob/main/GOALS.md#all-environments) is a core goal of the project with an initial focus on kube. The outcome of this issue should help add more clarity on internal k8s specific tasks and components as well as end user UX and arch.
> 
> from an end user intent perspective, the user could either specify the platform they can running on via the BootstrapConfig as suggested [here](https://github.com/envoyproxy/gateway/pull/95#discussion_r890674588) or `envoy-gateway` can have distinct subcommands - `kubernetes` & `local/stand-alone/docker` . from a project perspective would prefer if everything lives in the same repo initially to speed up development.

:+1:

**Comment by danehans** [comment]
I created a [brainstorming doc](https://docs.google.com/document/d/1bZAlFzuq1ivqUu_VlboaC_2XqZSoYgAOM6qdOh04kZg/edit?usp=sharing) to allow more freeform discussion on this topic. As we did in https://github.com/envoyproxy/gateway/issues/60, a summary and any agreed-upon outcomes should be surfaced in this issue before it is closed.

cc: @alexgervais @LukeShu @arkodg @youngnick @skriss

**Comment by danehans** [comment]
closing due to #111 that provides details of the agreed-upon EG design.

**Comment by danehans** [comment]
Note: An EG release will include a Docker image and a bin artifact.
