### ISSUE TITLE
Dynamically setup containerPorts in proxy infrastructure

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1032]
*Description*:
The proxy infrastructure is currently statically creating containerPorts for the managed envoy proxy deployment
https://github.com/envoyproxy/gateway/blob/17d325d3ff59e04a045fff49a1edaafe3f633314/internal/infrastructure/kubernetes/proxy_deployment.go#L193

These should be dynamically set based on the IR
https://github.com/envoyproxy/gateway/blob/17d325d3ff59e04a045fff49a1edaafe3f633314/internal/ir/infra.go#L55

This is a cosmetic bug, containerPort is purely informational 

relates to https://github.com/envoyproxy/gateway/pull/997#discussion_r1103029693

**Comment by ShawnHXH** [comment]
Hi, is this task still available? I'm willing to take it.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/1157
