### ISSUE TITLE
xds grpc disconnect

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1038]
*Environment*:

gateway: lastest from main branch
envoy: 1.24-latest

*Logs*:
>Include the access logs and the Envoy logs.
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/2174082/218451068-3a95a4db-bee1-4e53-9f61-1999cf1d5aef.png">

**Comment by arkodg** [comment]
@qicz do you seen this issue with `gateway-dev:latest` and `envoy:1.25-latest` ?

**Comment by qicz** [comment]
> @qicz do you seen this issue with `gateway-dev:latest` and `envoy:1.25-latest` ?

I will watch this, feedback soon.

**Comment by qicz** [comment]
I have further verified this issue and may need to adjust the timeout of the grpc connection.

```yaml
  - connect_timeout: 60s
    load_assignment:
      cluster_name: xds_cluster
```

I set the `conection_time` to 60s, maybe my environment is slower. 

suggestion: adjusting to 10s.  you can assign this task to me. @arkodg

**Comment by arkodg** [comment]
thanks, static xds cluster https://github.com/envoyproxy/gateway/blob/2c57f3d3adbf4ce9f64126233bea323300929d67/internal/infrastructure/kubernetes/bootstrap.yaml.tpl#L32 probably should match dynamic cluster settings
https://github.com/envoyproxy/gateway/blob/2c57f3d3adbf4ce9f64126233bea323300929d67/internal/xds/translator/cluster.go#L34 (5s)

**Comment by zirain** [comment]
this can be part of https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoyproxy_types.go

**Comment by qicz** [comment]
> thanks, static xds cluster
> 
> https://github.com/envoyproxy/gateway/blob/2c57f3d3adbf4ce9f64126233bea323300929d67/internal/infrastructure/kubernetes/bootstrap.yaml.tpl#L32
> 
> probably should match dynamic cluster settings
> https://github.com/envoyproxy/gateway/blob/2c57f3d3adbf4ce9f64126233bea323300929d67/internal/xds/translator/cluster.go#L34
> 
> (5s)

 the dynamic cluster settings may need the k8s gateway api support or use the envoyproxy api provides the global cluster timeout. the static xds cluster adjust the `.tp` file only.

**Comment by qicz** [comment]
> this can be part of https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoyproxy_types.go

bingo

**Comment by qicz** [comment]
fixed by #1058, close it.

**Comment by zirain** [comment]
wrong PR number, updated.

**Comment by qicz** [comment]
> 

thanks

**Comment by qicz** [comment]
> wrong PR number, updated.

thanks @zirain
