### ISSUE TITLE
Add GH workflow for `egctl`

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1045]
*Description*:

We should add `egctl` to build and test workflow, and release/(latest-release) workflow.

Subtasks:
- [x] toolings
- [x] build and test
- [x] release
- [x] latest-release
- [x] get-egctl.sh and hosted on [gateway.envoyproxy.io](https://gateway.envoyproxy.io/)

**Comment by AliceProxy** [comment]
IMO default install to `/usr/local/bin` should be ok assuming it is easy and obvious although I also really like the idea of installing to the local directory and then allowing the user to move the binary to their chosen location.

**Comment by arkodg** [comment]
hey @Xunzhuo can we get this into 0.4.0-rc1 ?

**Comment by Xunzhuo** [comment]
@arkodg sure :)
