### ISSUE TITLE
Decision: Shipping artifact structure

### ISSUE THREAD

**Issue by youngnick** [envoyproxy/gateway#105]
As part of discussing #103, the community discussed how we should ship Envoy Gateway, in order to meet the "run on Kubernetes or not" part of the design. Actual decision records are ~bolded~ italicized.

*We agreed that the code paths for these two options should be largely separate because they are so different.*

We discussed whether that meant we should produce separate binaries or subcommands of a single binary, and *we agreed that we will ship subcommands of a single binary for the different operating modes*.

Then we discussed how we will actually ship this single binary with subcommands, and decided that *we will ship both container and standalone binary for the single binary.*

These decisions are not final until this issue has received maintainer votes in the form of comments or reacts, and community feedback one way or the other.

**Comment by arkodg** [comment]
+1 for shipping a single binary, a container image packaged with the single binary, and representing the entry points for `kube` and `local` as subcommands within that same binary

**Comment by danehans** [comment]
> We discussed whether that meant we should produce separate binaries or subcommands of a single binary, and we agreed that we will ship subcommands of a single binary for the different operating modes.

+1

> Then we discussed how we will actually ship this single binary with subcommands, and decided that we will ship both container and standalone binary for the single binary.

+1

**Comment by danehans** [comment]
xref https://github.com/envoyproxy/gateway/issues/106#issuecomment-1152619680 for capturing decisions in the design doc.

**Comment by alexgervais** [comment]
> We agreed that the code paths for these two options should be largely separate because they are so different.

+1

> We discussed whether that meant we should produce separate binaries or subcommands of a single binary, and we agreed that we will ship subcommands of a single binary for the different operating modes.

+1

> Then we discussed how we will actually ship this single binary with subcommands, and decided that we will ship both container and standalone binary for the single binary.

+1

**Comment by danehans** [comment]
@youngnick, et al. can you help me better understand the benefits of using separate subcommands to support different operating environments instead of using a CLI flag/config field? This is how I envisioned running EG on different platforms:

#### Run EG on Kube:
Using the `platform` flag:
```sh
$ kubectl apply -f ./my/eg/deployment.yaml
$ cat ./my/eg/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg
  namespace: eg-system
spec:
...
      containers:
      - command: ["envoy-gateway"]
        args:
        - start
        - --platform=Kubernetes
```

Using the `platform` field of the config file:
```sh
$ kubectl apply -f ./my/eg/deployment.yaml
$ cat ./my/eg/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg
  namespace: eg-system
spec:
...
      containers:
      - args:
        - start
        - --config-path=/my/eg/config.yaml
        command: ["envoy-gateway"]
        volumeMounts:
          - name: eg-config
            mountPath: /my/eg
            readOnly: true
...
      volumes:
        - name: eg-config
          configMap:
            name: eg
            items:
            - key: config.yaml
              path: config.yaml

$ cat ./my/eg/config.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BootstrapConfig
platform: Kubernetes
kubernetes:
  ...
...
```
The EG `start` subcommand will run the k8s controllers and any other Kube-specific functionality since `platform=Kubernetes`.

#### Run EG on Non-Kube:
Using the `platform` flag:
```
$ envoy-gateway start --platform=Linux
```

Using the `config-path` flag:
```
$ envoy-gateway start --config-path=./my/eg/config.yaml
$ cat ./my/eg/config.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BootstrapConfig
platform: Linux
Linux:
  ...
```

This seems to align with https://github.com/envoyproxy/gateway/issues/107.

**Comment by youngnick** [comment]
I think that what we will need to build is a little more nuanced than that, see https://github.com/envoyproxy/gateway/issues/107#issuecomment-1154744635 for a little more detail there.

To answer the question, I'm worried about code separation and complexity of testing. Subcommands enforce a strong separation all they way up to the `main.go` of the parent command, so it will be harder to have abstractions or code leak across.

Additionally, I'm worried about how complex the testing regime will be for all of the provider options you describe above. At the very least, we'll need to confirm that the provider/mode selection code works with a set of tests of `main.go` and other high-level things, which I've found tricky to do in the past.

All of these are not super strong arguments, just convenience. But I think that there's definitely something to talk about with respect to what constitutes a `platform` or `provider`.

**Comment by danehans** [comment]
#111 fixes this issue. #95 provides additional supporting details of the config API.

> *We agreed that the code paths for these two options should be largely separate because they are so different.*

We agreed that EG will have a single entrypoint. An operator can be considered in the future for managing EG. As #111 states, EG (control plane) will manage the Envoy proxy fleet (data plane).

> We discussed whether that meant we should produce separate binaries or subcommands of a single binary, and *we agreed that we will ship subcommands of a single binary for the different operating modes*.

This N/A since  EG will have a single command entrypoint, i.e. `start`. 

> Then we discussed how we will actually ship this single binary with subcommands, and decided that *we will ship both container and standalone binary for the single binary.*

EG release artifacts will consist of a Docker image and a bin.
