### ISSUE TITLE
`ext_authz`  Authentication

### ISSUE THREAD

**Issue by Xervon** [envoyproxy/gateway#1059]
*Description*:
Are there any plans of supporting `ext_authz` request authentication?

**Comment by arkodg** [comment]
@Xervon the project supports a native [Authn API](https://gateway.envoyproxy.io/v0.3.0/user/authn.html) and plans on allowing advanced users to configure envoy filters such as `ext_authz` as well, https://github.com/envoyproxy/gateway/issues/24 is the tracking issue that should address this use case, which should hopefully be part of the 0.4.0 release in April 2023

**Comment by Xervon** [comment]
Thanks for the quick answer. I guess I should have clarified that I had already seen both of those. I was wondering if there were already plans to extend the `AuthenticationFilter` with support for `ext_authz` (similar to #881 as far as I understand that one). And if there are no plans regarding this, what would have to be done if I wanted to take a stab at this?

**Comment by arkodg** [comment]
@Xervon imho [ext_authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto) is something an advanced user would be aware of, so would prefer taking the #24 route, understanding the shortcomings once implemented and used, and if it still required, expose the fields of the underlying envoy filter into the higher level authn API

**Comment by arkodg** [comment]
thanks for sharing all the references for other projects @Xervon , the [original design doc](https://docs.google.com/document/d/1TlQjBy1utEwgrxE_HVT4-EHpVJ51hgnfMuAh0Q_uNoE/edit#heading=h.h6z8hgjmkv0g) did account for `ext_authz`, hoping other @envoyproxy/gateway-maintainers can chime in

**Comment by arkodg** [comment]
speaking to many users at Kubecon, who would like to integrate with an external authz system like OPA 
this can now be added into https://gateway.envoyproxy.io/latest/api/extension_types/#securitypolicy

**Comment by akhenakh** [comment]
Agree it's a very common need to point to an ext_authz_filter filter to talk to an authorization server, resorting to patching xDS for a basic need is not optimal
