### ISSUE TITLE
Decision: Deployment models can differ based on platform

### ISSUE THREAD

**Issue by youngnick** [envoyproxy/gateway#106]
During discussion in the community meeting of #103 and #105, we discussed whether the different platforms could or should have different deployment models, and came to an agreement that yes, they should.

*We decided that different platforms (Kube or non-Kube) can and should have different deployment models*.

This decision is not final until this issue has received maintainer votes in the form of comments or reacts, and community feedback one way or the other.

This issue will probably help resolving #97 as well.

**Comment by arkodg** [comment]
+1, `kube` and `local` platforms can have different deployment models to optimize for that platform

**Comment by danehans** [comment]
> We decided that different platforms (Kube or non-Kube) can and should have different deployment models.

+1 with the caveat of removing "should" and using "can".  Specifically, I would like to see:

"Envoy Gateway can run on different platforms, e.g. Kubernetes, Virtual Machines, etc. The deployment model for Envoy Gateway may differ based on the platform it runs on."

**Comment by danehans** [comment]
@youngnick for this issue and others that require a decision, I think it's a good idea to capture the decision beyond just closing the issue. What do you think about updating the design doc with the decisions?

**Comment by youngnick** [comment]
Yes, either updating the design doc, or having a series of decision documents would be great. Probably, updating the design doc is better, so that there's a single source of truth.

**Comment by danehans** [comment]
@youngnick I'm closing now that #111 has merged. Feel free to reopen if needed.
