### ISSUE TITLE
How to run Envoy proxy in a different namespace than Envoy Gateway?

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1067]
*Description*:
Is it possible to run Envoy proxy in a different namespace than Envoy Gateway?
Envoy Gateway runs Envoy proxy in the same namespace, by default in envoy-gateway-system

**Comment by arkodg** [comment]
hi @rkosyk it should be possible by changing/templatizing the defaults set in the kustomize dir today
https://github.com/envoyproxy/gateway/tree/main/internal/provider/kubernetes/config
this will hopefully we a top level user facing customizable field once we support [helm charts](https://github.com/envoyproxy/gateway/pull/651)

**Comment by rkosyk** [comment]
@arkodg 
Sorry, maybe my question was not clear enough.
I have envoy-gateway pod in the "envoy-gateway-system" namespace.
I have created EnvoyProxy and Gateway custom resources in the "default" namespace and want the envoy proxy pod to be run in the "default" namespace. But the envoy proxy pod (envoy-default-envoy-64656661-7d4f8c9dd5-86zxh) is run in the "envoy-gateway-system" namespace.
<img width="919" alt="image" src="https://user-images.githubusercontent.com/11256736/220558343-0e1a3bc9-2368-4612-a930-3a256e76824f.png">

Is it possible to make the envoy proxy pod run in the "default" namespace, or any other specific namespace, not the same as where envoy-gateway is run?

**Comment by arkodg** [comment]
thanks for the clarification @rkosyk , as of now, Envoy Gateway is limiting itself to the `envoy-gateway-system` namespace to create new resources, it might not have access to create resources in other namespaces
curious why is such a use case interesting for you

**Comment by zirain** [comment]
multi-tenancy?

**Comment by rkosyk** [comment]
> multi-tenancy?

Exactly

**Comment by arkodg** [comment]
> @arkodg what about put `envoy-proxy` in the namespace of `Gateway` CR?

this would mean the users would need to give EG permission to create deployments in all namespaces, which might be excessive from a user perspective

**Comment by rkosyk** [comment]
Let me explain our use case.
We have N tenants deployed into the separate namespaces.
Among other resources, every tenant has its own MongoDB and Rabbitmq clusters that are managed with MongoDB and Rabbitmq operators accordingly. We need to expose MongoDB and Rabbitmq ports outside of Kubernetes cluster to give access to external users. To do this we would like to use Envoy-proxy (Gateway) and TCPRoute in every tenant's namespace and one GatewayClass. Envoy-gateway is in its own separate namespace - "envoy-gateway-system".
It would be nice to have for envoy-proxy a similar approach to what we have with Mongodb and Rabbitmq - resources of one tenant are placed in one namespace.

![image](https://user-images.githubusercontent.com/11256736/221114404-6e24fba5-cfbb-4095-8ee3-5ad246428cd0.png)

**Comment by arkodg** [comment]
thanks for illustrating your use case @rkosyk 
hoping others from @envoyproxy/gateway-maintainers can chime in

**Comment by zirain** [comment]
FYI, istio allowed create ingress in all namespaces, https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by rkosyk** [comment]
Thanks @arkodg @zirain 
I tried Istio Gateway previously. It has almost everything that is needed for us except one thing - potentially we will want to integrate gateway proxy pods into our Linkerd service mesh and it looks impossible to do, Istio proxy pod does not allow injecting Linkerd sidecar container.
By the way, there is a similar problem with envoy-proxy pod at the moment but the reason is different - envoy-proxy has automountServiceAccountToken=false,
https://github.com/envoyproxy/gateway/blob/f735041d6ce31e104bf00f9a96f47d327634a923/internal/infrastructure/kubernetes/deployment.go#L156
Linkerd requires this parameter to be "true" to inject its sidecar proxy container successfully.

**Comment by arkodg** [comment]
> 

I know @kflynn was able to run EG on Linkerd, does something need to be changed regarding the highlighted field

**Comment by arkodg** [comment]
this issue boils down to what static permissions we are okay EG runs with
1) Only create resources in a single namespace
2) Create resources in all namespaces

We could add incorporate (2) using some explicit knob at the GatewayClass level, and ensure the helm charts deploy the right permissions during install

**Comment by kflynn** [comment]
@rkosyk What version of Linkerd and Kubernetes are you using? I was able to get Envoy Gateway to behave nicely with Linkerd 2.12 (.4 FTR) by adding the `linkerd.io/inject` annotation to the `envoy-gateway-system` namespace.

(Obviously, that doesn't solve your tenancy issue; I'm just talking about Linkerd here.)

**Comment by rkosyk** [comment]
@kflynn  Kubernetes 1.22, Linkerd 2.11.2
There is no problem with Envoy-gateway pod and Linkerd.
The problem is with Envoy-proxy pod that is provisioned dynamically with Envoy-gateway.
Envoy-proxy pod has automountServiceAccountToken="false". Linkerd requires this parameter to be "true" 
https://github.com/envoyproxy/gateway/blob/f735041d6ce31e104bf00f9a96f47d327634a923/internal/infrastructure/kubernetes/deployment.go#L156
If I manually patch automountServiceAccountToken to "true" in Envoy-proxy deployment, after the Envoy-proxy pod restart everything works as expected.
Would be nice to have this parameter configurable or "true" by default.

**Comment by kflynn** [comment]
@rkosyk Hmmm, Linkerd 2.12.4 is current, and I think it should work for you as-is -- can you give that a try?

**Comment by rkosyk** [comment]
@kflynn Yes, I have tested it and can confirm that it works with Linked 2.12.4
It looks like automountServiceAccountToken="true" is not a hard requirement starting from Linkerd 2.12.0
https://github.com/linkerd/website/pull/1547
Thanks
