### ISSUE TITLE
Support GRPCRoute regex type match

### ISSUE THREAD

**Issue by sbko** [envoyproxy/gateway#1071]
*Description*:

support for https://gateway-api.sigs.k8s.io/geps/gep-1016/#type-regularexpression is blocked by https://github.com/kubernetes-sigs/gateway-api/issues/1746

add regex support [here](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/route.go#L391) after upstream issue is resolved.

**Comment by arkodg** [comment]
should be ready to be worked on since https://github.com/kubernetes-sigs/gateway-api/issues/1746 has been fixed and brought into this project as part of the v0.6.2 bump

**Comment by shawnh2** [comment]
hi, I'm willing to take this, assign me please

**Comment by Xunzhuo** [comment]
Close in favor of: https://github.com/envoyproxy/gateway/pull/1240
