### ISSUE TITLE
gateway oomkilled

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1076]
*Environment*:
>Include the environment like gateway version, envoy version and so on.
gateway: latest(main)
envoyproxy: 1.25

*Logs*:

![image](https://user-images.githubusercontent.com/2174082/221460226-df3997b2-248b-43b4-9a9a-effd32284c89.png)

**Comment by qicz** [comment]
pls assign to me @arkodg

**Comment by qicz** [comment]
I think the default limit memory can update to 512m

![image](https://user-images.githubusercontent.com/2174082/221461040-06f2e339-d2ac-4480-a2a1-88c5bd910625.png)

**Comment by zirain** [comment]
this will be configurable after https://github.com/envoyproxy/gateway/issues/1072.

**Comment by Xunzhuo** [comment]
@qicz good catch, default limit is a bit low here, I think.

**Comment by qicz** [comment]
> @qicz good catch, default limit is a bit low here, I think.

yes, but #1072 will fix this. I will close this issue
