### ISSUE TITLE
Ensure static xds-cluster has same field values as dynamic cluster

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1078]
*Description*:
Avoid drift by adding a test to unmarshal the xds-cluster in bootstrap [template file ](https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/bootstrap.yaml.tpl)and ensuring it matches the output of [dynamic cluster creation](https://github.com/envoyproxy/gateway/blob/ec762438d54b63a9cbbc3678bc4e514306beac2d/internal/xds/translator/cluster.go#L22)

**Comment by cnvergence** [comment]
I will take a look

**Comment by arkodg** [comment]
thanks @cnvergence, heads up, the bootstrap package has been recently moved into https://github.com/envoyproxy/gateway/tree/main/internal/xds/bootstrap
