### ISSUE TITLE
support auto release charts and host eg charts on GitHub Repo

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1090]
*Description*:

1. support auto release eg charts
2. host Helm Charts via GitHub Pages and Releases

subtask of #1072.

Blocker:

chart-releaser-action needs to use github pages via branch not github action. Our site for now is using github action. We need to refactor our versioned docs to transfer into `gh-pages` branch, instead of github actions.

[optional *Relevant Links*:]

Use: https://github.com/helm/chart-releaser-action
Ref: https://github.com/helm/chart-releaser

**Comment by arkodg** [comment]
hey @Xunzhuo can you highlight the pros and cons of hosting in GH vs something like Docker Hub which supports OCI Artifacts now

**Comment by zirain** [comment]
+1 for using OCI if possible.

**Comment by Xunzhuo** [comment]
I think using DockerHub is a good option too. I am very sure of the differences between them.

Let us hear some ideas from @AliceProxy.

**Comment by kflynn** [comment]
+1 for DockerHub, after reading over the Docker doc above. 🙂

**Comment by LanceEa** [comment]
Adding to the +1 on DockerHub for charts.
