### ISSUE TITLE
What's the boundary of this project?

### ISSUE THREAD

**Issue by RRobot-lm** [envoyproxy/gateway#1096]
*Description*:
1. Does the project only contain the official Envoy's feature? For example, will it ship extra Lua/Wasm/Go plugins?
2. It's said that other gateways can build upon this project. Is it still the target? If I develop a gateway based on it, which feature should I put upstream, and which feature should I keep along?

**Comment by zirain** [comment]
please checkout https://github.com/envoyproxy/gateway/blob/main/docs/latest/design/system-design.md

**Comment by Xunzhuo** [comment]
Hi @RRobot-lm 

> * Does the project only contain the official Envoy's feature? For example, will it ship extra Lua/Wasm/Go plugins?

We will providing some ways to extend EG like something like EnvoyFilter in Istio, which allows end users to use more super custom abilities of envoyproxy.

> It's said that other gateways can build upon this project. Is it still the target? If I develop a gateway based on it, which feature should I put upstream, and which feature should I keep along?

We discussed Extending EG in https://github.com/envoyproxy/gateway/pull/1074.
It is a feature we are driven for the next release. Welcome to comment if you have any ideas.

**Comment by arkodg** [comment]
here are some more links to help understand the scope of project
* [Goals](https://github.com/envoyproxy/gateway/blob/main/GOALS.md)
* [Matt Klien's blog](https://medium.com/envoyproxy/introducing-envoy-gateway-ad385cc59532)

**Comment by RRobot-lm** [comment]
Thanks!
