### ISSUE TITLE
Internal error occurred: failed calling webhook

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#1097]
*Description*:
> When applying file gateway.yaml as bellow, it has error:
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---

have error: Error from server (InternalError): error when creating "gateway.yaml": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s": context deadline exceeded

Please help me fix it. Thank you

I apply it on AWS EKS Cluster

**Comment by zirain** [comment]
how did you install GatewayAPI/EG ?

**Comment by quyenhoang96** [comment]
> how did you install GatewayAPI/EG ?

I use helm to install as bellow:
https://github.com/envoyproxy/gateway/tree/main/charts/eg

In file gatewayapi-crds.yaml have configuration about admission as:
ValidatingWebhookConfiguration gateway-api-admission, gateway-api-webhook-server ...
If If I delete them all, then I will apply GatewayClass, and it works.

Is there any problem with gateway-api-admission when installing on EKS ?

**Comment by qicz** [comment]
@quyenhoang96 just the admission server does not start， try apply again when admission server started at gateway-system namespace.

**Comment by quyenhoang96** [comment]
> 

I checked the admission server. It works very well.

**Comment by zirain** [comment]
do you have network issue from ControlPlane nodes to worker nodes?

**Comment by zirain** [comment]
In most cases, it may be a security group problem.

**Comment by quyenhoang96** [comment]
> do you have network issue from ControlPlane nodes to worker nodes?

Network between ControlPlane nodes and  worker nodes work well.

**Comment by quyenhoang96** [comment]
> hi @quyenhoang96 , if this issue is related to AWS, can we close this ?

For now, I still can't fix it, so I don't know if this bug belongs to Amazon Web Service (AWS) or not.

**Comment by arkodg** [comment]
closing this issue for now, please reopen if you see this issue again
