### ISSUE TITLE
Create ROADMAP.md

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#11]
A document about the project roadmap helps users understand
* WHAT - future scope and deliverable for the project
* WHEN - timelines for delivering these milestones / also helps with GH project visibility
* HOW - procedure for users to request & upvote new items into the roadmap

**Comment by youngnick** [comment]
Big +1 from me for using milestones, but I think @danehans' rough outline is pretty good. I think that @skriss point about conformance being a moving target is a good one too, so we should mark a Gateway API release as the first target, and work towards that. (Perhaps v0.4.3, the current release, or v0.5.0, due soon, that will move some resources to v1beta1.)
