### ISSUE TITLE
proposal: LoadbalancingPolicy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1105]
*Description*:
Allow the user to specify Load Balancing policies to load balance requests from the gateway to the upstream.

[optional *Relevant Links*:]
Relates to https://github.com/kubernetes-sigs/gateway-api/issues/1778

Currently the requests are being load balanced at an L3 / kube-proxy level since requests are being sent to the Cluster IP of the Service. We need to route to the endpoints directly with https://github.com/envoyproxy/gateway/issues/35

**Comment by qicz** [comment]
should we provide the global locadbalancing policy in envoyproxy API?

**Comment by arkodg** [comment]
+1 to adding a global policy in `EnvoyProxy`, it probably needs to be done in a way that it can be overridden per Backend
