### ISSUE TITLE
Allow the user to not have to specify all K8s resources in `egctl x translate --to=xds`

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1122]
*Description*:
Today the user must specify all K8s resources when translating from `gateway-api` to `xds`. Support an argument such as `--add-missing-resources` where the user only specifies the Gateway API resources and `egctl` adds the rest (Namespaces, Services, Secrets) as dummy resources.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by muyuan0** [comment]
I would like to split this task into three steps and finish them one by one:
- [ ] provide default Namespace
- [ ] provide default GatewayClass and Gateway
- [ ] provide default Service

**Comment by arkodg** [comment]
hey @muyuan0 thanks for implementing the first part for `namespaces`. 
curious if you are still looking into issue ? if not, will add the `help-wanted` label so another contributor can help out.

**Comment by muyuan0** [comment]
Sorry for missing this! I have been super busy recently, so I can't give any time to implement the default service. But I will find some time to do it this weekend. Or maybe the next week.

**Comment by arkodg** [comment]
no rush @muyuan0, thanks for the comment
