### ISSUE TITLE
CI is failing due to missing Helm chart repository name

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1139]
*Description*:

The last few PRs have been failing since the GHA is unable to push the helm chart into docker HUB
e.g. https://github.com/envoyproxy/gateway/actions/runs/4401947795/jobs/7708816453

Raising this issue to solve the following
- [x] Get CI to be green again https://github.com/envoyproxy/gateway/pull/1140
- [x] Decide on the chart name (`envoy-gateway` vs `envoy-gateway-chart`) since this decides the repo name within Docker Hub https://github.com/envoyproxy/gateway/issues/1151
- [x] Request access from a `envoyproxy` admin to create above repo in Docker Hub

**Comment by zirain** [comment]
+1 for `envoyproxy/envoy-gateway` or `envoyproxy-charts/gateway`
