### ISSUE TITLE
Improve addXdsCluster internal method signature

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1141]
*Description*:

Relates to https://github.com/envoyproxy/gateway/pull/1118#discussion_r1133013212

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yang20150702** [comment]
Hi, I want to fix this issue. pls assign me.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/1174
