### ISSUE TITLE
Support GRPCRoute and HTTPRoute on the same Gateway listener

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1142]
*Description*:

* Do we need to support GRPCRoute and HTTPRoute attached the same Gateway Listener ?

If we do we need to refactor the [xDS HCM Logic](https://github.com/envoyproxy/gateway/blob/f219904808675376a5b1ba445cd08b01a36b3a73/internal/xds/translator/listener.go#L99) that changes the codec type as well as includes web socket options based on whether the listener is linked to HTTP2 or not

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by muyuan0** [comment]
> Do we need to support GRPCRoute and HTTPRoute attached the same Gateway Listener ?

There are a few real-world cases of this. For example, etcd will expose port 2379 for both gRPC and HTTP API.

**Comment by arkodg** [comment]
thanks for pointing that out @muyuan0, can you also link this to the etcd docs as well

**Comment by arkodg** [comment]
great thanks for sharing these links @muyuan0, we can prioritize this issue once this becomes more relevant for users

**Comment by quyenhoang96** [comment]
> 

Do you mean itself detect protocol to upgrade ?

**Comment by muyuan0** [comment]
Yes. Envoy will do auto detection if the codeType is AUTO, see

https://github.com/envoyproxy/envoy/blob/6c702f45fadf4abd2f24605e3d9e81c748b13f85/source/common/http/conn_manager_utility.cc#L56-L76
