### ISSUE TITLE
egctl cannot retrieve endpoint config

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1147]
```bash
kubectl exec -n envoy-gateway-system envoy-gateway-57b7d8bb9c-kkhvs -it -- egctl c proxy e envoy-default-eg-63636f73-78f9b7cfdd-676kd
error: unknown resourceType endpoint
command terminated with exit code 1
```

**Comment by zirain** [comment]
IIRC, there's no endpoint before https://github.com/envoyproxy/gateway/pull/1118?

**Comment by qicz** [comment]
> IIRC, there's no endpoint before #1118?

#1118 merged version

**Comment by zirain** [comment]
@qicz Are you interested in finishing this？

**Comment by qicz** [comment]
> @qicz Are you interested in finishing this？

did It @zirain #1148
