### ISSUE TITLE
Support Distinct Match Type for Source IP based Ratelimiting 

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1150]
*Description*:
* Today [the SourceIP client selector](https://github.com/envoyproxy/gateway/blob/29619902a75ecc8bd454d82727f22a955eda1d83/api/v1alpha1/ratelimitfilter_types.go#L107) allows the user to specify a IP subnet. All IPs within the subnet are treated as the same client / part of the same rate limit bucket i.e. if `SourceIP` is `192.168.1.0/24` then requests from `192.168.1.1` and `192.168.1.2` count towards the same rate limit.

Another use case is, user might want to ratelimit all IPs equally within an IP Subnet i.e. if `SourceIP` is `192.168.1.0/24` then `192.168.1.1` and `192.168.1.2` should be allowed X requests/unit individually. Suggest using a match type called `Distinct` to represent this. Without this feature a user has to specify multiple entries such as `192.168.1.1/32` and `192.168.1.2/32` which can be tedious and hard to manage when these IPs are in the order of hundreds or thousands.

This feature _might_ need upstream work to
* Send Client Address (and not masked address) as a descriptor value from the Rate Limit filter to Rate Limit Service
* Pass a unique key from Rate Limit Filter
* No new work will be needed in `envoyproxy/ratelimit` since it already supports [this](https://github.com/envoyproxy/ratelimit#example-3)

**Comment by zirain** [comment]
IIRC, the result `remote_addres` is IP string without CIDR.

**Comment by arkodg** [comment]
@zirain , the top level descriptor
```
  - key: masked_remote_address //catch all the source IPs inside a CIDR
    value: 192.168.0.0/16
```
is added to separate this match from another RL match

so on the envoy side both https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-remoteaddress & https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-maskedremoteaddress need to be set

I think this is genius @zhaohuabing 🚀

**Comment by zhaohuabing** [comment]
> @zirain , the top level descriptor
> ```
>   - key: masked_remote_address //catch all the source IPs inside a CIDR
>     value: 192.168.0.0/16
> ```
> is added to separate this match from another RL match
> 
> so on the envoy side both https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-remoteaddress & https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-maskedremoteaddress need to be set
> 
> I think this is genius @zhaohuabing 🚀 
> 
>     

Thanks @arkodg for confirming this. I'll go with this implementation then.

**Comment by zhaohuabing** [comment]
To support both CIDR and distinct IP I consider deprecate SourceIP and introduce a new RemoteAddress property in RemoteAddress.
```go
type RateLimitSelectCondition struct {
	Headers []HeaderMatch `json:"headers,omitempty"`

	// @deprecated: Use RemoteAddress instead.
	SourceIP *string `json:"sourceIP,omitempty"`

	// RemoteAddress is the IP CIDR that represents the range of Source IP Addresses of the client.
	RemoteAddress *RemoteAddress `json:"remoteAddress,omitempty"`
}

type RemoteAddressMatchType string

const (
	RemoteAddressMatchCIDR     RemoteAddressMatchType = "CIDR"
	RemoteAddressMatchDistinct RemoteAddressMatchType = "Distinct"
)

type RemoteAddress struct {
	Type    *RemoteAddressMatchType `json:"type"`
	Address string                  `json:"address"`
}
```

**Comment by zirain** [comment]
thanks @zhaohuabing , verify this via https://github.com/zirain/playground/commit/588a84198bbce804fc731082f9d03ca9e88f3e2a
