### ISSUE TITLE
decision: Helm Docker Repository name and Chart versioning scheme

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1151]
*Description*:
1. It would be ideal if the Application Image and Application Helm Chart could live in the same repository https://hub.docker.com/r/envoyproxy/gateway/tags but since you cannot have two artifacts in the same repository with the same tag (version is the tag), we will need to create a separate repository to store Helm Charts.
Brainstorming some names - `gateway-helm` , `gateway-chart`
Here's an example https://hub.docker.com/r/apache/skywalking-helm

2. The Helm Chart version/tag must be semVar based, so we need a way to represent the latest (bleeding edge) Helm Chart version that is linked to the latest release https://github.com/envoyproxy/gateway/releases/tag/latest
Suggesting `v0.0.0-latest` here, this is used in other projects such as Apache SkyWalking.

3. Do we need another repo similar to [envoyproxy/gateway-dev](https://hub.docker.com/r/envoyproxy/gateway-dev/tags) to save Helm Charts tied to every merged commit ?

**Comment by arkodg** [comment]
ptal @zirain @Xunzhuo @skriss @youngnick @AliceProxy

**Comment by arkodg** [comment]
@AliceProxy @kflynn and I discussed this issue in the community meeting today and this is our preference
1) Use a separate repo called `gateway-helm` to store Helm charts
2) Use `v0.0.0-latest` as the Chart version for the `latest` release
3) There is no strong use case to create a `gateway-dev-helm` repo at this moment

**Comment by zirain** [comment]
copy that, No objection.

**Comment by Xunzhuo** [comment]
+1 for this. Need someone to create the repo for us.

**Comment by haq204** [comment]
Also +1

**Comment by arkodg** [comment]
great thanks for the comments everyone, looks like we have majority consensus
@mattklein123 can you please help create a repository in Docker Hub called `gateway-helm` under `envoyproxy`, TIA !

**Comment by Xunzhuo** [comment]
@mattklein123 told me that @phlax has all the creds for docker, etc.

Maybe phlax can help create one repo called `gateway-helm` for us?

cc @phlax

**Comment by youngnick** [comment]
+1 from me.

**Comment by arkodg** [comment]
thanks @Xunzhuo for driving this change
Here is the repo https://hub.docker.com/r/envoyproxy/gateway-helm/tags
