### ISSUE TITLE
Open `Always suggest updating pull request branches`

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1154]
maybe turn on `Always suggest updating pull request branches` ?

![image](https://user-images.githubusercontent.com/4354057/225192646-7cc6cbd7-972c-4571-acf1-e670bb501c8a.png)

cc @envoyproxy/gateway-maintainers

**Comment by Xunzhuo** [comment]
ref: https://github.com/envoyproxy/gateway/pull/1143

**Comment by arkodg** [comment]
will this rerun CI, we essentially need a CI rerun so `make test` can detect any config drifts

**Comment by Xunzhuo** [comment]
It will, see https://github.com/envoyproxy/gateway/pull/1164

**Comment by zirain** [comment]
it's opened.
