### ISSUE TITLE
Public Slack Channel

### ISSUE THREAD

**Issue by bryanasdev000** [envoyproxy/gateway#116]
Hey folks, I hope everyone is well.

I was wondering if the project already have a public Slack channel, I did a quick search but all links redir to https://envoyproxy.slack.com/archives/C03E6NHLESV , which blocks emails that are not in lfyt or linuxfoundation domains.

Thanks in advanced.

**Comment by alexgervais** [comment]
Hi @bryanasdev000, nice catch!
Going to https://envoyproxy.io/slack should allow you to register. Does it work for you?
Let me know, and I'll update the README accordingly.

**Comment by bryanasdev000** [comment]
> Hi @bryanasdev000, nice catch! Going to https://envoyproxy.io/slack should allow you to register. Does it work for you? Let me know, and I'll update the README accordingly.

Nope, I get "The email address must match one of the domains listed below. Please try another email." 

Which is lyft.com and linuxfoundation.org.

**Comment by bryanasdev000** [comment]
![Screenshot from 2022-06-21 11-06-09](https://user-images.githubusercontent.com/53131727/174819645-d594ef1f-8981-4b0f-a11c-cf3953b08b41.png)

**Comment by alexgervais** [comment]
@lizan, @danehans, would you be able to help? Something looks odd with Envoy's Slack configuration.

**Comment by lizan** [comment]
cc @mattklein123

I don't have admin access to Slack, seems the register link in Envoy repo doesn't allow outside registration either.

**Comment by mattklein123** [comment]
The link probably expired. I will fix it. Such a PITA.

**Comment by mattklein123** [comment]
Should be fixed soon. https://github.com/envoyproxy/envoy-website/pull/259

**Comment by bryanasdev000** [comment]
Sorry for the delay, can confirm that's working, thanks!
