### ISSUE TITLE
EnvoyGateway v1.0 release readiness criteria

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1160]
*Description*:
Tracks everything needed for Envoy Gateway to be reach `v1.0` giving users confidence to run it in production
- [ ] Majority API Gateway features implemented and exposed using a stable API. Requires upstream Gateway APIs to be graduated (tracked with https://github.com/kubernetes-sigs/gateway-api/discussions/1801)
  - [x] Conformance tests passing for all v1.0 Gateway API upstream features
  - [ ] E2E tests written and passing for all extended features
  - [x] 60%-80% code coverage (from unit tests)
- [ ] Day 2 operations in place
  - [ ]  Install
  - [ ]  Observability
    - [ ] Review logging to make sure we messaging is clear and logs are set to the appropriate verbosity level 
  - [ ]  Triage
  - [ ]  Upgrade
  - [ ]  Customizing Envoy Deployments
- [ ] Meets some criteria of performance when used at scale
- [ ] Document everything

When - TBD

**Comment by arkodg** [comment]
@envoyproxy/gateway-maintainers please feel free to edit this description

**Comment by Xunzhuo** [comment]
Close by https://github.com/envoyproxy/gateway/issues/2249
