### ISSUE TITLE
Why do requests need to add a request header named Host

### ISSUE THREAD

**Issue by ZhangSetSail** [envoyproxy/gateway#1170]
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/101104760/225843077-24e9ed32-a504-4541-8dfd-eb5d6fd97cde.png">

**Comment by arkodg** [comment]
Hi @ZhangSetSail please refer to the RFC for HTTP/1.1 https://www.rfc-editor.org/rfc/rfc2616#page-128
It is a required header
