### ISSUE TITLE
set envoy proxy & ratelimit container resource requests

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1196]
set the envoy proxy container the minimum amount of computing resources required.

- [x] envoy proxy container resources settings
- [x] ratelimit container resources settings
- [x] resources settings api docs
- [x] envoy proxy setting user face docs by #1203 
- [x] ratelimit  setting user face docs

**Comment by arkodg** [comment]
@qicz is this issue related to changing the default resource settings https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/proxy_deployment.go
or adding an API to change the defaults https://github.com/envoyproxy/gateway/blob/c459f655f971f3c3ef986f1fe2a16ee65a906f2c/api/config/v1alpha1/envoyproxy_types.go#L82 ?
(both are valid and needed :) )

**Comment by qicz** [comment]
> 

@arkodg yes, I would like to do this, pls assign to me

**Comment by qicz** [comment]
> @qicz is this issue related to changing the default resource settings https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/proxy_deployment.go or adding an API to change the defaults
> 
> https://github.com/envoyproxy/gateway/blob/c459f655f971f3c3ef986f1fe2a16ee65a906f2c/api/config/v1alpha1/envoyproxy_types.go#L82
> 
> ?
> (both are valid and needed :) )

@arkodg  yes, I would like to do this, pls assign to me

**Comment by qicz** [comment]
support by #1197 #1218
