### ISSUE TITLE
Enable GatewayWithAttachedRoutes test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1201]
*Description*:
As part of bumping to v0.6.2 https://github.com/envoyproxy/gateway/pull/1153, we had to disable `GatewayWithAttachedRoutes` which checks for the `ListenerConditionAccepted` to be set https://github.com/kubernetes-sigs/gateway-api/blob/3e2ea60a2b04f3d4ce380f2520dd6027ea678f7d/conformance/tests/gateway-with-attached-routes.go#L66

We need to ensure we always set this condition here https://github.com/envoyproxy/gateway/blob/a4afb8cc8dc08ebf0110f5ce11a747d8cb647614/internal/gatewayapi/validate.go#L151
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by muyuan0** [comment]
> _Description_: As part of bumping to v0.6.2 #1153, we had to disable `GatewayWithAttachedRoutes` which checks for the `ListenerConditionAccepted` to be set [kubernetes-sigs/gateway-api@`3e2ea60`/conformance/tests/gateway-with-attached-routes.go#L66](https://github.com/kubernetes-sigs/gateway-api/blob/3e2ea60a2b04f3d4ce380f2520dd6027ea678f7d/conformance/tests/gateway-with-attached-routes.go#L66)
> 
> We need to ensure we always set this condition here
> 
> https://github.com/envoyproxy/gateway/blob/a4afb8cc8dc08ebf0110f5ce11a747d8cb647614/internal/gatewayapi/validate.go#L151
> 
> [optional _Relevant Links_:]
> 
> > Any extra documentation required to understand the issue.

I found that changing the condition at https://github.com/envoyproxy/gateway/blob/a4afb8cc8dc08ebf0110f5ce11a747d8cb647614/internal/gatewayapi/validate.go#L151
will break some other conformance tests like GatewaySecretReferenceGrantSpecific.

Maybe we should set the condition only after there is a route attached to the given listener.

**Comment by arkodg** [comment]
can you elaborate @muyuan0 ?
I see some code in the next few lines https://github.com/envoyproxy/gateway/blob/a4afb8cc8dc08ebf0110f5ce11a747d8cb647614/internal/gatewayapi/validate.go#L158 that is looking at a specific index rather than a search which might be causing some issue ?

**Comment by muyuan0** [comment]
Some tests like https://github.com/kubernetes-sigs/gateway-api/blob/67fa2e560b3737921c1b2a6962f36d1b8e920e5d/conformance/tests/gateway-secret-reference-grant-all-in-namespace.go#L51 will expect the programmed condition is set.

Maybe you mean setting both the Accepted and the Programmed at the same time and I misunderstood?

**Comment by arkodg** [comment]
yes both Accepted and Programmed need to set at the same time for the good case, with different `message` strings.
Accepted` message can be `Listener has been successfully translated` and `Programmed` message can be `Sending translated listener configuration to the data plane`
