### ISSUE TITLE
Support Managed Envoy Service Type

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1202]
support `ClusterIP` for cluster-internal proxy: just for cluster-internal
support `Loadbalancer` for edge proxy: can work for internal with eg svc and for internet directly
but doesn't support `NodePort`

ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

- [x] provide custom proxy service spec API 
- [x] API doc
- [x] user face doc

**Comment by qicz** [comment]
pls assign to me

**Comment by arkodg** [comment]
@qicz can you elaborate on which specific fields in the Envoy Service you would like to customize and why ?

**Comment by qicz** [comment]
> @qicz can you elaborate on which specific fields in the Envoy Service you would like to customize and why ?

clusterip or loadbalancer

**Comment by arkodg** [comment]
+1 for `ClusterIP` and `Loadbalancer` `type` https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types. Can you please update the GH issue to be specific about this feature .

sidenote - I dont think we can support `Nodeport` unless we are allowed to specify `ip:port` in Status.Addresses. https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.GatewayAddress
would this be okay @youngnick  ?

**Comment by qicz** [comment]
> +1 for `ClusterIP` and `Loadbalancer` `type` https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types. Can you please update the GH issue to be specific about this feature .
> 
> sidenote - I dont think we can support `Nodeport` unless we are allowed to specify `ip:port` in Status.Addresses. https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.GatewayAddress would this be okay @youngnick ?

@arkodg updated, can you review again?

**Comment by arkodg** [comment]
went ahead and also updated title, thanks in advance for working on this @qicz !

**Comment by zirain** [comment]
should EG provide `ClusterIP` and `Loadbalancer` and same time? or multi `Loadbalancer` service?

one case is provide internal lb and internet lb at the same time.

**Comment by qicz** [comment]
> should EG provide `ClusterIP` and `Loadbalancer` and same time? or multi `Loadbalancer` service?
> 
> one case is provide internal lb and internet lb at the same time.

imo, the two type don't have to exist at the same time. 
clusterip, just for internal
Loadbalancer can work for internal with eg svc  and for internet diretly

**Comment by arkodg** [comment]
> should EG provide `ClusterIP` and `Loadbalancer` and same time? or multi `Loadbalancer` service?
> 
> one case is provide internal lb and internet lb at the same time.

can't the client connect directly using Loadbalancer IP or Service FQDN ?

**Comment by zirain** [comment]
I'm saying multi services for one `EnvoyProxy`.

**Comment by arkodg** [comment]
> I'm saying multi services for one `EnvoyProxy`.

curious why, isn't `Loadbalancer` a superset of `ClusterIP` ?

**Comment by zirain** [comment]
Sorry, my previous information may have been a bit misleading.
So the key point is will `EG` allow multi services for one Gateway/EnvoyProxy?

**Comment by arkodg** [comment]
> Sorry, my previous information may have been a bit misleading.
> So the key point is will `EG` allow multi services for one Gateway/EnvoyProxy?

can you please clarify with an example

**Comment by zirain** [comment]
@arkodg I'm thinking make `EnvoyService` to slice 

https://github.com/envoyproxy/gateway/blob/384577334dea2c0ba28800643a2b94fea4eed244/api/config/v1alpha1/envoyproxy_types.go#L95

**Comment by arkodg** [comment]
> @arkodg I'm thinking make `EnvoyService` to slice
> 
> https://github.com/envoyproxy/gateway/blob/384577334dea2c0ba28800643a2b94fea4eed244/api/config/v1alpha1/envoyproxy_types.go#L95

can you share why  ?

**Comment by zirain** [comment]
@qicz can you add user face doc?

**Comment by qicz** [comment]
> @qicz can you add user face doc?

#1203 did this, thanks @Xunzhuo

**Comment by qicz** [comment]
supported by #1205， #1286
