### ISSUE TITLE
`TestServeXdsServerListenFailed` panics when `make test`

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1204]
I am using darwin/arm64, running make test will panic like:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/48784001/227139943-124d2c74-9919-4435-90ee-3164d8e7a66a.png">

**Comment by muyuan0** [comment]
Maybe it is relative to https://github.com/agiledragon/gomonkey/issues/10.
Would you try the solution at https://github.com/eisenxp/macos-golink-wrapper?

**Comment by Xunzhuo** [comment]
I think adding this testcase brought less meaning but increases the UX of local development, we cannot let every contributor to set it up like this way.

cc @arkodg

**Comment by zirain** [comment]
I will try on `darwin/amd64` later.

**Comment by zirain** [comment]
> I will try on `darwin/amd64` later.

passed on `darwin/amd64`

**Comment by Xunzhuo** [comment]
Looks like only not work in darwin arm64.

**Comment by muyuan0** [comment]
Let me find a way to test it without gomonkey.
