### ISSUE TITLE
move config testcases into yaml testdata files

### ISSUE THREAD

**Issue by haq204** [envoyproxy/gateway#1206]
*Description*:
https://github.com/envoyproxy/gateway/blob/main/internal/envoygateway/config/config_test.go#L27 is starting to get a little unwieldy.

Let's split them into yaml testdata files similar to what we do with other tests

**Comment by arkodg** [comment]
+1 to YAML 🧑‍🌾 ing

**Comment by zirain** [comment]
@haq204 are you still working on this?

**Comment by haq204** [comment]
@zirain I haven't looked at this in a while. unassigning myself

**Comment by yuluo-yx** [comment]
@shawnh2 https://github.com/envoyproxy/gateway/blob/main/internal/envoygateway/config/config.go

In this code, is there a function to decode the yml configuration? I didn't find it. Can you help me? I saw the function in Decoder to decode EnvoyGateway configuration.

**Comment by shawnh2** [comment]
hi @yuluo-yx, it seems this issue has been solved via #2024. so close this one now.

thanks for looking into it, you can try other issues that with `good-first-issue` or `help-wanted`.

**Comment by yuluo-yx** [comment]
> hi @yuluo-yx, since #2024 has been merged, it seems we don't face this issue anymore. so close this one now.
> 
> thanks for looking into this, you can try other issues that with `good-first-issue` or `help-wanted` tag.

got it.
