### ISSUE TITLE
Support Envoy Proxy automountServiceAccountToken configuration

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1210]
*Description*:
>Add support to configure automountServiceAccountToken for Proxy Pods

This parameter is set to false at the moment:
https://github.com/envoyproxy/gateway/blob/384577334dea2c0ba28800643a2b94fea4eed244/internal/infrastructure/kubernetes/proxy_deployment.go#L86

In our case, we need the possibility to set automountServiceAccountToken to true in order to integrate Envoy Proxy with Linkerd service mesh.
automountServiceAccountToken=true is the hard requirement of older versions of Linkerd (< 2.12.0). We need Envoy Proxy works with older Linkerd versions as well.

**Comment by arkodg** [comment]
mounting the service account token can be used to abuse the entire data plane so im a -1 on this.
since newer versions of Linkerd already support this, imo this is not needed now, but prefer to keep this issue opened to gather more use cases

**Comment by arkodg** [comment]
closing as not planned
