### ISSUE TITLE
Support Envoy Proxy container securityContext configuration

### ISSUE THREAD

**Issue by rkosyk** [envoyproxy/gateway#1211]
*Description*:
>Be able to set security context on the Envoy Proxy container

[*Relevant Links*:]
>https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container

**Comment by qicz** [comment]
if  @rkosyk  does not pick this, please assign it to me

**Comment by qicz** [comment]
> something to start thinking about, should the config be
> 
> ```
> podSecurityContext:
> .....
> containerSecurityContext:
> ....
> ```
> 
> or
> 
> ```
> pod:
>   annotations:
>   securityContext:
> container: 
>   securityContext
> ```

I think the second option is good, I will do it with this.

**Comment by zirain** [comment]
+1 for 
```
pod:
  annotations:
  securityContext:
container: 
  securityContext
```

**Comment by zirain** [comment]
fxied by https://github.com/envoyproxy/gateway/pull/1232
