### ISSUE TITLE
should we setup fullpath log format.

### ISSUE THREAD

**Issue by misstick86** [envoyproxy/gateway#1216]
*Description*:
> As we know, Gateway use `zap` package as log print. but It's short path on output each line text.  so It's hard to look over which file when there is have same filepath. we need a fullpath log format or some format that base on one directory behind or not?

Here is a example:
```
2023-03-25T23:01:03.519+0800    INFO    /Users/xx/go/src/github.com/envoy/gateway/internal/log/log_test.go:17     this is test
```
 but I think it's too long. May be we just need this. 

```
2023-03-25T23:01:03.519+0800    INFO   internal/log/log_test.go:17     this is test
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
+1

**Comment by cnvergence** [comment]
Hey, I will take a look

**Comment by arkodg** [comment]
great thanks @cnvergence !

**Comment by kflynn** [comment]
Talking about this in the Envoy Gateway meeting... lots of questions around whether the fullpath use case is really desired, or not so much. Any further thoughts from anyone? If not... I might recommend we just close this one until we have a concrete use case that needs the longer paths.

**Comment by cnvergence** [comment]
As there are no concrete use cases for this, I think it should be closed.
If there will be a need to make a configurable logging, relative path log format can also be added based on custom [CallerEncoder](https://github.com/uber-go/zap/blob/master/zapcore/encoder.go#L276)

**Comment by cnvergence** [comment]
As there are no concrete use cases for this, I think it should be closed.
If there will be a need to make a configurable logging, the desired relative path log format can be added by creating a custom [CallerEncoder](https://github.com/uber-go/zap/blob/master/zapcore/encoder.go#L276)

**Comment by kflynn** [comment]
Closing this one and #1237 – thanks @cnvergence! The work is much appreciated. 🙂
