### ISSUE TITLE
import alias consistency

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1220]
The currently used import is not friendly, and recommend to standardize it uniformly. The following are suggestions:

- 3rd or external libs 
    - k8s import
    - envoy go-control panel import

> module with version
> if the module name is too long, use a short name, like `gateway-api `use `gwapi`.

```golang
appsv1 "k8s.io/api/apps/v1"
corev1 "k8s.io/api/core/v1"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```

```golang
clusterv3 "github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3"
corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
endpointv3 "github.com/envoyproxy/go-control-plane/envoy/config/endpoint/v3"
httpv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/upstreams/http/v3"
```

- eg API import

> **no alias** using version directly

```golang
import  configv1a1 "github.com/envoyproxy/gateway/api/config/v1alpha1"
import "github.com/envoyproxy/gateway/api/v1alpha1"
...
RateLimit *configv1alpha1.RateLimit
```

> exists other API

- eg API: using version directly
- other API: module with version

```golang
// other API
gwapiv1a2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
gwapiv1b1 "sigs.k8s.io/gateway-api/apis/v1beta1"
// eg API
"github.com/envoyproxy/gateway/api/config/v1alpha1"
```

**Comment by qicz** [comment]
@arkodg could you give some suggestions about this topic?

**Comment by arkodg** [comment]
I think <name><version> sounds readable and both name and version can be shortened e.g. `alpha1` can be shortened to `a1` so end imported aliases look like  `endpointv3`,  `gwapiv1b1`

**Comment by qicz** [comment]
> I think nameversion sounds readable and both name and version can be shortened e.g. `alpha1` can be shortened to `a1` so end imported aliases look like `endpointv3`, `gwapiv1b1`

well, I will do it by this way, pls assign to me

**Comment by arkodg** [comment]
@zirain is this solved with https://github.com/envoyproxy/gateway/pull/1593 ?

**Comment by zirain** [comment]
no, still has issue like `egcfgv1a1` and `cfgv1a1`

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/3603
