### ISSUE TITLE
Merge Gateways on to a single EnvoyProxy fleet

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1230]
*Description*:
* Today we map the GatewayAPI `Gateway` resource on to a unique Envoy Proxy fleet (https://github.com/envoyproxy/gateway/pull/404 has more info) , creating a new Envoy Proxy infrastructure for every `Gateway` resource created. This design does not efficiently utilize the infra resources in the clusters
* This approach was needed because the Gateway API spec does allow a Listener (Port, Protocol, Hostname) tuple to be same across Gateway resources.

Raising this issue to create a way for Gateway resources to be merged on to the same Envoy Proxy Infrastructure by the user signaling this intent - one suggestion is to define a field in the GatewayClass paramsRef resource (`EnvoyProxy`) called
`mergeGateways`. Setting this field would merge all Gateway Listeners but would also ensure that this tuple (Port, Protocol, Hostname) is unique across all Listeners on all Gateways (if not, the newest conflicting listener would be rejected)

**Comment by cnvergence** [comment]
I can take a look at this one :) @arkodg

**Comment by arkodg** [comment]
great @cnvergence thanks !
recommend starting off with an API PR, since this is a API change, building consensus might get take time, will help out to ensure this work moves in a positive direction.

Another thing to note, that there is an alternative proposal upstream https://github.com/kubernetes-sigs/gateway-api/pull/1863 which is taking the approach of linking child (Gateway) to parent (Gateway) thereby merging with it, rather than what is being suggested here - parent (GatewayClass) enforces merge semantics and children (Gateway) are merged into 1. I personally prefer what is suggested in this issue, but would like the community to chime in on which approach to take

**Comment by tamalsaha** [comment]
We are looking to use Envoy Gateway to expose databases using TCP connections. We would like users to be able to define their own listener per database (not edit the same Gateway object). This feature will help us make sure one IP can expose many different databases different TCP ports. 

My understanding is that this is a supported model for the service gateway project. We would appreciate support for this in Envoy gateway. 
https://kubernetes.slack.com/archives/CR0H13KGA/p1691411234021039?thread_ts=1691400241.997149&cid=CR0H13KGA

**Comment by arkodg** [comment]
if we do decide to go ahead and not wait for upstream support, imo there are two options here
* add `mergeGateways` boolean field to `EnvoyGateway` API
  * cons -
    * affects all `GatewayClasses`, so the user loses out on granularity, today we support only 1, but we may support multiple in the future
* add `mergeGateways` boolean field to `EnvoyProxy` API
  * cons -
    * if we do decide to attach `EnvoyProxy` directly to `Gateway` (today we only support attaching to `GatewayClass`), then the field wouldn't make sense, would be a no-op, and would only have some effect when set in the resource that is attached to the `GatewayClass`

**Comment by cnvergence** [comment]
I think it will be better to utilize the EnvoyProxy API primarily due to the considerations regarding granularity, given the future support of multiple GatewayClasses and that [upstream](https://github.com/kubernetes-sigs/gateway-api/pull/1863) proposal has not been yet introduced.

**Comment by arkodg** [comment]
above approach sounds good @cnvergence, if you have cycles please feel free to continue with this.
I think this is going to be a massive refactor, thinking out loud, the magic is going to be how seamlessly we can CRUD `IR`s - either per `GatewayClass` or per `Gateway` (which is what is done today) based on the `mergeGateways` flag without incurring too much complexity/readibility issues.
Here's an old PR that replaced `IR`s per `GatewayClass` to IR per `Gateway` that you may find handy https://github.com/envoyproxy/gateway/pull/404.

thanks again for building this one out !

**Comment by cnvergence** [comment]
Thanks!
I should have cycles this week, so I will take a look into it again.
