### ISSUE TITLE
support wasm-proxy extension

### ISSUE THREAD

**Issue by caibirdme** [envoyproxy/gateway#1236]
When using a gateway, users often require many additional features beyond basic traffic forwarding, such as authentication and request modification, and these functions can be quite complex. Envoy supports both Lua and WebAssembly (Wasm) as extensions, so I hope the gateway can support users in using Wasm to write extensions and facilitate their deployment and maintenance. The ideal process is:

1. Users develop Wasm plugins using languages such as Go/Rust and generate xxx.wasm files.
2. Save xxx.wasm as a configmap.
3. Create a new CRD to configure the Wasm filter (internally linked to the configmap containing the Wasm file).
4. Associate the new Wasm CR with the HTTPRoute using ExtensionRef.

**Comment by zirain** [comment]
duplicate with https://github.com/envoyproxy/gateway/issues/71?

**Comment by arkodg** [comment]
yeah @caibirdme recommend looking into #71 and #24, we definitely want a way to support user defined wasm extensions in the neer future
closing this issue for now, lets continue discussing in the other highlighted issues
