### ISSUE TITLE
Remove Docker Dev and CI Option

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#124]
https://github.com/envoyproxy/gateway/issues/90#issuecomment-1169338289 vote passed to remove MAKE_IN_DOCKER as a dev/CI option. Dev/CI should be done locally.

**Comment by lizan** [comment]
The biggest drawback is GitHub actions CI image is on rolling update basis and it contains many tools that might be accidentally pulled in the build flow without documentation. Also we will loose track what was used at the time a release is built. 
So perhaps we should revisit it before the next release.

**Comment by danehans** [comment]
> So perhaps we should revisit it before the next release.

Yes, let's revisit.

**Comment by daixiang0** [comment]
@danehans what do you think about https://github.com/envoyproxy/gateway/issues/90#issuecomment-1169425379, if accepted I will process it.
