### ISSUE TITLE
Dedup code pertaining to xRoute using reflection

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1252]
*Description*:
There is a lot of code in https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/contexts.go and https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/route.go that could be deduplicated using reflection https://pkg.go.dev/reflect

**Comment by Xunzhuo** [comment]
I can work on it in v0.5.0 : )

**Comment by Xunzhuo** [comment]
I will unassign this one for recent I am lack of bandwidth.

**Comment by arkodg** [comment]
thanks @shawnh2 !
