### ISSUE TITLE
ratelimit: switch to XdsGrpcSotwProvider

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1254]
For now, we use [FileProvider](https://github.com/envoyproxy/ratelimit/blob/main/src/provider/file_provider.go#L16) in RLS

After https://github.com/envoyproxy/ratelimit/pull/373, [XdsGrpcSotwProvider](https://github.com/envoyproxy/ratelimit/blob/main/src/provider/xds_grpc_sotw_provider.go#L31) can be used to speed config propagation. 

cc @arkodg

**Comment by arkodg** [comment]
+1 
The reasons for doing this sooner than later
* should improve config propagation speed
* we can leverage the xDS response into Route Status Condition (Ready, RateLimitServiceProgrammed etc)

**Comment by shawnh2** [comment]
hi, I can work on this issue, assign please

**Comment by zirain** [comment]
@shawnh2 thanks!

**Comment by shawnh2** [comment]
may hold untill https://github.com/envoyproxy/ratelimit/pull/373 included in next release of envoyproxy/ratelimit

**Comment by zirain** [comment]
I don't think there's routine release flow, use hash tag is ok to me.

**Comment by shawnh2** [comment]
> I don't think there's routine release flow, use hash tag is ok to me.

okay, thanks for the heads up
