### ISSUE TITLE
EndpointSlice Support

### ISSUE THREAD

**Issue by pgold30** [envoyproxy/gateway#1256]
*Description*:
EndpointSlice is now enabled by default in Kubernetes and offers some solid performance benefits for clusters with large Endpoint sets. It might be worthwhile to support consuming EndpointSlice, at least as optional.

Envoy is designed for scale and the use case for endpointslice also. 

The lack of EndpointSlices implementation is unfortunately impacting production for us now. Since Kubernetes v1.22, Services that exceed 1000 Pods/network endpoints, Endpoints are now being truncated to a maximum of 1000 items. 
Im sure there are many other people with the same issue. (same [here](https://github.com/kubernetes/ingress-nginx/issues/6017#issuecomment-1170285796) in Countour)

Outlining the pieces needed to implement this issue @arkodg  pointed [here](https://github.com/envoyproxy/gateway/issues/35#issuecomment-1387344863) 

Work Items:

- [x]  Add EndpointSlice support in the Kubernetes Provider https://github.com/envoyproxy/gateway/pull/1474
- [x] Parse EndpointSlice support to Xds IR Route Destinations in the Gateway API Translator https://github.com/envoyproxy/gateway/pull/1494
- [ ] #1900

[*Relevant Links*:]
[Similar to Countour open issue](https://github.com/projectcontour/contour/issues/2696).
This was shortly discussed [here](https://github.com/envoyproxy/gateway/issues/35) and [this explanation](https://github.com/envoyproxy/gateway/issues/35#issuecomment-1396422011)
This was fixed on Feb 15 for nginx-ingress [here](https://github.com/kubernetes/ingress-nginx/pull/8890)

**Comment by Xunzhuo** [comment]
Thanks for raising it @pgold30, I will take this in v0.5.0.

**Comment by arkodg** [comment]
thanks for picking this one up @Xunzhuo  !

**Comment by arkodg** [comment]
sidenote - this might also require an `EnvoyProxy` API change to add a field to disable endpoint resolution / fall back to service VIP, in case the user prefers routing/load balancing via kube-proxy

**Comment by arkodg** [comment]
moving this into the backlog for now, since this is not a must have for v0.5.0

**Comment by Xunzhuo** [comment]
Hey @arkodg, since you have started working on this issue, let me transfer this to you, thanks!
