### ISSUE TITLE
Lack of ratelimit resources settings

### ISSUE THREAD

**Issue by xuaning67** [envoyproxy/gateway#1261]
Hello,  I've been using envoy for development recently and I would like to use the ratelimit settings in my project. But I didn't find the relevant resource settings, instead, I notice that proxy has similar settings. So I hope this requirement can be realized, because I urgently need this setting right now. Thanks very much!

**Comment by zirain** [comment]
duplicate of #1196

FYI: https://github.com/envoyproxy/gateway/pull/1218
