### ISSUE TITLE
Pick TLS Cert based on SNI

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1275]
*Description*:
Relates to https://github.com/envoyproxy/gateway/pull/1241#discussion_r1161427156

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
cc @chauhanshubham

**Comment by chauhanshubham** [comment]
thanks @arkodg will take this up.

**Comment by arkodg** [comment]
reopening this issue to tracks completion of docs for SNI based cert selection
