### ISSUE TITLE
Add user docs with past presentation links

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1278]
*Description*:
Add a page in our docs site that links all Envoy Gateway past presentations and slides

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zhaohuabing** [comment]
I can take this one if you could tell me where can I find those presentations. I'm thinking about an introduction of EG in the first Chinese community meeting. The past presentations can be very good inputs.

**Comment by arkodg** [comment]
thanks ! here's the talk from Kubecon NA 2022 https://www.youtube.com/watch?v=3MUOZc8XNCc
@AliceProxy can you link the slides for that talk here ?
