### ISSUE TITLE
Add validations for TLS Certs for a specific listener

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1292]
*Description*:
Validate TLS Certs for a specific listener and update status
relates to https://github.com/envoyproxy/gateway/pull/1291#pullrequestreview-1380403980

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by cnvergence** [comment]
I can take a look at this in the meantime 🙂

**Comment by arkodg** [comment]
thanks @cnvergence suggesting to keep all validation logic for multiple secrets within https://github.com/envoyproxy/gateway/blob/6baaaf1df622a295f93e23c4fa8b15c16cf2f9da/internal/gatewayapi/tls.go#L18 so its easier to maintain
