### ISSUE TITLE
envoyproxy instance svc update error after gateway restart

### ISSUE THREAD

**Issue by spwangxp** [envoyproxy/gateway#1340]
*Description*:
>What issue is being seen?
after gateway restart, gateway will update the exist envoy proxy instance, so there will encounter an error, seem like https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/infra.go#L74 miss add the original info to new svc.

*Repro steps*:
> apply an gateway cr and envoyproxy cr, check an envoy proxy instance whether created in envoy-gateway-system, then restart the gateway.

*Environment*:
> the main branch code; 
k8s server: v1.19.8

*Logs*:
>2023-04-23T11:00:59.473+0800    ERROR   runner/runner.go:68     failed to create new infra      {"runner": "infrastructure", "error": "failed to update service envoy-gateway-system/envoy-default-eg-64656661: Service \"envoy-default-eg-64656661\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable"}
github.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR.func1
        gateway/internal/infrastructure/runner/runner.go:68
gateway/internal/message.HandleSubscription[...]
        gateway/internal/message/watchutil.go:28
github.com/envoyproxy/gateway/internal/infrastructure/runner.(*Runner).subscribeToProxyInfraIR
        gateway/internal/infrastructure/runner/runner.go:57

**Comment by spwangxp** [comment]
this [if](https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/applier/apply.go#L125) always be false due to svc.spec.ClusterIP/svc.spec.CheckNodePort/svc.spec.*.nodePort always different.

**Comment by zirain** [comment]
cc @arkodg , this seems a issue from the begining.
