### ISSUE TITLE
Collapse patch docs dirs into minor version while highlighting commands based on patch ver

### ISSUE THREAD

**Issue by AliceProxy** [envoyproxy/gateway#1358]
*Description*:
Re: #1357 the release guide currently instructs you to generate the new docs directory only using the major and minor version (ex: `make docs-release TAG=v{MAJOR}.{MINOR}`). While generating the docs however; it causes all the pages that reference the image tag or URL to contain the wrong version (ex: `v0.4` instead of `v0.4.0`).

I would be +1 for only having one docs directory per minor release. I don't think we need to keep making separate docs directories for each patch release. If we do want to move forward with this approach, then the `docs-release` make target will need to be updated to take input such as `make docs-release TAG=v0.5.0` and use the directory name and patch version separately where needed.

**Comment by arkodg** [comment]
we currently have 1 doc per minor release, closing this one
