### ISSUE TITLE
helm install is not idempotent

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1361]
After follow this guide: https://gateway.envoyproxy.io/v0.4.0/user/quickstart.html, pods in gateway-system are not removed.

```
k get pod -n gateway-system
NAME                                           READY   STATUS      RESTARTS   AGE
gateway-api-admission-jv26k                    0/1     Completed   0          2m1s
gateway-api-admission-patch-bt6ss              0/1     Completed   0          2m1s
gateway-api-admission-server-f95c4df77-dlw6d   1/1     Running     0          2m1s
```

cc @arkodg @Xunzhuo

**Comment by arkodg** [comment]
should we add an extra clean up step saying `Delete gateway-system` and make it opt in, because there will be one validation webhook controller, but multiple GW API controllers in the cluster ?

**Comment by Xunzhuo** [comment]
@arkodg Yes, that is why we put gwapi resources in crds/ , since there might be not only one gateway providers.

We use intall.yaml before, but if we clean it up with delete -f intstall.yaml, we might delete gwapi resources wrongly if other providers are using too.

**Comment by arkodg** [comment]
we could add more steps such as 
```
kubectl delete namespace gateway-system
```

But the CRDs still remain in the cluster

Another option I was playing with was using `helm template`
```
helm template eg oci://docker.io/envoyproxy/gateway-helm --version v0.4.0 -n envoy-gateway-system --include-crds | kubectl delete -f -
```

This correctly deletes everything, but leaves helm confused, if I run helm install again after this
```
$ helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.4.0 -n envoy-gateway-system --create-namespace
Pulled: docker.io/envoyproxy/gateway-helm:v0.4.0
Digest: sha256:6dd5be285169065d6e1d3e2167984dcf1ae06e2f87bc37c1414becce0a733e45
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
```

**Comment by zirain** [comment]
there's two ways to manage crds in helm: 
1. [Let helm Do It For You](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)
2. [Separate Charts](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts)

even use method-1, IMO you should remove adminission server resources out of crds folder

**Comment by arkodg** [comment]
@zirain if the admission server out, we might accidentally delete it if there are multiple EG running in the same cluster and we want to delete some of them, but not all

**Comment by zirain** [comment]
this's supre odd, use independent install/uninstall step for gateway-api installation?

**Comment by kflynn** [comment]
I would strongly vote for a separate CRDs chart that's manually installed. Don't do it as a dependent chart, just let the user install the CRDs, then the Envoy Gateway control plane. (This is the way Linkerd does it.)

**Comment by arkodg** [comment]
should be fixed with https://github.com/envoyproxy/gateway/issues/1721
