### ISSUE TITLE
finalizers on gatewayclass is not clean

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1362]
finalizers on gatewayclass is not clean when you're not clean gateway before uninstall EG, which will block deleting of gatewayclass CRD.

```bash
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.4.0 -n envoy-gateway-system --create-namespace
kubectl apply -f examples/kubernetes/quickstart.yaml
helm uninstall eg -n envoy-gateway-system

kubectl get gc eg  -oyaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"GatewayClass","metadata":{"annotations":{},"name":"eg"},"spec":{"controllerName":"gateway.envoyproxy.io/gatewayclass-controller"}}
  creationTimestamp: "2023-04-25T06:32:39Z"
  finalizers:
  - gateway-exists-finalizer.gateway.networking.k8s.io
  generation: 1
  name: eg
  resourceVersion: "13546"
  uid: 7d99c041-5751-41cb-ba34-9793cb27e5a2
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
status:
  conditions:
  - lastTransitionTime: "2023-04-25T06:32:39Z"
    message: Valid GatewayClass
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
```

cc @arkodg

**Comment by arkodg** [comment]
thanks for highlighting this @zirain, any idea what the issue is here, why did the gateway not get deleted ?

**Comment by zirain** [comment]
you need remove all gateway before uninstall EG

**Comment by arkodg** [comment]
> you need remove all gateway before uninstall EG

isn't that the reason finalizers were added, to stop deletion of GatewayClass if one or more linked Gateways existed ?

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/blob/7a116c90faa1954fdbba2a7f8d5c32ead0443067/internal/provider/kubernetes/controller.go#L246-L245

**Comment by arkodg** [comment]
> https://github.com/envoyproxy/gateway/blob/7a116c90faa1954fdbba2a7f8d5c32ead0443067/internal/provider/kubernetes/controller.go#L246-L245

can you elaborate ?

**Comment by zirain** [comment]
once a gateway attached to gatewayclass, EG will add finalizer to gatewayclass, if users directly uninstall the control plane before removing all gateway resources, finalizer will not be cleaned, it's will be a block when you're trying to delete gateway crds.

**Comment by arkodg** [comment]
> once a gateway attached to gatewayclass, EG will add finalizer to gatewayclass, if users directly uninstall the control plane before removing all gateway resources, finalizer will not be cleaned, it's will be a block when you're trying to delete gateway crds.

isn't this intentional, I believe the reason to add a finalizer is to prevent such deletion or order them.
If users dont want this, we should just remove the finalizer

**Comment by zirain** [comment]
At least shoud be mentioned this in doc.

**Comment by arkodg** [comment]
+1 Quickstart docs should mention this, keeping this issue open until the docs are added

**Comment by zirain** [comment]
there's a cleanup step in [doc](https://gateway.envoyproxy.io/v0.4.0/user/quickstart.html#clean-up)
