### ISSUE TITLE
ci: correct permission for cherrypick action

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1371]
https://github.com/envoyproxy/gateway/actions/runs/4815400332/jobs/8574055891

![image](https://user-images.githubusercontent.com/4354057/234746606-7912f38c-e445-432f-9a43-0283d2e1a741.png)

**Comment by arkodg** [comment]
@zirain guessing we need to enable `pull_request: write` permissions for this workflow ?
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/#setting-permissions-in-the-workflow

**Comment by zirain** [comment]
yes, I ask @mattklein123 via slack, but didn't get response for now, he's busy with other staffs.

**Comment by mattklein123** [comment]
I'm not sure what I need to change. I checked the permissions and it looks like the default is read/write.

**Comment by zirain** [comment]
@mattklein123 is this enabled?

![image](https://user-images.githubusercontent.com/4354057/236084241-41ec4981-2a4d-4eb2-bce9-09df6907f878.png)

**Comment by mattklein123** [comment]
Yes that is what it looks like.

**Comment by Xunzhuo** [comment]
@zirain can we close this one ?

**Comment by zirain** [comment]
need verify, I will close it later.

**Comment by zirain** [comment]
still not working as expected

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/1439

see demo PR: https://github.com/envoyproxy/gateway/pull/1440
