### ISSUE TITLE
Run Envoy Gateway locally on host

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1393]
*Description*:

- [x]  Design document https://github.com/envoyproxy/gateway/pull/1382
- [x]  Define Provider API https://github.com/envoyproxy/gateway/pull/1402
- [x]  Implement File ResourceProvider https://github.com/envoyproxy/gateway/pull/3159
- [x]   Implement Host InfrastructureProvider https://github.com/envoyproxy/gateway/issues/4481
- [ ]   User Facing docs

[optional *Relevant Links*:]
Relates to Relates to https://github.com/envoyproxy/gateway/issues/1001 & https://github.com/envoyproxy/gateway/issues/1035

**Comment by arkodg** [comment]
the API is in, implementation is remaining, unassigned myself since I won't be able to pick up the implementation anytime soon due to other higher priority issues in the project, if anyone in the community is interested in picking this one up, please go for it

**Comment by vladimirfx** [comment]
Testing Envoy Gateway v1.0.0-rc.1 as a replacement for Cilium Gateway implementation. There are plenty of options (great!) but I can't understand how to use Envoy Gateway on the edge cluster where VIP is assigned to the distinct node. 

Can I configure the Envoy Gateway to run as DaemonSet?

**Comment by shawnh2** [comment]
I would love to see this kicks in after GA, wanna give it a try, so assign myself.

**Comment by arkodg** [comment]
moving this to v1.2.0 to track docs work
