### ISSUE TITLE
Create Docker Hub Repo for EG Image

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#14]
A docker hub repo is needed to store EG images. The push will be triggered by a GH action.

**Comment by danehans** [comment]
@mattklein123 PTAL at https://github.com/envoyproxy/gateway/issues/75. When you have a moment, can you help with the Docker repo and push creds?

**Comment by lizan** [comment]
`envoyproxy/gateway` and `envoyproxy/gateway-dev` repositories are created. creds are in GitHub actions secret as `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD`
