### ISSUE TITLE
Vary the use of egctl

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1403]
*Description*:

Currently `eg` provides the `egctl` client to debug any issue easily.  But the client is outside k8s, the use have to download the `egctl` to the local or k8s host, at the same time when the user extends more extension features needs to recompile it. 

 I think we should use `egctl` simply and diversely.

- For simply: combining all commands into a single binary, the user can use the `egctl` commands easily. On k8s, use `egctl` like 

``` shell
kubectl exec -n envoy-gateway-system envoy-gateway-xxx -it -- envoy-gateway egctl ....
```

-  For diversely:  provides outside `egctl` client  and commands combined `eg` version 
   -  outside `egctl` works on a local laptop
   -  commands combined works on others' place

How to combine all commands:

``` golang
func main() {
	// the envoy-gateway commands
	commands := cmd.GetRootCommand()
	// combine the egctl to envoy-gateway root commands
	commands.AddCommand(egctl.GetRootCommand())
	if err := commands.Execute(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
```

or

``` golang
func main() {
	// the envoy-gateway commands
	commands := cmd.GetRootCommand()
	// combine the egctl sub commands to envoy-gateway root commands
	commands.AddCommand(egctl.GetRootCommand().Commands()...)
	if err := commands.Execute(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
```

For binary or image size:

the commands combined version, the `eg` binary is just a little bigger than the current version.

cc @arkodg

**Comment by zirain** [comment]
I don't think it's a good pratice to do this.

**Comment by qicz** [comment]
> I don't think it's a good pratice to do this.

As an end-user, the combined version is more convenient, and especially in k8s, there is no need to download.

**Comment by arkodg** [comment]
lets make a decision on this, @envoyproxy/gateway-maintainers anyone in favor of this ?

**Comment by arkodg** [comment]
closing this as not planned
