### ISSUE TITLE
Auto-assigned IP address can be the External IPs of Envoy Proxy Service in LoadBalancer mode

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#1405]
After #1322 was merged, we can define `Gateway.Spec.Addresses` as the Envoy Proxy Service External IPs.

But when we deploy the Envoy Proxy Service in `LoadBalancer` mode along with MetalLB, the latter will automatically assign a IP to `Gateway.Spec.Addresses`, causing Envoy Proxy Service to have an External IP.

It won't cause any bugs, but IMO this behavior is inappropriate because **only user-defined** IP address should be the External IPs instead of auto-assigned IP address.

cc @arkodg WDYT?

---

Relevant: #360

**Comment by chauhanshubham** [comment]
wouldn't this require integrations with L4 LBs, responsible for providing the IPs.
For instance, for integration with metallb, we'll have to use this annotation specified here https://metallb.universe.tf/usage/#requesting-specific-ips
GKE would require you to specify the `.spec.loadBalancerIP` https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#use_a_service
etc.

**Comment by arkodg** [comment]
> wouldn't this require integrations with L4 LBs, responsible for providing the IPs.
> For instance, for integration with metallb, we'll have to use this annotation specified here https://metallb.universe.tf/usage/#requesting-specific-ips
> GKE would require you to specify the `.spec.loadBalancerIP` https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#use_a_service
> etc.

@chauhanshubham I would assume a separate controller and a separate `Gateway` resource wold need to be created and the same `spec.Addresses` would need to be assigned if the user is requesting the address to also be assigned to the L3/L4 LoadBalancer.

**Comment by shawnh2** [comment]
false alarm.

the MetalLB does not populates `spec.Addresses` of the `Gateway`, it only populates `status.Addresses` of Service, which is expected. but the MetalLB will also assign this populated address to be the External IP of this Service, which is also expected.
