### ISSUE TITLE
How to deploy Envoy Gateway using the host network mode instead of the load balancer mode

### ISSUE THREAD

**Issue by yeaheo** [envoyproxy/gateway#1427]
*Description*:
> If deploy Envoy Gateway on a self-managed cluster where LoadBalancer type services are not available, how can I configure it to use HostNetwork mode and leverage the host's network? 
Does Envoy Gateway currently support this way?

[optional *Relevant Links*:]
>

**Comment by Xunzhuo** [comment]
You can customize EG with envoyproxy API to set envoyproxy service type to `ClusterIP`.

**Comment by yeaheo** [comment]
> You can customize EG via envoyproxy API to set envoyproxy service type to `ClusterIP`.
> 
> Valid svc type are: `ClusterIP`, `LoadBalancer` and `NodePort`, default is `LoadBalancer`.
ok，I will try it out, thanks !!!

**Comment by yeaheo** [comment]
> You can customize EG via envoyproxy API to set envoyproxy service type to `ClusterIP`.
> 
> Valid svc type are: `ClusterIP`, `LoadBalancer` and `NodePort`, default is `LoadBalancer`.

ok，I will try it out, thanks !!!

**Comment by Xunzhuo** [comment]
close it for now
