### ISSUE TITLE
Add functionality in cert-gen to skip creating certs or rewrite existing certs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1471]
*Description*:
* By default cert-gen should not create new certs, if they already exist in the same namespace, e.g. during upgrades
* A new arg such as `--rewrite-certs` should be added if we want cert-gen to delete existing certs and create new ones

**Comment by kflynn** [comment]
This sounds good to me, yeah. The default for the update case should be to reuse your existing certs.
