### ISSUE TITLE
Whether the log "no envoyproxies exist" level should be modified

### ISSUE THREAD

**Issue by hemenghong** [envoyproxy/gateway#1472]
*Description*:
> when gateway reconcile, EnvoyProxyList must be null, why return this error? is there should modify to log and return nil?

*Repro steps*:
> 1、create gateway 
2、create proxy, and get gateway error logs

*Logs*:
>2023-06-01T05:51:50.646Z        ERROR   kubernetes/controller.go:237    failed to process parametersRef for gatewayclass                                    {"runner": "provider", "name": "eg", "error": "no envoyproxies exist in namespace envoy-gateway-system"}
2023-06-01T05:51:50.655Z        ERROR   kubernetes/controller.go:237    failed to process parametersRef for gatewayclass                                    {"runner": "provider", "name": "eg", "error": "no envoyproxies exist in namespace envoy-gateway-system"}

**Comment by zirain** [comment]
did you setup `parametersRef` ?

**Comment by arkodg** [comment]
https://github.com/envoyproxy/gateway/blob/22bd06b33f914e406bba9ce9690e92cc3f5c3226/internal/provider/kubernetes/controller.go#L237 seems like a legit error
can you share the o/p of
```
kubectl get gatewayclass -A -o yaml
```
&

```kubectl get envoyproxy -A -o yaml```

**Comment by qicz** [comment]
> https://github.com/envoyproxy/gateway/blob/22bd06b33f914e406bba9ce9690e92cc3f5c3226/internal/provider/kubernetes/controller.go#L237
> 
> seems like a legit error
> can you share the o/p of
> 
> ```
> kubectl get gatewayclass -A -o yaml
> ```
> 
> &
> 
> `kubectl get envoyproxy -A -o yaml`

IMO, the `return` is missed

```go
	// Process the parametersRef of the accepted GatewayClass.
	if acceptedGC.Spec.ParametersRef != nil && acceptedGC.DeletionTimestamp == nil {
		if err := r.processParamsRef(ctx, acceptedGC, resourceTree); err != nil {
			msg := fmt.Sprintf("%s: %v", status.MsgGatewayClassInvalidParams, err)
			if err := r.gatewayClassUpdater(ctx, acceptedGC, false, string(gwapiv1b1.GatewayClassReasonInvalidParameters), msg); err != nil {
				r.log.Error(err, "unable to update GatewayClass status")
			}
			r.log.Error(err, "failed to process parametersRef for gatewayclass", "name", acceptedGC.Name)
			// missed this return
			return reconcile.Result{}, err
		}
	}

	if err := r.gatewayClassUpdater(ctx, acceptedGC, true, string(gwapiv1b1.GatewayClassReasonAccepted), status.MsgValidGatewayClass); err != nil {
		r.log.Error(err, "unable to update GatewayClass status")
		return reconcile.Result{}, err
	}

```
the same time

https://github.com/envoyproxy/gateway/blob/22bd06b33f914e406bba9ce9690e92cc3f5c3226/internal/provider/kubernetes/controller.go#L1253

IMO we should change like this

```go
	if len(epList.Items) == 0 {
		r.log.Info("no envoyproxies exist in namespace %s", r.namespace)
		return nil
	}
```

cc @arkodg @zirain 

@hemenghong you can pick this and fix it
