### ISSUE TITLE
Fix /retest GH action

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1518]
*Description*:
Fix the `/retest` [GH Action](https://github.com/envoyproxy/gateway/blob/main/.github/workflows/retest.yaml) that doesnt seem to be working correctly, error logs are [here](https://github.com/envoyproxy/gateway/actions/runs/5217604389/jobs/9417601727)

*Repro*
Add a  `/retest` comment on any PR

**Comment by zirain** [comment]
I think this need someone who has admin role on this repo.

**Comment by kranurag7** [comment]
@arkodg I think this should be fixed now. I don't see any failed [workflows](https://github.com/envoyproxy/gateway/actions/workflows/retest.yaml) in the last five days.

**Comment by Xunzhuo** [comment]
https://github.com/envoyproxy/gateway/actions/runs/5322024655

**Comment by tmsnan** [comment]
We can use envoy's retest script
https://github.com/envoyproxy/toolshed/blob/main/gh-actions/retest/retest.ts

**Comment by tmsnan** [comment]
Test is ok 
https://github.com/tmsnan/gateway/actions/runs/5401117981
