### ISSUE TITLE
Run Gateway API conformance in CI

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#157]
Gateway API conformance tests should run as part of CI, to serve as our end-to-end testing. We should run the set of tests that are included in the Gateway API release that we're using (currently v0.5.0). Initially we'll want these to be non-blocking as we work towards a conformant implementation, but eventually they should be merge-blocking. 

xref. #65

**Comment by skriss** [comment]
I've got much of this ready, but blocked for now until we have a functioning binary & YAML manifest.

**Comment by skriss** [comment]
Still to do:
- add CI steps that run conformance
- when running for a PR, use the container image built for the PR rather than the default `envoyproxy/gateway-dev:latest`

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/425
