### ISSUE TITLE
Clean up unused Envoy Proxy resource that was referenced by Gateway Class

### ISSUE THREAD

**Issue by cnvergence** [envoyproxy/gateway#1575]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Having initially deployed the GatewayClass with `parametersRef`, the user can later edit it and remove the envoy proxy resource from `parametersRef`.
It would be good to check for such updates and clean up the unused resource from the cluster.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

It could be another follow-up to these PRs 
- https://github.com/envoyproxy/gateway/issues/648
- https://github.com/envoyproxy/gateway/issues/865

**Comment by arkodg** [comment]
closing as not planned, EG should not clean up EnvoyProxy resource created by the user
