### ISSUE TITLE
Deployment of ratelimit hard code is LoadBalancer

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#1577]
Deployment of ratelimit hard code is LoadBalancer
But I want to change its type of Service. How to configure it ?

**Comment by zirain** [comment]
@qicz this seems related to reusage of `DefaultKubernetesServiceType`, can you take a look?

**Comment by zirain** [comment]
Thanks for catching this

**Comment by cnvergence** [comment]
I can take a look at this one

**Comment by cnvergence** [comment]
As per https://github.com/envoyproxy/gateway/pull/1578#discussion_r1239995329, I will change the default value to Cluster.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/1578
