### ISSUE TITLE
EG auto restart, and status be CrashLoopBackOff

### ISSUE THREAD

**Issue by hemenghong** [envoyproxy/gateway#1587]
*Description*:
>install EG error  

*Repro steps*:
>1、Install EG
2、EG  auto restart later
3、View the details of a previously logs

*Environment*:
>the latest version

*Logs*:
>fatal error: concurrent map iteration and map write
goroutine 513 [running]:
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*kubernetesProviderStore).listNodeAddresses(...)
        /build/internal/provider/kubernetes/store.go:61
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).statusUpdateForGateway(0x40005e2fc0, {0x24b66a8, 0x40001c8000}, 0x4026a96820)
        /build/internal/provider/kubernetes/controller.go:353 +0x2e0
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).validateDeploymentForReconcile(0x40005e2fc0, {0x24d1220?, 0x404122b900?})
        /build/internal/provider/kubernetes/predicates.go:215 +0xc8
sigs.k8s.io/controller-runtime/pkg/predicate.NewPredicateFuncs.func2({{0x24d1220?, 0x4047169400?}, {0x24d1220?, 0x404122b900?}})
        /build/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:110 +0x3c
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update(...)
        /build/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:88
sigs.k8s.io/controller-runtime/pkg/internal/source.(*EventHandler).OnUpdate(0x40038ce000, {0x2106300?, 0x4047169400}, {0x2106300?, 0x404122b900})
        /build/vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/event_handler.go:113 +0x31c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /build/vendor/k8s.io/client-go/tools/cache/controller.go:250
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /build/vendor/k8s.io/client-go/tools/cache/shared_informer.go:971 +0xf8
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000e44728?, {0x2490500, 0x4002b7dbf0}, 0x1, 0x40038a6240)
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0x40038c9c20)
        /build/vendor/k8s.io/client-go/tools/cache/shared_informer.go:967 +0x68
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x58
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /build/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x80

**Comment by zirain** [comment]
thanks for reporting, looks like a typical concurrent error
