### ISSUE TITLE
Proxy always terminating

### ISSUE THREAD

**Issue by hemenghong** [envoyproxy/gateway#1590]
*Description*:
>after install eg and proxy, when I add or delete a httproute, proxy will new pods then terminating every time, as shown

*Environment*:
>the latest version

*Logs*:
>
![image](https://github.com/envoyproxy/gateway/assets/30815911/dd6cc697-b2ee-441f-a513-29f29a393c69)

**Comment by shawnh2** [comment]
it seems like the problem of OpenShift, cause in kubernetes cluster everything works fine.

**Comment by qicz** [comment]
> it seems like the problem of OpenShift, cause in native kubernetes cluster everything works fine.

hey, native works fine but there is a compare nit.

**Comment by arkodg** [comment]
are you still seeing this issue @hemenghong with the latest release ?

**Comment by qicz** [comment]
Fixed by #1594
