### ISSUE TITLE
Document ports opened on Envoy Gateway and Envoy Proxy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1598]
*Description*:
Document the ports being listened on, in an installation page

Envoy Gateway
* Xds EnvoyProxy Server - 18000
* Xds RateLimit Server - 18001
* Admin Server - 19000

Envoy Proxy
* Admin Server - 19000
* Heath Check Listener - 19001

**Comment by slayer321** [comment]
Hi @arkodg, I did like to work on this issue. Can you assign it to me?

**Comment by arkodg** [comment]
thanks @slayer321, one approach for this issue could be to add a new `Installation` page [here](https://github.com/envoyproxy/gateway/tree/main/docs/latest/user) that would become visible [here](https://gateway.envoyproxy.io/latest/user_docs.html) . This page could be reused in the future to also add Helm chart install customization details
