### ISSUE TITLE
gateway memory leak

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1604]
using the main branch version
works on arm host
OpenShift

![image](https://github.com/envoyproxy/gateway/assets/2174082/3cb395b1-e1cd-4803-ad9f-b3178f0c642d)
![image](https://github.com/envoyproxy/gateway/assets/2174082/dbf9388e-cb23-4845-a7a5-a4ff40f4e1ef)
![image](https://github.com/envoyproxy/gateway/assets/2174082/c8a2e3c3-e729-42e5-8e6e-58b229c7e4e9)
![image](https://github.com/envoyproxy/gateway/assets/2174082/0316872c-ac7d-4ee0-a806-1bb76006c4fa)
![image](https://github.com/envoyproxy/gateway/assets/2174082/9e0e0be3-75a9-40a7-80af-f3a6a2e2f72f)
![image](https://github.com/envoyproxy/gateway/assets/2174082/58310a4f-f2e4-4502-86e9-a8e96a93e77f)
![image](https://github.com/envoyproxy/gateway/assets/2174082/f3aeb21d-e0cf-4927-a5ee-a6c28bb94cc9)

**Comment by qicz** [comment]
![image](https://github.com/envoyproxy/gateway/assets/2174082/9e0e0be3-75a9-40a7-80af-f3a6a2e2f72f)

**Comment by qicz** [comment]
![image](https://github.com/envoyproxy/gateway/assets/2174082/58310a4f-f2e4-4502-86e9-a8e96a93e77f)

**Comment by qicz** [comment]
the bug is that when InfraIR changed, infraManage will create or update new proxy resources.
create the service account EG does not compare the different, create or update the service account, at the same time, k8s will create a new secret. EG list watch more secret resources and occupy more memory 
https://github.com/envoyproxy/gateway/blob/81cdde6af34dc16b68495ec136ab80ce8569e5a9/internal/infrastructure/kubernetes/infra_resource.go#L22-L37

![image](https://github.com/envoyproxy/gateway/assets/2174082/de1ddd66-1397-4509-b7b6-eaa24fc55c97)

**Comment by zirain** [comment]
As we talked offline, this seems a bug related to OpenShift.

**Comment by qicz** [comment]
> As we talked offline, this seems a bug related to OpenShift.

yes. In fact, it is truly that is unnecessary to update the sa.

**Comment by arkodg** [comment]
has this issue been resolved @qicz ?

**Comment by qicz** [comment]
> has this issue been resolved @qicz ?

Fixed by #1609
