### ISSUE TITLE
Highlight Helm Chart customizations in the Installation Page

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1611]
*Description*:
Highlight the many ways the Envoy Gateway can be customized using helm, shown here
https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm#values to the user
in the docs website, in the installation page https://github.com/envoyproxy/gateway/blob/main/docs/latest/user/installation.md

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by slayer321** [comment]
Hi @arkodg, I  did like to work on this issue. 
I had some queries .. so some of the ways I can think of showing the customization with helm chart are below 

Increase the replica 
```
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace --set deployment.replicas=2
```
Change the ports for `grpc` and `ratelimit`
```
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace --set deployment.replicas=2 --set "deployment.ports[0].name=grpc" --set "deployment.ports[0].port=18005" --set "deployment.ports[0].targetPort=18000" --set "deployment.ports[1].name=ratelimit" --set "deployment.ports[1].port=18006" --set "deployment.ports[1].targetPort=18001"
```
any other customization we did like to show ?

**Comment by arkodg** [comment]
hey @slayer321 above examples are a great way to highlight how to modify values from the CLI directly . Another great addition would be to highlight how to modify make more complex changes using the `values.yaml` files as shown in https://helm.sh/docs/chart_template_guide/values_files/  (which users will most likely save in `git`).

This page should also show (or link) to the Helm Values API, might need to incorporate this https://github.com/envoyproxy/gateway/pull/1283/files#r1163529206
so we could incorporate the tool into our docs generation similar to https://github.com/envoyproxy/gateway/blob/a5982c395cb5845f53b7c25fec0368222bf33ed3/tools/make/docs.mk#L40 
cc @Xunzhuo for any suggestions

**Comment by slayer321** [comment]
Hey @arkodg , I was working on this issue and while adding [helm-docs](https://github.com/norwoodj/helm-docs) to our docs.mk file. I found that after running the make command for that it is removing the whole [Usage](https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/README.md#usage) section for the helm README file. I think it is not required that as we only need to have helm related instruction inside that README.md file right ?

**Comment by arkodg** [comment]
@slayer321 might make sense to create a new dir  (`helm`) + file  (`api.md`) under https://github.com/envoyproxy/gateway/tree/main/docs/latest to save the o/p of `helm-docs`, which can then be linked in the installation docs
