### ISSUE TITLE
Apply EG Role and RoleBinding when running in namespaced mode

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1619]
*Description*:
Envoy Gateway recently added support to allow users to limit the namespaces Envoy Gateway watches to gather resources in https://github.com/envoyproxy/gateway/issues/1117

This also means Envoy Gateway can use namespaced `Role` & `RoleBinding` resources instead of `ClusterRole` https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/generated/rbac/roles.yaml reducing the permissions needed to operate.

**Comment by shawnh2** [comment]
hi, i can take a look at this, plz assign
