### ISSUE TITLE
return 500's for invalid HTTPRoute backend refs

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#162]
There is a set of rules around how to handle 1+ invalid backend refs on an HTTPRoute that generally involve returning 500 responses for any invalid backends. This needs to be implemented properly.

https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule (see backendRefs).

Needed for core conformance.

**Comment by AliceProxy** [comment]
I'll take this issue

**Comment by danehans** [comment]
@AliceProxy FYI I'm seeing this issue with the following conformance tests:

https://github.com/envoyproxy/gateway/issues/431
https://github.com/envoyproxy/gateway/issues/432
https://github.com/envoyproxy/gateway/issues/433

Please see these issues for additional details.

**Comment by AliceProxy** [comment]
> @AliceProxy FYI I'm seeing this issue with the following conformance tests:
> 
> #431 #432 #433
> 
> Please see these issues for additional details.

:+1: The changes I was working on at the end of last week didn't properly handle the weighted responses so I switched over to a solution similar to how Istio is doing it. I'm trying to get a PR up for the gateway meeting in a few hours, but I'll keep working on this until it's done either way today.
