### ISSUE TITLE
support for x-ratelimit-* response headers in ratelimit 

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/gateway#1620]
*Description*:
> support for x-ratelimit-* response headers in ratelimit (easy to check current limit status）
[`XRateLimitHeadersRFCVersion` ](https://github.com/envoyproxy/envoy/blob/4e51ba92fe9effd943f68568762c3b213ec818bd/api/envoy/extensions/common/ratelimit/v3/ratelimit.proto#L20C1-L35C2)

[optional *Relevant Links*:]
>[draft RFC Version 03 ](https://datatracker.ietf.org/doc/id/draft-polli-ratelimit-headers-03.html)

**Comment by tmsnan** [comment]
If accepted, I can complete this。

**Comment by arkodg** [comment]
+1

**Comment by quyenhoang96** [comment]
If no one has done it, you can give it to me
