### ISSUE TITLE
watch resource with selector

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1622]
*Description*:
in order to optimize EG occupy high memory,  #1610 supports EG watching the spec namespace. but the users need to list all namespaces that need watching.  It's not convenient, we can watch the namespace that has some label.  IMO should watch the namespace with the same label, like `shared-gateway-access`  https://gateway-api.sigs.k8s.io/guides/multiple-ns/

xref: https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.15.0/pkg/cache#Options

cc @arkodg

**Comment by arkodg** [comment]
+1

**Comment by arkodg** [comment]
can probably define a `Type` field in https://github.com/envoyproxy/gateway/blob/3892d9047488fee65be118e4998ce026a84352cd/api/config/v1alpha1/envoygateway_types.go#L166 to differentiate between `Namespaces` and `LabelSelectors`

**Comment by den3tsou** [comment]
I am interested in this. Could I please take this one?

**Comment by den3tsou** [comment]
Hi @qicz @arkodg and @zirain. I believe that this is tricky to do after my investigation. `controller-runtime` only doesn't support this out of the box. The only solution I can think of to support this is to get a list of namespace with certain labels and feed those namespaces into [Cache](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.15.0/pkg/cache#Options). However, this means controller needs to be restarted every time when new namespaces are added. Otherwise, those newly added namespaces will not be watched. What's your thoughts on this?

**Comment by arkodg** [comment]
@den3tsou one way could be to add a predicate function to all resources https://github.com/envoyproxy/gateway/blob/708287e53af5146873c91c9a4cda2a9ed8126f03/internal/provider/kubernetes/controller.go#L1071 which only return `true` if their namespace of the namespaced resource has the labels set

**Comment by den3tsou** [comment]
Hi @arkodg, I have a look at your suggestion. But I found that client.Object doesn't return a namespace object. It only returns a stirng. Is this what you are referring to?
```go
// Object lets you work with object metadata from any of the versioned or
// internal API objects. Attempting to set or retrieve a field on an object that does
// not support that field (Name, UID, Namespace on lists) will be a no-op and return
// a default value.
type Object interface {
	GetNamespace() string
	SetNamespace(namespace string)
	GetName() string
	SetName(name string)
	GetGenerateName() string
	SetGenerateName(name string)
	GetUID() types.UID
	SetUID(uid types.UID)
	GetResourceVersion() string
	SetResourceVersion(version string)
	GetGeneration() int64
	SetGeneration(generation int64)
	GetSelfLink() string
	SetSelfLink(selfLink string)
	GetCreationTimestamp() Time
	SetCreationTimestamp(timestamp Time)
	GetDeletionTimestamp() *Time
	SetDeletionTimestamp(timestamp *Time)
	GetDeletionGracePeriodSeconds() *int64
	SetDeletionGracePeriodSeconds(*int64)
	GetLabels() map[string]string
	SetLabels(labels map[string]string)
	GetAnnotations() map[string]string
	SetAnnotations(annotations map[string]string)
	GetFinalizers() []string
	SetFinalizers(finalizers []string)
	GetOwnerReferences() []OwnerReference
	SetOwnerReferences([]OwnerReference)
	GetManagedFields() []ManagedFieldsEntry
	SetManagedFields(managedFields []ManagedFieldsEntry)
}

```

**Comment by den3tsou** [comment]
Thanks for the confirmation! I was thinking if additional query is too expensive for each event. But I will see how it goes

**Comment by den3tsou** [comment]
Thanks for confirmaing this. I was thinking if making addtional request to get Namespace object is worth or not.

**Comment by arkodg** [comment]
yeah it should be fine, since this query is retrieving info from the local cache and not the API server
