### ISSUE TITLE
Gateway 504 timeout

### ISSUE THREAD

**Issue by lostz** [envoyproxy/gateway#1645]
This is my first time using it, and I currently have a 504 in my gateway log. Can you tell me how to modify it to solve this problem? Thank you.

**Comment by arkodg** [comment]
can you share more info @lostz 
* what configuration are applying in your cluster
* where are you seeing the `504`, in your client, in the envoy proxy pod ?

**Comment by lostz** [comment]
I installed it via Helm without making any configuration changes. I saw a 504 in the logs of the Envoy pod, and the client I used to send requests also received a 504 error code. The logs for the service requests I accessed are normal.

**Comment by arkodg** [comment]
hi @lostz , `504` is tied to timeout, which makes me think that the httproute->backend is not correctly configured
can you share the o/p of `kubectl get gateway class,gateways,httproutes -A -o yaml`
as well as the o/p of the backend service & deployment you are using as your backend

**Comment by arkodg** [comment]
please reopen @lostz if you are still seeing this issue
