### ISSUE TITLE
ci: e2e test is flaky

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1646]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

https://github.com/envoyproxy/gateway/actions/runs/5514681008/jobs/10054338746

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by tmsnan** [comment]
related issue #1616

**Comment by arkodg** [comment]
same as https://github.com/envoyproxy/gateway/issues/1616
