### ISSUE TITLE
Run `ValidateAll()` for Xds Resources before adding them to Xds Resource Table

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1647]
*Description*:

Run the `ValidateAll()` method associated with each resource (https://github.com/envoyproxy/go-control-plane/blob/25fcba6ee652be7c29ee36eb1b7cdbe0fd0e3b43/envoy/config/endpoint/v3/endpoint.pb.validate.go#L49) before adding them into the Xds Resource Table https://github.com/envoyproxy/gateway/blob/ab7aed6ad997216853325a64bdb708064e6de594/internal/xds/types/resourceversiontable.go#L66

Here is an example where it should be added 
https://github.com/envoyproxy/gateway/blob/ab7aed6ad997216853325a64bdb708064e6de594/internal/xds/translator/translator.go#L88

It is done in some functions such as for the EnvoyPatchPolicy https://github.com/envoyproxy/gateway/blob/ab7aed6ad997216853325a64bdb708064e6de594/internal/xds/translator/jsonpatch.go#L73
but should be done everywhere

**Comment by Ronnie-personal** [comment]
@arkodg  Could you assign the issue to me? I have created the PR.

Thanks!
