### ISSUE TITLE
Add Gateway Status Support 

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#165]
*Description*:
Add initial support for gateway status.

Depends on:

https://github.com/envoyproxy/gateway/pull/150
https://github.com/envoyproxy/gateway/pull/164

[optional *Relevant Links*:]
The implementation should follow [Contour's implementation](https://github.com/projectcontour/contour/blob/main/internal/status/gatewaystatus.go), and be consistent with the existing Kube provider [controllers](https://github.com/envoyproxy/gateway/tree/main/pkg/provider/kubernetes).

**Comment by skriss** [comment]
Note that much of this is already implemented in https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi, but there may be some additional infra-related status items that need to be computed.

**Comment by danehans** [comment]
All kube provider controllers need to write status back to kube API.

**Comment by danehans** [comment]
Although the resource translator can handle status updates, something still needs to `Update()` using kube client.
