### ISSUE TITLE
Add common tools for envoy

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/gateway#1657]
*Description*:
>At present, the gateway uses the `envoyproxy/envoy-dev:latest`  image by default, but the image is very streamlined (without basic tools such as `curl`, `netstat`, `tcpdump`, etc.), I think the gateway can add these basic commands  to recompile the basic envoy image , which will be convenient to use.
For example
The curl tool to frequently query the envoy's `/config_dump` and `/stats` interface.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
We have `egctl` to do such things

**Comment by tmsnan** [comment]
Thanks, `egctl` looks powerful, I will use etctl instead.

**Comment by zirain** [comment]
you can use egctl or just change image tag: https://www.envoyproxy.io/docs/envoy/latest/start/install#start-install-docker
