### ISSUE TITLE
Add support for RateLimitFilter in `egctl x translate`

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1668]
*Description*:
Add the ability to accept `RateLimitFilter` YAML as input in `egctl x translate` and output the corresponding xds resource similar to what is done in https://github.com/envoyproxy/gateway/pull/1659

**Comment by zirain** [comment]
is #1653 the right link?

**Comment by arkodg** [comment]
my bad, fixed :)

**Comment by slayer321** [comment]
Hey @arkodg , I did like to work on this issue.
