### ISSUE TITLE
followup: support more options from proxy metric

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1669]
1. stats_matcher https://github.com/envoyproxy/gateway/pull/1653#issuecomment-1633593610
2. HistogramBucketSettings https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto.html#config-metrics-v3-histogrambucketsettings

**Comment by tmsnan** [comment]
hi, i can help with that, plz assign

**Comment by zirain** [comment]
go for it @tmsnan

**Comment by arkodg** [comment]
moving this to v0.6.0-rc1

**Comment by tmsnan** [comment]
3. stats_tags https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#envoy-v3-api-msg-config-metrics-v3-tagspecifier，provide available tag extraction rules. releated #727

**Comment by zirain** [comment]
close this now, more features should be tracked one by one.
