### ISSUE TITLE
envoy-ratelimit error when envoy-gateway re-deploy

### ISSUE THREAD

**Issue by quyenhoang96** [envoyproxy/gateway#1692]
When I re-deploy new version of the envoy-gateway, the envoy-rate limit shows an error:

<img width="1699" alt="Screenshot 2023-07-23 at 11 41 35" src="https://github.com/envoyproxy/gateway/assets/120354221/f5cfaaae-89a2-4273-aec6-47a84b960770">

**Comment by zirain** [comment]
can you make sure of the upgrade strategy of EG？

**Comment by quyenhoang96** [comment]
> can you make sure of the upgrade strategy of EG？

Hi @zirain Zi What is EG's upgrade strategy?

**Comment by shawnh2** [comment]
hi @quyenhoang96 , do you mean the error `Failed to receive configuration from xDS Management Server: ...`?

this error is kind related to #1690, for now, the envoy-ratelimit does not get deleted/undeployed when envoy-gateway gets deleted/restart. 

so you can see after this error, envoy-ratelimit is connected to xDS Management server again. 

this error may be fixed after #1690 landed.

**Comment by quyenhoang96** [comment]
> hi @quyenhoang96 , do you mean the error `Failed to receive configuration from xDS Management Server: ...`?
> 
> this error is kind related to #1690, for now, the envoy-ratelimit does not get deleted/undeployed when envoy-gateway gets deleted/restart.
> 
> so you can see after this error, envoy-ratelimit is connected to xDS Management server again.
> 
> this error may be fixed after #1690 landed.

Hi @shawnh2 . Thank you. I will comeback when it is done.

**Comment by shawnh2** [comment]
hi @quyenhoang96 , the changes has been landed, you can retry it

**Comment by arkodg** [comment]
closing this issue for now, @quyenhoang96 please reopen if you see this issue again
thanks @shawnh2 for all the fixes related to this
