### ISSUE TITLE
Docs Publishing Strategy

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#17]
Should Envoy Gateway's documentation be separate from Envoy's [official docs](https://www.envoyproxy.io/docs/envoy/latest/) or integrate with https://github.com/envoyproxy/envoy-website

**Comment by kflynn** [comment]
I'll take this on, although it seems not possible to assign me right now. 😂

**Comment by danehans** [comment]
@mattklein123 @phlax @lizan I'm unable to assign @kflynn to the issue. Can someone advise?

**Comment by mattklein123** [comment]
I added explicit read access for the assignable team. I think that fixed it. Assigned.

**Comment by kflynn** [comment]
Thanks @mattklein123! #203 is a bare-bones first cut here.

**Comment by danehans** [comment]
xref
- updating contrib guide: https://github.com/envoyproxy/gateway/issues/295
- quickstart guide: https://github.com/envoyproxy/gateway/issues/275

**Comment by phlax** [comment]
i would say lets link it in initially - not sure exactly how/where - but i think that will be easiest

**Comment by arkodg** [comment]
@danehans @kflynn are we keeping this issue open to track eventually linking https://gateway.envoyproxy.io/v0.2.0/ to https://www.envoyproxy.io/docs ?

**Comment by danehans** [comment]
Let's keep our current strategy of using GH Pages to publish EG docs. If anyone disagrees, feel free to reopen.
