### ISSUE TITLE
Design document for Gateway Extension shows incorrect configuration

### ISSUE THREAD

**Issue by rinswind** [envoyproxy/gateway#1724]
The API reference is not enough to figure out how to implement an Envoy Gateway Extension.
The better source is the design document.
The configuration outlined in the document is now different from the API reference and no longer works:
https://github.com/envoyproxy/gateway/blob/main/docs/latest/design/extending-envoy-gateway.md?plain=1#L50

**Comment by arkodg** [comment]
thanks for trying this out, ive also raised https://github.com/envoyproxy/gateway/issues/1726 which should help users get started with the extension manager framework easily
