### ISSUE TITLE
Handle Backend Pod Upgrades

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1743]
If 2 backend pods are undergoing a rolling restart, add outlier detection and retry settings in Envoy proxy to ensure no traffic intended for the backend is dropped

**Comment by tanujd11** [comment]
Since we have clusterIP as backend to the envoy gateway, Isn't it k8s service responsibility to do this. What am I missing here?

**Comment by arkodg** [comment]
@tanujd11 you're right now, at this point, this is moot since we have only have ClusterIP endpoint, but once EndpointSlice support (https://github.com/envoyproxy/gateway/pull/1494) lands, we'll have to handle the case where the control plane / EG is not fast enough to propagate current `Ready` endpoints to Envoy Proxy so we'll need to add some mechanism in Envoy to deal with this eventual consistency such as outlier detection and trying out another endpoint in the xds cluster

**Comment by tanujd11** [comment]
Hi @arkodg I can pick this up. Since we have EndpointSlice support enabled, What about having outlierDetection API in backendTrafficPolicy API?
