### ISSUE TITLE
XDS connections need TCP keepalives

### ISSUE THREAD

**Issue by jackkleeman** [envoyproxy/gateway#1746]
*Description*:
It is possible for XDS connections to half close, leaving envoy pods without config. This is well documented in other XDS implementations and is generally resolved with keepalives:
https://github.com/envoyproxy/envoy/issues/6323
https://github.com/projectcontour/contour/pull/1746

**Comment by arkodg** [comment]
+1
subset of https://github.com/envoyproxy/gateway/issues/1565
