### ISSUE TITLE
Improve visual representation of the docs website

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1752]
*Description*:

The EG docs website https://gateway.envoyproxy.io/ can be visually improved by adding styling in the current docs infra based on `sphinx` https://www.sphinx-doc.org/en/master/usage/theming.html  or we can also consider using another tool such as Hugo https://gohugo.io/hugo-modules/theme-components/

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers on which direction to take

**Comment by zirain** [comment]
prefer to move use [Hugo](https://gohugo.io/) or https://docusaurus.io/

**Comment by Xunzhuo** [comment]
> prefer to move use [Hugo](https://gohugo.io/) or https://docusaurus.io/

+1

**Comment by arkodg** [comment]
@zirain @Xunzhuo any idea on the rough estimate on how much time such a refactor (to `hugo`) might take ?

**Comment by zirain** [comment]
should put this into Summer LFX.
