### ISSUE TITLE
Add @qicz to maintainers

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1759]
*Description*:

After @qicz becomes eg reviewer, he continues to actively contribute feature/refactor/fixes and code reviews to eg. Also he is engaging to put EG in production and we recieved many valuable feedbacks from real production environment.

So I want to sponsor his maintainer membership, and hopes him can continuely contribute to eg and makes more values in new role.

PRs from him: https://github.com/envoyproxy/gateway/commits?author=qicz

cc @envoyproxy/gateway-maintainers

**Comment by AliceProxy** [comment]
+1, he has definitely earned a spot in my opinion

**Comment by Xunzhuo** [comment]
cc @zirain @skriss, hey forks, it would be great to hear from you.

**Comment by zirain** [comment]
+1 from me
