### ISSUE TITLE
TLS termination breaks jwt authenticaton

### ISSUE THREAD

**Issue by dukes7gh** [envoyproxy/gateway#1768]
*Description*:
When jwt authentication filter is applied to a HTTP route while TLS termination is used all the routes become unavailable returning 404. TLS termination seems to break GRPC routes also with the latest build when jwt filter is included.

*Repro steps*:
[tls-term-jwt.yaml.txt](https://github.com/envoyproxy/gateway/files/12270129/tls-term-jwt.yaml.txt)

* Relevant Links
https://gateway.envoyproxy.io/v0.5.0/user/secure-gateways.html
https://gateway.envoyproxy.io/v0.5.0/user/authn.html
https://github.com/envoyproxy/gateway/pull/1720

**Comment by tanujd11** [comment]
@arkodg I can take a look at this.
