### ISSUE TITLE
Allow custom (-options in the) Service object - allocateLoadBalancerNodePorts: false

### ISSUE THREAD

**Issue by dihmandrake** [envoyproxy/gateway#1772]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Allow for custom `Service` (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#servicespec-v1-core) objects to be provided in `KubernetesServiceSpec` (https://gateway.envoyproxy.io/latest/api/config_types.html#kubernetesservicespec) instead of only `ServiceType`.
The only aspect overridden by Envoy Gateway would need be the `selector` object in the `Service`.
Having the Service object exposed to configuration allows for all sorts of custom deployments .

Specifically, I am looking for a way to support `allocateLoadBalancerNodePorts: false`.
Likely others will also start to look into custom: `loadBalancerClass` or other options.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

See: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation

**Comment by arkodg** [comment]
thanks for raising this issue @dihmandrake, seeing 2 ways to solve your specific case of setting `allocateLoadBalancerNodePorts: false` when managed Envoy Proxy Service is of type `LoadBalancer`
* Can all external load balancer implementations (AWS, GKE etc) work with `allocateLoadBalancerNodePorts: false` ? If yes, we can just set this by default, and a user can use service type `NodePort` to enable node ports
* start supported BYO Envoy Proxy service and deployment sooner than later https://github.com/envoyproxy/gateway/issues/1379

**Comment by arkodg** [comment]
@dihmandrake whether `allocateLoadBalancerNodePorts` makes it into https://gateway.envoyproxy.io/v0.5.0/api/config_types.html#kubernetesservicespec, is tied to how many users using this project need to configure this. lets leave this issue open so we can track this.

this is where BYO solves the project maintenance / support problem of providing an alternative to enable all user needs w/o having to maintain the API / logic in the project. I do agree, this approach comes with a lot of gotchas

**Comment by zirain** [comment]
do EG need check the version of kubernetes cluster?

**Comment by arkodg** [comment]
dont think so, since feature is stable from v1.24 https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation

**Comment by zirain** [comment]
> dont think so, since feature is stable from v1.24 https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation

that sounds good.

**Comment by den3tsou** [comment]
Can I help with this please? If I understand correctly, we would like to add one additional field `KubernetesServiceSpec. allocateLoadBalancerNodePorts`. Is it correct?

**Comment by zirain** [comment]
@den3tsou Thanks for the help.
