### ISSUE TITLE
Why does Helm charts crds folder has Deployments?

### ISSUE THREAD

**Issue by tamalsaha** [envoyproxy/gateway#1773]
*Description*:
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/crds/gatewayapi-crds.yaml#L9195-L9440

As you can see helm crds folder has Deployment, and other types of resources. It should only have crds. What is going on here?

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by zirain** [comment]
this's a known issue, plan to remove in v0.6.

**Comment by arkodg** [comment]
should be fixed with https://github.com/envoyproxy/gateway/issues/1721

**Comment by arkodg** [comment]
should be fixed once we import upstream gateway api v1.0, which does not include any deployments or resources, relates to https://github.com/kubernetes-sigs/gateway-api/pull/2401

**Comment by tamalsaha** [comment]
Thanks. But my understanding is that further changes will be needed the envoy/gateway helm chart to install the webhook deployment. Is that correct?

**Comment by arkodg** [comment]
@tamalsaha webhooks based validation has been replaced by CEL based validation which is baked into the CRD schema itself.
