### ISSUE TITLE
Support non-root user for Gateway

### ISSUE THREAD

**Issue by tamalsaha** [envoyproxy/gateway#1775]
*Description*:
We are using Envoy Gateway in a cluster where all pods must run as non-root user. I understand that means Gateway won't be able to use ports < 1024. This is ok in our case since all the ports are used to expose various TCP services via a Gateway. 

We would like a way to configure this for the Deployment generated by the controller and set `securityContext`.

Thanks!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
should be possible today with https://gateway.envoyproxy.io/v0.5.0/api/config_types.html#kubernetescontainerspec
similar examples in https://gateway.envoyproxy.io/v0.5.0/user/customize-envoyproxy.html#customize-envoyproxy-deployment-resources

closing this issue for now, please reopen if these links dont solve your issue
