### ISSUE TITLE
Prometheus stats not working with EG generated cluster names

### ISSUE THREAD

**Issue by psinghal20** [envoyproxy/gateway#1785]
*Description*:
>What issue is being seen? 

Incorrect Prometheus metric names being generated by Envoy because of cluster names having the hostnames.

EG generates cluster names by appending hostnames(exposed in the HTTPRoute). For example, Cluster names in EG look like this: `default/backend/rule/0/match/0-www.example.com`.

When generating cluster metrics, Envoy uses these cluster names. The problem comes when Envoy tries to convert them to Prometheus expected format. Envoy generates the metrics in the format `cluster.default/backend/rule/0/match/0-www.example.com.upstream_cx_total: 12` which, when get converted to Prometheus metrics, are converted to `envoy_cluster_example_com_upstream_cx_total{cluster_name="default/backend/rule/0/match/0-www"}`.  Notice the incorrect metric name and cluster name in the above exposed metric in prom stats.

The incorrect translation is due to Envoy assuming that cluster names will not have `.`. Envoy breaks the initial metric name at the first period and takes the first part as the cluster name and the rest as the metric name. This leads to the cluster name being incorrectly parsed as `default/backend/rule/0/match/0-www` and the metric name as `example_com_upstream_cx_total`.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Instal EG and enable Prometheus by adding an Envoy Proxy config provided here: https://raw.githubusercontent.com/envoyproxy/gateway/latest/examples/kubernetes/metric/prometheus.yaml

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

Latest master

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by arkodg** [comment]
thanks for finding this issue, let me look into this

**Comment by tmsnan** [comment]
https://github.com/envoyproxy/gateway/issues/1669#issuecomment-1653011042 。We need some constraints, set a custom regular extractor.

**Comment by arkodg** [comment]
@tmsnan  the issue is we rely on IR Route Name (which appends host)
https://github.com/envoyproxy/gateway/blob/c0a619ca85c916658424d6b74870744bf14a4f1d/internal/gatewayapi/route.go#L513 which is in turn used as the xds cluster name https://github.com/envoyproxy/gateway/blob/c0a619ca85c916658424d6b74870744bf14a4f1d/internal/xds/translator/translator.go#L177

im refactoring the code to provide a new name field for a IR RouteDestination so its not linked to IR HTTPRoute

**Comment by tmsnan** [comment]
@arkodg Add some special fields after the host, so that the custom extraction can be completely extracted, of course, this is a bit of a hack. In actual use, it is also very useful if the host can be added to the metric.
