### ISSUE TITLE
Support Multiple RequestMirror filters per HTTPRoute Rule

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1811]
*Description*:

* Allow the user to specify multiple https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRequestMirrorFilter within a single rule

Changes needed
* Create a Mirror Backend/ IR RouteDestination per Filter https://github.com/envoyproxy/gateway/blob/4285f4e269ff309e81ec24b2f80fa9b5343f6a8f/internal/gatewayapi/filters.go#L810, possibly using `filterIdx` as a unique identifier
* Make the Mirror field a list in https://github.com/envoyproxy/gateway/blob/4285f4e269ff309e81ec24b2f80fa9b5343f6a8f/internal/ir/xds.go#L264

* Build a new xds mirror policy per mirror route destination https://github.com/envoyproxy/gateway/blob/4285f4e269ff309e81ec24b2f80fa9b5343f6a8f/internal/xds/translator/route.go#L296

**Comment by Ronnie-personal** [comment]
Hi @arkodg 
I would like to understand further on this issue.

We need to modify the Name by adding the third parameter 'filterIdx'? Where do we obtain filterIdx?
				`filterContext.Mirror = &ir.RouteDestination{
					Name: fmt.Sprintf("%s-mirror", irRouteDestinationName(filterContext.Route, filterContext.RuleIdx)),
				}`

Do we need to change the signature for the 'buildXdsRequestMirrorPolicies' function?

**Comment by arkodg** [comment]
thanks for looking into this @Ronnie-personal, assigning this to you for now

the filterIdx can be set when the context is created in https://github.com/envoyproxy/gateway/blob/4285f4e269ff309e81ec24b2f80fa9b5343f6a8f/internal/gatewayapi/filters.go#L38

and yes the signature for `buildXdsRequestMirrorPolicies` will change

**Comment by arkodg** [comment]
rethinking again, maybe the filterIdx can be directly passed here https://github.com/envoyproxy/gateway/blob/4285f4e269ff309e81ec24b2f80fa9b5343f6a8f/internal/gatewayapi/filters.go#L100

**Comment by Ronnie-personal** [comment]
Am I on the right track with the following code changes?

`func buildXdsRequestMirrorPolicies(mirrorDestinations []*ir.RouteDestination) []*routev3.RouteAction_RequestMirrorPolicy {
	var mirrorPolicies []*routev3.RouteAction_RequestMirrorPolicy
	for _, mirrorDest := range mirrorDestinations {
		mirrorPolicies = append(mirrorPolicies, &routev3.RouteAction_RequestMirrorPolicy{
			Cluster: mirrorDest.Name,
		})
	}
	return mirrorPolicies
}`

**Comment by arkodg** [comment]
@Ronnie-personal it's easier to add feedback on PRs, can you please raise one

**Comment by Ronnie-personal** [comment]
Sure, I will raise draft PR.
