### ISSUE TITLE
Integrate david-martin / gateway-api-state-metrics in docs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1823]
*Description*:
@david-martin has created a Grafana dashboard to help monitor Gateway API resource https://github.com/david-martin/gateway-api-state-metrics. This dashboard aggregates resource status conditions and can serve to improve Day 2 operations at scale. 

Taking a quick look at the repo, it should work out of the box with Envoy Gateway, since the metrics are based off the K8s API server.

We could add a docs page to show integration with this dashboard

**Comment by david-martin** [comment]
I've been able to get the metrics & dashboard working with Envoy Gateway.
I followed the Installation guide from [here](https://gateway.envoyproxy.io/latest/user/quickstart.html#installation), using a local kind cluster

Commands:
```bash
kind create cluster
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace
kubectl wait --timeout=5m -n envoy-gateway-system deployment/envoy-gateway --for=condition=Available
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/latest/quickstart.yaml -n default
```

Then followed the README from [here](https://github.com/david-martin/gateway-api-state-metrics/tree/main/examples/kube-prometheus#kube-prometheus-example) with that repo cloned locally.

Here's the GatewayClasss dashboard I got
![image](https://github.com/envoyproxy/gateway/assets/878251/8428e74f-7c37-41e6-8b8a-550807814c84)

I noticed the defintion of 'Unhealthy' gateways I went with could be wrong depending on the implementation of gatway.status.conditions. I made the assumption that a healthy Gateway has an Accepted and Programmed state. Perhaps I'm misunderstanding [the spec](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayStatus).
Easy to adjust the queries here.
![image](https://github.com/envoyproxy/gateway/assets/878251/f52bd4c1-3100-4854-9ade-db613385774f)

```prometheus
count((gatewayapi_gateway_status{type="Accepted"} == 0) or (gatewayapi_gateway_status{type="Programmed"} == 0)) or vector(0)
```

**Comment by arkodg** [comment]
hey @david-martin, thanks for building out the dashboards, and also trying it out with Envoy Gateway

From the the commands youve run, it looks like you may not have deployed a bare metal loadbalancer, which is required since by default the `ServiceType` is `Loadbalancer` for the managed Envoy Proxy service. (you can also [change this](https://gateway.envoyproxy.io/v0.5.0/user/customize-envoyproxy.html) to `ClusterIP` or `NodePort` if you'd like to)

you could install one by running `make create-cluster` which creates a kind cluster and deploys metallb.

I tend to test with Docker Desktop K8s which has its own LB implementation. Here's what the `Gateway` looks like which does have the `Programmed` condition to be set to `True`
```
$ kubectl get gateway -A -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1beta1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"eg","namespace":"default"},"spec":{"gatewayClassName":"eg","listeners":[{"name":"http","port":80,"protocol":"HTTP"}]}}
    creationTimestamp: "2023-08-21T22:53:08Z"
    generation: 1
    name: eg
    namespace: default
    resourceVersion: "56394"
    uid: b4e901cc-f16c-4750-b160-50f968c7de9f
  spec:
    gatewayClassName: eg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
  status:
    addresses:
    - type: IPAddress
      value: 127.0.0.1
    - type: Hostname
      value: localhost
    conditions:
    - lastTransitionTime: "2023-08-21T22:53:08Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-08-23T07:58:01Z"
      message: Address assigned to the Gateway, 1/1 envoy Deployment replicas available
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    listeners:
    - attachedRoutes: 1
      conditions:
      - lastTransitionTime: "2023-08-21T22:53:08Z"
        message: Sending translated listener configuration to the data plane
        observedGeneration: 1
        reason: Programmed
        status: "True"
        type: Programmed
      - lastTransitionTime: "2023-08-21T22:53:08Z"
        message: Listener has been successfully translated
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      name: http
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      - group: gateway.networking.k8s.io
        kind: GRPCRoute
kind: List
metadata:
  resourceVersion: ""
```

**Comment by arkodg** [comment]
glad it works now !

raised https://github.com/envoyproxy/gateway/pull/1849 to ensure others dont hit this again

yeah https://github.com/envoyproxy/gateway/tree/main/docs/latest/user is a good spot to add these installation steps
