### ISSUE TITLE
Enable selecting zipkin tracing provider

### ISSUE THREAD

**Issue by basvanbeek** [envoyproxy/gateway#1827]
*Description*:
Currently Envoy Gateway only supports the OpenTelemetry tracer, this makes EG unsuitable to plug into platforms where other solutions are being used (especially regarding trace context propagation). Some may want to transition to OpenTelemetry in the future but others have significant investments in other solutions (often using the B3 context propagation standard from the Zipkin ecosystem) or use tracing ecosystems that simply can't be supported by OpenTelemetry (e.g. Apache SkyWalking).

As an ingress typically is the location where also the sampling decision is made, it is very important to support at least the core instrumentation that Envoy supports. At the very least start with Zipkin (for B3 propagation) and SkyWalking (native instrumentation is not OTel compatible)

**Comment by zirain** [comment]
cc @arkodg
