### ISSUE TITLE
Allow to set Service LoadBalancer IP

### ISSUE THREAD

**Issue by mazzy89** [envoyproxy/gateway#1841]
*Description*:
At the current state it is not possible to set to the created Service LoadBalancer an user static IP address. The property is not exposed. 

There are cases in various cloud providers like GCP where it is possibile to create a static IP address and reference it around.

There is a TODO in the EnvoyProxy ServiceSpec.

**Comment by mazzy89** [comment]
I don't think it should be hard to set so I can wire a PR.

**Comment by arkodg** [comment]
it looks like `loadBalancerIP` is deprecated https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
looking at the GKE docs https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer-parameters can you achieve the same by using a `networking.gke.io/internal-load-balancer-subnet` annotation to specify a /32 subnet (`10.11.12.13/32`)?

**Comment by arkodg** [comment]
yes you could always use GKE gateway but you'd be missing out on the extensive features in Envoy Gateway :) 

even Envoy Gateway supports `Gateway.Spec.Addresses` but it doesnt affect the Cloud Loabalancer

curious why `networking.gke.io/internal-load-balancer-subnet` won't work, my guess is, if you submit subnet to be 1 IP (/32 range for IPv4) , then the service must be assigned that IP

**Comment by mazzy89** [comment]
As said above I have a public IP v4. That annotation is internal subnet. Doesn't not relate at all with public IP addresses.

**Comment by arkodg** [comment]
ah yes, thanks for the clarification

**Comment by mazzy89** [comment]
Then I think the way to go would be as the approach proposed done by Google https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#use_a_named_ip_address where the IP address would be referenced as a named IP address. However this would be a GCP only approach. what do you think?

**Comment by arkodg** [comment]
I dont think above approach will work, the `Gateway` defined is tied to a GKE GatewayClass `gke-l7-rilb` which is tied to a GKE controller which is probably doing some magic under the hood to stitch together a path from the Google LB to the Loadbalancer Gateway service

**Comment by mazzy89** [comment]
Sure. The logic there is tight to GKE but so would be also ours. I mean the logic in the envoy gateway controller would be: get the IP address from GCP using the named address, assign this IP to the Service LoadBalancer. This last part I'm sure it should be vendor agnostic and Kubernetes sig-network group has some idea how to achieve that. I haven't looked at it yet.

**Comment by arkodg** [comment]
Envoy Gateway supports the ability to set an address to the Gateway https://gateway.envoyproxy.io/v0.5.0/user/gateway-address.html which translates to `Service.Spec.ExternalIPs` , so If we set `Gateway.Spec.Addresses` to above NamedAddress, traffic will def enter Envoy Proxy pods, but the question is who is guaranteeing that traffic with DST IP set to NamedAddress is actually entering the k8s cluster

**Comment by mazzy89** [comment]
We would still need to implement in the envoy gateway controller gcp vendor logic to make sure that in the provider THAT named ip addr is set to the provider LB.

**Comment by AliceProxy** [comment]
+1 IMO we definitely need a way to support configuring this on a per-gateway basis, even if it is only a temporary solution since even though the field is deprecated, it is still the main way that GKE users assign IPs to LB services.

cc @LanceEa if you want to add any other comments or ideas/suggestions to this conversation

**Comment by haq204** [comment]
> Limits support for multiple Gateways that are provisioned per EG instance since the EnvoyProxy config is shared* and only attaches to the GatewayClass today - (I think there is an open issue to address this though)

yea there's a [GEP](https://gateway-api.sigs.k8s.io/geps/gep-1867/) to add parametersRef to gateway to configure per-gateway infrastructure. Once that's in place, we can start attaching EnvoyProxy on Gateways which would be pretty useful here.

I would even make an argument that staticIP should be a first class field for gateway infrastructure.

**Comment by arkodg** [comment]
thanks for the details @LanceEa, based on the fact that the field is not going to be removed any time soon, im okay with EG adding support for it. 

reg outage due to DNS record going stale, recommend External DNS + Gateway API integration :)
https://gateway.envoyproxy.io/v0.5.0/user/tls-cert-manager.html#using-externaldns
