### ISSUE TITLE
How to upgrade Envoy Gateway use helm

### ISSUE THREAD

**Issue by alvin-7** [envoyproxy/gateway#1867]
*Description*:

I have use helm to install Envoy Gateway in my k8s cluster.
But I want to use helm to upgrade my values.yaml, but I can't find this document.

I try to use `helm upgrade eg oci://docker.io/envoyproxy/gateway-helm -f values.yaml`, but it can't work.

**Comment by shawnh2** [comment]
you can use helm upgrade like this:

```bash
helm upgrade -f charts/gateway-helm/values.yaml -n envoy-gateway-system eg ./charts/gateway-helm
```

assign the charts to your local `./charts/gateway-helm`.

**Comment by alvin-7** [comment]
> you can use helm upgrade like this:
> 
> ```shell
> helm upgrade -f charts/gateway-helm/values.yaml -n envoy-gateway-system eg ./charts/gateway-helm
> ```
> 
> assign the charts to your local `./charts/gateway-helm`.

I only maintained the values.yaml file containing the fields I wanted to modify. 
If using this command, the error Error: UPGRADE FAILED: template: gateway-helm/templates/envoy-gateway-metrics-service.yaml:14:12: executing "gateway-helm/templates/envoy-gateway-metrics-service.yaml" at <.Values.envoyGatewayMetricsService.ports>: nil pointer evaluating interface {}.ports will appear. 

It seems that if a variable is not written to the values.yaml file, it will have the default value.

**Comment by shawnh2** [comment]
the `values.yaml` file in `/charts/gateway-helm` is a generated file.

if you want to use the `values.yaml` file in `/charts/gateway-helm`, you should modify `values.tmpl.yaml` first, and then using `make helm-generate` to generate the `values.yaml`. after this, the `helm upgrade` make sence.

**Comment by shawnh2** [comment]
Hear no respond, close it for now, feel free to repoen if there's still issue.
