### ISSUE TITLE
Test: UT is flaky

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1868]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

https://github.com/envoyproxy/gateway/actions/runs/6079605681/attempts/1

**Comment by yigang01** [comment]
hi,xunzhuo,Can you assign this to me @Xunzhuo

**Comment by Xunzhuo** [comment]
https://github.com/envoyproxy/gateway/actions/runs/6167029866/job/16737390752

**Comment by yigang01** [comment]
> 
The reason for the error is the same, but the information has increased and I still haven't replicated it locally. Let me take a look at this error first

**Comment by shawnh2** [comment]
The logs for this run have expired and are no longer available. So closing this issue, we can reopen another if running into it.
