### ISSUE TITLE
Support retries

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1907]
*Description*:

Add retry settings to be able to retry making requests to a backend

Relates to
* https://github.com/kubernetes-sigs/gateway-api/issues/1731
* https://github.com/envoyproxy/gateway/issues/1821#issuecomment-1729935509
* https://github.com/envoyproxy/gateway/pull/1899#issuecomment-1725910504

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
need something like TimeoutPolicy on upstream?

**Comment by arkodg** [comment]
@zirain, based on @kflynn's comment [here](https://github.com/envoyproxy/gateway/issues/1821#issuecomment-1729935509) we should try and implement in this project as a top level field within `BackendTrafficPolicy`

**Comment by zirain** [comment]
oh, may bad, there's only one client(the proxy) in ingress mode.
yes, we can put retries under `BackendTrafficPolicy `.
