### ISSUE TITLE
AttachedRoutes not necessarily on accepted routes and listeners

### ISSUE THREAD

**Issue by tanujd11** [envoyproxy/gateway#1916]
*Description*:
With the PR given below, change in Listener or Route status does not impact successful attachment. At the moment we only increment this count when route and listener is accepted.

[optional *Relevant Links*:]
https://github.com/kubernetes-sigs/gateway-api/pull/2396

**Comment by danehans** [comment]
xref https://github.com/kubernetes-sigs/gateway-api/pull/2477 adds a conformance test upstream that exercises the attachedRoutes spec [update](https://github.com/kubernetes-sigs/gateway-api/pull/2396).

**Comment by danehans** [comment]
@arkodg this issue is more involved than what I expected so please unassign me. I created the above draft PR that can be used as guidance for a proper PR to fix this issue.
