### ISSUE TITLE
Panic because of invalid result during xDS translation

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#1917]
*Description*:
When integrating Envoy Gateway and Envoy Gateway Extension service, I observed that during the xDS translation result, when an error occurred, it would be panicking because there was some operation to the result variable before the error check.
https://github.com/envoyproxy/gateway/blob/7d9e16e4997e7118d70ea910a6ef9d0732426878/internal/xds/translator/runner/runner.go#L80-L98

*Repro steps*:

In my scenario, we can simply produce an error from one of the hooks registered through the Envoy Gateway Extension service. Then you will see Envoy Gateway no longer up and running because of panicking.

*Environment*:
Tested on Envoy Gateway v0.5.0, but the code also persists in the main branch.

*Logs*:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1792a64]

goroutine 97 [running]:
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate.func1({{0x400086d170?, 0x1733654?}, 0x78?, 0x4000138f50?})
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:79 +0x1a4
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...](0x2112300, 0x4000d4df88?)
        /home/runner/work/gateway/gateway/internal/message/watchutil.go:36 +0x104
github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).subscribeAndTranslate(0x40003ba180, {0x20f19b8?, 0x4000528410?})
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:52 +0x70
created by github.com/envoyproxy/gateway/internal/xds/translator/runner.(*Runner).Start
        /home/runner/work/gateway/gateway/internal/xds/translator/runner/runner.go:45 +0x1f8
```

*Expectation*:

The error during xDS translation should be returned and logged instead of panicking.

**Comment by arkodg** [comment]
cc @AliceProxy @haq204 since this is only seen with the extension service

**Comment by ardikabs** [comment]
hi @arkodg , could I pick this one up for the fix?

**Comment by arkodg** [comment]
sure @ardikabs , thanks !
