### ISSUE TITLE
Support FQDN Address Type in EndpointSlice

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1922]
*Description*:
We've recently added support for EndpointSlice, and current only support Static IPv4 Endpoint Addresses
We should also add support for FQDN address types 
https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#address-types

[optional *Relevant Links*:]

* looks like no changes are needed in the gateway api layer https://github.com/envoyproxy/gateway/blob/8f138f5ffdb050e4d61bee2328f27d1fe7303835/internal/gatewayapi/route.go#L1043
* in the xds translator layer, we'd need to detect whether the endpoint is a static address or FQDN and pass the right endpoint type (Static or DNS) https://github.com/envoyproxy/gateway/blob/8f138f5ffdb050e4d61bee2328f27d1fe7303835/internal/xds/translator/translator.go#L219
* Above step may require splitting up endpoints in multiple clusters if we need to handle mix endpoints (some static and some DNS)

**Comment by arkodg** [comment]
this is a good alternative to supporting ExternalName in Service

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/issues/873

**Comment by shawnh2** [comment]
hi, interested in picking this one up, assign please.

**Comment by arkodg** [comment]
thanks @shawnh2, recommend working on top of the changes introduced by https://github.com/envoyproxy/gateway/pull/1947

**Comment by EltonzHu** [comment]
@arkodg I think this approach has the same security risks as using externalName service. Does Envoy gateway community approve this feature design?

Thank you!

**Comment by arkodg** [comment]
can you elaborate on the security risk here ?

**Comment by EltonzHu** [comment]
> can you elaborate on the security risk here ?

Sure. 

These security issues are mainly related to ingress:
- Any DNS name can be resolved to sensitive IPs that may expose content the proxy has access to but is not supposed to expose. 
- DNS resolution to 127.0.0.1 attack which can break into Envoy admin endpoint. Hopefully the Envoy community can fix this [Admin Endpoint Security issue](https://github.com/envoyproxy/envoy/issues/2763).
- Because of the way kube DNS works, if you know the name of a service and the name of the namespace it's in, you can use a servicename.svc.namespace.cluster.local ExternalName to expose it, and, unless you have good NetworkPolicy and a CNI that enforces it correctly, the proxy will allow it.

Ref: Above are summarized from [link](https://github.com/kubernetes-sigs/gateway-api/discussions/1837#discussioncomment-5363846).

**Comment by arkodg** [comment]
Yes above security concerns have been mitigated because the definition of a FQDN endpoint has moved from a less privileged resource ( Service ) to a more privileged resource ( EndpointSlice) which only a few have access to edit

**Comment by EltonzHu** [comment]
> Yes above security concerns have been mitigated because the definition of a FQDN endpoint has moved from a less privileged resource ( Service ) to a more privileged resource ( EndpointSlice) which only a few have access to edit

Thanks @arkodg for the confirmation. 
Three more questions.
1. If we go with this EndpointSlice solution, any K8S clusters version below 1.21 can not be supported. Any other work around for those clusters?
2. @shawnh2 Any ETA for this feature implementation? Is this going to be included in the next release 0.6?
3. I was looking into the code. It is doable as @arkodg mentioned it in the above. However, which Envoy cluster type we are going to pick for EndpointSlice with FQDN type? Stric DNS or Logical DNS? Either of them can be applied depends on the DNS configuration externally. I did not see any discussion about handlering Envoy cluster type above. I am thinking to use annotation to address this problem. What do you think? @arkodg @shawnh2

**Comment by shawnh2** [comment]
1. We have a [compatibility matrix](https://gateway.envoyproxy.io/blog/2022/10/01/versions/) for Envoy Gateway, the lowest Kubernetes version we support is v1.24.
2. I will take a further look into this issue about this week, but I shall assume this feature wont be in the next release 0.6.

**Comment by EltonzHu** [comment]
@arkodg @shawnh2 Looks like K8S community is still considering deprecate FQDN type from endpointslice as seen in the head of the main branch from K8S repo: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/discovery/endpointslice/strategy.go#L221

Are you guys aware of this?

**Comment by arkodg** [comment]
looks like you already found the issue https://github.com/kubernetes/kubernetes/issues/114210 @EltonzHu, its still being discussed

**Comment by EltonzHu** [comment]
> looks like you already found the issue [kubernetes/kubernetes#114210](https://github.com/kubernetes/kubernetes/issues/114210) @EltonzHu, its still being discussed

Yes. Thank you for the confirmation. @arkodg

**Comment by shawnh2** [comment]
https://github.com/envoyproxy/gateway/blob/fb9cb18c94b03751a3dbcae9dcfa639d1d61213a/internal/gatewayapi/route.go#L1140-L1143

assume you have two endpointslices that associate with one service, one is IP address type, the other is FQDN address type. all the endpoints in these two endpointslices will be mixed into one vector via above function.

in the xds translator layer, should we separate the endpoints by its address type? and create a different xds cluster for each address-type endpoints? in that case, how to associate these xds clusters with only one xds route?

IMHO, the `static` type endpoint is fine. the [EDS cluster type](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#endpoint-discovery-service-eds) supports the [endpoint address field](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-address) to be a FQDN type address. so maybe we don't have to detect whether the endpoint type is a static or FQDN.

https://github.com/envoyproxy/gateway/blob/fb9cb18c94b03751a3dbcae9dcfa639d1d61213a/internal/xds/translator/cluster.go#L46-L47

cc @arkodg

**Comment by EltonzHu** [comment]
> https://github.com/envoyproxy/gateway/blob/fb9cb18c94b03751a3dbcae9dcfa639d1d61213a/internal/gatewayapi/route.go#L1140-L1143
> 
> assume you have two endpointslices that associate with one service, one is IP address type, the other is FQDN address type. all the endpoints in these two endpointslices will be mixed into one vector via above function.
> 
> in the xds translator layer, should we separate the endpoints by its address type? and create a different xds cluster for each address-type endpoints? in that case, how to associate these xds clusters with only one xds route?
> 
> IMHO, the `static` type endpoint is fine. the [EDS cluster type](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#endpoint-discovery-service-eds) supports the [endpoint address field](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-address) to be a FQDN type address. so maybe we don't have to detect whether the endpoint type is a static or FQDN.
> 
> https://github.com/envoyproxy/gateway/blob/fb9cb18c94b03751a3dbcae9dcfa639d1d61213a/internal/xds/translator/cluster.go#L46-L47
> 
> cc @arkodg


From [EDS cluster type](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#endpoint-discovery-service-eds)
![image](https://github.com/envoyproxy/gateway/assets/42920376/c5260cf2-0354-48ea-878d-e17d613e17c3)
From [endpoint address field](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-socketaddress)
![image](https://github.com/envoyproxy/gateway/assets/42920376/74f2681a-d431-46cf-8af0-62bb6bc86650)

Above information show that address inside EDS must be an IP, so we can not use EDS for address type as an FQDN.

**Comment by EltonzHu** [comment]
Regarding this case "User have two endpointslices that associate with one service, one is IP address type, the other is FQDN address type. ",
we can use weight balancing from the routing layer in technical stand point. However, from the practice of using L7 proxy, we should not allow this kind of configuration.

**Comment by arkodg** [comment]
agree with @EltonzHu 
@shawnh2 lets keep it simple for now, if `EndpointSlice` contains mixed endpoint types (`Static` & `FQDN`), lets set  the status `ResolvedRefs=False` and discontinue processing the backendRef
