### ISSUE TITLE
e2e test is flaky in CI

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1932]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

https://github.com/envoyproxy/gateway/actions/runs/6431169623/job/17463786201

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

```
    --- FAIL: TestE2E/RateLimit (2.13s)
        --- FAIL: TestE2E/RateLimit/block_all_ips (2.06s)
```

**Comment by ardikabs** [comment]
this is also happening on my PR, https://github.com/envoyproxy/gateway/actions/runs/6416541986/job/17420861887#step:6:2904.

```
    --- FAIL: TestE2E/RateLimitBasedJwtClaims (1.46s)
        --- FAIL: TestE2E/RateLimitBasedJwtClaims/ratelimit_based_on_jwt_claims (1.33s)
```

**Comment by shawnh2** [comment]
The logs for this run have expired and are no longer available. So closing this, we can open another issue if running into it.
