### ISSUE TITLE
Conformance: Set ResolvedRefs Condition by Default

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#1956]
The `ResolvedRefs` gateway listener status condition should be set to `true` by default.

xref: https://github.com/kubernetes-sigs/gateway-api/pull/2247

**Comment by arkodg** [comment]
welcome back @danehans :)

**Comment by Xunzhuo** [comment]
Welcome back @danehans ！

**Comment by zirain** [comment]
Welcome back @danehans

**Comment by zhaohuabing** [comment]
It's nice to see you again here @danehans
