### ISSUE TITLE
Add CEL validation tests for xPolicy resources

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1964]
*Description*:
We've recently started add CEL validations in our APIs e.g. https://github.com/envoyproxy/gateway/pull/1961
Would be great to add validation tests so its easier to understand what works and what doesnt
Here's an example of how upstream does it https://github.com/kubernetes-sigs/gateway-api/blob/2b9aeb0c7fa3d558e42074486c230406e7ac80ce/pkg/test/cel/grpcroute_test.go#L416

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
we should add valiation for other EG CRDs.
