### ISSUE TITLE
Update Community Meeting Time

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#198]
The community meeting currently has the following issues:

1. Is longer than most OSS meetings.
2. Overlaps every other week with the GAMMA community call.
3. Is not friendly for all time zones.

**Comment by danehans** [comment]
> Is longer than most OSS meetings.

I suggest we change the meeting length from 2 hours to 1 hour.

> Overlaps every other week with the GAMMA community call.

This is a difficult issue to resolve while supporting AUS and EST timezones. Moving the meeting to 4:00 PT is late for EST and any earlier is bad for AUS. One option is to move the Tues meeting to 9:00 AM PT which resolves 2 and 3 but then we lose AUS. Thoughts?

**Comment by skriss** [comment]
:+1: to shortening meetings to an hour since we've gotten through the big initial design discussions. We should be able to move to just once a week and rely more on async communication, too.

Alternating time slots to be friendly to the most time zones sounds good to me. I can personally work with any of the options.

**Comment by youngnick** [comment]
Yes, I think that now the big design decisions are made, we can flip back to one meeting per week for one hour.

We can either tick tock or just do before the APAC GAMMA timeslot each week. Sucks a bit for me, but it keeps my early mornings to twice a week, which is better than more mornings.

**Comment by danehans** [comment]
During today's community call, maintainers agreed to the following meeting schedule:
- Tuesday's 2-3 PT
- Thursday's 9-10 PT
