### ISSUE TITLE
Decision: Enable Prometheus Endpoint by default for EnvoyProxy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1998]
*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers 
this will make metrics consistent with control plane

**Comment by arkodg** [comment]
im a +1 on this, and prefer if we add a `disable` knob in case someone wants to disable it when enabling otel

**Comment by zirain** [comment]
I forget why it's like this, but that's what I thought, big +1.
