### ISSUE TITLE
Extend EnvoyGateway Control Plane

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#20]
Consider defining a [WASM](https://www.tetrate.io/blog/wasm-modules-and-envoy-extensibility-explained-part-1/) ABI spec for Control Plane APIGateways similar to [proxy-wasm](https://github.com/proxy-wasm/spec) so the components defined in https://github.com/envoyproxy/gateway/pull/16 can be extended by users to define new control plane APIGateway functionality . [wazero](https://github.com/tetratelabs/wazero) might be an apt runtime to use.

**Comment by arkodg** [comment]
cc @AliceProxy

**Comment by danehans** [comment]
xref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/config

**Comment by Xunzhuo** [comment]
Do we have a more detailed proposal or design doc for it?

cc @AliceProxy  @danehans

**Comment by danehans** [comment]
@AliceProxy has been assigned so I'll let her respond.
