### ISSUE TITLE
Remove RateLimitFilter & AuthenticaionFilter

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2006]
*Description*:

Remove these filters and add these features as fields in `BackendTrafficPolicy` & `SecurityPolicy`

This will be a breaking change that needs to be highlighted in the release notes

**Comment by zirain** [comment]
will `BackendTrafficPolicy` & `SecurityPolicy` ready in v0.6?

**Comment by arkodg** [comment]
thats the plan @zirain, we are trying :)
