### ISSUE TITLE
Add E2E Tests for UDPRoute

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2011]
*Description*:

Add E2E tests in https://github.com/envoyproxy/gateway/tree/main/test/e2e/tests to test UDPRoute

**Comment by Xunzhuo** [comment]
Should this be done in upstream ?

**Comment by arkodg** [comment]
it might be faster to do it here and then move the exact test upstream

**Comment by cnvergence** [comment]
I can take a look :)

**Comment by zirain** [comment]
ping @cnvergence , just want to make sure you're still working around.

**Comment by cnvergence** [comment]
@zirain, yes, I will push my changes today

**Comment by cnvergence** [comment]
should we bring it to upstream when it's ready?

**Comment by zirain** [comment]
you can proposal it at anytime

**Comment by cnvergence** [comment]
xref: https://github.com/kubernetes-sigs/gateway-api/pull/2661
