### ISSUE TITLE
Any plan for Chinese version doc content?

### ISSUE THREAD

**Issue by wilsonwu** [envoyproxy/gateway#2012]
Is there any plan for Chinese version of doc site content? I'd like to contribute.

**Comment by arkodg** [comment]
great idea, @Xunzhuo can you share what needs to be done here
@wilsonwu are you interested in picking this up ?

**Comment by Xunzhuo** [comment]
Thanks! But I think for now it is not the best time for it, APIs / features are not stable yet. I suggest working on it after GA.

cc @envoyproxy/gateway-maintainers WDYT?

**Comment by wilsonwu** [comment]
> Thanks! But I think for now it is not the best time for it, APIs / features are not stable yet. I suggest working on it after GA.
> 
> cc @envoyproxy/gateway-maintainers WDYT?

Great, please let me know if anytime we can start.

**Comment by DomineCore** [comment]
I had the privilege of reading the documentation of Envoy Gateway, and I must say it is exceptionally well-written. I am thoroughly impressed by the quality of the content and I am also interested in participating in the translation work.😄

**Comment by shawnh2** [comment]
thanks @DomineCore, contributions are always welcome. like @Xunzhuo suggests, we would like to work on that after EG going GA.

**Comment by zirain** [comment]
because of https://github.com/envoyproxy/gateway/issues/2979, it would be great let's focus on that first.
