### ISSUE TITLE
Upload Grafana dashboards on grafana.com

### ISSUE THREAD

**Issue by psinghal20** [envoyproxy/gateway#2018]
*Description*:
>Describe the desired behavior, what scenario it enables, and how it
would be used.

There are 3 sample Grafana dashboards added as examples for visualizing envoy metrics as part of this PR: https://github.com/envoyproxy/gateway/pull/1997

We should upload these dashboards to the grafana.com dashboards catalog. We can create a workflow to release these dashboards.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
I want to understand the maintaince of the grafana dashboards, are these dashboards only used in EG or a common used dashboards for envoyproxy.

**Comment by psinghal20** [comment]
These dashboards are common dashboards with Envoy proxy. There are no EG control plane metrics currently added as part of the dashboard.

**Comment by arkodg** [comment]
closing this we now have a helm chart with the dashboards inside it
