### ISSUE TITLE
State and Future of EnvoyGateway Extension Points

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2025]
## Current State

In v0.4.0, eg introduces [ExtensionManager](https://gateway.envoyproxy.io/latest/design/extending-envoy-gateway/), grpc based extension hooks, to dynamically modify xds resources generated by EG.

In v0.5.0, eg introduces [EnvoyPatchPolicy](https://gateway.envoyproxy.io/latest/design/envoy-patch-policy/), a CRD resource, to dynamically patch xds resource generated by EG.

In the two above approaches, the extension target is the whole xds resources. It unlocks the full power of xds for vendors/teams to extend EG abilities, which is powerful and flexible. 

## What`s More?

EnvoyProxy itself provides some extension http filters, which allows people dynamically extend envoyproxy without restarting it, like [Lua](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter), [WASM](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/wasm_filter) and new introduced [Go](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter) Extension Filter.

I propose EG to provide high level APIs(CRDs) to abstract these extension points. From my experience of using EnvoyFilter in istio, compared with the full xds patch/modify, these ways have more specific target scopes and easier to be control, which are safer , easier and less dangerous to be used.

## ExtensionRef or PolicyAttachment ?

ExtensionRef can be used per-route-rule/per-backend, and PolicyAttachment can be used to whole Gateway/xRoute.

+ WASMFilter or WASMExtensionPolicy CRD
+ LuaFilter or LuaExtensionPolicy CRD
+ GoFilter  or GoExtensionPolicy CRD

**Comment by arkodg** [comment]
Im a +1 on this idea, it can be a safer, less scoped way than [EnvoyPatchPolicy](https://gateway.envoyproxy.io/latest/design/envoy-patch-policy/)  of extending EG

**Comment by denniskniep** [comment]
@zhaohuabing @arkodg  is there already some progress on integrating GoLang Filters (HTTP, Network)

Envoy Docs:
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/golang_filter#config-network-filters-golang
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter#config-http-filters-golang


Envoy Examples:
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/golang-http
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/golang-network

**Comment by zirain** [comment]
@denniskniep is it a part of envoy core? if not, maybe we should wait for it.

**Comment by denniskniep** [comment]
@zirain 
code is located in `/contrib/golang` folder of envoy repo in main branch:
https://github.com/envoyproxy/envoy/tree/main/contrib/golang

Current status is `alpha` 

see [here](https://github.com/envoyproxy/envoy/blob/9263d8801404bd4a9b657df0a38281f9bd2ddd95/contrib/extensions_metadata.yaml#L11) and [here](https://github.com/envoyproxy/envoy/blob/9263d8801404bd4a9b657df0a38281f9bd2ddd95/contrib/extensions_metadata.yaml#L51)


What do you mean exactly with envoy core?

**Comment by zirain** [comment]
can you use these filter with `envoyproxy/envoy:<version>` image instead of `envoyproxy/envoy:contrib-<version>`?

**Comment by denniskniep** [comment]
yes, its only available within `contrib` image ([api docs](https://www.envoyproxy.io/docs/envoy/v1.31.0/api-v3/extensions/filters/http/golang/v3alpha/golang.proto))

**Comment by arkodg** [comment]
closing this since this is completed and we are tracking the remaining issue #4627 seperately
