### ISSUE TITLE
Add user facing docs for the MergeGateways feature

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2030]
*Description*:
>Describe the issue.

Add user facing docs for the merge gateways feature introduced in https://github.com/envoyproxy/gateway/pull/1938

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by cnvergence** [comment]
@shawnh2 would you mind if I take over on this doc, since I'm working on multiple gc documentation?

**Comment by shawnh2** [comment]
> @shawnh2 would you mind if I take over on this doc, since I'm working on multiple gc documentation?

sure, go ahead.
