### ISSUE TITLE
Add docs for upgrading Envoy Gateway

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2031]
*Description*:
>Describe the issue.

The steps to upgrade Envoy Gateway is different than when installing Envoy Gateway for the first time.
Since helm skips updating the CRDs, we need to add explicit steps to
1. Reinstall CRDs
2. helm upgrade

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by UtkarshUmre** [comment]
I'm interested in working on this documentation-related issue. Would you be able to assign it to me?

**Comment by arkodg** [comment]
thanks for picking this on up @UtkarshUmre, my recommendation would be to ask users to run `helm template` + `filter CRDs` + `kubectl apply` for the upgrade case (since CRDs are not updated/applied by helm when they exist in the cluster) before running `helm install` to install the controller

**Comment by UtkarshUmre** [comment]
hey @arkodg can you guide me what i have to do to solve this issue

**Comment by arkodg** [comment]
@UtkarshUmre the outcome of this issue is a new doc around `Envoy Gateway upgrades` under User Guides https://gateway.envoyproxy.io/latest/user/
* it should assume there's an existing Envoy Gateway running in the system
* above comment https://github.com/envoyproxy/gateway/issues/2031#issuecomment-1828459200 hints at what the upgrade steps will look like

**Comment by arkodg** [comment]
@UtkarshUmre are you planning on working on this one ?

**Comment by UtkarshUmre** [comment]
Hey, I'm a bit busy right now, Feel free to assign it to someone else who's interested

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/4013
