### ISSUE TITLE
Update Gateway API Implementations page with Envoy Gateway details

### ISSUE THREAD

**Issue by youngnick** [envoyproxy/gateway#204]
*Description*:
Gateway API has an [Implementations Page](https://gateway-api.sigs.k8s.io/implementations/) page, we should list Envoy Gateway on there.

This issue covers adding a listing there that covers we are working on EG, we will update as part of releasing v0.2.0 final.

**Comment by youngnick** [comment]
I've created kubernetes-sigs/gateway-api#1464 for this.

**Comment by Xunzhuo** [comment]
Thanks @youngnick

**Comment by danehans** [comment]
https://gateway-api.sigs.k8s.io/implementations/#envoy-gateway booyah!

**Comment by danehans** [comment]
https://github.com/envoyproxy/gateway/issues/624 for adding a return ref ;-)
