### ISSUE TITLE
Add helm lint to `make lint`

### ISSUE THREAD

**Issue by PetrMc** [envoyproxy/gateway#2057]
*Description*:

Per @arkodg  [comment](https://github.com/envoyproxy/gateway/pull/1913#issuecomment-1739872090) 
we needed the way to validate the helm chart is capable with AWS `helm lint` 

After back and forth with AWS it's confirmed that the specific version `3.8.1' of Helm is required, ataching the screenshot here: 
![image](https://github.com/envoyproxy/gateway/assets/19846180/0e2be7b4-65b1-4d63-b50f-65c539c48d83)

*Relevant Links*:

the desired version - https://github.com/helm/helm/releases/tag/v3.8.1

Reference of the existing Helm tags - https://github.com/helm/helm/tags

**Comment by arkodg** [comment]
thanks for raising this @PetrMc, would be good to add `helm lint` into our existing `lint` target
