### ISSUE TITLE
Add docs for demonstrating LoadBalancer using BackendTrafficPolicy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2069]
*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
This can be covered by https://github.com/envoyproxy/gateway/issues/2070, let us close this.

**Comment by arkodg** [comment]
lets keep both open, imo this is a good candidate for `user guide` and #2070 is a good candidate for a new section called `concepts`
