### ISSUE TITLE
 race detected

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2073]
```console
FAIL    github.com/envoyproxy/gateway/internal/provider/kubernetes

2023-10-26T08:12:23.774+0800    INFO    kubernetes/routes.go:330        processing HTTPRoute    {"namespace": "test", "name": "test"}
--- FAIL: TestProcessHTTPRoutes (0.00s)
    --- FAIL: TestProcessHTTPRoutes/httproute_with_one_filter_from_extension (0.00s)
        testing.go:1465: race detected during execution of test
    testing.go:1465: race detected during execution of test

```

**Comment by arkodg** [comment]
maybe not worth solving since this will be removed soon via https://github.com/envoyproxy/gateway/issues/2006

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/actions/runs/6680648373/job/18153968476?pr=2106

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/actions/runs/6717168305/job/18255036035

**Comment by shawnh2** [comment]
The logs for this run have expired and are no longer available. We can close this now, reopen another issue if running into it.
