### ISSUE TITLE
Implement Metrics instrumentation for Watchable Map

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2089]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Implement Metrics instrumentation for WatchableMap.

**Comment by shawnh2** [comment]
Hi @Xunzhuo, is this issue considered to be done? or we have something else to do?

**Comment by Xunzhuo** [comment]
We can close this, thanks, but need to revisit the naming patterns before adding more metrics. 

@shawnh2
