### ISSUE TITLE
Implement Metrics instrumentation for Infra Manager

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2091]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Implement Metrics instrumentation for Infra Manager

**Comment by shawnh2** [comment]
Blocked by https://github.com/envoyproxy/gateway/pull/3446

**Comment by Xunzhuo** [comment]
Can we continue for this ? @shawnh2 

Looks like this is the only left sub-task for cp metrics.

**Comment by shawnh2** [comment]
Sure, I'm working on this :)
