### ISSUE TITLE
Implement Metrics instrumentation

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2092]
*Description*:

Do metrics instrumentation in EG components:

- [x] Provider: 
  - [x] controller-runtime metrics 
  - [x] watchable map metrics
- [x] GWAPI-Translator
  - [x] watchable map metrics
- [x] xDS-Translator
  - [x] watchable map metrics
- [x] xDS-Server
  - [x] watchable map metrics
  - [x] xds server metrics
- [x] Infra-Manager
  - [x] watchable map metrics
  - [ ] infra-manager metrics
- [x] Status Updater

Implement Metrics instrumentation for EG CP Observability.

- [x] https://github.com/envoyproxy/gateway/issues/2089
- [x] https://github.com/envoyproxy/gateway/issues/2090
- [x] https://github.com/envoyproxy/gateway/issues/2091
- [x] https://github.com/envoyproxy/gateway/issues/2131
- [ ] #3474

**Comment by arkodg** [comment]
@Xunzhuo still planning on working on this for v1.0 ?

**Comment by shawnh2** [comment]
The design of Metrics for EG CP shall follow the idea as @Xunzhuo outlined here. I'll post the initial metrics design here before any implementation.

**Comment by Xunzhuo** [comment]
@shawnh2 thanks for continuing to implement this, ping me if you need more reviews.
