### ISSUE TITLE
Expose Additional Bootstrap Config Options

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#212]
With https://github.com/envoyproxy/gateway/pull/206, only the Xds server address is configurable. The Xds server port and admin add/port should also be configurable.

**Comment by NomadXD** [comment]
@danehans Can I work on this ? New contributor here :-)

**Comment by danehans** [comment]
Go for it. Note that PR #206 is required so either cherry-pick the PR or wait for it to merge.

**Comment by danehans** [comment]
@NomadXD note that the xds server address and port need to be plumbed to https://github.com/envoyproxy/gateway/blob/main/internal/xds/server/runner/runner.go#L57-L59.

**Comment by NomadXD** [comment]
@danehans I cherry picked your PR and added placeholders `{{ .XdsServerPort }}` , `{{ .AdminServerAddress }}` and `{{ .AdminServerPort }}` to the template.

Regarding using the config values for creating the address, we can't access the bootstrap config in the Config defined here. https://github.com/envoyproxy/gateway/blob/d2303d5974fc34c4719b006fd9a4752b07a1c4e7/internal/xds/server/runner/runner.go#L22

Also the bootstrap config struct also defined as a private struct. 
https://github.com/envoyproxy/gateway/blob/06447e3ff4866a75217deab69dfbe613340298be/internal/infrastructure/kubernetes/deployment.go#L104

Should we need make it public and pass to the config to access from https://github.com/envoyproxy/gateway/blob/main/internal/xds/server/runner/runner.go#L57-L59 ??

**Comment by danehans** [comment]
@NomadXD #206 has been merged. It went through some minor changes, so drop the cherry-pick and rebase from main.

> Regarding using the config values for creating the address, we can't access the bootstrap config in the Config defined here.

Expose the xDS and admin endpoint config through the [EnvoyGateway](https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoygateway_types.go) API type. Note that this is the configuration of the xDS server, e.g. Envoy Gateway.

> Also the bootstrap config struct is defined as a private struct.

This is the config of the xDS client, e.g. Envoy. The [EnvoyProxy](https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoyproxy_types.go) API type should be used for managing Envoy config. This will be more tricky since the Kubernetes provider does not implement the EnvoyProxy API. If you have not done so already, please review the [Config API design doc](https://github.com/envoyproxy/gateway/blob/main/docs/design/CONFIG_API.md). The GatewayClass controller should get the EnvoyProxy object from the Kube API server when a reconciling a GatewayClass that is managed by Envoy Gateway and has `spec.parametersRef` set. The EnvoyProxy object should be validated and then passed to subscribers through the watchable provider resources using `Store()`. I suggest taking time to review the [watchable design doc](https://github.com/envoyproxy/gateway/blob/d2303d5974fc34c4719b006fd9a4752b07a1c4e7/docs/design/watching.md) to understand how Envoy Gateway implements watchable for components to share data. If this feels like more than you can absorb, then feel free to just parameterize the xds/admin endpoint values as variables in the Kubernetes pkg similar to the existing`XdsServerAddress`.

We should validate inputs and also include logic to ensure the client/server grpc ports match.

**Comment by NomadXD** [comment]
@danehans Thanks a lot for the info. Helped me a lot to understand the concepts here.

I created the PR #243 to fix #212. 

Regarding exposing the xDS config through GatewayAPI, I opened a new issue #244 to track it separately.
