### ISSUE TITLE
Support Health Check

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2126]
*Description*:

Add Health Check support to BackendTrafficPolicy.

**Comment by lizj3624** [comment]
+1

**Comment by arkodg** [comment]
@Xunzhuo can you elaborate on this, is this referring to active health checks ?

**Comment by Xunzhuo** [comment]
Yep, it is @arkodg : )

**Comment by lemonlinger** [comment]
Hi @Xunzhuo,

I'm interested in working on this issue. Is it still open for contribution? If so, I'd like to claim it.

**Comment by Xunzhuo** [comment]
Cool, thanks for picking it up @lemonlinger

**Comment by arkodg** [comment]
keep this issue open to track completion of docs

**Comment by shawnh2** [comment]
we can close this for now, the docs and e2e test for health check are tracked by #2417 #2418
