### ISSUE TITLE
Implement Metrics instrumentation for Status Updater

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2131]
*Description*:

Implement Metrics instrumentation for Status Updater

**Comment by shawnh2** [comment]
The metrics for status updater shall move forward based on #2130

**Comment by shawnh2** [comment]
blocked by #2951, since we are trying to remove `internal/status`

**Comment by shawnh2** [comment]
> The metrics for status updater shall move forward based on #2130

also follow the metrics design in #2130
