### ISSUE TITLE
Envoy Gateway logo design

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2147]
*Description*:

As we maintainers discussed in Slack, eg needs a logo built on top of envoyproxy logo.

This might need some helps from CNCF artwork.

cc @envoyproxy/admins , @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
reopening this issue since we dont have a dedicated envoy gateway logo yet

**Comment by arkodg** [comment]
as a temporary measure I propose we use the Envoy logo with the `gateway` text below similar to the image shared below (w/o the pink) . This allows us to have a logo for now and we can contnue iterating to find a better one

![image (9)](https://github.com/envoyproxy/gateway/assets/9469142/f54e329f-2135-41a8-a046-b2d095de73fa)

wdyt @envoyproxy/gateway-maintainers @envoyproxy/gateway-reviewers

**Comment by zirain** [comment]
+1, better than nothing

**Comment by shawnh2** [comment]
+1

**Comment by zhaohuabing** [comment]
+1

Nit gateway -> Gateway

**Comment by Xunzhuo** [comment]
+1

Thanks

**Comment by cnvergence** [comment]
+1

**Comment by Xunzhuo** [comment]
Here are some logos designed by CNCF Service Desk:

![envoy_gateway_battery (1)](https://github.com/envoyproxy/gateway/assets/48784001/44e2be90-85fb-4611-8025-5dfd0f97e393)

![envoy_gateway_logo_rev1 (1)](https://github.com/envoyproxy/gateway/assets/48784001/a7fde915-34d1-4816-8589-560a609ca58e)

**Comment by shawnh2** [comment]
like the second one, share the same design language as envoyproxy.

**Comment by arkodg** [comment]
raised a new issue with CNCF https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2420

based off the comment in https://github.com/envoyproxy/gateway/issues/2147#issuecomment-2207706188
@MB-Designs helped create these logos (thanks !) attaching them here, everyone please share your thoughts ( 👍  / 👎 )

<img width="625" alt="Screenshot 2024-08-15 at 5 09 49 PM" src="https://github.com/user-attachments/assets/08420420-cc69-42bd-915c-07250261d448">

<img width="612" alt="Screenshot 2024-08-15 at 5 09 16 PM" src="https://github.com/user-attachments/assets/6b43d400-88b7-4683-8371-9c849eee8a77">

**Comment by AliceProxy** [comment]
3 looks overall best IMO and good for places where there is enough horizontal room to include it such as on page headers, 4 as a nice option for things that take up a circular/square frame so that there is less white space.

**Comment by AliceProxy** [comment]
![Screenshot from 2024-08-28 19-09-44](https://github.com/user-attachments/assets/755aa222-128f-4771-86ad-fda055d38b3a)

This one from above I really like the skewed/stacked icon and it looks good, but I think we should stick with the flat design as that is what the main envoy website/project uses.

**Comment by Xunzhuo** [comment]
+1 for 3 or 4

**Comment by arkodg** [comment]
thanks everyone for sharing your preference ! looks like 3 & 4 is the preferred option here for the short term, hopefully we can iterate and build another logo out in the long term
@MB-Designs chatted with @@nate-double-u , and you should be able to raise a PR in [https://github.com/envoyproxy/artwork/](https://github.com/envoyproxy/artwork/tree/main) , Nate suggested creating another dir inside https://github.com/cncf/artwork/tree/main/projects/envoy

**Comment by MB-Designs** [comment]
@arkodg @nate-double-u 

 I don't have upload rights. Could you give me access?
 
I also generated a logo overview presentation and the final logo source files.

[Envoy Gateway Logo Final Source.zip](https://github.com/user-attachments/files/16935270/Envoy.Gateway.Logo.Final.Source.zip)
[Envoy Proxy Logo Final Source.zip](https://github.com/user-attachments/files/16935272/Envoy.Proxy.Logo.Final.Source.zip)


[envoy-gataway-logo-final.pdf](https://github.com/user-attachments/files/16935240/envoy-gataway-logo-final.pdf)
[envoy-proxy-logo-final.pdf](https://github.com/user-attachments/files/16935241/envoy-proxy-logo-final.pdf)

**Comment by nate-double-u** [comment]
Hi, thanks for this @MB-Designs!

Could you package this like we do over in [cncf/artwork](https://github.com/cncf/artwork)?

I'd like to create a folder under [the existing envoy stuff](https://github.com/cncf/artwork/tree/main/projects/envoy) for this.

Here's the format we use:
```
├── envoy-logo-final.pdf
├── horizontal
│   ├── black
│   │   ├── envoy-horizontal-black.png
│   │   └── envoy-horizontal-black.svg
│   ├── color
│   │   ├── envoy-horizontal-color.png
│   │   ├── envoy-horizontal-color.svg
│   │   ├── envoy-horizontal-white-text.png
│   │   └── envoy-horizontal-white-text.svg
│   └── white
│       ├── envoy-horizontal-white.png
│       └── envoy-horizontal-white.svg
├── icon
│   ├── black
│   │   ├── envoy-icon-black.png
│   │   └── envoy-icon-black.svg
│   ├── color
│   │   ├── envoy-icon-color.png
│   │   └── envoy-icon-color.svg
│   └── white
│       ├── envoy-icon-white.png
│       └── envoy-icon-white.svg
└── stacked
    ├── black
    │   ├── envoy-stacked-black.png
    │   └── envoy-stacked-black.svg
    ├── color
    │   ├── envoy-stacked-color.png
    │   ├── envoy-stacked-color.svg
    │   ├── envoy-stacked-white-text.png
    │   └── envoy-stacked-white-text.svg
    └── white
        ├── envoy-stacked-white.png
        └── envoy-stacked-white.svg
```

**Comment by arkodg** [comment]
@nate-double-u what naming convention and structure do you prefer here ? 
* should we rename the envoy proxy logos or let them be as is ? 
* should the envoy gateway logos be prefixed with `envoy-gateway`?

**Comment by nate-double-u** [comment]
> should we rename the envoy proxy logos or let them be as is?

Let's leave those as is, there may be links to them around and making a redirect in a github repo is hard.

> should the envoy gateway logos be prefixed with envoy-gateway?

I think we should create a new folder for this work in the [cncf/artwork](https://github.com/cncf/artwork) repo. 

The exsting envoy logos are in the `artwork/projects/envoy` folder, so I suggest either:
* artwork/projects/envoy/envoy-gateway
* artwork/projects/envoy-gateway

<small>(I don't think I have a strong preference for either option)</small>

**Comment by arkodg** [comment]
thanks for the response +1 to `artwork/projects/envoy/envoy-gateway`

**Comment by MB-Designs** [comment]
> horizontal

@nate-double-u I will generate a logo package.

**Comment by MB-Designs** [comment]
@nate-double-u @arkodg Envoy gateway logo package has been generated.
[envoy-gateway-logo-final.zip](https://github.com/user-attachments/files/16975913/envoy-gateway-logo-final.zip)

**Comment by nate-double-u** [comment]
Thanks @MB-Designs, i've opened a PR over in cncf/artwork: https://github.com/cncf/artwork/pull/505 (and do have a question for you over there 🙂)

**Comment by nate-double-u** [comment]
https://github.com/cncf/artwork/pull/505 has merged in, I think this means we can close this issue :)

Thanks for all the work @MB-Designs!

**Comment by arkodg** [comment]
great, thanks @MB-Designs @Xunzhuo @nate-double-u !
