### ISSUE TITLE
Support GEP-1762

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2148]
https://gateway-api.sigs.k8s.io/geps/gep-1762/

cc @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
@zirain what is the use case here ?
is it linking static Envoy Proxy infra to Gateways using this field ? If so, as part of this issue we must also generate Envoy Proxy Infra via helm

**Comment by zirain** [comment]
need support `GatewayInfrastructure`?

**Comment by arkodg** [comment]
@zirain can you elaborate ?

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/issues/1379

**Comment by zirain** [comment]
@arkodg I think EG should follow https://gateway-api.sigs.k8s.io/geps/gep-1762/#automated-deployments
