### ISSUE TITLE
Move compatibility matrix out of blog

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2151]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Compatibility matrix lives under blog
https://gateway.envoyproxy.io/blog/2022/10/01/versions/

Should live closer to install

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by zirain** [comment]
need a user page about this.

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/2237

**Comment by arkodg** [comment]
its been moved into https://gateway.envoyproxy.io/v1.0.1/install/matrix/
