### ISSUE TITLE
Add E2E Test for Loadbalancing

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2153]
*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ChloroplastYu** [comment]
Hi! Perhaps I can work on this issue. 

Could you please describe this issue in more detail?

**Comment by arkodg** [comment]
* consistent hash + source ip - we need to make sure traffic always reaches same backend
* round robin - traffic is split somewhat equally amongst backends
you can validate based on check based on response header which contains the pod name in the header
you probably need to increase the number of replicas in the default e2e tests
thanks for helping out with this one !

**Comment by ChloroplastYu** [comment]
Thanks for your reply, I think I already understand what I need to achieve now, you can assign this issue to me @arkodg

**Comment by arkodg** [comment]
hey @ChloroplastYu are you still planning on working on this one ?

**Comment by ChloroplastYu** [comment]
> hey @ChloroplastYu are you still planning on working on this one ?

@arkodg sorry for taking so long, but I still plan to work on this issue
