### ISSUE TITLE
Auto Generate Release Notes

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2154]
*Description*:
>Describe the issue.

Generate Release notes based on GH PR descriptions and Titles

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
does this help? https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by arkodg** [comment]
closing this, since this was addressed with https://github.com/envoyproxy/gateway/issues/4472
