### ISSUE TITLE
Update Versions Matrix

### ISSUE THREAD

**Issue by candita** [envoyproxy/gateway#2165]
The Envoy Gateway versions matrix is missing Gateway API v1.0.0.  
https://gateway.envoyproxy.io/blog/2022/10/01/versions/

According to https://gateway-api.sigs.k8s.io/implementations/#envoy-gateway it supports v1.0.0.

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/issues/2151
@Xunzhuo can you help

**Comment by Xunzhuo** [comment]
@arkodg Yep, will update it tomorrow
