### ISSUE TITLE
Roadmap for v0.7.0

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2176]
*Description*:

Roadmap for v0.7.0, we need to figure out what issues should be put in v0.7.0

**Comment by jindrichpilar-kosik** [comment]
Hi, is there a roadmap of planned releases?

[Roadmap in documentation](https://gateway.envoyproxy.io/v0.6.0/contributions/roadmap/#v060v060-preparation-for-ga)  says 

> v0.6.0: Preparation for GA

So I was expecting v1.0.0 straight after v0.6.0.

---
We are looking forward to using Envoy Gateway in production but if the timeline is unfavorable we will be forced to choose differently. Plain Gateway API functionality is not enough for us so migration would not be easy.

**Comment by Xunzhuo** [comment]
Yep, @jindrichpilar-kosik, we maintainers mostly agree for the next release as v1.0.0, the GA milestone for EG. But details are still discussing. The result will be public after the discussion is finished.

**Comment by Xunzhuo** [comment]
@jindrichpilar-kosik https://github.com/envoyproxy/gateway/issues/2249

close by https://github.com/envoyproxy/gateway/issues/2249
