### ISSUE TITLE
Generate DeepCopy methods for XdsResources

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#218]
*Description*:
* Address the comment in https://github.com/envoyproxy/gateway/blob/603e2a3ea048f405640f8278f8897baf7261f419/internal/xds/types/resourceversiontable.go#L10 which requires us to add DeepCopy() methods needed by the watchable package.

* adding the `+k8s:deepcopy-gen=true` tag and running `make generate` fails to generate the methods/file
```git diff
diff --git a/internal/xds/types/resourceversiontable.go b/internal/xds/types/resourceversiontable.go
index 5c24a7c..0d92b68 100644
--- a/internal/xds/types/resourceversiontable.go
+++ b/internal/xds/types/resourceversiontable.go
@@ -11,6 +11,7 @@ import (
 // github.com/envoyproxy/go-control-plane/pkg/cache/v3.NewSnapshot
 // takes; if we decide that we want to change this type, then we'd
 // have to do conversion.
+// +k8s:deepcopy-gen=true
 type XdsResources = map[resource.Type][]types.Resource
 
 // ResourceVersionTable holds all the translated xds resources
```

* Add a unit test similar to https://github.com/envoyproxy/gateway/pull/217 for the `XdsResources` message once the methods have been added

**Comment by danehans** [comment]
xref https://github.com/envoyproxy/gateway/issues/229

**Comment by zirain** [comment]
cc @arkodg, seems we can not use `controller-gen` to achieve this.
```console
type XdsResources map[string]int // working
//type XdsResources2 = map[string]int // not working: interface conversion: types.Type is *types.Map, not *types.Named
//type XdsResources3 map[string]interface{} // not working: invalid map value type: interface{}
```

**Comment by arkodg** [comment]
Yah @zirain, attempting to  handwrite `DeepCopy` now
