### ISSUE TITLE
Support non version pages on the website

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2195]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Currently user docs such as https://gateway.envoyproxy.io/v0.6.0/user/ have the version as a path prefix.
This makes it hard to save this page in other locations because it points a specific version (which will soon become an older version) .
Instead we should also support `https://gateway.envoyproxy.io/user/` which points to the current version

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
cc @Xunzhuo

**Comment by lou-lan** [comment]
The 'latest' version is always fixed, https://gateway.envoyproxy.io/latest/design/goals/.

**Comment by zirain** [comment]
do you mean select current version(0.6.0) as default?

**Comment by arkodg** [comment]
I would like to add reference in other projects/documentations that do not have version in the path prefix e.g.  https://gateway.envoyproxy.io/user/ , but take the user to the newest stable version (v0.6.0 as of today, maybe v0.7.0 once its releases)

**Comment by zirain** [comment]
I'm not sure, but maybe https://github.com/istio/istio.io/pull/15092/files will help.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/3819
