### ISSUE TITLE
Handle GatewayClass deletions

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#222]
*Description*:

The current logic in the  the gateway class controller only adds gatewayclasses to the context https://github.com/envoyproxy/gateway/blob/d2303d5974fc34c4719b006fd9a4752b07a1c4e7/internal/provider/kubernetes/gatewayclass.go#L109 but does not delete any.
This affects https://github.com/envoyproxy/gateway/blob/d2303d5974fc34c4719b006fd9a4752b07a1c4e7/internal/provider/kubernetes/gatewayclass.go#L186 which might hold a stale GatewayClass that might have been deleted

Raising this issue to fix this case

Related comments https://github.com/envoyproxy/gateway/pull/193#discussion_r938301491

**Comment by Xunzhuo** [comment]
I can help on this, plz assign this to me:)

**Comment by danehans** [comment]
@Xunzhuo thanks for taking this on.

**Comment by danehans** [comment]
@chauhanshubham do you have cycles to take this issue on?

**Comment by chauhanshubham** [comment]
> @chauhanshubham do you have cycles to take this issue on?

Sure.
