### ISSUE TITLE
Remove the need to specify test name in xds translator lib

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2229]
*Description*:
>Describe the issue.

The Xds Translator test defined here https://github.com/envoyproxy/gateway/blob/87bc96fededc5de24ef14776be91c1802453cde1/internal/xds/translator/translator_test.go#L44
relies on the test being explicitly defined in this function.

This can be improved by removing the need to do so, similar to what is done in the Gateway API Translate test https://github.com/envoyproxy/gateway/blob/87bc96fededc5de24ef14776be91c1802453cde1/internal/gatewayapi/translator_test.go#L45

this should reduce number of merge conflicts in the project

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by UtkarshUmre** [comment]
I'm interested in working on this issue. Can you assign it to me

**Comment by zirain** [comment]
@UtkarshUmre are you still working on this?
