### ISSUE TITLE
Add e2e test for weighted backend

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2238]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Set up e2e test for weighted backend, prevent https://github.com/envoyproxy/gateway/pull/2187

**Comment by ShyunnY** [comment]
@Xunzhuo  Hello Xunzhuo, I'm interested in this issue. Could you please provide more information?

**Comment by arkodg** [comment]
Hey @ShyunnY the conformance tests live in https://github.com/envoyproxy/gateway/tree/main/test/e2e
Here's the feature we need to add an e2e for https://gateway-api.sigs.k8s.io/guides/traffic-splitting/#http-traffic-splitting

**Comment by ShyunnY** [comment]
@arkodg 
I encountered some problems when writing e2e tests: I need to obtain the pod information in the backend response body as a traffic identifier to calculate the weight of routing to different backends under given traffic. But the `CapturedResponse` obtained by `suite.RoundTripper.CaptureRoundTrip(req)` seems to only contain response metadata. I can't determine which backend this traffic is routed to.
Currently I want to use the `net.http` package to solve this problem. Do you have a better way?

**Comment by zirain** [comment]
> @arkodg I encountered some problems when writing e2e tests: I need to obtain the pod information in the backend response body as a traffic identifier to calculate the weight of routing to different backends under given traffic. But the `CapturedResponse` obtained by `suite.RoundTripper.CaptureRoundTrip(req)` seems to only contain response metadata. I can't determine which backend this traffic is routed to. Currently I want to use the `net.http` package to solve this problem. Do you have a better way?

will stats help?

**Comment by arkodg** [comment]
@ShyunnY is it possible to rewrite https://github.com/kubernetes-sigs/gateway-api/blob/38f629931dce810032d43107a27343e210fe4a89/conformance/utils/roundtripper/roundtripper.go#L153 here to also  accept Body (unmarshal body into `Context`) in this repo and later enhance the upstream code ?
or fixing it in upstream first also works

**Comment by ShyunnY** [comment]
> @ShyunnY is it possible to rewrite https://github.com/kubernetes-sigs/gateway-api/blob/38f629931dce810032d43107a27343e210fe4a89/conformance/utils/roundtripper/roundtripper.go#L153 here to also accept Body (unmarshal body into `Context`) in this repo and later enhance the upstream code ? or fixing it in upstream first also works

The implementation of the RoundTripper interface was written with too little extensibility, which prevented me from wrapping it. If we chose to rewrite this approach, I think it would add a lot of unnecessary code. I have already raised an issue with the upstream. We can write this test later.

**Comment by ShyunnY** [comment]
> > @arkodg I encountered some problems when writing e2e tests: I need to obtain the pod information in the backend response body as a traffic identifier to calculate the weight of routing to different backends under given traffic. But the `CapturedResponse` obtained by `suite.RoundTripper.CaptureRoundTrip(req)` seems to only contain response metadata. I can't determine which backend this traffic is routed to. Currently I want to use the `net.http` package to solve this problem. Do you have a better way?
> 
> will stats help?

We need to get information from the echoserver response body to indicate the real routing backend of the traffic. Stats cannot help us.

**Comment by ShyunnY** [comment]
@arkodg The upstream gatewya-api seems to be far away from changing this issue. Should we still choose to implement a simple RoundTripper ourselves so that it can be released in v1.0.0rc?
