### ISSUE TITLE
docs: broken format displayed under `JWT` reference

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#2239]
*Description*:
Link to v0.6.0 docs: https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#jwt.
Link to latest docs: https://gateway.envoyproxy.io/latest/api/extension_types/#jwt.

<img width="1180" alt="image" src="https://github.com/envoyproxy/gateway/assets/12388578/be22a41a-1dc8-4b29-afc9-5bb58ac4f16b">
Reference:

https://github.com/envoyproxy/gateway/blob/73fbd62999d570dc6c60dc92d82878e2a9f352e1/site/content/en/latest/api/extension_types.md?plain=1#L895-L896

*Repro steps*:

A newline result in the docs site to add additional columns on `providers` field under `JWT` references.
Code: 
https://github.com/envoyproxy/gateway/blob/73fbd62999d570dc6c60dc92d82878e2a9f352e1/api/v1alpha1/jwt_types.go#L9-L13.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
v0.6.0 and latest

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by zirain** [comment]
@ardikabs would you like to send a fix?

**Comment by ardikabs** [comment]
sure @zirain .
