### ISSUE TITLE
Envoy Gateway GA Plan 

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2249]
# Envoy Gateway GA Plan

This issue tracks all the necessary steps for Envoy Gateway to reach `v1.0`, providing users with the confidence to run it in production. 

***Plan Release Time***: The GA is planned for **early March 2024, before KubeCon Paris 2024**. 

> I will be responsible for: manage GitHub issue/project, set priorities, and release the v1.0.0.

## Stability
  - [x] Pass conformance tests for all v1.0 Gateway API upstream features
  - [x] Write and pass E2E tests for all extended features
  - [x] Achieve 60%-80% code coverage (from unit tests)

## Performance at Scale
- [x] Meet certain performance criteria when used at scale
- [x] Performance Report

### Core (Gateway API Implementation)

Implement and expose the majority of API Gateway features using a stable API. This requires the upstream Gateway APIs to be graduated (tracked with https://github.com/kubernetes-sigs/gateway-api/discussions/1801)

#### Protocol Support
- [x] HTTP
- [x] gRPC
- [x] TCP
- [x] TLS
- [x] UDP

#### Cross Namespace Access Control
- [x] ReferenceGrant

#### Traffic Management
- [x] More Advanced Match Routing Rules:
  - [x] Header
  - [x] Method
  - [x] Param
  - [x] Host
  - [x] Path
- [x] Timeout
- [x] Request Header Modifier
- [x] Response Header Modifier
- [x] Request Mirror
- [x] Request Redirect
- [x] URL Rewrite
- [x] Weighted Backend

#### Security

- [x] CORS
- [x] BasicAuth
- [x] JWT
- [x] OIDC

##### Client Side

- [x] EnableProxyProtocol
- [x] TCPKeepAlive
- [x] HTTP3/QUIC

##### Backend Side

- [x] Global Ratelimit
- [x] Local Ratelimit
- [x] LoadBalancing
- [x] ProxyProtocol
- [x] TCPKeepAlive
- [x] Active Health Check 
- [x] Retry
- [x] Circuit Breaker
- [x] Fault Injection

#### Extensibility

- [x] Envoy Gateway Extension Manager
- [x] EnvoyPatchPolicy
- [x] WASM/Go/Lua PluginPolicy

## Flexible Deploy Mode
- [x] Multiple GatewayClass per Envoy Gateway
- [x] One GatewayClass per Envoy Gateway
- [x] Merged Gateway per Envoy Gateway
- [x] Namespaces scope watch mode
- [x] Cluster scope watch mode
- [ ] Deploy EnvoyProxy Instance in Gateway CR namespace
- [x] Deploy EnvoyProxy Instance in Envoy Gateway namespace
- [x] Multi-tenancy Envoy Gateway in different namespace
- [x] Multi Cluster Support with MCS API

## Day 2 Operations
- [x] Install
  - [x] Helm
  - [x] Yaml
- [x] Observability
  - [x] Data Plane
  - [x] Control Plane
- [x] `egctl` command line tool
  - [x] Core
  - [ ] Extended
- [ ] Triage
- [x] HPA
- [x] Upgrades (CRD, Envoy Proxy, Envoy Gateway)
- [x] Customize Envoy Kubernetes Resources

## Documentation
- [ ] Document all features, operations, and other relevant information

### Team Session
1. All issues related to GA should be managed under [Envoy Gateway: The Road to GA](https://github.com/orgs/envoyproxy/projects/7), which includes the following sections: Backlog, Todo, In Progress, Review, and Done.
2. All issues related to GA should be labeled for identification: `road-to-ga`

### Blog Post
- [x] Publish a blog post about Envoy Gateway on both blog.envoyproxy.io and gateway.envoyproxy.io

### CNCF Logo Design
- [ ] Design a CNCF logo for Envoy Gateway

**Comment by shawnh2** [comment]
Since the benchmark part has been added, do we need to reevaluate this ? @Xunzhuo

**Comment by Xunzhuo** [comment]
@shawnh2 Updated thanks!
