### ISSUE TITLE
preserving the client IP address

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/gateway#2252]
*Description*:
>
Currently, the gateway supports two methods for obtaining the client IP address (proxy protocol  in the four-layer and x-forwarded-for in the seven-layer). But, I think some additional details need to be added.
1. proxy protocol
The Proxy protocol to enable Layer 4 listeners to retrieve client IP addresses. But currently gateway only supports http listener, we need to expand to support non-http/https scenarios.
#2203

2. x-forwarded-for
`x-forwarded-for` is a layer-7 protocol method for saving client IP addresses. The current gateway also utilizes it for current limiting based on the source IP. But,  source IP-based rate limiting in the gateway only supports direct connections to the gateway. To accommodate scenarios involving indirect connections to the gateway and obtain the correct client IP address, it may be necessary to introduce the [xff_num_trusted_hops](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for) field. In multi-hop scenarios, it is important to note that the XFF header may be susceptible to forgery.
![client_ip drawio](https://github.com/envoyproxy/gateway/assets/12018633/3dfa2e9f-d604-4fe7-9f6d-524665548ad3)

[optional *Relevant Links*:]
>
#946 
https://github.com/envoyproxy/gateway/blob/0add22b8c58111606243e688611c63b96784cb75/api/v1alpha1/clienttrafficpolicy_types.go#L55C1-L58C15
https://github.com/envoyproxy/gateway/issues/1328

**Comment by robd003** [comment]
Is there a way to restrict X-Forwarded-For to only allow it from trusted CIDR blocks?

**Comment by tmsnan** [comment]
@robd003, Do you want to restrict based on remote IP? rbac is being implemented.https://github.com/envoyproxy/gateway/issues/2250.

You can use the `source ip` field. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-principal

**Comment by robd003** [comment]
@tmsnan I'm not trying to block end-user IPs from accessing the proxy.

This is more about trusting only certain CIDR blocks to give valid X-Forwarded-For headers. It's very easy for someone to spoof this data, but if you limit to trusting the X-Forwarded-For to only certain CIDR blocks then you can be certain that end user IPs are correct and not forged.

**Comment by zirain** [comment]
sounds like a WAF?

**Comment by robd003** [comment]
@zirain It's more than that. CloudFlare is a CDN that will cache, has POPs close to your users (so much less latency) and will filter DDoS traffic.

**Comment by robd003** [comment]
https://github.com/envoyproxy/envoy/issues/31296

**Comment by robd003** [comment]
> > This is more about trusting only certain CIDR blocks to give valid X-Forwarded-For headers. It's very easy for someone to spoof this data, but if you limit to trusting the X-Forwarded-For to only certain CIDR blocks then you can be certain that end user IPs are correct and not forged.
> 
> 😄Get it. It seems you want to add the trusted CIDR IP to `X-Forwarded-For`. Currently, envoy does not support this. You can raise this issue in envoy.

Specifically I _**ONLY**_ want to pass along `X-Forwarded-For` headers if the remote client IP matches one of the CIDR blocks in an ACL. Of there is no match, then strip the `X-Forwarded-For` header from the request and just pass the source IP for the connection in as `X-Forwarded-For`

**Comment by zirain** [comment]
IMO, you can implement that with a custom filter(e.g. WASM ), and then path the listener with [EnvoyPatch](https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#envoypatchpolicy).

**Comment by robd003** [comment]
@zirain Can you point me in the direction of some good example code for this? I'm relatively new to the Envoy universe.

**Comment by zirain** [comment]
here is something for you:

https://github.com/proxy-wasm/proxy-wasm-cpp-host

https://github.com/istio-ecosystem/wasm-extensions

**Comment by lambdai** [comment]
@zirain X-forwarded-for processor is part of HCM. It mutate the remote address (for a HTTP stream) before any HTTP filter.
I don't think wasm filter or any http filter could rollback what XFF has done.

**Comment by zirain** [comment]
> @zirain X-forwarded-for processor is part of HCM. It mutate the remote address (for a HTTP stream) before any HTTP filter. I don't think wasm filter or any http filter could rollback what XFF has done.

My plan is terminate the request if the XFF doesn't `matches one of the CIDR blocks in an ACL.`, but it looks like the original requirement is `f there is no match, then strip the X-Forwarded-For header from the request and just pass the source IP for the connection in as X-Forwarded-For`.

**Comment by arkodg** [comment]
@tmsnan reg 1., for TCP (non HTTP), the `tcp_proxy` filter is used, which should forward/proxy the proxy protocol headers to upstream

**Comment by davidalger** [comment]
> To accommodate scenarios involving indirect connections to the gateway and obtain the correct client IP address, it may be necessary to introduce the `xff_num_trusted_hops` field.

I unsurprisingly ran into this deploying the Envoy Gateway on GKE clusters residing behind global GCP balancers where there are 2 hops and TLS is terminated on the GCP balancer rather than on the Envoy proxies. With the GCP balancer I can actually get the client IP by having the GCP balancer pass it along on an internal header which I include in the logs, but `X-Forwarded-Proto` otoh is completely disregarded unless `xff_num_trusted_hops` is non-zero and since TLS is terminated on the GCP balancer, this header is the only way to know if the request was made via http or https by the end user.

Setting `xff_num_trusted_hops` to 2 in this case was key (allows `X-Forwarded-Proto` to be trusted as well as the chain of IP address in `X-Forwarded-For` set by the balancer). Not sure if it's common or useful enough to be able to set this without using the more advanced `EnvoyPatchPolicy` but it is rather easily accomplished:

```yaml
    jsonPatches:
    - name: envoy-gateway/l7-global-external/http
      operation:
        op: add
        path: /default_filter_chain/filters/0/typed_config/xff_num_trusted_hops
        value: 2
      type: type.googleapis.com/envoy.config.listener.v3.Listener
```

**Comment by zirain** [comment]
first pass: this can be part of `EnvoyProxy`

**Comment by arkodg** [comment]
adding an option to configure `xff_num_trusted_hops` in `EnvoyProxy` config sgtm

**Comment by davidalger** [comment]
@zirain @arkodg given `xff_num_trusted_hops` is configured on the listeners, it would seem to make sense that this would be configured via `ClientTrafficPolicy` since it is attached to a `Gateway` (and optionally specific listeners on a Gateway) rather than `EnvoyProxy` which is limited to being attached to a `GatewayClass`.

In anticipating this will be an agreeable approach, I have opened a PR with a working implementation for review: #2535
