### ISSUE TITLE
Canary Deployment for config

### ISSUE THREAD

**Issue by sonnydinhgc** [envoyproxy/gateway#2255]
*Description*:
Hi there
I'd like to inquire about the process for adding or updating a new route or similar configurations. Is there an approach available that allows us to implement a canary release for these configurations?

**Comment by zhaohuabing** [comment]
Do you mean you want to apply the new config for just part of the incoming requests?
If that's the case, EG doesn't have a "Canary Deployment for config" feature, but you can try to use weighted routing to achieve something similar.

**Comment by zhaohuabing** [comment]
I think this can be achieved by deploying two Envoy Gateway instances side by side, one for serving the production traffic, and one for canary/testing traffic. Once the testing is done, we can change the DNS to point to the canary one.

**Comment by sonnyriverr** [comment]
@zhaohuabing  do you have example?

**Comment by sonnydinhgc** [comment]
@zhaohuabing  do you have any example?

**Comment by zhaohuabing** [comment]
I didn't try it myself. You're free to try this approach and report back any findings in this issue.

You can set a different controller name in the values.yaml when installing the canary eg instance, then you can have two sets of configurations, one for production, and one for canary testing.

For example:
controller name: gateway.envoyproxy.io/gatewayclass-controller-1 -> gateway calss: eg1 -> gateway1 -> xRoute1
controller name: gateway.envoyproxy.io/gatewayclass-controller-2 -> gateway calss: eg2 -> gateway2 -> xRoute2

**Comment by sonnydinhgc** [comment]
Got it thanks

**Comment by Xunzhuo** [comment]
@sonnydinhgc PTAL https://gateway.envoyproxy.io/latest/user/deployment-mode/

**Comment by arkodg** [comment]
closing this one since the solution has been shared
