### ISSUE TITLE
EnvoyGateway CRD Definition is not in HELM

### ISSUE THREAD

**Issue by mikebevz** [envoyproxy/gateway#2262]
*Description*:
I cannot find EnvoyGateway CRD (https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#envoygateway) in the Helm Chart (v0.6.0, latest)

Is it possible to register an extension in v0.6.0?

**Comment by bladedancer** [comment]
This might just be noise - I don't know why it's not a registered CRD but it's used in the envoy-gateway-config configmap to configure the gateway directly. I presume you could register the extension in that configmap.

**Comment by mikebevz** [comment]
Thank for the answer. Got it. Thanks!
