### ISSUE TITLE
OOM killed

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#2265]
*Description*:

watch some HTTPRoute that has some error. maybe the service does not exist. the EG has been killed due to  `Reconcile` them.

*Logs*:
![image](https://github.com/envoyproxy/gateway/assets/2174082/3caf06e7-a8a0-4574-9557-861733d4b90c)

**Comment by qicz** [comment]
IMO, should set `RequeueAfter` to requeue

**Comment by Xunzhuo** [comment]
I did not reproduce it, can you provide the steps to reproduce it ? @qicz

**Comment by Xunzhuo** [comment]
Tried that and just HTTPRoute reported BackendNotFound, the eg works still well

**Comment by qicz** [comment]
> Tried that and just HTTPRoute reported BackendNotFound, the eg works still well

 this report too often and there are more invalid HTTPRoute, the EG has been killed due to Reconcile them.

**Comment by zzjin** [comment]
@qicz I'm facing same error here.
But My usage is setting about ~1300 `HTTPRoute` CR with about ~20 `Gateway` with `mergeGateway=true`. 
![image](https://github.com/envoyproxy/gateway/assets/679757/40ccbafc-9eea-4759-811d-5df50709635e)


May be it's not `non-exists` backends cause eg oom, but the count of gateway api crs cause eg oom, I'm facing that deployment `envoy-gateway` pod eats too many memory.
![image](https://github.com/envoyproxy/gateway/assets/679757/2e0c5d32-36bf-4e59-92ab-f934d667f4fd)
default eg memory limit is 1g, you can change this to unlimited, but the problem is still the problem.

**Comment by arkodg** [comment]
@qicz in your logs, can you please paste the entire log showing the namespace and name of service, along with `kubectl` info on the service as well the httproute that is linking to it ?

**Comment by qicz** [comment]
> @qicz in your logs, can you please paste the entire log showing the namespace and name of service, along with `kubectl` info on the service as well the httproute that is linking to it ?

@arkodg sorry reply slowly. the namespace and service are from my company app, so they have been cleared by me.

**Comment by qicz** [comment]
> @qicz I'm facing same error here. But My usage is setting about ~1300 `HTTPRoute` CR with about ~20 `Gateway` with `mergeGateway=true`. ![image](https://private-user-images.githubusercontent.com/679757/291266027-40ccbafc-9eea-4759-811d-5df50709635e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzY5MDcsIm5iZiI6MTcwNDg3NjYwNywicGF0aCI6Ii82Nzk3NTcvMjkxMjY2MDI3LTQwY2NiYWZjLTllZWEtNDc1OS04MTFkLTVkZjUwNzA5NjM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwODUwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjJlYjJkNWExMmZiYWEzY2U0ZjgzMzY0OGE1NDJhNmI5YjJiNjRlY2U1YTZkOTFjYzlhMTM5M2QzNzNiMjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vwqa1lD8CxB4rfL6iLaX-yhttxWfGrUcSXj5EITNf-I)
> 
> May be it's not `non-exists` backends cause eg oom, but the count of gateway api crs cause eg oom, I'm facing that deployment `envoy-gateway` pod eats too many memory. ![image](https://private-user-images.githubusercontent.com/679757/291265823-2e0c5d32-36bf-4e59-92ab-f934d667f4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzY5MDcsIm5iZiI6MTcwNDg3NjYwNywicGF0aCI6Ii82Nzk3NTcvMjkxMjY1ODIzLTJlMGM1ZDMyLTM2YmYtNGU1OS05MmFiLWY5MzRkNjY3ZjRmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwODUwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTk0Nzg3YTcxN2U5NDJjY2VjN2IzMGNmMDhkMGMwMzEwNmEzZGZmMWNiZGY1OTBiZDUwNWM5Y2MxMTZjMTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fJGXhduyfWkfhY7z2FO-yqWfe-A6TlZ2Vji4Amch4p8) default eg memory limit is 1g, you can change this to unlimited, but the problem is still the problem.

in my case, there are only ~30 `HTTPRoute`.  but can not set the memory to unlimited, it is bad for the Kubernetes cluster

**Comment by zzjin** [comment]
> in my case, there are only ~30 `HTTPRoute`. but can not set the memory to unlimited, it is bad for the Kubernetes cluster

No need to be unlimited, but some thing larger for routes is enough.
But as always, it must be some thing wrong with oom here.

**Comment by qicz** [comment]
> @qicz @zzjin can you outline steps to reproduce the problem, from this chat its hard to understand what the trigger is

The analysis concludes that the OOM problem is that there are many secrets and the MEM limit is not set properly.

**Comment by qicz** [comment]
suggestion: using protobuf connect to Kubernetes to optimize the mem. xref #1596

**Comment by zzjin** [comment]
> > @qicz @zzjin can you outline steps to reproduce the problem, from this chat its hard to understand what the trigger is
> 
> The analysis concludes that the OOM problem is that there are many secrets and the MEM limit is not set properly.

May be that's the problem, our cluster we have about ~3000 ingress with https,witch means about ~3000 secrets.

**Comment by arkodg** [comment]
@qicz can you share mem stats of EG before & after https://github.com/envoyproxy/gateway/pull/1596 ?

**Comment by arkodg** [comment]
closing due to no response, please reopen if you hit this issue again

**Comment by miguelvr** [comment]
Hi @arkodg, I've hit the same issue.

It seems like the envoy gateway is creating infinite HTTPRoutes for the HTTP01 challenge, while the challenge is not satisfied. My (unproven) theory is that it is provisioning the `HTTPRoute` resource with `generate_name` instead of using a predictable name, and this causes an infinite reconciliation loop.

**Comment by arkodg** [comment]
thanks for debugging this one @miguelvr , cross linking the cert-manager issue here https://github.com/cert-manager/cert-manager/issues/7176

@envoyproxy/gateway-maintainers should we consider something like[ envoy's overload manager ](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/overload_manager) where we stop reconciling more resources (flag this in a `GatewayClass` status) in case we hit some specified memory threshold ?
