### ISSUE TITLE
JWT SecurityPolicy does not forward Authorization header by default

### ISSUE THREAD

**Issue by akhenakh** [envoyproxy/gateway#2295]
The JWT SecurityPolicy if enabled does not forward the `Authorization` header upstream.

This is the default behaviour in Proxy if `forward` is not set to true:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter#jwtprovider

Yet it is a weird behaviour for a gateway to temper headers from the original request.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter#jwtprovider
relevant code https://github.com/envoyproxy/gateway/blob/f3e4e932d0749f38af339a92ec68cebbf29645ef/internal/xds/translator/jwt.go#L139-L145

Adding `Forward: true` will result of not removing the `Authorization` header.

I'm not sure myself what would be a sane default, but this could become a parameter or at least documented in Gateway.

**Comment by akhenakh** [comment]
Slack discussion https://envoyproxy.slack.com/archives/C03E6NHLESV/p1701708137782169

**Comment by zhaohuabing** [comment]
We have two options here:
1. Expose Envoy `forward` knob to EG `SecurityPolicy` API
2. Set `forward` to `true` when translating the xds

I am leaning towards option 2 because it doesn't harm to pass down the JWT authorization header. WDYT @arkodg @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
looks like we went ahead with 2. which was completed with #2300, can this be closed @zhaohuabing ?

**Comment by zhaohuabing** [comment]
> looks like we went ahead with 2. which was completed with #2300, can this be closed @zhaohuabing ?

Correct. We don't have to modify API with option 2. And if we need to give users the choice to move the token out later, we can add it to the API.
