### ISSUE TITLE
Support Default GatewayClass and Gateway Management

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#23]
To simplify the UX (especially for dev's), the project should support managing a default GatewayClass and Gateway. For example, when EG is started with an ENV var or CLI flag such as `--default-gateway-class=true` and `--default-gateway=true` it will create the default GatewayClass and default Gateway resources.

Open Questions:
1. What namespace should be used for the default Gateway? To support the most simple use case, the `default` namespace can be used? If the `Gateway` is created in the EG system namespace, then the default Gateway needs to support cross-namespace routing as this ns is not meant for proxied apps, [xref](https://gateway-api.sigs.k8s.io/v1alpha2/guides/multiple-ns/).
2. Should EG support active management of these resources, e.g. someone deletes the default Gateway and EG will recrate it.
3. Other considerations?

**Comment by adamdunstan** [comment]
Depending on the overall configuration construction of the solution, I could see the value of adding the GatewayClass by default but not the Gateway.  When implemented to include the allocation of an external IP Address, the address is allocated when the Gateway is created.  This is logical, an IP address has a different lifecycle than a route, allocating an address before its needed doesnt seem like the right correct action.  The second reason this doesnt seem right is that Gateway resources are not global, they are namespaced and would probably be associated with a specific application or team.  To share a Gateway the gateway listener resource is configured with the namespaces that routes can be attached.  Not sure how a sensible default could be constructed

**Comment by danehans** [comment]
We need to keep in mind the "batteries included" approach to streamline onboarding app devs with Envoy.  The default gc/gw could look similar to [this upstream example](https://github.com/kubernetes-sigs/gateway-api/blob/master/examples/v1alpha2/basic-http.yaml#L1-L21) but include a [tls config](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayTLSConfig).
