### ISSUE TITLE
Problems using Envoy Gateway with GKE

### ISSUE THREAD

**Issue by jimangel** [envoyproxy/gateway#2301]
## Description:
Trying to use Envoy Gateway on a GKE cluster with the Gateway API CRDs already installed (`v1beta1`) results in:

```
failed to create provider Kubernetes: failted to create gatewayapi controller: failed to get API group resources: unable to retrieve the complete list of server APIs: gateway.networking.k8s.io/v1: the server could not find the requested resource
```

I assumed that Envoy's implementation of Gateway API would [not have a hard requirement on v1](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/resource.go#L14) but that seems incorrect.

Trying to install the v1 CRDs directly get's overridden by GKE:

```
kubectl apply -k “https://github.com/kubernetes-sigs/gateway-api//config/crd/experimental?ref=v1.0.0”
```

Checking to see what versions are installed on GKE:

```
kubectl get crd -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{range .spec.versions[*]}{.name}{": storage="}{.storage}{"\n"}{end}{end}'
```

Output:

```
gatewayclasses.gateway.networking.k8s.io
v1alpha2: storage=false
v1beta1: storage=true
gateways.gateway.networking.k8s.io
v1alpha2: storage=false
v1beta1: storage=true
```

It appears that on GKE, you cannot install v1 if using their managed Gateway API "standard" channel.

Compared to a non-GKE, working, cluster output:

```
gatewayclasses.gateway.networking.k8s.io
v1: storage=false
v1beta1: storage=true
gateways.gateway.networking.k8s.io
v1: storage=false
v1beta1: storage=true
```

**Problem 1:** The helm chart bundles CRDs of upstream Gateway API & Envoy CRDs, meaning there's no easy way to only install one or the other. Where this would be handy, is clusters that already have Gateway API (the OSS spec) installed and they are looking at adding different gateways.

**Problem 2:** It appears that Envoy Gateway has a hard requirement for the latest Gateway API version being at `v1` and having `v1beta1` is not enough, regardless of version storage.

**Problem 3:** If someone was on GKE, running with the managed Gateway API CRDs, there is no easy path to leveraging Envoy Gateway. While this could be an issue for Google / GKE to solve, if Envoy Gateway API worked with `v1beta1` we would have an easier path to migrate.

**Problem 4:** It appears Envoy Gateway installs the experimental APIs which also could be different from someone's cluster.

Gateway API being out of tree was supposed to allow folks to "BYOcrds" and then enable various Gateway API implementations. The way Envoy Gateway is approaching it today removes a lot of that promise / value.

## Solution:

- Make the installation of Gateway API CRDs "out of scope" for the helm charts and provide the steps as a pre-req
- Drop the hard requirement to have `v1` unless there's a technical reason in doing so
  - Potentially support/warn `v1beta1` (and any other Gateway API CRDs) in logs so consumers can leverage Envoy Gateway and migrate to latest supported version
- Drop the (hard/soft?) requirement for _experimental_ Gateway APIs and let the consumer choose

I'm happy to strip out the OSS Gateway API CRDs from the helm charts and revise the `README.md` but would need additional support / nudging for how the code changes could/would be handled. I would also love to hear folk's thoughts on the matter! Thanks!

**Comment by jimangel** [comment]
If anyone else runs into this, I've temporarily worked around the issue using version `v0.5.0`:

```
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.5.0 -n envoy-gateway-system --create-namespace
```

**Comment by zirain** [comment]
I recall I saw this somewhere, but cann't recall.

**Comment by zhaohuabing** [comment]
@jimangel Thanks for reporting this issue.

If I understand correctly, this actually requires Envoy Gateway to supports different versions of Gateway API. While this may be technically feasible, it would need massive architectural modification,  and I am not entirely certain whether it would be a prudent decision. @envoyproxy/envoy-maintainers

**Comment by arkodg** [comment]
@zhaohuabing has shared some workarounds / alternate solutions, closing this issue
