### ISSUE TITLE
Support Ext Auth in the SecurityPolicy

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2306]
*Description*:
As an app developer, I would like to call out to an external service to check if a request is allowed to access the protected resource.

[optional *Relevant Links*:]

Envoy  ExtAuth filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter

**Comment by arkodg** [comment]
dup of https://github.com/envoyproxy/gateway/issues/1059

**Comment by zirain** [comment]
let's close this first.
