### ISSUE TITLE
Find the right home for maximum number of parallel retries

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2322]
*Description*:
EG needs to find the right home for "maximum number of parallel retries"

* Option 1:  par of the [Circuit Breaker setting in BackendTrafficPolicy](https://github.com/envoyproxy/gateway/pull/2284)
* Option 2:  par of the [Retry setting in BackendTrafficPolicy](https://github.com/envoyproxy/gateway/pull/2168)

I prefer option 1 because: 
Even though both have "retries" in their name, "maximum number of parallel retries" and "request retires" serve two different purposes. The concurrent max retries setting is inherently associated with the Circuit Breaker, which fails requests quickly when  lot of retries happen and apply back pressure on downstream. On the other hand, request retries are specifically designed to mitigate transient network issues. Would love more insights from @kflynn and other @envoyproxy/gateway-maintainers

[optional *Relevant Links*:]
* https://github.com/envoyproxy/gateway/pull/2284
* https://github.com/envoyproxy/gateway/pull/2168

**Comment by Xunzhuo** [comment]
Should they configure separately, since they have different purposes ?

**Comment by zhaohuabing** [comment]
> y configure separately, since they have different purposes ?

That's my suggestion.

**Comment by kflynn** [comment]
What's the actual purpose of configuring parallel retries? It clearly doesn't make any sense that a single request will be be sent to multiple upstream instances in parallel, so this implies that many downstream requests are arriving, failing, and being retried.

Given that Envoy configures budgeted retries in circuit breaking, and counted retries separately, I wonder if it also separates its counting of parallel retries between the two. Does anyone happen to know the answer to that? 

I would hope that it doesn't, in which case I would hope that this would be a single setting in the `Retry` configuration. But I don't know what Envoy actually does...

**Comment by zhaohuabing** [comment]
> Given that Envoy configures budgeted retries in circuit breaking, and counted retries separately, I wonder if it also separates its counting of parallel retries between the two. Does anyone happen to know the answer to that?

@kflynn  I'm not sure I get your question here. If you're referring the `max_retries` and `retry_budget` in the [CircuitBreakers](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers-thresholds), I believe only one of them should be specified, and according to envoy docs, `retry_budget` is the recommended one.

> Cluster maximum active retries: The maximum number of retries that can be outstanding to all hosts in a cluster at any given time. In general we recommend using [retry budgets](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-field-config-cluster-v3-circuitbreakers-thresholds-retry-budget); however, if static circuit breaking is preferred it should aggressively circuit break retries. This is so that retries for sporadic failures are allowed, but the overall retry volume cannot explode and cause large scale cascading failure. If this circuit breaker overflows the [upstream_rq_retry_overflow](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#config-cluster-manager-cluster-stats) counter for the cluster will increment.

**Comment by guydc** [comment]
While working on #2725 I noticed that the default envoy max_retry limit is quite low (3) leading to retry overflow when there is a [significant amount of requests](https://github.com/envoyproxy/gateway/actions/runs/8118438104/job/22194033455?pr=2725#step:6:1611) to a restarting backend. Envoy provides a [sample](https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/transient_failures#outlier-detection) that increases this value to 10 to deal with restart scenarios. Should we use a more permissive default, e.g. 20% default retry budget?
