### ISSUE TITLE
k8s support matrix should be revisited pre GA

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2333]
*Description*:
k8s support matrix should be revisited pre GA

**Comment by arkodg** [comment]
I think we should support last 5 k8s versions, similar to what upstream Gateway API supports
but we could reduce CI time, and only run 1st, 3rd and 5th k8s version https://github.com/envoyproxy/gateway/blob/1775624114aedee731bee565a0a100eeee80fc13/.github/workflows/build_and_test.yaml#L83

wdyt @envoyproxy/gateway-maintainers ?
