### ISSUE TITLE
Add ability to set k8s fields not defined in the EnvoyProxy provider config

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2346]
*Description*:
Envoy Gateway allows users to customize the Envoy Proxy fleet resources such as - Deployment, Service and HPA. These customizations are a subset of the the entire resource spec

https://github.com/envoyproxy/gateway/blob/5d691f2b312fb1fadce7cd7220759334f796ee6d/api/v1alpha1/shared_types.go#L54

Would be great if we can add a generic way to patch/set any field in the above resources so
* users can make edits without waiting for the field to be added and exposed in a future release
* EG doesnt need to add all fields, especially ones such as `hostNetwork` that are not common case scenarios

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
@zirain Thoughts on this ?

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/pull/2337#issuecomment-1866229984

**Comment by arkodg** [comment]
we could allow users to specify a merge patch (strategic or json merge patch) https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-strategic-merge-patch-to-update-a-deployment

**Comment by arkodg** [comment]
thoughts on ?
```
merge:
  type: StrategicMerge
  spec:
    .......
```

**Comment by zirain** [comment]
> thoughts on ?
> 
> ```
> merge:
>   type: StrategicMerge
>   spec:
>     .......
> ```

looks good to me
