### ISSUE TITLE
Enable OpenSSF Scorecard

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2347]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Monitor security best practices using https://github.com/ossf/scorecard

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
Should we also consider [openssf best practices](https://www.bestpractices.dev/en)?

**Comment by arkodg** [comment]
@zhaohuabing I believe scorecard evaluates based on best practices implemented, so implementing them will be a by product of the introducing the scorecard
