### ISSUE TITLE
Unify how we represent external services/endpoints

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2348]
*Description*:
>Describe the issue.

Raising this issue to align on how we represent external endpoints or services in EG APIs

The two most common pattern I'm seeing are

* URL
e.g the Redis URL with the RateLimit config https://github.com/envoyproxy/gateway/blob/5d691f2b312fb1fadce7cd7220759334f796ee6d/api/v1alpha1/envoygateway_types.go#L366

* Host and Port

e.g the Extension Service config https://github.com/envoyproxy/gateway/blob/5d691f2b312fb1fadce7cd7220759334f796ee6d/api/v1alpha1/envoygateway_types.go#L409

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers @envoyproxy/gateway-reviewers

**Comment by zhaohuabing** [comment]
My two cents:
* If it's an HTTP URL with a path, it should be a URL
* If it's just a host and a port,  we should not use a URL

So both the Redis and Extension service should be represented by "Host and Port".

**Comment by arkodg** [comment]
if we need to specify protocol as well, that would be 3 field to maintain for the project and define for the user vs defining all 3 in the URL

**Comment by zhaohuabing** [comment]
> if we need to specify protocol as well, that would be 3 field to maintain for the project and define for the user vs defining all 3 in the URL

Ha, that's a fair point. :-)

**Comment by zhaohuabing** [comment]
One problem of using URL instead of a triple(protocol, host,port) is that it's harder to limit and verify the protocol and other parts of the URL. For example, Ext Auth supports two protocols: GRPC and HTTP, which can be easily limited with a predefined enum, but probably can only be verified when translating the `SecurityPolicy` API to IRs.

**Comment by zhaohuabing** [comment]
> One problem of using URL instead of a triple(protocol, host,port) is that it's harder to limit and verify the protocol and other parts of the URL. For example, Ext Auth supports two protocols: GRPC and HTTP, which can be easily limited with a predefined enum, but probably can only be verified when translating the `SecurityPolicy` API to IRs.

It can be validated with a regex like "^https?:\/\/(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*(:[0-9]+)?$"

**Comment by arkodg** [comment]
thanks for sharing the validation technique @zhaohuabing, +1 to using a single `URL` field

**Comment by arkodg** [comment]
@zirain, does that sgty ?

**Comment by zirain** [comment]
what about grpc?

**Comment by arkodg** [comment]
> what about grpc?

`grpc://<>` or `grpcs://<>` , can't find any supporting doc, apart from docs in other implementations such as Postman and NGINX

**Comment by zirain** [comment]
> > what about grpc?
> 
> `grpc://<>` or `grpcs://<>` , can't find any supporting doc, apart from docs of other implementations such as Postman and NGINX

if so, make sense to me.

**Comment by zhaohuabing** [comment]
https://github.com/envoyproxy/gateway/pull/2313#discussion_r1440048392

**Comment by arkodg** [comment]
closing since we are trying to use the upstream backendRef definition wherever possible
