### ISSUE TITLE
Implement liveness and readiness probes on the Deployment

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#235]
There are liveness and readiness probes defined on the envoy-gateway Deployment: https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/config/envoy-gateway/deploy_and_ns.yaml#L40-L49

However, I don't see any code that implements these, and in my test cluster the pod is not responding to them and therefore not becoming ready / getting restarted regularly.

They need to either be implemented, or removed for now until we're ready to implement them so the pod can at least run.

**Comment by skriss** [comment]
The probe definitions have been temporarily removed in #238 to unblock running EG in cluster but should eventually be re-added and implemented properly.

**Comment by skriss** [comment]
> I can help on this, assign this to me plz

Great, thanks @Xunzhuo!

**Comment by danehans** [comment]
@Xunzhuo are you still able to help with this issue?
