### ISSUE TITLE
External IP with confusion.

### ISSUE THREAD

**Issue by zzjin** [envoyproxy/gateway#2378]
@see https://github.com/envoyproxy/gateway/pull/2309#issuecomment-1863546962

> @Xunzhuo you can route to the service port (80/443) via External IP

The External IP is not the silver bullet for resolve network problems.

In such a scenario: multiple users have one cluster sharing gateway, which means each user's hostname is different, but they all share cluster node's 80/443.

When there is no any outside LB/DNS, just some nodes with k8s installed, the cluster admin must have to consider:
1. Let all user have rights to update one Gateway CR(CR with External IP being set), this method have some grant leaks such as every user can changed others hostname because there are only one gateway cr.
2. Let every user have their own gateway CR, but this lead to every user must known cluster's all External IPs, when cluster node is updated(add/delete), every gateway CR must update to match.
3. Both method above have one more permission leakage problem, witch is, every user can set listeners to any port, other than 80/443, when they know cluster externalIP. So the node's service may be overridded by this method.

**Comment by arkodg** [comment]
can we worked around with the DaemonSet support https://gateway.envoyproxy.io/latest/api/extension_types/#kubernetesdaemonsetspec
