### ISSUE TITLE
Documentation about standalone use

### ISSUE THREAD

**Issue by deepankarsharma** [envoyproxy/gateway#2415]
*Description*:
Envoy Gateway website introduces Gateway as "Manages Envoy Proxy as a Standalone or Kubernetes-based Application Gateway". However I have been unable to find any documentation or pointers on standalone use of Envoy Gateway outside Kubernetes. Would appreciate some pointers / writeups / examples of standalone use in the documentation.

[optional *Relevant Links*:]
https://gateway.envoyproxy.io/

**Comment by arkodg** [comment]
stand alone is being tracked with https://github.com/envoyproxy/gateway/issues/1393
