### ISSUE TITLE
docs: Downstream TLS Settings

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2421]
*Description*:
>Describe the issue.

Relates to https://github.com/envoyproxy/gateway/pull/2297 & https://github.com/envoyproxy/gateway/issues/2286

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
thanks @zesiar0

**Comment by arkodg** [comment]
@zesiar0 can you comment here so we can assign this to you ?

**Comment by zesiar0** [comment]
> @zesiar0 can you comment here so we can assign this to you ?

sorry, I mistake the issue. Please this issue to me
