### ISSUE TITLE
Add support JWT extraction from `headers` and `params`

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#2429]
*Description*:
Related to #2186 

Currently, I have a use case that demands multiple JWT extractions from the header (`Authorization Bearer`) or the cookies.

**The use case:**
My current org has invested time to move into Envoy Gateway as a replacement for Ingress, we have microservices coming from multiple entities in which they used different ways to extract the JWT, either from the header and/or the cookie. With the most recent version of Envoy Gateway, we can only satisfy JWT extraction from cookies but not from any other methods (e.g., headers or params).

[optional *Relevant Links*:]

**Comment by ardikabs** [comment]
please assign to me if the triage can be accepted

**Comment by cnvergence** [comment]
@ardikabs assigned, thanks!
