### ISSUE TITLE
Unused update/patch verbs in EG RBAC

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/gateway#2449]
*Description*:
EnvoyGateway RBAC in helm chart contains unused update & patch verbs for the following resources:
- gateway.envoyproxy.io.envoyproxies
- gateway.envoyproxy.io.envoypatchpolicies
- gateway.envoyproxy.io.clienttrafficpolicies
- gateway.envoyproxy.io.backendtrafficpolicies
- gateway.envoyproxy.io.securitypolicies
- gateway.networking.k8s.io.gateways
- gateway.networking.k8s.io.grpcroutes
- gateway.networking.k8s.io.httproutes
- gateway.networking.k8s.io.referencegrants
- gateway.networking.k8s.io.referencepolicies
- gateway.networking.k8s.io.tcproutes
- gateway.networking.k8s.io.tlsroutes
- gateway.networking.k8s.io.udproutes

Is it on purpose? maybe a preparation for future finalizers usage?

[optional *Relevant Links*:]
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/_rbac.tpl#L74-L75
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/templates/_rbac.tpl#L106-L107

**Comment by arkodg** [comment]
`update` is used to update the `Status`  subresource, unsure about `patch`
reg finalizers, we only have it for the `GatewayClass`

**Comment by shahar-h** [comment]
@arkodg there are separate rules for `Status` subresource:
https://github.com/envoyproxy/gateway/blob/9081d82e0b3e0d2c21b36355029eb8dd4126fe18/charts/gateway-helm/templates/_rbac.tpl#L79-L88
https://github.com/envoyproxy/gateway/blob/9081d82e0b3e0d2c21b36355029eb8dd4126fe18/charts/gateway-helm/templates/_rbac.tpl#L110-L122

**Comment by arkodg** [comment]
ah thanks for finding that, looks like this issue will need some triaging, maybe we can remove above verbs and see how we do in the conformance test

**Comment by shahar-h** [comment]
@arkodg I can open a PR. can you assign me?
