### ISSUE TITLE
Support Allow/Deny IP Subnets

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2462]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

As a user, I would like to limit the client IP address to a few subnets for some cases as well as also deny specific subnets

**Comment by arkodg** [comment]
Envoy supports this https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-principal

does this feature belong in `ClientTrafficPolicy` or `BackendTrafficPolicy` ?

**Comment by tmsnan** [comment]
Vote for `SecurityPolicy`. Access control is reasonable as a security policy.

**Comment by arkodg** [comment]
if the `SecurityPolicy` with ip subnet info is applied at the Gateway level, it can be overridden at the route level if another `SecurityPolicy` is applied at route level

**Comment by tmsnan** [comment]
Is it possible to add a disclaimer stating that the use of routing override is not recommended?

**Comment by zhaohuabing** [comment]
Should the https://github.com/envoyproxy/gateway/issues/2250 be the right home for this?

**Comment by zhaohuabing** [comment]
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-principal



> if the `SecurityPolicy` with ip subnet info is applied at the Gateway level, it can be overridden at the route level if another `SecurityPolicy` is applied at route level

I didn't get it. Another route level `SecurityPolicy` without Allow/Deny IP setting won't override Gateway level configuration. This should be only in the Gateway level?

**Comment by zetaab** [comment]
well at least I have use case that same gateway should be apple to serve clients from the internet, but some routes need to have allow/deny ip setting.

**Comment by arkodg** [comment]
@zhaohuabing A route level SecurityPolicy without Allow/Deny IP setting will override the Allow/Deny IP setting in Gateway level, until we implement https://github.com/envoyproxy/gateway/issues/1934
Can you share why `rbac` is a better home ? If we took that approach, config would look like
```
jwt:
   .........
acl:
   jwt:
     claims: ......   
```

vs

```
jwt:
  .....
  claims: .......
```

**Comment by arkodg** [comment]
thanks for sharing your use case @zetaab, based on community feedback sounds like `SecurityPolicy` is the way to go here

**Comment by zhaohuabing** [comment]
> @zhaohuabing A route level SecurityPolicy without Allow/Deny IP setting will override the Allow/Deny IP setting in Gateway level, until we implement #1934 

In the current implementation of `SecurityPolicy`, it doesn't. For example, if a route level `SecurityPolicy` doesn't has OIDC configuration, but a Gateway level `SecurityPolicy` has,  the Gateway level OIDC applies. As the below example shows:

https://github.com/envoyproxy/gateway/blob/95f4c10b9559d376362d7e71d5e8f31cae601b18/internal/gatewayapi/securitypolicy.go#L359-L374

**Comment by arkodg** [comment]
@zhaohuabing you are right, this needs to be fixed, being tracked with https://github.com/envoyproxy/gateway/issues/2055 which needs improvements in this logic https://github.com/envoyproxy/gateway/blob/100d3103363c64a5be480ee0a2d66e585a9882f1/internal/gatewayapi/securitypolicy.go#L360

**Comment by zinuga** [comment]
@arkodg so this wont be in GA release?

**Comment by zetaab** [comment]
@zinuga I have been implementing the api design for this in https://github.com/envoyproxy/gateway/pull/2652 its pretty fast implement after the api design is accepted.

**Comment by arkodg** [comment]
thanks for driving this @zetaab, the API is close to getting merged, if the implementation does complete by rc (March 1st-4th), we should be able to support it in v1.0

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/pull/2652
