### ISSUE TITLE
Surface resource status summary in egctl

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2463]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

As a user, Id like to use egtcl to give me a summary of the status of all resources so I can quickly find out 
if resources have be translated and programmed correctly into the data plane

Suggestions for UX
* egctl x status
OR
* egctl x analyze

Relates to https://github.com/envoyproxy/gateway/issues/2028

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
+1 for `egctl x status`

**Comment by shawnh2** [comment]
`egctl x status` sounds excellent, im interested in picking this one up, so assign myself

**Comment by arkodg** [comment]
thanks for picking this up @shawnh2
personally would love to see a `--quiet` and a `--verbose` option so as a user I can use this command to quickly check if something is wrong in the system (--quiet is useful here) or dig deep into state of all/or specific resource (--verbose is useful here)

linking gwctl which could be useful as a lib https://github.com/kubernetes-sigs/gateway-api/tree/main/gwctl

**Comment by shawnh2** [comment]
here's my design of `egctl x status`, cc @arkodg 

the cmd uix would be:
```bash
egctl x status [resources-type, default all] 
    [-n, --namespace, default all] 
    [-q, --quiet, default false] 
    [-v, --verbose, default false]
```

the usage:
```shell
# only show the summary of all resources with unhealthy status
egctl x status -q

# only show the summary of all resources with unhealthy status under a specific namespace
egctl x status -q -n foobar

# only show the summary of gatewayclass resources with unhealthy status in details
egctl x status gtw -q -v

# only show the summary of httproute resources with unhealthy status in details under a specific namespace
egctl x status httproute -q -v -n foobar
```

by default, `eg x status` show the summary of these information of resources:
```text
Resources Namespace, Resources Name, Created Time, Status
```

with `--verbose` on, the information of displayed resources depends on each resources type:
```text
# for gatewayclass type
Resources Namespace, Resources Name, Created Time, Status, Controller Name

# for gateway type
Resources Namespace, Resources Name, Created Time, Status, Listeners (its name and port number)

# ...
```

**Comment by arkodg** [comment]
thanks for kickstarting the design on this @shawnh2, here are some thoughts
* prefer the column to be called `CONDITIONS` instead of `STATUS`
* prefer if we didn't need a top level `policies` or `routes` and instead use the exact kind name .e.g `clientrafficpolicy` , `httproute`
* do we need `GroupVersion` ? can we do without it ?
* when `-v` and `-q` is disabled lets print all conditions - `type` , `status` and `reason`
* when `-q` is set, lets print only first `type` `status` and `reason` . This would mean we'd need to find another option to
print unhealthy resources. dont have a clear answer here
* when `-v` is set, lets print all condition fields including `observedGeneration`, `message` and `lastTransitionTime`
