### ISSUE TITLE
Support disablement of Envoy extensions

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/gateway#2479]
*Description*:
We would like to be able to disable envoy extensions as part of security hardening.
In order to achieve that `--disable-extensions <extension list>` cli flag needs to be provided to Envoy.

Today there are specific Envoy cli flags that can be configured explicitly as part of [EnvoyProxySpec](https://gateway.envoyproxy.io/latest/api/extension_types/#envoyproxyspec):
* [--log-level](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-l)
* [--component-log-level](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-component-log-level)
* [--concurrency](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency)
* [--config-yaml](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-config-yaml)

One approach to support `--disable-extensions` is to add an explicit configuration under EnvoyProxySpec.

A more generic approach would be to add support for `EnvoyExtraArgs` configuration, also under EnvoyProxySpec.
This will allow support of other Envoy cli args without changes in the code.
However, this approach raises some questions:
* Overriding existing args(i.e. `--log-level`) would cause Envoy to crash with `Argument already set!` error. Is this an acceptable behavior or do we want to somehow add a validation? Should args overriding be supported at all?
* Using non supported args will cause Envoy to crash with `Could not find match for argument` error.  Is this an acceptable behavior or do we want to somehow add a validation? I guess that we want to avoid holding a list of all supported cli args for validation.

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-disable-extensions
https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml

**Comment by zirain** [comment]
What are the benefits of this?

**Comment by zirain** [comment]
sorry for missing that part, `EnvoyExtraArgs ` sounds good to me.

**Comment by zirain** [comment]
> Overriding existing args(i.e. --log-level) would cause Envoy to crash with Argument already set! error. Is this an acceptable behavior or do we want to somehow add a validation? Should args overriding be supported at all?
Using non supported args will cause Envoy to crash with Could not find match for argument error. Is this an acceptable behavior or do we want to somehow add a validation? I guess that we want to avoid holding a list of all supported cli args for validation.

we can add validation for this, e.g ignore non supported args, ignore `log-level` if it existed, and throw an warn message.

**Comment by zirain** [comment]
> In order to ignore non supported args we need maintain a list of all Envoy supported args. Do we want to do that?

You can point out the risks and end users should take control.

**Comment by arkodg** [comment]
* since the API is called `EnvoyProxy`, thoughts on calling the field `extraArgs` or `extraCLIArgs` ?
* we can start without any validation, similar to what we've done for the deployment env args, and track this as a follow up.

**Comment by shahar-h** [comment]
+1 For extraArgs
