### ISSUE TITLE
Should We Do a 2-Way Reconcile of Resource Maps

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#248]
Should we do a full two-way reconcile of resource maps of the Kube provider? This will ensure resources from the map still exist in the API server, and the appropriate controller will remove them if they don't.

xref: https://github.com/envoyproxy/gateway/pull/230#discussion_r955377496

**Comment by arkodg** [comment]
@danehans is this needed ?
imho the data in the watchable map is based off the controller cache which should be in sync with the API Server, so shouldn't be needed

**Comment by arkodg** [comment]
can we close this issue @danehans  ?

**Comment by arkodg** [comment]
closing this issue for now @danehans , please feel free to open if you think this feature is still needed
