### ISSUE TITLE
docs: Show routing to service outside cluster using FQDN based EndpointSlices

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2482]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Support for FQDN Based EndpointSlice https://github.com/envoyproxy/gateway/issues/1922 was recently added, highlight this features in the user guide

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yuluo-yx** [comment]
@arkodg pls assign to me, I want to try.

**Comment by yuluo-yx** [comment]
I understand what this pr does, I read the documentation on the eg website, 
but it's not clear where to add it and what kind of instructions should be added, can you guide me? 
Thank you! @arkodg

**Comment by arkodg** [comment]
@yuluo-yx it would live under https://github.com/envoyproxy/gateway/tree/main/site/content/en/latest/user
a http routing example similar to the one in Quickstart should work https://github.com/envoyproxy/gateway/blob/main/site/content/en/latest/user/quickstart.md
and instead of a backend deployment, you can use a public fqdn for your endpointslice
