### ISSUE TITLE
Add a status to EnvoyPatchPolicy when the feature is disabled

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2502]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

The EnvoyPatchPolicy API only works when enabled in the startup `EnvoyGateway` config as highlighted here 
https://gateway.envoyproxy.io/latest/user/envoy-patch-policy/#enable-envoypatchpolicy

We've seen many users forget to enable this field and are confused by the API is not working.

One solution is to add a status condition (`Accepted: False`) with a reason mentioning that the feature is disabled and must be enabled in order for this resource to work as expected.

**Comment by arkodg** [comment]
related places that need to change
* https://github.com/envoyproxy/gateway/blob/850339813762c37b6c1bee10f161598290662e9c/internal/provider/kubernetes/controller.go#L1577
* https://github.com/envoyproxy/gateway/blob/850339813762c37b6c1bee10f161598290662e9c/internal/provider/kubernetes/controller.go#L269

**Comment by soulxu** [comment]
https://github.com/envoyproxy/gateway/pull/2504

Yup, I'm the one of user get confused :)
