### ISSUE TITLE
Envoy Client Certs for Ext Auth and Backend TLS

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2536]
*Description*:
>Describe the issue.

Raising this PR to make a decision on which client certs to use when originating a TLS connection to ext Auth and Backend TLS (relates to https://github.com/kubernetes-sigs/gateway-api/discussions/2743)

Option 1
Reuse Listener (Downstream) certs

Option 2
Define a common proxy cert in the `EnvoyProxy` config

Option 3 (not possible today)
Define certs in each config
* within the SecurityPolicy.ExtAuth.TLS field
* not possible in BackendTLS, since its a upstream API

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
> Option 1
> Reuse Listener (Downstream) certs

The problem of this approach is that existing ext auth and jwt services may not be able to verify the Listener certs.

**Comment by arkodg** [comment]
> EG doesn't use a global root ca like Istio does. So the problem of the first two approaches is that existing ext auth and jwt services may not be able to verify the client certs.

@zhaohuabing imo its a matter of sharing the CA (which is meant to be shared for validating trust anchor) with those entities (ext auth svc and backend)

**Comment by zhaohuabing** [comment]
> > EG doesn't use a global root ca like Istio does. So the problem of the first two approaches is that existing ext auth and jwt services may not be able to verify the client certs.
> 
> @zhaohuabing imo its a matter of sharing the CA (which is meant to be shared for validating trust anchor) with those entities (ext auth svc and backend)


One possible solution is allow the user to specify an external Root CA cert in the EnvoyProxy config. This Root CA cert is generated by a well-known public/shared CA trusted by all the external services and backends. 
Then Envoy can use this root CA to generate the server certs for the Listeners and the client certs for the Backends and the external services.

**Comment by guydc** [comment]
Option 1: it's possible (not 100% sure) that a server cert cannot always be used as a client cert, e.g. if it doesn't have the appropriate [extended key usage](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12) `TLS WWW client authentication`. For example, see [here](https://docs.apigee.com/how-to-guides/validating-certificate-purpose#extended-key-usage). 

Option 2 limits flexibility and option 3 creates a bit of duplication. I think that they're ok as mid-term mitigations. 
 
I think that in one of the community meetings, we discussed the following option as well:
- Extend BackendTrafficPolicy to support a TLS section, like we do in ClientTrafficPolicy, which will also include client certs. 
- Allow BTP to attach to K8s Services. Order of precedence for applying configuration is: xRoute > Gateway > Service. 
- ExtAuth, RL, ExtProc can use a Service-level BTP to define TLS behaviors (and possibly other cluster-level settings [circuit breakers, timeouts, ... ]).
- xRoute/Gateway-attached BTP is used to set client certs for upstream backend connections.

**Comment by arkodg** [comment]
another option is defining the envoy certs within the EnvoyProxy API

**Comment by zhaohuabing** [comment]
How can EG know which backend service enforces client validation and which doesn't require it?

**Comment by arkodg** [comment]
suggest waiting for upstream to align on naming https://github.com/kubernetes-sigs/gateway-api/pull/2910

**Comment by guydc** [comment]
> suggest waiting for upstream to align on naming [kubernetes-sigs/gateway-api#2910](https://github.com/kubernetes-sigs/gateway-api/pull/2910)

With the merge of the above, should we proceed with for something like: 

- `BackendTLS.ClientCertificateRef` for Client Certificate: #2984 
- `BackendTLS.Validation` for TLS Params #2901

**Comment by arkodg** [comment]
Fixed with https://github.com/envoyproxy/gateway/pull/3218

**Comment by guydc** [comment]
Hi @arkodg . I think that #3218 only included TLS params, not client certs. I think that @alexwo intends to pick up client certs in the future. Should we keep this open for now?

**Comment by arkodg** [comment]
my bad, reopening this one

**Comment by shawnh2** [comment]
closed in favor of https://github.com/envoyproxy/gateway/pull/3441
