### ISSUE TITLE
Support HTTP External Processing Filter

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#2546]
*Description*:
Envoy’s HTTP [External Processing Filter]( https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter) can be used by vendors and extension developers to enhance Envoy Proxy's data-plane feature set. The `ext-proc` filter implements a callout to an external grpc service in request and response flows. The external processor service can inspect and mutate requests and responses, access context data such as attributes and dynamic metadata and emit dynamic metadata. 

The external processing filter is included in the envoy base image and its security posture is robust. The external processing protocol and/or filter are also used in the industry for extensibility and integration: [GCP Application LB](https://cloud.google.com/service-extensions/docs/callouts-overview), [Gloo Edge](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/extproc/about/), [Imperva WAF](https://docs.imperva.com/bundle/v14.7-web-application-firewall-user-guide/page/79024.htm). 

Envoy Gateway can support the external processing filter in a way that is similar to the [ext-authz implementation](https://github.com/envoyproxy/gateway/pull/2435). If supported, this filter will fulfill some of the GA requirements outlined in #2025 related to Envoy Proxy extensibility.

**Comment by arkodg** [comment]
+1 to this
my preference would be to include this into #2025 as a new Policy and combine all dev extensions into one new Policy resource type 
cc @Xunzhuo

**Comment by zirain** [comment]
we could do this with EnvoyPatchPolicy now, right? what the benifit for create an new policy?

**Comment by arkodg** [comment]
a dedicated ExtensionAPI can do a better job
* dealing with config validation
* reducing surface area of extension
* doing extra work such as downloading wasm from registry

**Comment by zirain** [comment]
> doing extra work such as downloading wasm from registry

you want download wasm in controlplane?

**Comment by zirain** [comment]
I'm +1 for a dedicated ExtensionAPI, maybe named (Gateway|Proxy|Envoy)(Http/Networking)Filter, focus on insert/replace filters, and use ECDS to send XDS.

**Comment by Xunzhuo** [comment]
+1 for adding support to this, thanks for raisin it @guydc.

**Comment by guydc** [comment]
Please assign to me.
