### ISSUE TITLE
Use BackendRef to define Ext Auth Service

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2551]
*Description*:
>Describe the issue.

Consider using BackendRef definition https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.BackendObjectReference In the Ext Auth API instead of the current host:port definition https://gateway.envoyproxy.io/latest/api/extension_types/#extauth

* safer, since backendRef access to another namespace can be controlled using a ReferenceGrant
* deduplicates user authoring the ext auth endpoint definition in multiple places
* can be handy in the future in case we want to apply a Policy to a BackendRef e.g. BackendTLSPolicy
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1alpha2.BackendTLSPolicySpec

Relates to https://github.com/envoyproxy/gateway/issues/1059

Also relates to
*  ext-proc svc defintion https://github.com/envoyproxy/gateway/issues/2546
* upstream TLS https://github.com/envoyproxy/gateway/issues/2536

**Comment by arkodg** [comment]
@zhaohuabing this was discussed in the community meeting today with @guydc , and I'm a +1 on this, wdyt
cc @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
The implication of using 'BackendObjectRefrence' is that out of cluster ext auth services will not be supported. But I guess this is okay because normally the ext auth service should be deployed inside the cluster as a k8s service.

**Comment by arkodg** [comment]
> The implication of using 'BackendObjectRefrence' is that out of cluster ext auth services will not be supported. But I guess this is okay because normally the ext auth service should be deployed inside the cluster as a k8s service.

Yah, you can still use FQDN EndpointSlices for the out of cluster case, but it isn't pretty
