### ISSUE TITLE
Filter Ordering

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2571]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

* Some users would like to ratelimit request before authenticating them
* Some would like to first authenticate requests, retrieve claims based on the JWT, and ratelimit based on that

To address such cases, we need to introduce the ability to specify a order of preference in case the default order needs to be overridden (lives in https://github.com/envoyproxy/gateway/blob/3f37499cef2c76589ccbcf83a77fef92257cf5da/internal/xds/translator/httpfilters.go#L87 )

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zhaohuabing** [comment]
This is blocking `EnvoyExtensionPolicy`.

**Comment by arkodg** [comment]
closing as completed with https://github.com/envoyproxy/gateway/pull/3273
