### ISSUE TITLE
Hide unimplemented API fields in docs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2575]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

* Do not publish docs for fields with a `non-implemented` annotation 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yuluo-yx** [comment]
I want to try, pls assign to me. @arkodg

**Comment by arkodg** [comment]
thanks @yuluo-yx 
* recommend looking at https://github.com/envoyproxy/gateway/pull/2549 on how to add annotations
* `tcpKeepAlive` in `backendTrafficPolicy` can be used to test this out (its currently unimplemented) https://github.com/envoyproxy/gateway/blob/d44f4be1d60b778b8acefc2b67008a8947fa62a5/api/v1alpha1/backendtrafficpolicy_types.go#L67
* the logic to skip/hide from docs is probably in here https://github.com/envoyproxy/gateway/tree/main/tools/crd-ref-docs/templates
cc @zirain

**Comment by yuluo-yx** [comment]
hi, I found out that this document is for generating custom crd resources right?

Also, I didn't find any field comment with `non-implemented` in the project code or in [the official documentation](https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#backendtrafficpolicy), how should I look for such a field?

**Comment by zirain** [comment]
FYI:
not all custom markers are supportted, see more below

https://github.com/elastic/crd-ref-docs/blob/9a3105b6ca763ea03393fa6f396046ad7b5d4e38/processor/processor.go#L482
