### ISSUE TITLE
Add `egctl config ratelimit` support

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#2584]
*Description*:

add a subcommand call `egctl config ratelimit`.

by debugging the #2564, i found this subcommand can be very convenient for developers or users, to quickly scrape the config of global ratelimit infra.

by requesting the debug port (enabled by default, which is `6070`) of RL `0:6070/rlconfig`, the output of this subcommand will be, for example:

```text
rl.category_account: unit=MINUTE requests_per_unit=4, shadow_mode: false
rl.source_cluster_proxy.destination_cluster_bkthomps: unit=MINUTE requests_per_unit=2, shadow_mode: false
rl.source_cluster_proxy.destination_cluster_mock: unit=MINUTE requests_per_unit=1, shadow_mode: false
rl.source_cluster_proxy.destination_cluster_override: unit=MINUTE requests_per_unit=2, shadow_mode: false
rl.source_cluster_proxy.destination_cluster_fake: unit=MINUTE requests_per_unit=2, shadow_mode: false
rl.foo: unit=MINUTE requests_per_unit=2, shadow_mode: false
rl.foo.baz_not-so-shady: unit=MINUTE requests_per_unit=3, shadow_mode: false
rl.foo.baz_shady: unit=MINUTE requests_per_unit=3, shadow_mode: true
rl.foo.bay: unit=UNKNOWN requests_per_unit=0, shadow_mode: false
rl.foo.bar: unit=MINUTE requests_per_unit=3, shadow_mode: false
rl.foo.bar_bkthomps: unit=MINUTE requests_per_unit=1, shadow_mode: false
rl.foo.bar_banned: unit=MINUTE requests_per_unit=0, shadow_mode: false
rl.foo.baz: unit=SECOND requests_per_unit=1, shadow_mode: false
rl.unspec: unit=MINUTE requests_per_unit=2, shadow_mode: false
rl.qux: unit=UNKNOWN requests_per_unit=0, shadow_mode: false
mongo_cps.database_users: unit=SECOND requests_per_unit=500, shadow_mode: false
mongo_cps.database_default: unit=SECOND requests_per_unit=500, shadow_mode: false
```

ref: 
- #2028
- https://github.com/envoyproxy/ratelimit?tab=readme-ov-file#debug-port

**Comment by ShyunnY** [comment]
I'm interested in this, do we just need to grab the ratelimit config?

**Comment by shawnh2** [comment]
> I'm interested in this, do we just need to grab the ratelimit config?

yes. just a heads up, before grabbing the config, you may also need to check out whether global ratelimit has been enabled.

thanks for picking this one up.

**Comment by ShyunnY** [comment]
I think we should not have ratelimit as a subcommand of `egctl config`. Instead, use the `egctl ratelimit` command directly.

This allows us to support more ratelimit features in the future, instead of just fetching the configuration.

@shawnh2

**Comment by shawnh2** [comment]
Nowadays, egctl follows the UI/UX of `egctl [verb] [resource]` paradigm. By considering `config` as a verb which can allow users to retrieve configs from somewhere, and its `route`, `listener`, `cluster` etc, and even `ratelimit`, are the resources which the verb operates on.

We would extend ratelimit with more features in the future, but the UI/UX should be consistent. But `egctl ratelimit` will simply fall into the `egctl [resource] [verb]` paradigm. By retrieving the config, you will have `egctl ratelimit config`, by scraping the stats, you will have `egctl ratelimit stats`, etc.

**Comment by ShyunnY** [comment]
My opinion is different from yours. I think components should be distinguished on the egctl, so that users or developers can more clearly know what component functions they need. 

And with the development of rate limit, we may need to add more functions for retrieving or debugging rate limit in the future.

**Comment by ShyunnY** [comment]
So I am also very entangled with this issue. We may add `egctl ratelimit debug`, `egctl ratelimit stats`, `egctl ratelimit /debug/pprof/` in the future.

This is more explicit than `egctl stats ratelimit`, `egctl debug ratelimit`.. Moreover, the ratelimit responsibilities are unified in the `egctl ratelimit` command.

**Comment by shawnh2** [comment]
right, so i will assume you are a resources-first kinda person 😄 which is cool.

there're have been a very looong debate about whether verb-first or resources-first paradigm is suitable for a CLI tool. 

- the former is adopted by many tools, like kubectl, nerdctl etc. their UI/X puts verbs first, resources second, so you dont see 'kubectl pod get' very offen.

- the latter is token by tools like ctr etc, their UI/X puts resources first, and verbs/operations second. like you proposed, you were treated ratelimit as a resource, and all the verbs/operations are around it.

i'm not sure which category egctl belongs 🤔, but from current implementations, i will say it's a verb-first one. \cc @XunZhuo

if we choose to go with 'egctl ratelimit xxx', current UI/X better be changed to 'egctl envoy-proxy xxx'. it could be very messy if one CLI tool supports two types of paradigm.

and also AFAIK there ain't any promised features to be added to egctl for ratelimit. the egctl can evolve, but lets keep 'egctl config ratelimit' first.

**Comment by ShyunnY** [comment]
I see what you mean and I think your idea is better than mine. I will modify the PR: #2674

**Comment by arkodg** [comment]
great discussion, you'll find more in https://github.com/envoyproxy/gateway/pull/797/files where we decided to go with `egctl <cmd> <entity> <name>`
