### ISSUE TITLE
Propagate XFCC header to the backend

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2599]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Propagate the XFCC header to the client after validating the client via mutual TLS
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-forwardclientcertdetails

Decisions
1) Defaults / Opt in or opt out

2) Where should it live

a) https://gateway.envoyproxy.io/latest/api/extension_types/#headersettings
or
b) https://gateway.envoyproxy.io/latest/api/extension_types/#clientvalidationcontext

- [x]  https://github.com/envoyproxy/gateway/pull/3202
- [ ]  Docs: XFCC
- [ ]  E2E: XFCC

**Comment by zufardhiyaulhaq** [comment]
how expensive is the computing process if we opt-in for the XFCC?

this can also being used later in the authorization API
https://github.com/envoyproxy/gateway/pull/2652

**Comment by zufardhiyaulhaq** [comment]
no stale
