### ISSUE TITLE
Add a knob to make `per_connection_buffer_limit_bytes` configurable

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2600]
Interesting discussion [here](https://github.com/envoyproxy/envoy/issues/8448) on compression performance and buffer sizing. Should we make `per_connection_buffer_limit_bytes` configurable as part of this issue? 

I can also think of future use cases that include buffering filters (ext-auth with body, WAF, ext-proc, lua, buffer) that should be part of the Envoy Gateway scope and require buffer size tuning.

_Originally posted by @guydc in https://github.com/envoyproxy/gateway/issues/2451#issuecomment-1937790606_

Currently default to 32Kb
https://github.com/envoyproxy/gateway/pull/1306

**Comment by yaelShechter** [comment]
Please assign to me
