### ISSUE TITLE
Validate the CA Cert

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2601]
*Description*:
>Describe the issue.

https://github.com/envoyproxy/gateway/pull/2490 adds support for downstream mTLS by introducing a way to input the CA Cert

This cert should be validated to make sure its contents are valid similar to what is done for the server tls certs in https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/tls.go

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by guydc** [comment]
Maybe also relevant:
- Server cert/key not malformed
- Server cert/key matching each other

**Comment by arkodg** [comment]
@guydc server cert/key validation is already done today https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/tls.go
