### ISSUE TITLE
e2e: downstream mTLS

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2614]
*Description*:
>Describe the issue.

Add an e2e for validating clients using a CA Cert as a trust anchor

Relates to https://github.com/envoyproxy/gateway/issues/88

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by guydc** [comment]
Also consider testing additional variants of this feature, such as:
- Optional client certificate validation
- XFCC behavior and format
