### ISSUE TITLE
Docs: Unified envoy gateway installation documentation.

### ISSUE THREAD

**Issue by yuluo-yx** [envoyproxy/gateway#2616]
*Description*:

In the Quick Start section of the website, there are already steps on how to install the envoy gateway. 

`https://gateway.envoyproxy.io/v0.6.0/user/quickstart/#installation` 

In other eg-related articles, the installation section of the Quick Start is referenced.

<img width="815" alt="image" src="https://github.com/envoyproxy/gateway/assets/77964041/cc21b5b9-fde8-4d28-b462-ad883df5458a">

In the individual articles, the steps for installing eg are rewritten, but the contents are the same.

<img width="831" alt="image" src="https://github.com/envoyproxy/gateway/assets/77964041/ac147bd3-3438-4e0e-9a13-92a38ababc81">

e.g.: 
1. https://gateway.envoyproxy.io/v0.6.0/user/http-routing/
2. https://gateway.envoyproxy.io/v0.6.0/user/grpc-routing/
3. https://gateway.envoyproxy.io/v0.6.0/user/tcp-routing/

IMO, it's possible to unify them and reduce duplicates in the document, if this is something that needs to be done, please assign it to me and I'll complete it

**Comment by shawnh2** [comment]
thanks for finding this, you can dedup these contents under [the latest doc](https://gateway.envoyproxy.io/latest/user/)
