### ISSUE TITLE
docs: User Guide for Ext Auth

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2625]
*Description*:
>Describe the issue.

Add user guide for the Ext Auth feature 

Relates to https://github.com/envoyproxy/gateway/issues/1059

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zhaohuabing** [comment]
Close this since ext auth doc has been added.

https://gateway.envoyproxy.io/v1.0.1/tasks/security/ext-auth/
