### ISSUE TITLE
Implement upstream TLS for Ext Auth Service

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2627]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Blocked on https://github.com/envoyproxy/gateway/pull/2247

Relates to https://github.com/envoyproxy/gateway/issues/1059

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
@zhaohuabing is there any extra work needed for this, or do you think #2247 will transparently handle this ?

**Comment by zhaohuabing** [comment]
#2247 already covers this because we are using backendreference.
