### ISSUE TITLE
Replace Status with PolicyAncestorStatus in CTP, BTP and SP

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2631]
*Description*:
>Describe the issue.

Use the upstream `PolicyAncestorStatus` definition which creates a top level structure per controller
https://gateway-api.sigs.k8s.io/geps/gep-713/#standard-status-struct

instead of what we have today e.g. https://github.com/envoyproxy/gateway/blob/1775624114aedee731bee565a0a100eeee80fc13/api/v1alpha1/backendtrafficpolicy_types.go#L97

Should fix https://github.com/envoyproxy/gateway/issues/2520

**Comment by shawnh2** [comment]
by updating `Status` in Policies to `PolicyAncestorStatus`, this will also requires some changes in `egctl x status`

**Comment by shawnh2** [comment]
should we change it directly to `PolicyAncestorStatus` or instead consider [`PolicyStatus`](https://github.com/kubernetes-sigs/gateway-api/blob/72f679c7c67228f5b4340e0c2f50cc04b36945b1/apis/v1alpha2/policy_types.go#L187) which each `Ancestors` can refer to objects that are either the Target of a policy or above it in terms of object hierarchy, as described [in here](https://github.com/kubernetes-sigs/gateway-api/blob/72f679c7c67228f5b4340e0c2f50cc04b36945b1/apis/v1alpha2/policy_types.go#L129)?

**Comment by arkodg** [comment]
ah I meant using the struct you referenced https://github.com/kubernetes-sigs/gateway-api/blob/72f679c7c67228f5b4340e0c2f50cc04b36945b1/apis/v1alpha2/policy_types.go#L187, thanks for clarifying

**Comment by arkodg** [comment]
blocked on https://github.com/envoyproxy/gateway/issues/2724#issuecomment-1970130948
