### ISSUE TITLE
feature: Create GatewayClass as part of the helm chart

### ISSUE THREAD

**Issue by tamalsaha** [envoyproxy/gateway#2635]
*Description*:
The helm chart defaults the gateway controller name and users can create only one GatewayClass with that controller name. So, it will be less confusing if the GatewayClass was created as part of the helm chart. This way, if I want to create a custom GatewayClass (because I want to the MergeGateway feature but only for some gateways), I know that I have to install the helm chart twice. Thanks!

[optional *Relevant Links*:]
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/values.tmpl.yaml#L28-L31

**Comment by arkodg** [comment]
adding user defined resources in the EG chart becomes tricky since it could extend to even `Gateway` or `EnvoyProxy` . Prefer if users create their own custom helm charts and use EG as a sub chart within it in case they want to deploy a `GatewayClass` via helm
