### ISSUE TITLE
Issues with E2E for multiple GatewayClass per controller

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#2636]
*Description*:

Since #2298 landed, EG has officially supported multiple GatewayClass per controller feature.

But when I wrote some e2e test in EG that utilize this feature, I noticed there's some wrong with upstream GW API conformance suites.

**The GW API only supports one GatewayClass in one conformance test suite**, which the gateway class name is assigned via `--gateway-class`.

https://github.com/envoyproxy/gateway/blob/a5125bfac07d56893d2c8a0c05b7df08d1b911a5/test/e2e/e2e_test.go#L43-L45

So when you apply a new GatewayClass in current EG e2e env settings, all the new Gateways that ref to this new GatewayClass, its `spec.gatewayClassName` **will be overwritten by the gateway class name of current test suite** (assigned via `--gateway-class`). 

- See [`prepareGateway` method in GW API conformance utils](https://github.com/kubernetes-sigs/gateway-api/blob/1bd31243c2431a1905b46d73b5d27c6856e9f8a8/conformance/utils/kubernetes/apply.go#L71) for this logic.

This will lead to:

- Current [multiple-gc e2e test case](https://github.com/envoyproxy/gateway/blob/main/test/e2e/tests/multiple-gc.go) (introduced via #2298) is meaningless. Though the `private` and `internet` GatewayClass has been created successfully, but the `private-gateway` and `internet-gateway` are still ref to the [base `envoy-gateway` GatewayClass](https://github.com/envoyproxy/gateway/blob/a5125bfac07d56893d2c8a0c05b7df08d1b911a5/test/config/gatewayclass.yaml#L4)
- Still very tricky to implement e2e test for merge gateways feature (#2029)

*Environment*:

lattest

**Comment by cnvergence** [comment]
indeed @shawnh2, nice catch
```bash
k get gateways -A 
NAMESPACE                   NAME                 CLASS           ADDRESS          PROGRAMMED   AGE
gateway-conformance-infra   all-namespaces       envoy-gateway   172.18.255.203   True         17s
gateway-conformance-infra   backend-namespaces   envoy-gateway   172.18.255.204   True         17s
gateway-conformance-infra   my-tcp-gateway       envoy-gateway   172.18.255.205   True         17s
gateway-conformance-infra   same-namespace       envoy-gateway   172.18.255.202   True         17s
gateway-conformance-udp     udp-gateway          envoy-gateway   172.18.255.206   True         17s
internet                    internet-gateway     envoy-gateway   172.18.255.208   True         13s
private                     private-gateway      envoy-gateway   172.18.255.207   True         13s
```

**Comment by cnvergence** [comment]
Shall we then remove this e2e test, until we figure out how to do it properly with GW API suite?

**Comment by shawnh2** [comment]
> Shall we then remove this e2e test, until we figure out how to do it properly with GW API suite?

SGTM

**Comment by shawnh2** [comment]
Raised an issue in upstream GW API https://github.com/kubernetes-sigs/gateway-api/issues/2785

**Comment by shawnh2** [comment]
for multiple gatewayclasses related e2e test case, we should create a new test suite for each gatewayclass. can take #2665 as an example.

**Comment by cnvergence** [comment]
I will try it out for multiple gc e2e tests.
Possibly we could extend what you had proposed for merged gateways, wdyt @shawnh2?

**Comment by shawnh2** [comment]
> I will try it out for multiple gc e2e tests.
> 
> https://github.com/envoyproxy/gateway/pull/2707
> 
> Possibly we could extend what you had proposed for merged gateways, wdyt @shawnh2?

sounds great
