### ISSUE TITLE
about loadBalancer

### ISSUE THREAD

**Issue by cx2c** [envoyproxy/gateway#2653]
<img width="897" alt="image" src="https://github.com/envoyproxy/gateway/assets/13431516/c9dc270c-b076-4369-9d85-9984d7d60959">

关于loadBalancer，通常我们希望loadBalancer对应的外网IP是固定的。 在生产的维护场景，我们会先手动在云控制台创建lb，然后在使用nginx-ingress或者是istio的时候，在编排中填入此lb的id进行固定。那Envoy Gateway怎么指定lb id呢。

还有在实际的使用窗景中， 我先创建一个GatewayClass，然后再基于此GatewayClass创建一个Gateway。当我创建多个Gateway时候，会创建多个LoadBalancer负载均衡。但是当我删除Gateway时， 系统还是会有一个LoadBalancer类型service并不会删除。请问Gateway正确的使用姿势是什么

**Comment by Xunzhuo** [comment]
In the cloud, if you want to reuse a created lb, you can usually specify the lb id in the Service annotation, so it is also similar in Envoy Gateway, you can customize the Service resource with EnvoyProxy CRD.

**Comment by Xunzhuo** [comment]
Second question, if you did not enable mergeGateway, 1 Gateway CR - 1 EnvoyProxy Deployment / Service, etc.

If you want to delete all created resources, you need to delete all Gateway CR.
