### ISSUE TITLE
docs: multiple GatewayClass deployment

### ISSUE THREAD

**Issue by cnvergence** [envoyproxy/gateway#2654]
Description:

Describe the issue.

Update the docs with multiple GatewayClass deployment mode

Relates to https://github.com/envoyproxy/gateway/issues/1231

[optional Relevant Links:]

Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
Hey @cnvergence can you help on it, since you implemented this feature : )

**Comment by cnvergence** [comment]
Sure, I will work on it
