### ISSUE TITLE
When there are multiple Gateways and `mergeGateway `is enabled , using CORS on one Gateway will affect the others 

### ISSUE THREAD

**Issue by NamiKazu** [envoyproxy/gateway#2666]
*Description*:
When there are multiple Gateways and `mergeGateway` is enabled , using CORS on one Gateway will affect the others 

*Repro steps*:
Install the Gateway API CRDs and Envoy Gateway 
```shell
helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace
```

Use aill-in-one yaml described below:

```shell
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true 
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealos-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: sealos-system
spec:
  gatewayClassName: eg
  listeners:
    - hostname: "*.192.168.0.15.nip.io"
      name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-oehe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdkzlmibsivuiqav
  namespace: ns-oehe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdkzlmibsivuiqav
  template:
    metadata:
      labels:
        app: bdkzlmibsivuiqav
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bdkzlmibsivuiqav
  namespace: ns-oehe
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bdkzlmibsivuiqav
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bdkzlmibsivuiqav
  namespace: ns-oehe
spec:
  hostnames:
  - ntjxuedx.192.168.0.15.nip.io
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
    namespace: sealos-system
    sectionName: http
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: bdkzlmibsivuiqav
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-vrpg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfqjpuycbgjrtdww
  namespace: ns-vrpg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfqjpuycbgjrtdww
  template:
    metadata:
      labels:
        app: mfqjpuycbgjrtdww
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mfqjpuycbgjrtdww
  namespace: ns-vrpg
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mfqjpuycbgjrtdww
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mfqjpuycbgjrtdww
  namespace: ns-vrpg
spec:
  gatewayClassName: eg
  listeners:
  - hostname: qccbahgo.qccbahgo
    name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mfqjpuycbgjrtdww
  namespace: ns-vrpg
spec:
  hostnames:
  - qccbahgo.qccbahgo
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: mfqjpuycbgjrtdww
    namespace: ns-vrpg
    sectionName: http
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: mfqjpuycbgjrtdww
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: cors-example
  namespace: sealos-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  cors:
    allowOrigins:
    - "http://*.foo.com"
    allowMethods:
    - PUT
    - GET
    - POST
    - DELETE
    - PATCH
    - OPTIONS
    maxAge: 600s
    allowCredentials: true
```

Get the name of the Envoy service created the by the  Gateway, because mergeGateway is enabled, the way to obtain the Envoy service differs from the quickstart.

```shell
export ENVOY_SERVICE=$(kubectl get svc -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gatewayclass=eg -o jsonpath='{.items[0].metadata.name}')
```
Port forward to the Envoy service
```shell
kubectl -n envoy-gateway-system port-forward service/${ENVOY_SERVICE} 8888:80 &
```
Verify that the CORS headers are present in the response of the OPTIONS request from `http://www.foo.com`, and the host is `ntjxuedx.192.168.0.15.nip.io`

```shell
curl -H "Origin: http://www.foo.com" \
  -H "Host: ntjxuedx.192.168.0.15.nip.io" \
  -H "Access-Control-Request-Method: GET" \
  -X OPTIONS -v -s \
  http://localhost:8888/
```
The following is the response, which is reasonable because this host is bound to the Gateway in the targetRef.

```shell
< HTTP/1.1 200 OK
< access-control-allow-origin: http://www.foo.com
< access-control-allow-credentials: true
< access-control-allow-methods: PUT, GET, POST, DELETE, PATCH, OPTIONS
< access-control-max-age: 600
```

Verify that the CORS headers are present in the response of the OPTIONS request from `http://www.foo.com`, and the host is `qccbahgo.qccbahgo`

```shell
curl -H "Origin: http://www.foo.com" \
  -H "Host: qccbahgo.qccbahgo" \
  -H "Access-Control-Request-Method: GET" \
  -X OPTIONS -v -s \
  http://localhost:8888/
```
The following is the response, the same as above which is unreasonable because this host is unrelated to the Gateway in the targetRef.

```shell
< HTTP/1.1 200 OK
< access-control-allow-origin: http://www.foo.com
< access-control-allow-credentials: true
< access-control-allow-methods: PUT, GET, POST, DELETE, PATCH, OPTIONS
< access-control-max-age: 600
```

I think it is unreasonable. Our use case is similar to the following structure: users can only operate on CRs in their own namespaces. However, when using CORS, it affects other Gateways in the cluster, which poses significant risks.

![img_v3_0275_843b3e72-c935-451c-8576-b575e7c8069g](https://github.com/envoyproxy/gateway/assets/60498292/24ca382b-7c34-4f0d-a29f-574545104596)

**Comment by liorokman** [comment]
@NamiKazu  Is it still possible to set different CORS definitions for different routes by attaching the `SecurityPolicy` to specific  `HTTPRoutes` instead of to one of the gateways?

**Comment by arkodg** [comment]
thanks for raising this @NamiKazu, looks like a bug
https://github.com/envoyproxy/gateway/blob/4c79ef9aa1e06d3b61b83e95f21d1705fa6568ba/internal/gatewayapi/securitypolicy.go#L373 is retrieving the top level IR with is collection of all listeners for all Gateways under the GatwayClass (for the `mergeGateways` case). For the merged gateway case, those listeners will need to be filtered to make sure they are part of the the target Gateway

this bug is probably present for all policies (CTP, BTP, SP)

as a workaround until its fixed, please refer to @liorokman's suggestion of targeting a `HTTPRoute`, but that may involve creating the `SecurityPolicy` in the app ns which you may not want

**Comment by NamiKazu** [comment]
Thanks for @liorokman's  suggestion, when attaching the `SecurityPolicy` to specific `HTTPRoutes`, the problem won't occur again.


And Thanks for @arkodg's guide, after analysis I find that when `mergeGateways` is enabled, translating the API into xdsIR will merge all `Gateway` into one xdsIR. Consequently, all `HTTPRoutes` associated with each `Gateway` will be merged together as the xdsIR's `HTTP` field. After getting the corresponding IR, policies are applied to all `HTTPRoute`s associated with the IR without distinction. I think this is the reason for the problem.

In a multi-tenant scenario, 
- `mergeGateways` is necessary, because there might be thousands of users, each with some listeners with different hosts. Users should not attach all listeners to one single `Gateway`, as this can easily exceed limits. So, they should have different `Gateway`s and enable `mergeGateways`. 
- Moreover, isolation between `Gateway`s is necessary, different users have different `Gateway`s, and their policies should not affect each other.

Therefore, I think that when `mergeGateway` is enabled and all gateways are merged into one xdsIR, routes need to be distinguished based on their associated gateway. When applying policies, only the relevant HTTPRoutes should have policies applied to achieve isolation between gateways.

In a word, although gateways has been merged, isolation between gateways is still important.
