### ISSUE TITLE
BTP Status getting modified by unrelated GatewayClass

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2724]
facing the same issue with BTP as in e2e test https://github.com/envoyproxy/gateway/actions/runs/8073622448/job/22057769156?pr=2665#step:6:2130

#2665 introduce merge gateways e2e test, that requires multiple-gatewayclass per controller feature. but this test will affects all the other test cases that have policies attached. because the new gatewayclass in controller will also update the policy status, even the policy is not belong to new GC's.

 so by fixing #2631, I think this issue can be resolved. assigning myself to these two issues.

_Originally posted by @shawnh2 in https://github.com/envoyproxy/gateway/issues/2520#issuecomment-1968509285_

**Comment by arkodg** [comment]
@shawnh2 I'm not sure how the upstream `PolicyStatus` field will help us here ?
to solve this for v1.0, I'm thinking lets just skip populating `gwv1a2.PolicyReasonTargetNotFound` as a workaround
https://github.com/envoyproxy/gateway/blob/8efa0d43a2755d19472686f0a8e7783d0a792fe9/internal/gatewayapi/backendtrafficpolicy.go#L151

Its not ideal, but its at least takes care of all these false positives

So as a user, if I dont see any `Accepted` condition on my policy, I should be worried that it never got applied on anything

**Comment by arkodg** [comment]
based on comments from https://github.com/kubernetes-sigs/gateway-api/issues/2755#issuecomment-1970397263 looks like skipping is the best option for all our policies

**Comment by shawnh2** [comment]
+1, for now lets just skiping the `PolicyReasonTargetNotFound` as a workround.

And as for `PolicyStatus`, I think this can solve the issue. For all the fresh new policies, we can populate its `ControllerName` and ancestors by what it is targeting to. If one BTP is targeting to a HTTPRoute, its ancestors will be HTTPRoute, Gateway and GatewayClass. Likewise, if one BTP is targeting to a Gateway, its ancestors will be Gateway and GatewayClass. 

By the next reconcile, the controller will first determine whether the policies should be handled by this controller via its `PolicyStatus.ControllerName`. And then determining whether the policies should be handled by this GatewayClass via its `PolicyStatus.Ancestors[i]`, if it should, then determining by Gateway or HTTPRoute in order.

**Comment by arkodg** [comment]
yah sounds good @shawnh2 for v1.0.0 prefer if we take the simple route forward on skipping `PolicyReasonTargetNotFound`
for all our policy types
