### ISSUE TITLE
Inconsistent Gateway Listener Processing

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#277]
`gateway.spec.listeners[].port` is processed by the infra and xds IRs. The infra IR uses this port as the port number of the Kube Envoy service. The xds IR uses this port to create the Envoy listener. For the Kube provider, the Envoy listeners should be created from the container ports, e.g. 8080 and 8443, of the Envoy deployment instead of `gateway.spec.listeners[].port`.

**Comment by danehans** [comment]
cc: @arkodg

**Comment by youngnick** [comment]
Good catch, this is a big gotcha with `listener.port`, that it should be the port that the listener is available on from the _outside_.

**Comment by arkodg** [comment]
this is being tracked via https://github.com/envoyproxy/gateway/issues/192

**Comment by danehans** [comment]
@arkodg i feel there is a subtle difference between this issue and the one you linked. This issue is a bug in the current state of how the translators process gateway ports. The linked bug is how to handle arbitrary ports. This issue must be resolved for RC1 while the linked issue can be resolved post v0.2.0.
