### ISSUE TITLE
Failed when trying to create Security Policy with basic auth

### ISSUE THREAD

**Issue by wlopes39** [envoyproxy/gateway#2787]
*Description*:

I can't create a SecurityPolicy for testing with basic auth.

*Repro steps*:

I'm following the https://gateway.envoyproxy.io/latest/user/basic-auth/ script and I can't apply the Create a SecurityPolicy step.

I tested with versions v1.0.0-rc.1, latest and v0.6.0.

*Environment*:

Kubernetes version: 1.27.8 - GKE
Chart: gateway-helm-v0.6.0
APP Version: v0.6.0

*Logs*:

Error from server (BadRequest): error when creating "STDIN": SecurityPolicy in version "v1alpha1" cannot be handled as a SecurityPolicy: strict decoding error: unknown field "spec.basicAuth"

**Comment by zirain** [comment]
cc @zhaohuabing

**Comment by wlopes39** [comment]
kubectl explain SecurityPolicy --recursive
[explain.txt](https://github.com/envoyproxy/gateway/files/14498893/explain.txt)

**Comment by arkodg** [comment]
@wlopes39 this feature was implemented later, please use `helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace
`
to test this

**Comment by arkodg** [comment]
I tested this out and it works, the issue you are most likely hitting is that you may have installed `v0.6.0` using `helm`, and then installed `v0.0.0-latest` using `helm` again.  helm unfortunately doesnt update CRDs so we were left with older CRDs

**Comment by wlopes39** [comment]
Hello,

That's exactly what I did. I will redo the tests tomorrow.

Thank you very much for your attention.

**Comment by wlopes39** [comment]
It worked to install the v0.0.0-latest version directly. Thanks
