### ISSUE TITLE
Configurable Envoy Access Logging

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#280]
Currently, Envoy access logs are sent to `/dev/null`. Users should have the ability to configure Envoy access logging through the EnvoyProxy API type.

**Comment by danehans** [comment]
In the meantime, do the following to enable access logging:
```
--- a/internal/infrastructure/kubernetes/bootstrap.yaml.tpl
+++ b/internal/infrastructure/kubernetes/bootstrap.yaml.tpl
@@ -1,5 +1,8 @@
 admin:
-  access_log_path: /dev/null
+  access_log:
+  - name: envoy.access_loggers.stdout
+    typed_config:
+      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
   address:
     socket_address:
       address: {{ .AdminServerAddress }}
```

**Comment by arkodg** [comment]
@danehans imho EG should propose a sane default such as ^ and any mod should be addressed via https://github.com/envoyproxy/gateway/issues/31 / https://github.com/envoyproxy/gateway/issues/24

**Comment by zirain** [comment]
for a short term, make bootstrap configurable seems enough.

for a long term, we may need something like [Telemetry](https://istio.io/latest/docs/reference/config/telemetry/) api in istio?

**Comment by lizan** [comment]
@danehans that is only for the admin endpoint, the other logs is configured via xDS component.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/1407 and https://github.com/envoyproxy/gateway/pull/1464
