### ISSUE TITLE
Incorrect Envoy Deployment and Service Labels

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#282]
Currently, the Envoy Deployment and Service use the [same labels](https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/config/envoy-gateway/deploy_and_ns.yaml#L5) as Envoy Gateway. This causes requests intended for Envoy to get kube-proxied between Envoy-gateway and envoy pods.

**Comment by zirain** [comment]
I have same issue during debug https://github.com/envoyproxy/gateway/issues/267.

I add `component: controller` on envoy-gateway and `component: envoy` on envoy-eg, but I do not think it's a good practice.

IMHO, the naming of the two components are not that good,
