### ISSUE TITLE
Potential Security Risk when SecurityPolicy fails for a Route

### ISSUE THREAD

**Issue by sam-burrell** [envoyproxy/gateway#2837]
*Description*:

Our use case is to use the `SecurityPolicy` to define OIDC auth for public routes and we are attaching a `SecurityPolicy` to any type of Route (`HTTPRoute`,  `GRPCRoute`)

- If the SecurityPolicy fails for any reason the default behaviour is for the route to have no SecurityPolicy and be public - for us this feels like a security risk.
- Is there a way for use to ensure that if a `SecurityPolicy` fails the HTTPRoute fails?

**Comment by arkodg** [comment]
this makes sense, it should not be very hard to implement, we already add a direct response of `500` in case any of the filters attached to a route cannot be resolved
what should the UX here be
* knob on `SecurityPolicy` or
* global knob in the startup config

**Comment by levsha** [comment]
TIL the SecurityPolicy may also fail on completely external issues like a (temporary) misconfiguration of the OIDC issuer, with an error like `'Error fetching endpoints from issuer: Get "https://auth.internal.XXXXXX": stopped after 10 redirects'. I guess temporary connectivity problems to the issuer may also cause the gateway to fail open.
It means that this behavior is clearly security vulnerability: the gateway can fail open on issues that can be completely out of control of the cluster administrator. This makes the current implementation of `SecurityPolicy` just useless as no one would want to have an authentication system that fails open ...

**Comment by arkodg** [comment]
if a BackendTrafficPolicy or a SecurityPolicy has not been `Accepted` , my preference is to return a direct response of `5XX` (500/503) for all routes tied to the policies
wdyt @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
> if a BackendTrafficPolicy or a SecurityPolicy has not been `Accepted` , my preference is to return a direct response of `5XX` (500/503) for all routes tied to the policies wdyt @envoyproxy/gateway-maintainers

+1

The current behavior of translation is in a best-effort manner, which means that the failed xPolicy will not be accepted but the targeted xRoute will be translated to xDS and sent to the Envoy fleet anyway.   This default behavior is incorrect for BackendTrafficPolicy and a security risk for SecurityPolicy.
