### ISSUE TITLE
gatewayclass does not reach Accepted: True state in AWS

### ISSUE THREAD

**Issue by wimnat** [envoyproxy/gateway#2860]
*Description*:

After trying out Envoy Gateway, I have installed it on an EKS cluster in AWS (EKS).

However, when adding my first `GatewayClass` resource, the resource is not accepted and the control plane reports it as "not found" despite it being returned with a `k get gatewayclass`.

The log message seems incorrect and describing the resource provides no further clues on where to look.  I don't think this is a bug as identical GatewayClass resource works fine on a local kind cluster.  However, without any further information from the logs, it's unclear what has gone wrong.

Install was via helm in to a custom namespace `a-envoy-gateway`.  Envoy Gateway version = `0.6.0`.  Control plane version is 1.26.

GatewayClass:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aws-nlb-internal
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: gatewayclass-config-aws-nlb-internal
    namespace: a-envoy-gateway
```
EnvoyProxy:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gatewayclass-config-aws-nlb-internal
  namespace: a-envoy-gateway
spec:
  provider:
    kubernetes:
      envoyDeployment:
        container:
          image: 1111111111111.dkr.ecr.us-east-1.amazonaws.com/mymirror/index.docker.io/envoyproxy/envoy:distroless-v1.28-latest
      envoyService:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-type: external
    type: Kubernetes
```
Envoy Gateway logs (relevant logs after GatewayClass is added):
```
2024-03-10T11:26:37.508Z        INFO    provider        kubernetes/predicates.go:37     gatewayclass has matching controller name, processing   {"runner": "provider", "name": "aws-nlb-internal"}
2024-03-10T11:26:37.508Z        INFO    provider        kubernetes/controller.go:154    reconciling gateways    {"runner": "provider"}
2024-03-10T11:26:37.508Z        INFO    provider        kubernetes/controller.go:1639   processing envoyproxy   {"runner": "provider", "namespace": "a-envoy-gateway", "name": "gatewayclass-config-aws-nlb-internal"}
2024-03-10T11:26:37.508Z        INFO    provider        kubernetes/controller.go:365    No gateways found for accepted gatewayclass     {"runner": "provider"}
2024-03-10T11:26:37.508Z        INFO    provider        kubernetes/controller.go:387    reconciled gateways successfully        {"runner": "provider"}
2024-03-10T11:26:37.509Z        INFO    provider        status/status.go:122    received a status update        {"runner": "provider", "namespace": "", "name": "aws-nlb-internal"}
2024-03-10T11:26:37.512Z        ERROR   provider        status/status.go:100    unable to update status {"runner": "provider", "name": "aws-nlb-internal", "namespace": "", "error": "gatewayclasses.gateway.networking.k8s.io \"aws-nlb-internal\" not found"}
```
GatewayClass status:
```
Name:         aws-nlb-internal
Namespace:
API Version:  gateway.networking.k8s.io/v1
Kind:         GatewayClass
Spec:
  Controller Name:  gateway.envoyproxy.io/gatewayclass-controller
  Parameters Ref:
    Group:      gateway.envoyproxy.io
    Kind:       EnvoyProxy
    Name:       gatewayclass-config-aws-nlb-internal
    Namespace:  a-envoy-gateway
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Waiting
    Status:                Unknown
    Type:                  Accepted
Events:                    <none>
```
And finally, a simple get of the gatewayclass object to show it does exist:
```
❯ k get gatewayclass
NAME               CONTROLLER                                      ACCEPTED   AGE
aws-nlb-internal   gateway.envoyproxy.io/gatewayclass-controller   Unknown    3m39s
```

I've tried simplifying the GatewayClass config by removing the `parametersRef` field but the result is the same.

I'm at a loss here and similar config has worked locally but the log message about not finding the `aws-nlb-internal` seems very suspicious.

I'd appreciate any pointers in where I should look next.

**Comment by arkodg** [comment]
@wimnat maybe its a issue around RBAC, does the controller have access to write status into gatewayclass (cluster scoped resource) in this specific environment ?

**Comment by wimnat** [comment]
It doesn't seem to be.  I tried a few things:

1. Tested with `kubectl can-i`.

```
❯ k auth can-i update GatewayClass --as=system:serviceaccount:a-envoy-gateway:envoy-gateway
Warning: resource 'gatewayclasses' is not namespace scoped in group 'gateway.networking.k8s.io'

yes
```

And checked the deployment is using that service account as expected.

```
❯ k get deployment envoy-gateway -n a-envoy-gateway -o yaml | grep serviceAccount
      serviceAccount: envoy-gateway
      serviceAccountName: envoy-gateway
```

2. Checked the k8s audit log.  I can see a message that relates to what the controller says (i.e. not found rather than not authorised):

![Screenshot 2024-03-11 at 17 15 05](https://github.com/envoyproxy/gateway/assets/7425606/cf930df3-7d02-493e-88b8-e6ab6069682c)

@arkodg do you know what the update is supposed to look like?  I.e. I wonder if i could just recreate the HTTP PUT or PATCH via curl and try that via `k proxy` to see what happens.

**Comment by wimnat** [comment]
I discovered the problem and it is now resolved.

The CRDs installed on to the cluster were missing the `subresrouce.status` fields.

The reason they were missing these fields is because I was rendering the helm chart using jsonnet.  When using the `std.parseYaml` library on the chart, it fails because there are empty objects defined in the chart.  You can see these empty objects if you download https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml and check out all of the envoygateway CRDs.  The comment about the CRD is actually in a different yaml document (separated by `---`) to the CRD itself.  This makes the yaml doc null.  Example in the screenshot below.

![Screenshot 2024-03-12 at 12 26 54](https://github.com/envoyproxy/gateway/assets/7425606/284ccbb0-874a-4af3-8fba-f3af81883b61)

So to get around this error in jsonnet I used the `std.prune` function to drop those empty objects.  However, `std.prune` is recursive so it went through the whole CRD and dropped other empty objects like `subresrouce.status: {}`.

The fix was to switch to use `std.filter` instead so there is no recursion.  The CRDs are now rendered correctly.

In a perfect world, the rendering of the `install.yaml` could be fixed so the comment is in the correct place and not in its own empty yaml doc but for now things are working for me 👍

**Comment by arkodg** [comment]
glad you got it to work @wimnat, can you raise a follow up GH issue with some prescriptive suggestions on how to improve the generated helm chart ?
