### ISSUE TITLE
feat: add support to configuring downstream idle timeout

### ISSUE THREAD

**Issue by yaelSchechter** [envoyproxy/gateway#2861]
*Description*:
Add `idleTimeout` to clientTrafficPolicy.

Currently, the downstream-connection idle timeout is fixed at one hour, unless it is less than the request timeout.
I propose adding an idleTimeout parameter to the clientTrafficPolicy configuration. This parameter would allow users to specify the duration of the downstream-connection idle timeout according to their specific requirements.

Rationale:
1. **Prevention of Load Balancer Issues:** When running a proxy in an IaaS, the load balancer of that IaaS might have an idle timeout configured (e.g., GCP with an idle timeout of 600 seconds: [documentation]( https://cloud.google.com/load-balancing/docs/https/#timeouts_and_retries:~:text=Application%20Load%20Balancer%3A-,600%20seconds,-2)). 
If the idle timeout of the LB is reached, the LB closes the connection silently without notifying the proxy, causing following requests to fail. Having a configurable downstream idle timeout can prevent this issue by ensuring that Envoy's idle timeout aligns with or is shorter than the LB’s idle timeout.

2. **Saving Resources:** Configuring the downstream idle timeout helps save resources by reducing the amount needed to maintain connections.

3. **Drain Process Optimization:** In cases where Envoy needs to be drained, having a lower idle timeout enables faster termination of idle connections and speeding up the release of resources.

**Comment by guydc** [comment]
This items was discussed in the community meeting. This setting can be added in the following location: https://github.com/envoyproxy/gateway/blob/a11aa70ddf78c058b38400044be5c4a5e2944fc4/api/v1alpha1/timeout_types.go#L45

**Comment by yaelSchechter** [comment]
Please assign me :)
