### ISSUE TITLE
docs: add adopters in main page

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#2866]
https://github.com/envoyproxy/gateway/blob/main/ADOPTERS.md

**Comment by shawnh2** [comment]
Hi @wilsonwu, could use a help for this issue as well ?

**Comment by wilsonwu** [comment]
> Hi @wilsonwu, could use a help for this issue as well ?
> 
> xref: #2781 

 Sure, I'd like to contribute on this.
