### ISSUE TITLE
expose prom port in rate limit service

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2869]
*Description*:
>Describe the issue.

Support Prometheus monitoring using service monitor

Relates to https://github.com/envoyproxy/gateway/pull/2729

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ShyunnY** [comment]
i can do this. :)

**Comment by zirain** [comment]
> i can do this. :)

you can use `/assign`
