### ISSUE TITLE
Add Job to Check for Image Tag and Pull Policy

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#288]
https://github.com/envoyproxy/gateway/pull/263 adds a Make target that updates the EG image tag and pull policy to all testing in a Kind cluster. A CI job should be created to ensure that the image is always "envoyproxy/gateway-dev:latest" and the imagePullPolicy is "Always".

**Comment by arkodg** [comment]
@danehans is this issue relevant, or can this be closed ?

**Comment by danehans** [comment]
No, this is still needed The kube-install-image target changes these settings A Job should be created to ensure these are not set in PRs.

**Comment by octonawish-akcodes** [comment]
Is this issue still needed?
