### ISSUE TITLE
translator: make sure `alpnProtocols` in right order

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2889]
should we sort this?

_Originally posted by @zirain in https://github.com/envoyproxy/gateway/pull/2887#discussion_r1520896894_

**Comment by liorokman** [comment]
According to the [rfc](https://datatracker.ietf.org/doc/html/rfc7301#section-3.2):

> It is expected that a server will have a list of protocols that it supports, in preference order,

If this is sorted alphabetically, then it's not possible for the user to decide the preference order.

**Comment by zirain** [comment]
then should point out this in API doc, and make sure everything in excepted order.
