### ISSUE TITLE
Remove duplicated HTTP filters

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#2891]
The current per-route filter implementation creates a filter in the HCM filter chain for each ir.HTTPRoute. This can result in duplicated HTTP filters with the same configuration and cause a huge Envoy configuration file.  To optimize this, we should only create one filter for each unique ODIC/ExtAuth/BaiscAuth configuration and reuse it across all applicable ir.HTTPRoute.

Thanks @guydc for identifying this during the ExtAuth PR review.

**Comment by guydc** [comment]
should we close this?

**Comment by arkodg** [comment]
this may need to be done for all per route filters :)
