### ISSUE TITLE
Broken  link in documentation for compatibility matrix

### ISSUE THREAD

**Issue by chicco785** [envoyproxy/gateway#2892]
*Description*:

The link to compatibility matrix is broken:
https://github.com/envoyproxy/gateway/blob/01a123a010012caff21cba8aff7fdbe59fc023fe/site/content/en/v0.6.0/user/quickstart.md?plain=1#L12

*Repro steps*:
open https://gateway.envoyproxy.io/v0.6.0/user/quickstart/ and click on the link.

**Comment by zirain** [comment]
both are acceptable.

**Comment by shawnh2** [comment]
so closing this one now
