### ISSUE TITLE
Support Tracing for Rate Limit Service

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2899]
*Description*:
Tracing is supported in the RateLimit Service today https://github.com/envoyproxy/ratelimit?tab=readme-ov-file#tracing

This can be exposed via the EnvoyGateway API https://gateway.envoyproxy.io/latest/api/extension_types/#ratelimittelemetry

**Comment by ShyunnY** [comment]
A small question, my idea is: add support at the api level, and at the same time add the enable/disable trace function for ratelimit at the infra level, right?  :)

**Comment by arkodg** [comment]
yah @ShyunnY it would look very similar to https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/tracing_types.go but live in the EnvoyGateway config within RateLimit
