### ISSUE TITLE
Collapse envoy-gateway-metrics-service into envoy-gateway service with a metrics port

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2919]
*Description*:
>Describe the issue.

Can we reuse the `envoy-gateway` service and add a new port to it ? imo its easier for operations 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
@zirain @Xunzhuo wdyt

**Comment by zirain** [comment]
I think we can reuse envoy-gateway service

**Comment by zhaohuabing** [comment]
Vote for reusing envoy-gateway service and adding a new port for metrics service.

**Comment by Xunzhuo** [comment]
+1 for reusing

**Comment by ShyunnY** [comment]
Until we have no more reasons to use a separate Service, I also support reusing the `envoy-gateway` Service

**Comment by ShyunnY** [comment]
i can do this :)
