### ISSUE TITLE
Gateway API Translator Should Support * Listener Hostnames

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#293]
Currently, the translator requires a listener hostname to be specified. However, the Gateway spec states "*" should be used to match all hostnames when unspecified. Update the translator to support this requirement.

xref: https://github.com/envoyproxy/gateway/pull/286#discussion_r958708032

**Comment by danehans** [comment]
@zirain please assign yourself if you can fix this bug.

**Comment by danehans** [comment]
cc: @arkodg @skriss

**Comment by zirain** [comment]
@danehans I can assign myself without permission, but will take a look at this.
