### ISSUE TITLE
Perform Helm Upgrade in E2E Upgrade Test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2941]
*Description*:
>Describe the issue.

The Upgrade Test today performs a Helm Uninstall and Install, this should be peforming a Helm Upgrade instead
https://github.com/envoyproxy/gateway/blob/main/test/e2e/tests/eg_upgrade.go

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
cc @alexwo

**Comment by alexwo** [comment]
Assign me, indeed i will fix it.

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/pull/2934

**Comment by alexwo** [comment]
@arkodg ,
I think we are actually good as we perform an upgrade:
https://github.com/envoyproxy/gateway/blob/main/test/e2e/tests/eg_upgrade.go#L81

It's a little confusing the uninstall is for main version (deployed by prior e2e tests) than we install the target version

**Comment by arkodg** [comment]
thanks for checking @alexwo and @guydc , sorry for the noise 🙈
