### ISSUE TITLE
Create Release GitHub Action

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#297]
Create a GH action that:

1. Pushes the tagged EG image to Docker hub.
2. Updates quickstart manifests, etc from main branch to release tag.

**Comment by danehans** [comment]
@arkodg @AliceProxy can one of you please assign yourself and have a PR pushed by 8/31/22 noon PT?

**Comment by Xunzhuo** [comment]
I can do this, you can assign this to me.
