### ISSUE TITLE
docs: set up linkinator for doc site

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2979]
Recently we made a lot of changes to the documentation, which ended up with a lot of dead links on the page.

https://github.com/JustinBeckwith/linkinator will help, EG should enable this on CI. I had a protype [here](https://github.com/zirain/gateway/tree/linkinator), anyone interested can move forward, I will be back next week.

cc @Xunzhuo @wilsonwu

**Comment by wilsonwu** [comment]
It is a good action for site quality, and in the early stage it will more easy, I'd like to contribute on this if anything I can do, and like Istio doc site, a MD lint is also good chose for us.
