### ISSUE TITLE
refactor: Do we refactor sinks on observables?

### ISSUE THREAD

**Issue by ShyunnY** [envoyproxy/gateway#2983]
I found that in the API observable configuration, using a lot of different Sink or Provider. 
For example: `EnvoyGatewayOpenTelemetrySink`, and the configuration of Provider in the Ratelimit Trace I am doing (#2974).

Essentially, no matter when we configure the OTEL Sink of metrics or trace, it is the configuration of the exporter. Do we need to build the configuration in https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/protocol/exporter.md into a common object so that it can share the place where the OTEL Sink needs to be configured in the API?

Like the following:
```go
type OTELSink struct {
	Protocol string 

	Endpoint string 

	Insecure *bool 

	Timeout string

        CertificateFile string

        Headers map[string][string]
}
```

**Comment by arkodg** [comment]
blocked on https://github.com/envoyproxy/gateway/issues/3041
