### ISSUE TITLE
docs: refactor the website

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#2987]
I think we should reconstruct the document site as follows:
- [ ] Merge `announcements` and `blogs`
- [x] Move "Get Involved" to menu, and it should not be versioned.

cc @Xunzhuo @arkodg

**Comment by Xunzhuo** [comment]
We should move releases out of versioned docs.

**Comment by shawnh2** [comment]
> We should move releases out of versioned docs.

+1 for moving https://gateway.envoyproxy.io/latest/releases/ out

**Comment by shawnh2** [comment]
suggest merge current https://gateway.envoyproxy.io/announcements/ and https://gateway.envoyproxy.io/blog/ into `News` with sections:

- `Release Announcement` for original https://gateway.envoyproxy.io/announcements/
- `Presentations` for original https://gateway.envoyproxy.io/blog/presentations/
- `Blogs` for original https://gateway.envoyproxy.io/blog/news/
