### ISSUE TITLE
Move to Patch API on infra-client

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/gateway#2995]
*Description*:
Follow up from #2807, which is still happening in the latest version (v1.0.0).  I noticed this behavior because the EG is utilizing the Update API instead of the Patch API in infra-client.
https://github.com/envoyproxy/gateway/blob/c655811da9310fc474164af8d97f929dae248cff/internal/infrastructure/kubernetes/infra_client.go#L40-L45

As a result, instead of only updating the changed field, it turned out to re-applies all fields causing the field to revert to its original value, instead of updating what changed. For example on the Deployment object, if the replicas field is set to null, it will be reverted to null.

So, I tried in my local to use Patch API, and it worked as expected.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
Hey @ardikabs I understand the need for the patch API, but can you help explain your issue a little more,  why is the update repeating multiple times

**Comment by ardikabs** [comment]
> Hey @ardikabs I understand the need for the patch API, but can you help explain your issue a little more, why is the update repeating multiple times

It think i used wrong word, what i meant, when we enable HPA on EnvoyProxy, then leave the replicas to null. Now the expectation replicas field will be handled by HPA controller, however if we are doing any operation to Gateway API resource, the reconciliation on EG will trigger to reapply the old Deployment object (with replicas null).

**Comment by ardikabs** [comment]
Apart from the Update or Patch API, I also observed that the equality check on the Deployment object will always result in false, because the Deployment object in Kubernetes has generated value on some field compared to what's being created in the EG infrastructure layer.
https://github.com/envoyproxy/gateway/blob/c655811da9310fc474164af8d97f929dae248cff/internal/infrastructure/kubernetes/infra_resource.go#L88-L90

This is also the reason why EG keeps reconciling it on any operation to Gateway API/Envoy Gateway resource.  For instance, when a user supplies non-default EnvoyDeployment but leaves the `pod.securityContext` to empty (nil), during the comparison, the current Deployment object would contain the generated value of `pod.spsecurityContext` as a result it became unequal. Please see the screenshot below when I try to print out the diff using `cmp.Diff`.

<img width="1501" alt="image" src="https://github.com/envoyproxy/gateway/assets/12388578/e96917e1-75fd-4de2-925e-fd8497630766">

**Comment by ardikabs** [comment]
if this makes sense, I would like to work on this @arkodg
