### ISSUE TITLE
Support attachment of policies to multiple Gateways

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#2999]
*Description*:
Gateway operators may want to attach common policies to a group of gateways. Currently, duplicated instances of a policy need to be created and attached to each Gateway to achieve this. This can lead to significant configuration duplication, especially when many virtual gateways are merged to a single envoy deployment. 

`EnvoyPatchPolicy` introduced a concept of [GatewayClass-atttached](https://github.com/envoyproxy/gateway/blob/0be74abf7c0f863064a03001f27fdcfe4c7a2279/site/content/en/v1.0.0/user/extensibility/envoy-patch-policy.md?plain=1#L107) policies for the merge gateways scenario. 

This form of attachment can be extended to other policies like `ClientTrafficPolicy`, `BackendTrafficPolicy`, `SecurityPolicy`, `EnvoyExtensionPolicy` and `BackendTLSPolicy`.

**Comment by arkodg** [comment]
Im a -1 on this

2 ways to apply policies (Gateway, Route) is sufficient to solve most cases, 3 ways makes the concepts of `defaults`, `overrides` and `merges` very complicated to comprehend for the user and compute for the translator

* For `EnvoyPatchPolicy` we only allow attaching to the `GatewayClass` if `mergeGateways` is set

**Comment by guydc** [comment]
> im a +1 for pluralizing `targetRefs` so multiple `Gateway`s can be targeted , would ideally like to get guidance on this from upstream before implementing this, this is something we can time box

Yes, that can also work pretty well, as long as selectors are supported, and users don't have to maintain an explicit gateway list.

**Comment by arkodg** [comment]
cc @AliceProxy who was a big +1 for ^

**Comment by davidalger** [comment]
+1 on pluralizing `targetRefs`, this would also be useful for targeting multiple `HTTPRoutes` via the same `BackendTrafficPolicy` for example where groups of routes may require an elevated timeout.

**Comment by arkodg** [comment]
related discussion in upstream https://github.com/kubernetes-sigs/gateway-api/pull/2966#discussion_r1565161217

**Comment by sadovnikov** [comment]
Gateway API [v1.1.0-rc1](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0-rc1) was released yesterday. It includes "_the targetRef field is now a targetRefs list and these references no longer include a namespace field_", which is good. However, it seems to be done only for the `BackendTLSPolicy` and to be implemented as a list of `targetRef`. 

It would be great to see it applied to the Direct Policy Attachment in general and as a choice between `targetRef` and `selector`

**Comment by arkodg** [comment]
The decision that needs to be made here is two fold
1. What does targeting multiple resources look like - is it similar to the upstream recommendation of using `targetRefs` or should Envoy Gateway adopt another way to target multiple resources
2. should the current way to target a single resource using `targetRef` be deprecated and removed in a future release ?

**Comment by arkodg** [comment]
unassigning myself, I won't have cycles to work on this issue for v1.1, if anyone else wants to drive this, please go ahead

**Comment by liorokman** [comment]
> The decision that needs to be made here is two fold
> 
> 1. What does targeting multiple resources look like - is it similar to the upstream recommendation of using `targetRefs` or should Envoy Gateway adopt another way to target multiple resources
> 2. should the current way to target a single resource using `targetRef` be deprecated (not removed) or deprecated and removed in a future release ?

What was the decision that was reached?

**Comment by arkodg** [comment]
thanks for picking this one up @liorokman 
reg 1. - requires a little more brainstorming - should we start off with `targetRefs` or also support label based `targets` , this affects the top level API field we introduce
reg 2. there was consensus in keeping the existing `targetRef` field for now

**Comment by arkodg** [comment]
@liorokman with `targetRefs`, attaching to 10-20 should be fine, then it may become tedious. So if we do decide to support the case of attaching to 100 Gateways, will that field we part of `PolicyReferences` as a member field  e.g. `targetSelector`

**Comment by liorokman** [comment]
Yes, I think that a target selector can definitely be a part of the `PolicyReferences` structure.

**Comment by sadovnikov** [comment]
@liorokman, thank you very much for #3581 👍  
Watching #3607 now :)
