### ISSUE TITLE
shutdownmanager image should be customizable

### ISSUE THREAD

**Issue by vixns** [envoyproxy/gateway#3000]
Hi,

Shutdownmanager image is hardcoded at https://github.com/envoyproxy/gateway/blob/0be74abf7c0f863064a03001f27fdcfe4c7a2279/api/v1alpha1/shared_types.go#L29

When testing an image from a fork, or when publishing to a private repository, this hardcoded value is on the way.

**Comment by arkodg** [comment]
Blocked on https://github.com/envoyproxy/gateway/issues/2808

**Comment by zirain** [comment]
duplicate with #2808
