### ISSUE TITLE
Doc broken link: the squash link in contributing page broken

### ISSUE THREAD

**Issue by wilsonwu** [envoyproxy/gateway#3005]
*Description*:
https://gateway.envoyproxy.io/latest/contributions/contributing/#fixing-dco
<img width="873" alt="image" src="https://github.com/envoyproxy/gateway/assets/1269496/11d0ac7d-d132-4f9d-bbb0-1f43b6907d30">

In this contributing page, the squash link: `https://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html` broken:
<img width="1133" alt="image" src="https://github.com/envoyproxy/gateway/assets/1269496/7b2e2e2e-2ed8-4889-81d6-70b82255c16d">

Seems the site is down or domain problem.

Shell we replace this link to another one? like: https://www.git-tower.com/learn/git/faq/git-squash

Please provide some suggestions, I can fix it.

**Comment by zirain** [comment]
The target is unstable, should replace it with another address.
