### ISSUE TITLE
Does Gateway support Propagating x-forwarded-client-cert(XFCC) ?

### ISSUE THREAD

**Issue by nasirudheen** [envoyproxy/gateway#3006]
*Description*:

I am using Envoy gateway and have configured mTLS based authentication. Further to this, looking for ways to fetch some fields in the client TLS cert and use it for authorization purpose. i.e, want to fetch some fields(for example CN from the client cert) and route the traffic to various backends based up on the value in the field. Can someone gimme some clue on this ?  Does Envoy Gateway supports Propagating [x-forwarded-client-cert](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#id19)(XFCC) header to the backend similar to how Envoy Proxy does ? I could see that there is a  GH issue opened up in this regard here, https://github.com/envoyproxy/gateway/issues/2599 . 

Or is there a better approach to get my requirement ?

Thanks in advance

**Comment by arkodg** [comment]
+1
closing as dup of https://github.com/envoyproxy/gateway/issues/2599
