### ISSUE TITLE
CEL Validations for BTP targeting non HTTPRoutes

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3020]
> hey @zhaohuabing we can't enforce validation here, because if the policy is applied to the Gateway, they could apply to `HTTPRoute`s as well as `TCPRoute`s

Should we enforce validation when the target is a xRoute? It would be confusing if HTTP-related setting is configured for TCP/UDP route.

And it would be nice if we could allow users to know which settings in the BTP can be applied to which type of route. Probably add some comments to BTP settings?

_Originally posted by @zhaohuabing in https://github.com/envoyproxy/gateway/issues/3004#issuecomment-2019389221_

**Comment by EraKin575** [comment]
is this issue still relevant?

**Comment by arkodg** [comment]
now that a Policy can target multiple targets using targetRefs or targetSelectors its possible that some of those targets may be a non HTTPRoute, but this cannot be computed at apply time
closing this issue for now
