### ISSUE TITLE
TestE2E/ConnectionLimit  Close_connections_over_limit e2e test seems to constantly fail

### ISSUE THREAD

**Issue by alexwo** [envoyproxy/gateway#3023]
Seems that this test constantly fails now:
https://github.com/envoyproxy/gateway/actions/runs/8434551780/job/23098264792?pr=3022
https://github.com/envoyproxy/gateway/actions/runs/8432274812/job/23091217953

**Comment by zhaohuabing** [comment]
@guydc could you please take a look?

Sorry that I didn't notice that the e2e tests haven't finished yet when merging the PR https://github.com/envoyproxy/gateway/pull/2952. My bad :-(

**Comment by zirain** [comment]
@zhaohuabing can you send a PR disable the test first?

**Comment by zhaohuabing** [comment]
@zirain sure. https://github.com/envoyproxy/gateway/pull/3025

**Comment by guydc** [comment]
Sorry, I made a renaming mistake e2e/docs. Trying to fix now.
