### ISSUE TITLE
feat: supports customized metrics flush period

### ISSUE THREAD

**Issue by ShyunnY** [envoyproxy/gateway#3038]
envoy-gateway uses otel/metrics as the infrastructure. By default, the export time of metrics is 60s:
> **ref**: By default, the returned Reader will collect and export data every 60 seconds, and will cancel any attempts that exceed 30 seconds, collect and export combined.

Just imagine:
+ When envoy-gateway is in a more important department to coordinate gateway resources, we may need to shorten the time for exporting metrics appropriately, which can allow us to improve the real-time performance of obtaining metrics. 
+ There is also a possibility that envoy-gateway is in a relatively marginal department and does not have high real-time requirements for metrics, so its cycle can be set slightly longer.

I think this looks like a nice feature and I will implement it if the idea is accepted.

**Comment by ShyunnY** [comment]
cc @Xunzhuo

**Comment by Xunzhuo** [comment]
I am Okay with this, please go ahead @ShyunnY thanks!
