### ISSUE TITLE
Model OpenTelelemetry Sinks as a BackendRef

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3041]
*Description*:
>Describe the issue.

- [x]  Add BackendRef field to all proxy OpenTelemetry fields (in Proxy Tracing and Metrics And Access Logs) in v1.1
- [x]  Deprecate `Protocol`, `Host`, `Port` in v1.1
- [ ]  Remove above fields in v1.2

Background

Currently the sink has fields such as `Host`, `Port`

* In EnvoyProxy config - https://github.com/envoyproxy/gateway/blob/f699edf3663f2b7e5a5d37756403e1551a7d3976/api/v1alpha1/envoyproxy_metric_types.go#L50

We've started to use BackendRef in newer APIs such as ext auth https://github.com/envoyproxy/gateway/blob/f699edf3663f2b7e5a5d37756403e1551a7d3976/api/v1alpha1/ext_auth_types.go#L70

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
ptal @envoyproxy/gateway-maintainers

**Comment by zirain** [comment]
+1 on this, what about protocol?

**Comment by arkodg** [comment]
@zirain is it safe to assume otel collector will always be running in the same cluster ?

For protocol we can use a seperate field or leverage appProtocol field inside the Service

**Comment by guydc** [comment]
+1

**Comment by Xunzhuo** [comment]
+1

**Comment by zirain** [comment]
we can add appProtocol, also we can try https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

**Comment by arkodg** [comment]
thanks folks, updated the issue description with the TODOs needed to complete this

**Comment by arkodg** [comment]
sidenote - imo we should continue to use `host` `port` for any config in `EnvoyGateway` config, because of the bootstrapping problem - we dont want to rely on a provider (which may not be initialized yet or be part of another runner) to fetch the endpoints, having access to it directly helps

**Comment by zirain** [comment]
need keep `protocol`?

**Comment by arkodg** [comment]
> need keep `protocol`?

I vote for getting it from `appProtocol` . if we think that UX isn't working, we can add `protocol` in this API

**Comment by zirain** [comment]
if it's a `service`, we should respect `appProtocol` first, then try exact from `name`?
Is there no possibility that the reference is not a `servcie` or doesn't contains `appProtocol `?

**Comment by arkodg** [comment]
suggest only supporting `Service` type for now, lets punt the future problem (supporting a non Service backendRef) for the future :)

**Comment by zirain** [comment]
this's done
