### ISSUE TITLE
Reorder fault Envoy filter and make it the first filter

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3046]
*Description*:
>Describe the issue.

Make the fault filter the first filter since it doesnt rely on other filter funcationality, may reject a request early and we can save on processing in other filters
https://github.com/envoyproxy/gateway/blob/3d519339bc68ab1f8ece22c89aeb757e7fcc58cd/internal/xds/translator/httpfilters.go#L100

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ShyunnY** [comment]
/assign
I am more than happy to take on this issue.
