### ISSUE TITLE
Support headers with underscore

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3047]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Rejected by default in Envoy Gateway to align with best practices https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge

An opt in field to enable/allow this would be great
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#enum-config-core-v3-httpprotocoloptions-headerswithunderscoresaction

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
https://gateway.envoyproxy.io/v1.0.0/api/extension_types/#headersettings can be a good home for this field

**Comment by guydc** [comment]
+1 for general transparency reasons. Is there a concrete use case that you're aware of?

**Comment by arkodg** [comment]
* yeah this was requested by a user
* also trying to get parity with ingress NGINX 
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers

**Comment by ardikabs** [comment]
can i work on this, @arkodg ? for context, I have encountered a use case in a legacy system with ingress Nginx that relying to underscore headers, and to address it, I made modifications to the xDS using an Envoy gateway extension service.

**Comment by arkodg** [comment]
looks like David beat you to it :)
https://github.com/envoyproxy/gateway/pull/3052
