### ISSUE TITLE
Support modifying http2 listener settings

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3048]
*Description*:
>Describe the desired behavior, what scenario it enables and how it

As a user, I'd like to increase the current defaults of these below settings for my setup
Defaults are derived from https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#configuring-envoy-as-an-edge-proxy

- [x] [initial_stream_window_size](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-initial-stream-window-size)

- [x] [initial_connection_window_size](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-initial-connection-window-size)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by guydc** [comment]
+1

**Comment by arkodg** [comment]
@guydc does this fall into `connection` or a new `http2` field within https://gateway.envoyproxy.io/latest/api/extension_types/#clienttrafficpolicyspec ?

**Comment by guydc** [comment]
I think that a new `http2` field would be more appropriate.

**Comment by arkodg** [comment]
discussed this in the meeting today, `http2` seems like a popular option, will go with this in the init PR
