### ISSUE TITLE
Better helm support for airgapped clusters with no access to public image registry

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3049]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Envoy Gateway uses 3 images

* docker.io/envoyproxy/gateway
* docker.io/envoyproxy/envoy
* docker.io/envoyproxy/ratelimit

Would be great if theres a simpler way to change the registry as a helm value without doing a helm template and edit

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

- [x] Shutdown Manager(Envoy Gateway) https://github.com/envoyproxy/gateway/pull/3269  https://github.com/envoyproxy/gateway/pull/3389
- [x] RateLimit https://github.com/envoyproxy/gateway/pull/3389
- [x] Statsd Exporter https://github.com/envoyproxy/gateway/issues/3369

**Comment by zirain** [comment]
aren't they share same registry?

**Comment by arkodg** [comment]
Let's track adding top level images configuration support for statsd exporter using this GH issue

**Comment by shawnh2** [comment]
Should we close this? Leave undo to be tracked via https://github.com/envoyproxy/gateway/issues/3369

**Comment by arkodg** [comment]
this is the parent issue / `epic`, so we should ideally leave both open :)

**Comment by s0uky** [comment]
What about envoy proxy image? That should be configurable too.

**Comment by zirain** [comment]
you should be able do that with https://gateway.envoyproxy.io/docs/api/extension_types/#envoyproxykubernetesprovider right now.
