### ISSUE TITLE
Pluralize backendRefs for non xRoute BackendRef

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3091]
non xRoute backendRef may need to be pluralized in case we want to handle Active / Standby cases. These are

- [x] OpenTelemetry https://github.com/envoyproxy/gateway/pull/3293
- [x] ext auth https://github.com/envoyproxy/gateway/pull/3469
- [x] ext proc https://github.com/envoyproxy/gateway/pull/2991

_Originally posted by @arkodg in https://github.com/envoyproxy/gateway/issues/3055#issuecomment-2036255077_

**Comment by guydc** [comment]
+1

**Comment by arkodg** [comment]
some more thoughts
* if we care only about the active and pass use case, another `backupBackendRef` 
* If we also want traffic splitting, we'll have to pluralize backendRef

**Comment by arkodg** [comment]
+1 for this

**Comment by arkodg** [comment]
@zhaohuabing even for the K8s there could be a Service local in the cluster and another Service ( on standby ) in another cluster represented as a ServiceImport

**Comment by zhaohuabing** [comment]
Yah, falling back to a remote cluster is a very persuasive case for me. +1 for this!

**Comment by zirain** [comment]
for OpenTelemetry,
1. accesslog and metric support multi sinks
2. tracing only support one backend

**Comment by kflynn** [comment]
This seems like a good idea, let's do it. 👍

**Comment by shawnh2** [comment]
@zirain is this finished?

**Comment by arkodg** [comment]
@zirain afaik we havent yet implemented `backendRefs` for extAuth, so reopening this issue

**Comment by zirain** [comment]
> @zirain afaik we havent yet implemented `backendRefs` for extAuth, so reopening this issue

It's done in https://github.com/envoyproxy/gateway/pull/3469

**Comment by zirain** [comment]
I think we can close it now, and create another one to track multi backends for ext_auth.
