### ISSUE TITLE
Rename "user guides" to "tasks"

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3098]
*Description*:

In the [envoy gateway docs](https://gateway.envoyproxy.io/v1.0.0/), one of the main sections is "User Guides."

The title "User Guides" doesn't accurately describe its contents, which are one-off tasks.
Can we rename "User Guides" to "Tasks"?
That's what Kubernetes and Istio call theirs.

[optional *Relevant Links*:]
- https://istio.io/latest/docs/
- https://kubernetes.io/docs/home/

**Comment by zirain** [comment]
LGTM, cc @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
+1
