### ISSUE TITLE
docs: customize-envoyproxy not working

### ISSUE THREAD

**Issue by nvcnvn** [envoyproxy/gateway#3106]
*Description*:
I'm following the quick start guide and then want to do some customization with the service deployment via https://gateway.envoyproxy.io/v0.4.0/user/customize-envoyproxy/#add-gatewayclass-parametersref 

But got the following error:
```
error: resource mapping not found for name: "custom-proxy-config" namespace: "envoy-gateway-system" from "k8s/networking.yaml": no matches for kind "EnvoyProxy" in version "config.gateway.envoyproxy.io/v1alpha1"
```
And I'm pretty sure after install the helm chart there is no "config.gateway.envoyproxy.io" crd.

[optional *Relevant Links*:]
https://gateway.envoyproxy.io/v0.4.0/user/quickstart/
https://gateway.envoyproxy.io/v0.4.0/user/customize-envoyproxy/

**Comment by ShyunnY** [comment]
You can try to use the latest version or v1.0.0 stable version

**Comment by nvcnvn** [comment]
@ShyunnY thanks for your help, checking the release note I found:
OK, so the `config.gateway.envoyproxy.io` moved into `gateway.envoyproxy.io`

**Comment by zirain** [comment]
this seems not a real issue, feel free to reopen.
