### ISSUE TITLE
docs: yaml artifacts in guides should code-highlight

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3137]
*Description*:

most of the tasks combine [a] displaying yaml to be applied with [b] applying it to the cluster using the shorthand:

```shell
cat <<EOF | kubectl apply -f -
---
some: yaml
EOF
```

this is great and convenient copy-paste.
but if the resources were presented first as bona-fide yaml, you'd get better yaml highlighting/color-coding, which makes it easier for the reader to review the content.
it also gives the reader an opportunity to copy just the yaml if they want to save these CRs on their file system and study them before doing a kubectl apply.
(also if the reader is not using the bash shell, that command might not work)

suggestion:  revise all instructions in the user guides / tasks such that we display yaml instead, along with an instruction to kubectl apply the resource[s] to the cluster:

```yaml
---
some: yaml
```

**Comment by eitansuez** [comment]
fyi, i have an implementation i'll submit shortly via a PR.

**Comment by yuluo-yx** [comment]
> fyi, i have an implementation i'll submit shortly via a PR.

got it.

**Comment by arkodg** [comment]
hey @eitansuez, can we also support applying via `STDIN` ? maybe using a tab view ? so the user doesn't need to think about saving and applying ?

**Comment by eitansuez** [comment]
that's a good idea.  let me work on that..

**Comment by eitansuez** [comment]
waiting on tabs capability to get merged, and then the plan will be to display two tabs - one with a command to apply the resource directly to the cluster, the other provides just the resource that a user can copy and save to a file before applying.

**Comment by shawnh2** [comment]
hi @eitansuez, can this be closed?
