### ISSUE TITLE
egctl x collect

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3143]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

* Collect information from the cluster (e.g. resources in `envoy-gateway-system`,  gateway API resources, EnvoyProxy configdump) to help EG developers diagnose any issues offline
* Support redaction

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/issues/2028

**Comment by zirain** [comment]
use name of `config-dump`?

**Comment by arkodg** [comment]
imo we probably want the o/p to be a tarball rather than just STDOUT text

**Comment by arkodg** [comment]
adding some existing tools we could reuse
* https://github.com/replicatedhq/troubleshoot

**Comment by zirain** [comment]
I will take a look at this.

**Comment by zirain** [comment]
[troubleshoot](https://github.com/replicatedhq/troubleshoot) didn't match our requirements:
1. [Cluster Resources](https://troubleshoot.sh/docs/collect/cluster-resources/) collector cannot filter custome resources from Gateway API and EG. We can send PRs to improve it but not sure how long it will take, and will upstream accept?
1. [Executing Commands](https://troubleshoot.sh/docs/collect/exec/) cannot run curl to gather config dump and prometheus metrics cause we're using `distroless` image; When the selector refers to more than one replica of a pod, the exec collector will execute in only one of the pods.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/3775
