### ISSUE TITLE
tab character in helm template

### ISSUE THREAD

**Issue by networkhermit** [envoyproxy/gateway#3153]
*Description*:

I find that envoy-gateway-service.yaml contains a tab character, I believe it is added by accident.

https://github.com/envoyproxy/gateway/blob/c943042cb61f5248df6bf9f38d555d4222f65c0d/charts/gateway-helm/templates/envoy-gateway-service.yaml#L14

**Comment by yigang01** [comment]
can you assign this to me @arkodg

**Comment by shawnh2** [comment]
closed in favor of #3169
