### ISSUE TITLE
Enriching the Prometheus metric labels emitted by Envoy from HCM/TcpProxy StatPrefix

### ISSUE THREAD

**Issue by shuji-2019** [envoyproxy/gateway#3160]
*Description*:

> Currently HCM [^1] StatPrefix [^3] can be `http` or `https`, TcpProxy [^2] StatPrefix [^4] can be `tcp`, `passthrough` or `terminate`. That maybe not enough for production usage.

Because it's common to deploy many listeners for different domains, even serve multiple domains by single listener in which domains are distinguished via FilterChainMatch.SNI [^5]. If all listeners share the same StatPrefix, it's difficult to tell how many traffic does specified domain have received. Consider sample from Envoy's `/stats/prometheus`.

```
# TYPE envoy_listener_http_downstream_rq_completed counter
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8080"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8081"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8082"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8083"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8084"} 1
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8085"} 6
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8086"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8087"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_7021"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8088"} 0
```

*Relevant Links*:

[^1]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager
[^2]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#extensions-filters-network-tcp-proxy-v3-tcpproxy
[^3]: https://github.com/envoyproxy/gateway/blob/32eca0b1a50e44af7acb41cbed77e7f22f6ad378/internal/xds/translator/listener.go#L207
[^4]: https://github.com/envoyproxy/gateway/blob/32eca0b1a50e44af7acb41cbed77e7f22f6ad378/internal/xds/translator/listener.go#L379
[^5]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchainmatch

**Comment by arkodg** [comment]
@shuji-2019 would https://github.com/envoyproxy/gateway/issues/3318 solve this use case ?

**Comment by aoledk** [comment]
> @shuji-2019 would #3318 solve this use case ?

#3318 can't solve this use case.

To solve this use case, meaningful `stat_prefix` should be set for HCM [^1] or TCPProxy [^2]. Like which hostname or port does the HCM or TCPProxy is serving for.

BTW, _shuji-2019_ is me and that account is abandoned.

[^1]: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats#statistics
[^2]: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter#statistics

**Comment by arkodg** [comment]
there may be multiple hostnames per `hcm`

**Comment by aoledk** [comment]
- For HTTP listeners on same port, will be translated to `default_filter_chain`, each hostname to single `VirtualHost` in same `HCM`. It's not suitable to set all hostnames as `stat_prefix`, maybe just contain `http` and `port`.

- For HTTPS listeners on same port, will be translated to `filter_chains`, each listener to single `HCM` with SNI match own hostname (only one hostname). `stat_prefix` can be set as hostname.

- For TCP listeners (only single TCP listener is allowed on single port), will be translated to `filter_chains`, each listener to single `TCPProxy` with no match. `stat_prefix` maybe contain `tcp` and `port`.

- For TLS listeners on same port, will be translated to `filter_chains`, each listener to single `TCPProxy` with SNI match own hostname (only one hostname). `stat_prefix` can be set as hostname.

**Comment by shawnh2** [comment]
can this be closed ?

**Comment by aoledk** [comment]
> can this be closed ?

It's fine to close this.
