### ISSUE TITLE
Support ClientTrafficPolicy for TCP Listener

### ISSUE THREAD

**Issue by shuji-2019** [envoyproxy/gateway#3163]
*Description*:
> TCP Listener can't be configured with `EnableProxyProtocol` / `IdleTimeout` / `ConnectionLimit` / `PerConnectionBufferLimit`, but those fields are already available in ClientTrafficPolicy.

If ClientTrafficPolicy can be attached to TCP Listener, less EnvoyPatchPolicy will be used to extend EG.

**Comment by aoledk** [comment]
@arkodg In community's plan, does this feature should be implemented after https://github.com/envoyproxy/gateway/issues/1635 refactor is done.

**Comment by arkodg** [comment]
yeah we should probably wait on #1635, if you'd like it up, go for it ! there's an existing WIP PR that may needs some rebasing
