### ISSUE TITLE
Create security policy to repo

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/gateway#3172]
*Description*:
Add a security policy in order to improve OpenSSF score:
<img width="468" alt="image" src="https://github.com/envoyproxy/gateway/assets/16555289/f945319e-b0b6-4b39-803b-fd177a14cc06">

[optional *Relevant Links*:]
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by arkodg** [comment]
dup of #2924
