### ISSUE TITLE
docs: provide a suggested path through the docs after the quickstart

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3179]
*Description*:

At the end of the quickstart (before the cleanup section), should provide a suggested list (no more than five) of follow-on tasks (representative of envoy gateway), to guide someone exploring the product.

perhaps:

- traffic/http-routing/
- traffic/http-traffic-splitting/
- traffic/global-rate-limit/
- traffic/grpc-routing/
- security/secure-gateways/

[optional *Relevant Links*:]

For example, I like how the k8s gw api docs do it, see:
- https://gateway-api.sigs.k8s.io/guides/

**Comment by eitansuez** [comment]
maybe replace the grpc routing with an authentication-related task?

**Comment by arkodg** [comment]
+1 to this

**Comment by zirain** [comment]
+1
