### ISSUE TITLE
docs: make kubectl patch commands use yaml instead of json payloads, for legibility

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3180]
*Description*:

i wonder whether the `kubectl patch` commands used in different guides can be recast using yaml instead of json, to eliminate some of that noise.

example:

https://gateway.envoyproxy.io/v1.0.1/tasks/security/basic-auth/#enable-https

```shell
kubectl patch gateway eg --type=json --patch '[{
   "op": "add",
   "path": "/spec/listeners/-",
   "value": {
      "name": "https",
      "protocol": "HTTPS",
      "port": 443,
      "tls": {
        "mode": "Terminate",
        "certificateRefs": [{
          "kind": "Secret",
          "group": "",
          "name": "example-cert",
        }],
      },
    },
}]'
```

becomes..

```shell
cat <<EOF | kubectl patch gateway eg --type=json --patch-file=/dev/stdin
- op: add
  path: "/spec/listeners/-"
  value:
    name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: example-cert
EOF
```

i'm not sure the yaml example above is the canonical way of using kubectl patch with yaml.  i'll look more closely at that if this issue is accepted post-triage.

**Comment by arkodg** [comment]
big +1

**Comment by eitansuez** [comment]
i looks like the above example can be simplified slightly to:

```shell
kubectl patch gateway eg --type=json --patch '
  - op: add
    path: "/spec/listeners/-"
    value:
      name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - group: ""
          kind: Secret
          name: example-cert
  '
```

i'll use that format as the recipe to edit each instance.

**Comment by ShyunnY** [comment]
> i looks like the above example can be simplified slightly to:
> 
> ```shell
> kubectl patch gateway eg --type=json --patch '
>   - op: add
>     path: "/spec/listeners/-"
>     value:
>       name: https
>       protocol: HTTPS
>       port: 443
>       tls:
>         mode: Terminate
>         certificateRefs:
>         - group: ""
>           kind: Secret
>           name: example-cert
>   '
> ```
> 
> i'll use that format as the recipe to edit each instance.

Maybe it would be better if we redirect the results to a file before executing?  :)

**Comment by eitansuez** [comment]
so for this issue the plan is to just translate the json to yaml.  in a [separate issue](https://github.com/envoyproxy/gateway/issues/3137) the idea is to provide two tabs, where one will just display the resource (or patch file) to apply, decoupled from the command that actually applies it.
