### ISSUE TITLE
enhancement: use IfNotPresent for versioned helm chart release

### ISSUE THREAD

**Issue by networkhermit** [envoyproxy/gateway#3183]
*Description*:
> Most versioned helm chart in the wild default to `IfNotPresent` for `imagePullPolicy`, versioned helm chart uses tagged image so it rarely change, and change the default is good for air gapped environment.

[optional *Relevant Links*:]
https://github.com/envoyproxy/gateway/blob/231b3b476bb897b9679f7e303904e8a4e9cc3999/charts/gateway-helm/values.tmpl.yaml#L6

**Comment by ShyunnY** [comment]
This looks good, what do you think? @zirain

**Comment by arkodg** [comment]
2 options here
* change it to `IfNotPresent` only for pinned releases
* set the default to `IfNotPresent` and change it to `Always` for `v0.0.0-latest`

ptal @envoyproxy/gateway-maintainers

**Comment by ShyunnY** [comment]
> 2 options here
> 
> * change it to `IfNotPresent` only for pinned releases
> * set the default to `IfNotPresent` and change it to `Always` for `v0.0.0-latest`
> 
> ptal @envoyproxy/gateway-maintainers

vote 2

**Comment by guydc** [comment]
+1 for `set the default to IfNotPresent and change it to Always for v0.0.0-latest`.

**Comment by zhaohuabing** [comment]
+1 for `set the default to IfNotPresent and change it to Always for v0.0.0-latest`. 

This is not related, but I'm curious, why `v0.0.0-latest` instead of `latest`?
