### ISSUE TITLE
e2e test for doc site

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3204]
there're more and more guides introuduced into our docs site, consider add test for them(at latest for `tasks`)?
we can learn from what `istio.io` did?

**Comment by Xunzhuo** [comment]
I think this will increase complexity and makes our CI more flaky

**Comment by zhaohuabing** [comment]
We have tests for checking dead links but no tests for typos?

**Comment by zirain** [comment]
> We have tests for checking dead links but no tests for typos?

yes, no tests for typos or wrong configurations.
