### ISSUE TITLE
Merge Gateway Tracing Root Trace service name random

### ISSUE THREAD

**Issue by owenhaynes** [envoyproxy/gateway#3210]
*Description*:
Traces that are emitted when using merge gateway  have a random gateway name as  the service name. They do not use the correct gateway name that the route is attached to.

*Repro steps*:

Run merge gateway with multiple gateways with named listeners with routes attached. You should notice pretty quickly that the service name does not match up with the gateway that the route and host belongs to

 
*Environment*:
envoy gateway 1.0.1

**Comment by cnvergence** [comment]
thanks for reporting @owenhaynes
