### ISSUE TITLE
Don't switch container port

### ISSUE THREAD

**Issue by zvlb** [envoyproxy/gateway#3226]
I continue to work on the possibility of using Envoy Gateway on bare metal installations of Kubernetes. In my case, services with the LoadBalancer type are not available in the cluster, so I need to launch containers on the required ports (which are specified in the CR Gateway) without executing logic in the [servicePortToContainerPort](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/helpers.go#L231) function.

At the moment, I see two solutions:

1. Add a flag to Envoy that disables the need to execute `servicePortToContainerPort`. I'm not very fond of this option because if I need multiple Gateways, not all of which should have `CAP_NET_BIND_SERVICE`, there will be problems.
2. Add a field to EnvoyProxy that will control this behavior.

Do you have any other suggestions? I can implement the agreed functionality.

**Comment by arkodg** [comment]
relates to https://github.com/envoyproxy/gateway/pull/2405
@Xunzhuo is a knob to opt out of this translation the only option ?

**Comment by zvlb** [comment]
If someone can create name for this options in field `EnvoyProxyKubernetesProvider` I can start to implement it)

**Comment by arkodg** [comment]
@zvlb would be great if you can take #2405 forward (as a new PR)
some open questions are
* right home - should this field live inside [EnvoyGateway](https://github.com/envoyproxy/gateway/blob/9a626f262317b90946219d7f85069221cce2c4b6/api/v1alpha1/envoygateway_types.go#L194) config or [EnvoyProxy](https://github.com/envoyproxy/gateway/blob/9a626f262317b90946219d7f85069221cce2c4b6/api/v1alpha1/envoyproxy_types.go#L241)

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/3333
