### ISSUE TITLE
Managing the Changelog

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#324]
The [changelog](https://github.com/envoyproxy/gateway/tree/main/changelogs) was not updated as part of the RC1 release. A changelog was generated as part of the [release](https://github.com/envoyproxy/gateway/releases/tag/v0.2.0-rc1). Should we remove the existing changelog and just use the GH release changelogs?

cc: @youngnick @LukeShu @arkodg

**Comment by arkodg** [comment]
* for now, we could leave the generated CHANGELOG as is, and maybe cleanup the older https://github.com/envoyproxy/gateway/tree/main/changelogs
* the GHA https://github.com/softprops/action-gh-release#-external-release-notes allows us to use any external Changelog generator
For rc2 we should consider something more sophisticated that is based off contents/labels in the PRs

**Comment by danehans** [comment]
xref #325

**Comment by danehans** [comment]
Reopened to use this issue as a recurring reminder to create a changelog per release.

**Comment by danehans** [comment]
This issue can be reclosed after https://github.com/envoyproxy/gateway/pull/325 has been merged.

**Comment by arkodg** [comment]
I liked how https://github.com/envoyproxy/gateway/releases/tag/v0.2.0-rc1 acknowledged community contributions, we should consider something similar going forward

**Comment by arkodg** [comment]
yeah looks like we've preserved it, which is great :) , but now i'm confused as to how https://github.com/envoyproxy/gateway/blob/main/changelogs/0.2.0-rc2.yaml is being presented to the user

**Comment by danehans** [comment]
Update changelog -> release notes.

**Comment by danehans** [comment]
Closed by https://github.com/envoyproxy/gateway/pull/475
