### ISSUE TITLE
Enable `loopvar` feature of go for EG

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#3244]
This loopvar feature of go 1.22 requires enable env `GOEXPERIMENT=loopvar` (default closed) explicitly. Maybe we could consider enable this feature for other places as well.

_Originally posted by @shawnh2 in https://github.com/envoyproxy/gateway/issues/2739#issuecomment-2068969587_

**Comment by shawnh2** [comment]
The usage of this feature requires setting go env specificly, for example `GOEXPERIMENT=loopvar go test`.

**Comment by Awinr** [comment]
I'm very interested in this issue, please assign it to me.

**Comment by shawnh2** [comment]
the loopvar can be detected by https://golangci-lint.run/usage/linters#copyloopvar

**Comment by EraKin575** [comment]
@shawnh2 is this issue still relevant? I would like to work on this

**Comment by EraKin575** [comment]
@Awinr are you working on this?

**Comment by shawnh2** [comment]
> @shawnh2 is this issue still relevant? I would like to work on this

Yes, thinks for taking this issue, assign you.
