### ISSUE TITLE
Support override_stream_error_on_invalid_http_message

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#3245]
*Description*:
Envoy Docs:

> if you run level two Envoy version 1.11.1 or greater which terminates HTTP/2 or above, we strongly advise you to change the HttpConnectionManager configuration of your level two Envoy, by setting its downstream [validation of HTTP messaging option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-error-on-invalid-http-message) to true

Envoy Gateway should support configuration of this setting, so that users can adjust it, based on their deployment mode (L1 or L2) and protocol versions in use. 

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/level_two

**Comment by shawnh2** [comment]
closed in favor of #3682
