### ISSUE TITLE
HealthCheck config for HTTP Downstream

### ISSUE THREAD

**Issue by modatwork** [envoyproxy/gateway#3258]
*Description*:

A HealthCheck config is required to setup a health check downstream HTTP filter, aiding the load balancer before Envoy in assessing Envoy’s health. Presently, a HealthCheck exists in the BackendTrafficPolicy, but it serves the upstream.

[optional *Relevant Links*:]

https://www.envoyproxy.io/docs/envoy/v1.29.2/configuration/http/http_filters/health_check_filter

**Comment by arkodg** [comment]
@modatwork I believe one already exists on 0.0.0.0:9001
https://gateway.envoyproxy.io/v1.0.1/install/install-helm/#envoyproxy
https://github.com/envoyproxy/gateway/pull/1568
we probably need to surface this info in a better way in docs

**Comment by modatwork** [comment]
@arkodg Thanks for replying.

> Heath Check	0.0.0.0	19001

I believe you are referring to port 19001, which is used for the entire Envoy process. Implementing a health check for each listener/filter-chain could prevent errors. Consider a scenario where two Envoy instances are deployed, each serving a different application and listening on distinct ports. If an Envoy is mistakenly added to the wrong load balancer, it would still be considered healthy due to both instances being operational on port 19001.

**Comment by arkodg** [comment]
sure +1 for adding this in ClientTrafficPolicy

**Comment by arkodg** [comment]
reopening as implementation is left
