### ISSUE TITLE
docs: "testing the configuration" in tabs

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3259]
*Description*:

Several of the tasks have a section titled "Testing the configuration" which offers a way to test the configuration both with and without the support of an external load balancer.

The [quickstart (latest version)](https://gateway.envoyproxy.io/latest/tasks/quickstart/#testing-the-configuration) was recently enhanced so that the two cases are presented in separate tabs using a tabbed pane widget.

It seems to me more logical to make the "*with* external load balancer support" case the default one -- i.e. the first tab.  Currently the ordering is reversed.

The following tasks also have a similar section for testing the configuration in two ways, but do not employ tabs:

- tasks/traffic/http3.md
- tasks/security/tls-passthrough.md
- tasks/security/secure-gateways.md
- tasks/security/backend-tls.md
- tasks/security/mutual-tls.md
- tasks/security/tls-termination.md

Proposed changes to the docs:

1. Reverse the tab order - put the "with external load balancer" case first
2. Retrofit all other tasks to also use tabs

**Comment by arkodg** [comment]
+1
