### ISSUE TITLE
Update Gateway API to v1.1.0-rc1

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3265]
*Description*:
>Describe the issue.

Gateway API just released a new version, lets bring in the rc version

More in https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0-rc1

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
Gateway API 1.1 timelines
Rc1: a few hours
v1.1: 2 weeks

**Comment by arkodg** [comment]
related https://github.com/envoyproxy/gateway/issues/2624#issuecomment-2047564216
