### ISSUE TITLE
make envoy-eg pod able to debug

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#327]
correct me if I'm wrong

Right now, there's no debug tool (`curl` etc) in `envoyproxy/envoy`, admin port is listen on `127.0.0.1`, we need provider a way to access `config_dump` for debug?

cc @danehans @arkodg WDYT?

**Comment by arkodg** [comment]
hey @zirain what about port forwarding to the envoy pod ?

**Comment by zirain** [comment]
> hey @zirain what about port forwarding to the envoy pod ?

that need open more than one shell, once the pod changed, you need port forward again.

I want just run one line script like following:
```
kubectl exec -it <pod_name> -nenvoy-gateway-system -- curl 127.0.0.1:19000/config_dump
```

**Comment by arkodg** [comment]
I understand your pain :). I think we might have to continue with above workflow until
* we have a debug subcommand such as `envoy-gateway collect` to collect `config_dump` and much more for offline triaging (we could target this for v0.2.0)
* or we support BYO Envoy Bootstrap config (scheduled for post v0.2.0)

**Comment by zirain** [comment]
Actually I have some workarounds now, just open a ticket to track this.

IMO, it's necessary, but not that urgent.

here's my proposal:
- change the base-images like [this](https://github.com/istio/istio/blob/master/docker/Dockerfile.base)
- add a subcommand like `istioctl pc all`(what we do in istio project) if we have tools like `egctl`

**Comment by zirain** [comment]
replaced by https://github.com/envoyproxy/gateway/issues/794
