### ISSUE TITLE
Add a knob to make per_connection_buffer_limit_bytes of cluster configurable

### ISSUE THREAD

**Issue by aoledk** [envoyproxy/gateway#3278]
*Description*:
> EG can configure `per_connection_buffer_limit_bytes` on xDS Listener currently via #2600, not available to configure `per_connection_buffer_limit_bytes` on xDS Cluster, default to `32KB`. A new knob will be better for entire buffer sizing control of  Envoy provisioned by EG.

[optional *Relevant Links*:]
> https://gateway.envoyproxy.io/latest/api/extension_types/#connection
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster

**Comment by ShyunnY** [comment]
hey, @aoledk 
Do you have any ideas or are you currently working on this PR?

**Comment by aoledk** [comment]
> hey, @aoledk Do you have any ideas or are you currently working on this PR?

@ShyunnY Perhaps this feature should be implemented via BackendTrafficPolicy, similar way like https://gateway.envoyproxy.io/latest/api/extension_types/#connection works. And I'm not working on this Issue.

**Comment by aoledk** [comment]
@guydc When EG is used as L4 proxy and serves massive long lived TCP connection, the buffer size of <Downstream, Envoy> and <Envoy, Upstream> connections should be controlled, to reduce memory consumption of Envoy.
