### ISSUE TITLE
Support access log formatters in EnvoyProxy

### ISSUE THREAD

**Issue by aoledk** [envoyproxy/gateway#3279]
*Description*:
> EG supports access log [^1], no formatters.
>
> Envoy support formatters [^2] when setting access log, such as `envoy.formatter.req_without_query` [^3], it will remove the query string and is used to avoid logging any sensitive information into the access log. It's very important for production usage.

[optional *Relevant Links*:]
[^1]: https://gateway.envoyproxy.io/latest/api/extension_types/#proxyaccesslogformat
[^2]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/substitution_format_string.proto#envoy-v3-api-msg-config-core-v3-substitutionformatstring
[^3]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto#extension-envoy-formatter-req-without-query

**Comment by zirain** [comment]
EG should check the format and opt-in formatters.

**Comment by aoledk** [comment]
@zirain I want to help.
