### ISSUE TITLE
Gateway & HTTPRoute status computed by Gateway API translator needs to be written to API

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#329]
Currently, the Gateway API translator computes status (conditions & other status fields) for the Gateways and HTTPRoutes that it processes. However, that status is not currently being written back to the API server.  Adding support for this is essential for making progress with Gateway API conformance.

xref #219 
xref #65

**Comment by danehans** [comment]
@skriss @Xunzhuo https://github.com/envoyproxy/gateway/issues/345 partially fixes this issue. For example:
```
$ kubectl get gateways -o yaml
...
  status:
    addresses:
    - type: IPAddress
      value: 172.20.255.200
    conditions:
    - lastTransitionTime: "2022-09-12T16:11:14Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Scheduled
      status: "True"
      type: Scheduled
    - lastTransitionTime: "2022-09-12T16:12:06Z"
      message: Address assigned to the Gateway
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
...
```

I consider this issue closed once https://github.com/envoyproxy/gateway/issues/345 is resolved.

**Comment by Xunzhuo** [comment]
Thanks @danehans

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/395
