### ISSUE TITLE
Set Gateway.Status.Addresses

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#330]
EG needs to set the [Gateway.Status.Addresses field](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayStatus) with the address that is bound for the Gateway (i.e. the Envoy LB service address). This is necessary in order to make progress with Gateway API conformance.

A related question: do all Gateways use the same address? Does this have the potential to cause any kind of conflict across Gateways/Routes?

xref #65

**Comment by danehans** [comment]
> A related question: do all Gateways use the same address? Does this have the potential to cause any kind of conflict across Gateways/Routes?

For the time being, I suggest we start off simple and have all Gateways use the same Service. Therefore, all Gateways will have the same address. A conflict can occur if a user specifies a Gateway address but I suggest we state this limitation in the v0.2.0 release notes and enforce through validation. Thoughts @arkodg @LukeShu @youngnick?
