### ISSUE TITLE
flaky: TestEGUpgrade/EGUpgrade

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3311]
https://github.com/envoyproxy/gateway/actions/runs/8896241845/job/24429998115

**Comment by alexwo** [comment]
this one failed on eg_upgrade.go:78: Failed to upgrade the release: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/envoyproxy/gateway-helm/blobs/sha256:529769988b9569b5e7b005df7ad6d2b7ccfdded07d2f374a08b91eadaaa6e2d2: 503 Service Unavailable, looks like docker issue?

**Comment by zirain** [comment]
> this one failed on eg_upgrade.go:78: Failed to upgrade the release: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/envoyproxy/gateway-helm/blobs/sha256:529769988b9569b5e7b005df7ad6d2b7ccfdded07d2f374a08b91eadaaa6e2d2: 503 Service Unavailable, looks like a docker.io connectivity issue?

if so, should retry.

**Comment by shawnh2** [comment]
closed in favour of https://github.com/envoyproxy/gateway/pull/3764
