### ISSUE TITLE
Session Persistence 

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3315]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Add support for the upstream Session Persistence feature outlined in this GEP 
https://gateway-api.sigs.k8s.io/geps/gep-1619/

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
blocked on https://github.com/envoyproxy/gateway/issues/3265

**Comment by arkodg** [comment]
related https://github.com/envoyproxy/gateway/issues/2624#issuecomment-2047564216

**Comment by arkodg** [comment]
hey @sanposhiho thanks for picking this one up !

**Comment by zhaohuabing** [comment]
> > dont add support for BackendLBPolicy, it was specifically designed to support implementations without Route level support for session persistence, Envoy can support it, so imo lets reduce the number of ways to configure sessionPersistence
> > [#2624 (comment)](https://github.com/envoyproxy/gateway/issues/2624#issuecomment-2047564216)
> 
> @arkodg @sanposhiho Sorry for chimining in late, so the final decision is supporting session sticky in both EG BTP and Gateway BackendLBPolicy?

NVM, I figured it out: strong affinity(Stateful filter) vs weak affinity(Hash LB) :-)
