### ISSUE TITLE
Under https://gateway.envoyproxy.io/v1.0.1/tasks/observability/proxy-observability/#traces

### ISSUE THREAD

**Issue by kevintatou** [envoyproxy/gateway#3339]
There is an issue with this part:
`kubectl apply -f https://raw.githubusercontent.com/envoyproxy/gateway/latest/examples/kubernetes/tracing/default.yaml
`

Applying does not work because it does not recognise the apiVersion. The only thing that works is this apiVersion:
`config.gateway.envoyproxy.io/v1alpha1`
instead of
`gateway.envoyproxy.io/v1alpha1`

Any ideas?

**Comment by zirain** [comment]
<img width="1024" alt="image" src="https://github.com/envoyproxy/gateway/assets/4354057/f5e23059-1c47-4107-b6f9-a3957895b479">

**Comment by arkodg** [comment]
cc @shawnh2

**Comment by kevintatou** [comment]
I am running 0.5.0 as per 
https://gateway.envoyproxy.io/v0.5.0/user/quickstart/
I see that gateways newest version is 1.0.1. 
So i guess i need to update it 😄 
Maybe the docs will be updated soon?

**Comment by kevintatou** [comment]
I dont mind updating it 😄

**Comment by kevintatou** [comment]
`NAME	NAMESPACE           	REVISION	UPDATED                              	STATUS  	CHART              	  APP VERSION
eg  	envoy-gateway-system	2       	2024-05-08 09:47:19.040548 +0200 CEST	deployed	gateway-helm-v1.0.1	  v1.0.1`

I updated to 1.0.1 And tried changing the apiversion. But it does not work 🤔  Not sure what i am missing.

**Comment by kevintatou** [comment]
A reinstall instead of upgrade fixed it 😄 thanks!

**Comment by shawnh2** [comment]
glad that helps
