### ISSUE TITLE
envoy-gateway pod suddenly starts crashing on startup with: no matches for kind "GRPCRoute"

### ISSUE THREAD

**Issue by pkit** [envoyproxy/gateway#3340]
```
2024-05-07T23:54:59.040Z        INFO    provider        kubernetes/controller.go:104    created gatewayapi controller   {"runner": "provider"}
Error: failed to create provider Kubernetes: failted to create gatewayapi controller: no matches for kind "GRPCRoute" in version "gateway.networking.k8s.io/v1"
Usage:
  envoy-gateway server [flags]

Aliases:
  server, serve

Flags:
  -c, --config-path string   The path to the configuration file.
  -h, --help                 help for server

failed to create provider Kubernetes: failted to create gatewayapi controller: no matches for kind "GRPCRoute" in version "gateway.networking.k8s.io/v1"

```
Literally **nothing** changed, the gateway was working fine for a week and it's just totally crashing now.
Obviously some gateways were added and removed, but the CRDs or deployment of `envoy-gateway` was not touched.

image: `envoyproxy/gateway-dev:latest`

**Comment by zirain** [comment]
please upgrade you gateway api crds to 1.1.0-rc2

**Comment by pkit** [comment]
Hmm, it looks like it's a bad idea to use `:latest` tag. 
I deploy through `flux` but it won't update CRDs by its own (because nothing changed), while it may still fetch a newer image.
Downgraded to `1.0.1` meanwhile.

**Comment by zirain** [comment]
> Hmm, it looks like it's a bad idea to use `:latest` tag. I deploy through `flux` but it won't update CRDs by its own (because nothing changed), while it may still fetch a newer image. Downgraded to `1.0.1` meanwhile.

yeah, latest/dev won't be stable.
