### ISSUE TITLE
Enable GatewayHTTPListenerIsolation conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3352]
*Description*:
>Describe the issue.

Details of the test are in https://github.com/kubernetes-sigs/gateway-api/pull/3047

Remove from https://github.com/envoyproxy/gateway/blob/0457ee7417288159eaa4422ee243b808a1696604/test/conformance/experimental_conformance_test.go#L33C3-L33C47 once fixed 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by levikobi** [comment]
Hi @arkodg, I would like to try taking on this one if that's ok.
If there's anything important/helpful I should know about before diving in, please let me know

**Comment by shawnh2** [comment]
Thanks @levikobi for picking this one up!

**Comment by arkodg** [comment]
thanks for picking this one up @levikobi ! feel free to comment on the issue here with what you are seeing fail in the test, and can link you to the relevant code that may need to be revisited

**Comment by arkodg** [comment]
hey @levikobi stil working on this one ? its would be great if we could get this into v1.1

**Comment by levikobi** [comment]
Hi @arkodg, sorry for the delay. I have been pretty busy lately.
Yes, I would like to work on this one. I'll keep you updated throughout this week.
When is v1.1 supposed to come out?

**Comment by levikobi** [comment]
Hi @arkodg 
I run `GatewayHTTPListenerIsolation` conformance test, and the following cases fail:
* `0_request_to_'bar.com/empty-hostname'_should_go_to_infra-backend-v1`
* `5_request_to_'bar.example.com/wildcard-example-com'_should_go_to_infra-backend-v1`
* `10_request_to_'bar.foo.example.com/wildcard-foo-example-com'_should_go_to_infra-backend-v1`
* `15_request_to_'abc.foo.example.com/abc-foo-example-com'_should_go_to_infra-backend-v1`
As the requests receive a 404 response.

The other cases are passing since they expect a 404 response.

I looked at the proxy instance and saw this log:
```
[2024-07-28 05:01:00.536][1][warning][config] [source/extensions/config_subscription/grpc/delta_subscription_state.cc:269] delta config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain *.example.com in route gateway-conformance-infra/http-listener-isolation-with-hostname-intersection/empty-hostname
[2024-07-28 05:01:00.536][1][warning][config] [source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain *.example.com in route gateway-conformance-infra/http-listener-isolation-with-hostname-intersection/empty-hostname
```

To my understanding, and please correct me if I'm wrong - the fix should be at the translation logic at `internal/gatewayapi/translator.go`?

**Comment by arkodg** [comment]
thanks for digging into this @levikobi 
relevant logic lives in https://github.com/envoyproxy/gateway/blob/87909aa0de3b233ebedb5ec5b633feb8cee0daba/internal/gatewayapi/route.go#L654 and https://github.com/envoyproxy/gateway/blob/87909aa0de3b233ebedb5ec5b633feb8cee0daba/internal/xds/translator/translator.go#L394

you can even convert the filing sub tests into unit tests by adding input test files in https://github.com/envoyproxy/gateway/tree/main/internal/gatewayapi/testdata and running `make testdata` and looking at the o/p file to decipher if its what we expect or not

**Comment by levikobi** [comment]
Thanks for the help @arkodg!
I managed to make the conformance tests pass and created a PR. However, It's still a draft since I want to add some more tests around the new code.
Please feel free to take a look though
