### ISSUE TITLE
Add-on / Extended Helm Chart

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3355]
*Description*:
>Describe the issue.

Consider introducing a add-on / helm chart that may be common while Installing Envoy Gateway
e.g. Monitoring components highlighted in 
https://gateway.envoyproxy.io/v1.0.1/tasks/observability/proxy-observability/ & 
https://gateway.envoyproxy.io/v1.0.1/tasks/observability/grafana-integration/

Relates to https://github.com/envoyproxy/gateway/pull/2260

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
will this introduce a new image on registry?

**Comment by arkodg** [comment]
yeah

**Comment by zirain** [comment]
how to handle the image version, start from `v1.1.0`(same with others)?

**Comment by arkodg** [comment]
Yeah keeping them in sync and using the same CI tooling seems like low maintenance

**Comment by zirain** [comment]
> Yeah keeping them in sync and using the same CI tooling seems like low maintenance

sounds good

**Comment by arkodg** [comment]
hey @shawnh2 hoping you can help with this one, imo the first 2 adds on in here could be `prometheus` and `grafana` and the dashboard assets to make data plane and control obs easier

**Comment by shawnh2** [comment]
Will add the rest dependencies for the addons-helm as a follow-up PR, once this addons-helm is all set. Docs and Makefiles shall be updated.
