### ISSUE TITLE
Design Authentication Policy as a GatewayAPI Extension

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#336]
*Description*:

This issue tracks the design of the authentication policy APIs for Envoy Gateway leveraging the extension points within the [Gateway API](https://gateway-api.sigs.k8s.io)

Design docs for extensions are [here](https://docs.google.com/document/d/12jEb81Hf40UeMqXtnGObowB3PzyB21VrF2m4dXGYnls/edit?usp=sharing) & specifically authentication policy are [here](https://docs.google.com/document/d/1TlQjBy1utEwgrxE_HVT4-EHpVJ51hgnfMuAh0Q_uNoE/edit)

**Comment by lizan** [comment]
@danehans do we want to have the docs translated into markdown into https://github.com/envoyproxy/gateway/tree/main/docs/design ?

**Comment by danehans** [comment]
Yes, design docs should be in markdown under `./docs/design`. Refer to the other merged design docs as a reference model for this design doc.

**Comment by lizan** [comment]
Sure, will open an PR for discussion this week.

**Comment by arkodg** [comment]
Design PR for JWT is [here](https://github.com/envoyproxy/gateway/pull/529)
