### ISSUE TITLE
Envoy Gateway Extension  still a viable in stable version?

### ISSUE THREAD

**Issue by Uburro** [envoyproxy/gateway#3365]
*Description*:

Is the Envoy Gateway Extension still a viable option when working with Envoy Gateway? I don't see this option in the latest documentation, only the Envoy Patch Policy in Extensibility.

[optional *[Relevant Links](https://gateway.envoyproxy.io/v0.5.0/design/extending-envoy-gateway/)*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
hey its still a viable option, the docs are being added as part of https://github.com/envoyproxy/gateway/pull/2931
cc @AliceProxy
