### ISSUE TITLE
Authorization based on JWT claims

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3367]
*Description*:
Supports JWT claims as `Principal` in the `Authorization` configuration of a `SecurityPolicy`.

Part of https://github.com/envoyproxy/gateway/issues/2250

Blocked by https://github.com/envoyproxy/envoy/issues/34092
[optional *Relevant Links*:]

@zetaab

**Comment by zetaab** [comment]
still valid

**Comment by zetaab** [comment]
fyi @zhaohuabing & @arkodg that envoy blocking PR just got merged.
