### ISSUE TITLE
Consider moving away from promStatsdExporterContainer

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3369]
*Description*:
>Describe the issue.

https://github.com/envoyproxy/gateway/pull/2729 added support for enabling scraping prometheus metrics using a sidecar container based off `prom/statsd-exporter:v0.18.0` . 
Pulling this image is tricky for air gapped clusters and adds another configuration point for syncing an extra image into a private registry

Can this be avoided if ratelimit introduced a prom endpoint natively, tracked with https://github.com/envoyproxy/ratelimit/issues/285

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
hey @shawnh2 interested in investigating the feasibility of this one ? There's a PR linked to the above issue, unsure what's missing to get it through the finish line
cc @zirain

**Comment by zirain** [comment]
I cannot recall all the details last time I tried(it's long ago), most likely because https://github.com/lyft/gostats/pull/119 didn't merge to master.

**Comment by shawnh2** [comment]
assign myself now, I will take a deeper look.

**Comment by zirain** [comment]
assign this to me

**Comment by zirain** [comment]
xref: https://github.com/envoyproxy/ratelimit/pull/681

**Comment by arkodg** [comment]
looks like the ratelimit PR got merged !
