### ISSUE TITLE
Deploy envoy gateway without load balancer via node port

### ISSUE THREAD

**Issue by SerheoReutty** [envoyproxy/gateway#3385]
Hello! Please, help me. My kubernetes cluster don't have loadbalancer. How i can deploy envoy gateway using a node port to send trafic from a remote loadbalancer?

**Comment by arkodg** [comment]
should be possible by configuring the [EnvoyProxy resource](https://gateway.envoyproxy.io/v1.0.1/tasks/operations/customize-envoyproxy/#customize-envoyproxy-service-annotations)
https://gateway.envoyproxy.io/v1.0.1/api/extension_types/#kubernetesservicespec

**Comment by SerheoReutty** [comment]
it try it. change default type for services to NodePort in manifest, but, after create gateway class and gateway, services is created with the LoadBalancer type. 
Maybe i'm doing something wrong. But, i don't understand.

`                          type:
                            default: NodePort
                            description: |-
                              Type determines how the Service is exposed. Defaults to LoadBalancer.
                              Valid options are ClusterIP, LoadBalancer and NodePort.
                              "LoadBalancer" means a service will be exposed via an external load balancer (if the cloud provider supports it).
                              "ClusterIP" means a service will only be accessible inside the cluster, via the cluster IP.
                              "NodePort" means a service will be exposed on a static Port on all Nodes of the cluster.
                            enum:
                            - ClusterIP
                            - LoadBalancer
                            - NodePort
                            type: string`

`service/envoy-default-test-gateway-40c68872   LoadBalancer   10.97.92.176     <pending>     80:32519/TCP                    4s`

**Comment by SerheoReutty** [comment]
Hi! Can anyone please help me? I really don't understand what I'm doing wrong. And can envoy gateway create services with type nodePort

**Comment by arkodg** [comment]
hey @SerheoReutty suggest going through all the steps outlined in https://gateway.envoyproxy.io/v1.0.1/tasks/operations/customize-envoyproxy/ to better understand how you can modify data plane Envoy Proxy fleet resources in Envoy Gateway

**Comment by SerheoReutty** [comment]
Thank you! i tried create custom option and ref gateway-class for this options. It's work!
