### ISSUE TITLE
Initial Message Service Design and Implementation

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#34]
https://github.com/envoyproxy/gateway/pull/16 specifies the need for a Message Service (MS) component to allow internal services to communicate while being loosely coupled. The MS details should be captured in this issue or a linked doc.

**Comment by danehans** [comment]
@arkodg I assigned this issue to you based on the 5/24/22 community meeting [notes](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing). Please unassign yourself if that's not the case.

**Comment by arkodg** [comment]
[Here's](https://docs.google.com/document/d/132sZxpOUHZV3qPSb21GM_q3fYl1h-Gvw22H8NMcDcUo/edit?usp=sharing) the initial design doc
