### ISSUE TITLE
docs: Observability of Envoy Gateway Component (not Envoy)

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/gateway#3404]
*Observability of Envoy Gateway Component (not Envoy)*:

To have full EG system observability and ease troubleshooting of various failure modes, is there is EG native metrics (not Envoy proxy) that helps to have insights into EG subcomponents like:

* Total/failed to translate resources (Resource translator)
* Total/failed to translate xDS resources (xDS translator)
* Total/failed to translate Infra resources (Infra translator)

Introducing such metrics (if they are not yet supported) will ease EG operators to troubleshoot various failure scenarios and increase confidence for prod deployment.

Could not find mentions of EG native metric in user docs.

**Comment by shawnh2** [comment]
Hi @nezdolik

The metrics of EG are still work in progress, tracked by https://github.com/envoyproxy/gateway/issues/2092, for now, the latest version has support these metrics:
- https://github.com/envoyproxy/gateway/blob/main/internal/message/metrics.go
- https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/metrics.go

The usage of EG metrics can refer to: https://gateway.envoyproxy.io/latest/tasks/observability/gateway-observability/

> Total/failed to translate resources (Resource translator)
Total/failed to translate xDS resources (xDS translator)
Total/failed to translate Infra resources (Infra translator)

These metrics can refer to:

https://github.com/envoyproxy/gateway/blob/c5ec046be14c4bb9049a7d3633900d2b8207d40f/internal/message/metrics.go#L15-L17

with different runner label, for example, like:

<img width="505" alt="image" src="https://github.com/envoyproxy/gateway/assets/40317966/f54833c5-b3b9-4a63-b630-08759ebb33cd">

- the `gateway-api` runner is for Resource translator
- the `xds-translator` runner is for xDS translator
- the `infrastructure` runner is for Infra translator

**Comment by arkodg** [comment]
converting this into a docs issue, because these metrics exist, but are not documented

**Comment by arkodg** [comment]
@Xunzhuo @zirain @shawnh2 is there a tool / tags to easily convert metrics to docs (.md) which we can publish in the docs website ?

**Comment by shawnh2** [comment]
Done some research, couldn't find any tool like that.

Since the metrics is not changed very often, maybe we could write a doc in our own.

**Comment by shawnh2** [comment]
will file a doc after https://github.com/envoyproxy/gateway/pull/3393 landed
