### ISSUE TITLE
TLSBackendPolicy´s TargetRef Name must be unique across all namespaces

### ISSUE THREAD

**Issue by denniskniep** [envoyproxy/gateway#3409]
My TLSBackendPolicy has a Service as TargetRef. This service name must be unique across all namespaces. Otherwise it will not consistently select the certs for the appropriate routes.

Maybe the problem is that `policies` are not filtered by namespace with `backendNamespace `?
https://github.com/envoyproxy/gateway/blob/c5ec046be14c4bb9049a7d3633900d2b8207d40f/internal/gatewayapi/backendtlspolicy.go#L127-L134

Reproduce:
* Create 2 Services with same name but in different namespaces
* Create 2 TLSBackendPolicy with same name but in different namespaces
* Create 2 HTTPRoutes with same name but in different namespaces and different Hostnames

**Comment by arkodg** [comment]
thanks for raising this bug ! yes, since we moved to gateway-api v1.1, `policy.spec.targetRef.Namespace` doesnt exist, so here we need to rely on `target`'s Namespace as a filter for the BackendTLSPolicies
