### ISSUE TITLE
probably want to use `RouteDestination` here

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3410]
probably want to use `RouteDestination` here
https://github.com/envoyproxy/gateway/blob/c5ec046be14c4bb9049a7d3633900d2b8207d40f/internal/ir/xds.go#L911 to reuse clusters internally

_Originally posted by @arkodg in https://github.com/envoyproxy/gateway/pull/3293#discussion_r1604151688_

**Comment by arkodg** [comment]
closing as completed with https://github.com/envoyproxy/gateway/pull/3293
