### ISSUE TITLE
API Reference doc cannot describe types from gateway-api package

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#3414]
*Description*:

For example, 

https://gateway.envoyproxy.io/latest/api/extension_types/#backendtrafficpolicy is missing `Status` field because the type of this field is from gateway-api package

https://github.com/envoyproxy/gateway/blob/02ff9eb749ba7eda1a53dfcbd80fb2b6f46b23fe/api/v1alpha1/backendtrafficpolicy_types.go#L33

https://gateway.envoyproxy.io/latest/api/extension_types/#httptimeout is missing the type description about `Duration`

https://github.com/envoyproxy/gateway/blob/02ff9eb749ba7eda1a53dfcbd80fb2b6f46b23fe/api/v1alpha1/timeout_types.go#L36

---

Anyway, as for the type that from gateway-api package, we dont need to maintain the type description in our docs, but at least link them with https://gateway-api.sigs.k8s.io/reference/spec/ in right place.

**Comment by zirain** [comment]
need update https://github.com/envoyproxy/gateway/blob/ed4222b78124de25d0c7094080567c45047d33c3/tools/crd-ref-docs/config.yaml#L8
