### ISSUE TITLE
Option to use Secret as CaCertificateRefs in BackendTLSPolicy

### ISSUE THREAD

**Issue by denniskniep** [envoyproxy/gateway#3425]
It would be nice if one could also use a Kind `Secret` as `CaCertificateRefs` in `BackendTLSPolicy`. And not limited to Kind `ConfigMap`.
That would perfectly match with [CertManagers](https://github.com/cert-manager/cert-manager) way to generate certs.

FYI: I also created a ticket in CertManager to be also flexible on this side: https://github.com/cert-manager/cert-manager/issues/7003

**Comment by shawnh2** [comment]
dup of #2777, the implementation is tracking by #3211
