### ISSUE TITLE
Decision: How to Pass Logger

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#344]
A logger gets passed around a few different ways throughout EG. Let's make a decision on which approach should be used for the project. ~Making this decision will unblock #278~:

1. Pass a context and individual funcs can create a logger from the context.
2. Pass `logr.Logger` as an input to funcs.
3. Add a `logr.Logger` to go structs and `log.NewLogger()` when initializing the struct.

**Comment by danehans** [comment]
@arkodg @LukeShu @youngnick @skriss I request your vote on this issue so we can unblock #344.

**Comment by danehans** [comment]
I vote for option 1.

**Comment by LukeShu** [comment]
I vote for option 1.

**Comment by AliceProxy** [comment]
I think option 1 is preferable.

**Comment by skriss** [comment]
I'll abstain, fine with whatever others prefer.

**Comment by arkodg** [comment]
I prefer option 4 -  Add global library logging scopes
This simplifies enabling component level logging and is also used in istio (here's an [example](https://github.com/istio/istio/blob/247e396dd30635ba44e81f324f4224967b75e02a/pkg/webhooks/validation/controller/controller.go#L51))
More info on this is in https://github.com/envoyproxy/gateway/issues/76#issuecomment-1149604515

**Comment by danehans** [comment]
Reopened so we can discuss and bring it to closure in the future.
