### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by pionar** [envoyproxy/gateway#3447]
On ubuntu 22 LTS , kubernetes version v1.30.1 after run:

`kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml`

Installation has failed with message:

`The CustomResourceDefinition "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by shawnh2** [comment]
Hi, thanks for reporting this. 

According to our [Compatibility Matrix](https://gateway.envoyproxy.io/v1.0.1/install/matrix/), we have not support k8s with version v1.30.x yet.

Should we update our Compatibility Matrix, and support k8s v1.30.x ? 

/cc @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
Please use server side apply
Relates to https://github.com/envoyproxy/gateway/issues/3257

**Comment by arkodg** [comment]
> Hi, thanks for reporting this.
> 
> According to our [Compatibility Matrix](https://gateway.envoyproxy.io/v1.0.1/install/matrix/), we have not support k8s with version v1.30.x yet.
> 
> Should we update our Compatibility Matrix, and support k8s v1.30.x ?
> 
> /cc @envoyproxy/gateway-maintainers

Yah we should do this soon
