### ISSUE TITLE
ci: test K8s v1.30

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3449]
Hi, thanks for reporting this. 

According to our [Compatibility Matrix](https://gateway.envoyproxy.io/v1.0.1/install/matrix/), we have not support k8s with version v1.30.x yet.

Should we update our Compatibility Matrix, and support k8s v1.30.x ? 

/cc @envoyproxy/gateway-maintainers

_Originally posted by @shawnh2 in https://github.com/envoyproxy/gateway/issues/3447#issuecomment-2122186298_

**Comment by zirain** [comment]
remove 1.26 and add 1.30
