### ISSUE TITLE
Set unique name for FilterChain in xDS listener's FilterChains

### ISSUE THREAD

**Issue by aoledk** [envoyproxy/gateway#3461]
*Description*:

After #3371 is done, we can attach policies to gateway or specific listener.

When multiple listeners differentiated by SNI are translated into single xDS listener, `PostHTTPListenerModify` will be invoked after every individual listener has been translated to single FilterChain, then extension server will receive the whole xDS listener and policies attaching to the specific listener.

But extension server can't know which FilterChain should be modified based on policies.

One solution is to set name for each FilterChain, name is `irListenerName(listener)` as mentioned in https://github.com/envoyproxy/gateway/issues/3307#issuecomment-2126474603. There will an exception where multiple non-TLS HTTP listeners will be translated to DefaultFilterChain, should be handle carefully.

[optional *Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchain

**Comment by aoledk** [comment]
@liorokman I noticed that you have assigned yourself on #2673 to hook non-HTTP listener, do you have a plan to setup a mechanism to let extension server know which FilterChain of xDS listener should be targeted by selected policies in single gRPC call ?

**Comment by liorokman** [comment]
@aoledk Keeping with the current behavior, the extension server will be called on the `PostHTTPListenerModify` once per xDS listener, not once per FilterChain of the xDS listener.

**Comment by aoledk** [comment]
> @aoledk Keeping with the current behavior, the extension server will be called on the `PostHTTPListenerModify` once per xDS listener, not once per FilterChain of the xDS listener.

If FilterChain hook is unavailable, then name of VirtualHost or FilterChain should be set.

Let me use examples to explain:

### Case A. 2 HTTP listeners(foo.com and bar.com) with same port

translated to 2 VirtualHosts in DefaultFilterChain, one VirtualHost's domains is `[foo.com]`, another is `[bar.com]`.

### Case B.  2 HTTPS listeners (foo.com and bar.com) with same port

translated to 2 FilterChains, one FilterChain's match SNIs is`[foo.com]`, another is `[bar.com]`.

### Case C. 2 TLS-terminated listeners (foo.com and bar.com) with same port

translated to 2 FilterChains, one FilterChain's match SNIs is`[foo.com]`, another is `[bar.com]`.

### Case D. 1 TLS-passthrough listeners with 2 TLSRoutes (foo.com and bar.com)

translated to 2 FilterChains, one FilterChain's match SNIs is`[foo.com]`, another is `[bar.com]`.

In **Case A**, if I want to enable waf filter for `foo.com`, extension server should find VirtualHost whose domains contain `foo.com` and enable waf filter for that VirtualHost. Here we can name VirtualHost with `irListenerName`.

In **Case B C D**, if I want to enable waf filter for `foo.com`, extension server should find FilterChain whose match SNIs contain `foo.com` and enable waf filter for that FilterChain. Here we can name FilterChain with `irListenerName/ir.TCPRoute.Name`.

**Comment by liorokman** [comment]
@aoledk can you check if the proposed fix in #3524 does what you need?

**Comment by aoledk** [comment]
> @aoledk can you check if the proposed fix in #3524 does what you need?

Since extension server only know which gateway or listener the policies are targeting, for **Case C D**, if we name FilterChain with `irRoute.Name` (usually be `xxxroute/{route.namespace}/{route.name}`), extension server will have no clue to select right FilterChain.

`ir.TCPListener` contains `ir.TCPRoute` array, that will lead to `TCPProxy` FilterChain array, so we should name FilterChains with `fmt.Sprintf("%s/%s", irListener.Name, irRoute.Name)`. All FilterChains with name prefixed by `irListener.Name` should be applied with policies.

**Comment by modatwork** [comment]
It may not be necessary to rely on filter chain name.

Envoy could bind a connection to a filter chain using [filter_chain_match](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchainmatch). The extension server could use a similar method to bind a policy to a filter chain.

**Comment by modatwork** [comment]
After attempting to incorporate ﻿`filter_chain_match` into the extension API, I have found that it is not a good idea for two reasons:
1. It would be preferable to have a consistent method for referencing a target rather than introducing a new one, such as the ﻿`filter_chain_match` style.
2. To utilize the ﻿`filter_chain_match` style API, redundant information would need to be added to the policy API. For example, a user would have to add a ﻿`hostname: xxx.com` field to both the policy API and the listener API to ensure the policy matches the listener.

**Comment by aoledk** [comment]
@liorokman @guydc Perhaps we need to reopen this issue until extension server can locate FilterChain correctly, no matter for HTTP or TCP listener.
