### ISSUE TITLE
Incorrect expiry time in RefreshToken in OIDC?

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/gateway#3462]
*Description*:
<img width="1590" alt="Screenshot 2024-05-23 at 14 23 23" src="https://github.com/envoyproxy/gateway/assets/22482503/d10aa7f5-eb36-4593-8ca6-9a7ab0b16176">

My current setup is that token lifetime is 60 minutes and refresh token lifetime is 2 days (configured in identity provider). However, with the current expiry times envoy cookie model cannot just work. Lets say that I got new tokens 10:41:13Z, everything is stored to cookies. Normal token will expiry 11:41:13Z and after that it is supposed to use refresh token to fetch new normal token. However, that is impossible because refresh token cookie was expired 11:41:13Z as well and there are no cookie anymore. RefreshToken lifetime should be longer than normal tokens. Should it be configurable?

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by arkodg** [comment]
cc @zhaohuabing

**Comment by zhaohuabing** [comment]
@zetaab Can you confirm what's the `expire_in` field in the refresh token returned from the IDP?

If expire_in is not set, a default value will be abled to be applied to the refresh token TTL once #3423 and its implementation are merged.
