### ISSUE TITLE
add CEL validation for BackendRef Group

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3468]
e.g. 

https://github.com/envoyproxy/gateway/blob/8f2e175de6ca0842f59be06ae37bbb6f196c69cd/api/v1alpha1/accesslogging_types.go#L117-L123

**Comment by phantooom** [comment]
i search `BackendRefs []BackendRef` in eg codebase. i found all BackendRefs field had been added.
//+kubebuilder:validation:XValidation

What can I do for this PR? Could you give me some suggestions?

**Comment by zirain** [comment]
Right now, only `Service` is support, should limit `group` is `empty`(use default value `core`) or `core`.

**Comment by phantooom** [comment]
i try to add CEL validation for BackendRef Group. 
`
panic: Failed to start testenv: unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "envoyproxies.gateway.envoyproxy.io": CustomResourceDefinition.apiextensions.k8s.io "envoyproxies.gateway.envoyproxy.io" is invalid: [

spec.validation.openAPIV3Schema.properties[spec].properties[telemetry].properties[accessLog].properties[settings].items.properties[sinks].items.properties[als].properties[backendRefs].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of 1.048576x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared), 


spec.validation.openAPIV3Schema.properties[spec].properties[telemetry].properties[accessLog].properties[settings].items.properties[sinks].items.properties[openTelemetry].properties[backendRefs].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of 1.048576x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)]
`

should we restrict  the maxitem for  ProxyAccessLog.Sinks  ProxyAccessLog.Settings?

**Comment by phantooom** [comment]
> i try to add CEL validation for BackendRef Group.
> 
> ```
> panic: Failed to start testenv: unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "envoyproxies.gateway.envoyproxy.io": CustomResourceDefinition.apiextensions.k8s.io "envoyproxies.gateway.envoyproxy.io" is invalid: [
> 
> spec.validation.openAPIV3Schema.properties[spec].properties[telemetry].properties[accessLog].properties[settings].items.properties[sinks].items.properties[als].properties[backendRefs].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of 1.048576x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared), 
> 
> 
> spec.validation.openAPIV3Schema.properties[spec].properties[telemetry].properties[accessLog].properties[settings].items.properties[sinks].items.properties[openTelemetry].properties[backendRefs].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of 1.048576x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)]
> ```
> 
> should we restrict the maxitem for ProxyAccessLog.Sinks ProxyAccessLog.Settings?

If we decide to limit maxitem, should it be done in this PR or in another PR?
