### ISSUE TITLE
Docs showing how to fetch Control Plane metrics

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3474]
We should have a page similar to https://gateway.envoyproxy.io/v1.0.1/tasks/observability/proxy-observability/ on how to fetch the metrics

We should also create a few Grafana dashboards and package it into the Add on Helm Chart https://github.com/envoyproxy/gateway/issues/3355

**Comment by shawnh2** [comment]
I've already add the doc https://gateway.envoyproxy.io/latest/tasks/observability/gateway-observability/ on how to fetch the CP metrics.

I will add the Grafana support for CP metrics for now and update this doc: https://gateway.envoyproxy.io/latest/tasks/observability/grafana-integration/

then we will be able to package Grafana into Addon Helm Chart.
