### ISSUE TITLE
Secret / configmap updates do not trigger a reconcile

### ISSUE THREAD

**Issue by alexwo** [envoyproxy/gateway#3496]
*Description*:
Secret and configmap updates do not trigger a reconcile.
This can impact certificate changes and certain rotation procedures, config updates.

*Repro steps*:
Since secrets don’t have a spec or generation field, this predicate causes us to ignore any updates to secret keys. Completely replacing the secret will trigger reconciliation, but if someone only updates the secret keys, those changes will be skipped.

https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/controller.go#L1209

**Comment by alexwo** [comment]
related -> https://github.com/envoyproxy/gateway/issues/3500

**Comment by shawnh2** [comment]
Fixed in favor of #3499
