### ISSUE TITLE
helm: support disabling cert-gen job

### ISSUE THREAD

**Issue by gecube** [envoyproxy/gateway#3501]
Good day!

I see that inside of helm chart we are using `kind: Job` to generate certificates. I'd like to ask to support disabling of this job as I can issue these certificates with cert-manager like I proposed in another project https://github.com/wazuh/wazuh-kubernetes/pull/577

**Comment by arkodg** [comment]
hey @gecube we highlight this integration in https://gateway.envoyproxy.io/v1.0.1/install/custom-cert/, in this case the job is a no-op, we can do better by adding explicit support to disable the job in helm

**Comment by gecube** [comment]
@arkodg Hi! Thanks, I already found this article on my own. It was tough, but anyway appreciate your fast reply.

> we can do better by adding explicit support to disable the job in helm

super idea!!!!

**Comment by ShyunnY** [comment]
It looks like we need to add a knob to turn/off, I think I should be able to complete this work.  :)

**Comment by arkodg** [comment]
thanks for picking this one up @ShyunnY, 
https://github.com/envoyproxy/gateway/blob/90a4b9910d86e19ed4a4d768c9e002eed54a2adc/charts/gateway-helm/values.tmpl.yaml#L68
thinking out loud, one UX in Helm for this could be
```
certgen: nil
```

**Comment by arkodg** [comment]
Disabling the cert-get job may also impact other features like OIDC, and it may be hard to make the user aware of this for such cases.
Since running the cert-gen job for this above case is a no-op, we prefer to keep in on, and skip generating certs for this case
