### ISSUE TITLE
At when external authentication service will be called?

### ISSUE THREAD

**Issue by KshitijaR16** [envoyproxy/gateway#3504]
*Description*:
Hi Team,
We deployment envoy-gateway with 1.0.1 helm version and security policy with external authentication.
Want to when that external authentication service will be called? Because we can see authentication is called for each httproute.
Applied the security at gateway level and few httproutes with common hostname like abc.com prefix with service name.
In external authentication deployment we can see logs for specific user=number of httproutes.

Want to know is this working correctly?

**Comment by arkodg** [comment]
Hi @KshitijaR16 here's the doc https://gateway.envoyproxy.io/v1.0.1/tasks/security/ext-auth/ highlighting how to integrate with an ext authz service, the SecurityPolicy can either target a HTTPRoute or a Gateway depending on your case

**Comment by KshitijaR16** [comment]
Hi @arkodg 
We configured external authentication with gateway as a target as mentioned in document.
In our case we configured almost 15 httproutes and when we call or access one of the httproute ,in external authentication service we can see 15 logs for 1 httproute access.
Any suggestions on this?

**Comment by arkodg** [comment]
can you elaborate/share the logs ?
