### ISSUE TITLE
Enable to configure topologySpreadConstraints for EG control plane

### ISSUE THREAD

**Issue by alexwo** [envoyproxy/gateway#3534]
Given that EG control plane is deployed with leader election enabled by default, it makes sense to provide an easy option to allow it to run across multiple availability zones to achieve a high availability (HA) deployment. One option currently available to achieve this is using pod affinity; however, adding topologySpreadConstraints offers even greater flexibility.

**Comment by shawnh2** [comment]
close in favor of #3535
