### ISSUE TITLE
add support to PodDisruptionBudget for envoyproxy / eg control plane

### ISSUE THREAD

**Issue by alexwo** [envoyproxy/gateway#3546]
By implementing a PDB, we can define policies that prevent too many instances of the Envoy Gateway / EG control plane from being simultaneously disrupted during voluntary operations such as node upgrades, rolling updates, or manual interventions.

- [x]  Envoy Gateway https://github.com/envoyproxy/gateway/pull/3545
- [x]  Envoy Proxy https://github.com/envoyproxy/gateway/pull/3583

**Comment by arkodg** [comment]
sure Im +1 to this as opt in, wdyt @envoyproxy/gateway-maintainers 

if majority are +1
* can we split this epic into 2 sub task to track CP and DP separately ?
* @alexwo is this something you'll be working on ? should I add this to the v1.1 milestone ?

**Comment by zirain** [comment]
lg if it's opt-in.

**Comment by alexwo** [comment]
> sure Im +1 to this as opt in, wdyt @envoyproxy/gateway-maintainers
> 
> if majority are +1
> 
> * can we split this epic into 2 sub task to track CP and DP separately ?
> * @alexwo is this something you'll be working on ? should I add this to the v1.1 milestone ?

yes, i can add it.

**Comment by arkodg** [comment]
thanks for volunteering to drive this one @alexwo

**Comment by guydc** [comment]
+1

**Comment by zhaohuabing** [comment]
+1
