### ISSUE TITLE
bug: extra api.md & README.md are generated in gateway-addons-helm 

### ISSUE THREAD

**Issue by alexwo** [envoyproxy/gateway#3547]
*steps to reproduce*:
Make any change in values.tmpl.yaml and run  make generate.

Results:
an extra README.md and api.md are generated at gateway-addons-helm

**Comment by shawnh2** [comment]
that's odd, nothing strange in `make helm-package`. I will take a took at this, thanks for reporting this.

as a workaround, you can run `make helm-generate.gateway-helm` instead.
