### ISSUE TITLE
Support multiple backendRefs for ext Auth Service

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3551]
I think we can close it now, and create another one to track multi backends for ext_auth.

_Originally posted by @zirain in https://github.com/envoyproxy/gateway/issues/3091#issuecomment-2149510155_

**Comment by zirain** [comment]
should we make sure there's a real user case first?

**Comment by arkodg** [comment]
* canary is one use case
* primary/secondary is the other, but we dont have a priority knob yet

**Comment by zirain** [comment]
> * canary is one use case
> * primary/secondary is the other, but we dont have a priority knob yet

yeah that's the key point.

**Comment by arkodg** [comment]
can this be closed @zirain  / @guydc  ?
