### ISSUE TITLE
possibly update the conditions used for invalid redirect filter options

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#357]
There's some ambiguity in the Gateway API spec as to what conditions should be used for various invalid options on the redirect filter -- the spec specifies a type that is not actually defined for HTTPRoutes. I think it's a typo in the spec and the PR below would fix it, but we'll see what the Gateway API maintainers think.

ref. https://github.com/envoyproxy/gateway/pull/249#discussion_r964126956

ref. https://github.com/kubernetes-sigs/gateway-api/pull/1382

**Comment by danehans** [comment]
@skriss Added this to the backlog. Feel free to change the milestone as needed.

**Comment by skriss** [comment]
Closing, replaced by #494
