### ISSUE TITLE
OpenTelemetry access logger support extension formatters

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3570]
follow https://github.com/envoyproxy/envoy/pull/34469

**Comment by zirain** [comment]
@aoledk interest in this?

**Comment by guydc** [comment]
+1 !

Can we also add the formatter extensions to File Access Logger and not just OTEL sink? These extensions are especially useful: 
- [extensions.formatter.metadata.v3.Metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/metadata/v3/metadata.proto#extensions-formatter-metadata-v3-metadata)
- [extensions.formatter.req_without_query.v3.ReqWithoutQuery](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto#extensions-formatter-req-without-query-v3-reqwithoutquery)
