### ISSUE TITLE
Does BasicAuth security policy challenge for credentials?

### ISSUE THREAD

**Issue by nbrns** [envoyproxy/gateway#3623]
*Description*:
I use the basic auth security policy to secure a frontend application with minimum effort. After applying the policy, the route correctly gives me a 401 if no basic auth credentials are sent.

However, I'd expect the proxy to challenge for credentials, such that a browser prompts for username and password.
I am a little bit confused, as I am almost sure that it prompted on my test setup yesterday, but it didn't prompt on my test setup today. 

Should the proxy challenge or did I see some flaky browser behaviour with the prompt yesterday?
If it doesn't challenge, is there any way to make the proxy challenge? E.g. by setting the WWW-Authenticate header?

**Comment by arkodg** [comment]
looks like this just got added to Envoy Proxy !
https://github.com/envoyproxy/envoy/issues/34015
and can be supported in EG now

**Comment by arkodg** [comment]
@zhaohuabing looks like there is no extra work needed here from EG side, and is available on v0.0.0-latest and should be available in the next release ?

**Comment by zhaohuabing** [comment]
> @zhaohuabing looks like there is no extra work needed here from EG side, and is available on v0.0.0-latest and should be available in the next release ?

Yes, It should be available with the latest Envoy image, without extra work on the EG side.

**Comment by nbrns** [comment]
You guys resolved my confusion! Apparently I accidentally installed the v0.0.0-latest on my test setup yesterday. I just verified that it does indeed prompt now.

Thanks so much, keep up the good work.
