### ISSUE TITLE
Support NetworkPolicy label from Gateway to proxy

### ISSUE THREAD

**Issue by christiancadieux** [envoyproxy/gateway#3627]
*Description*:
> 
Need to ability to create NetworkPolicy that refer to the proxy deployment that is created by the envoy-gateway. This would allow
to limit ingress to the proxy pods for example.
To do this we would need all or maybe some of the labels of the Gateway resource to be transferred to the proxy deployment. 
This way if a Gateway resource is created for example with:
```
   labels:
      gateway.io/tenant: tenant1
```

this label (except for the 'gateway.io') would be transferred to the proxy deployment template  labels (used to create the pods):
```
   labels:
      tenant: tenant1
```

and then a NetworkPolicy can be created with an endpointSelector tenant:tenant1 that  include ingress rules to limit ingress to specfic other pods (using identities/labels), namespaces or CIDRs.

These labels need to be transferred from the Gateway to the proxy deployment because there can be multiple gateways , each with possibly different access rules defined using NetworkPolicies. 

This kind of work using the envoyProxy resource but not really since the envoyProxy is tied to the GatewayClass - but here we need distinct label for each Gateway (one gatewayClass - many gateways).

[optional *Relevant Links*:]
>

**Comment by shawnh2** [comment]
We have the support of attaching EnvoyProxy to Gateways (as in https://github.com/envoyproxy/gateway/pull/3532, I believe  will land soon).

Yes, I think is a reasonable request. We can define that certain labels with prefix, like `transfer.gateway.io`, can be transferred from Gateway to proxy pod.

**Comment by zirain** [comment]
will https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure help?

**Comment by arkodg** [comment]
* this is already possible today in v1.0 using `gateway.spec.infrastructure.labels`
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure

* and will be possible in `v1.1` with `EnvoyProxy` resource being able to attach to `Gateway`s

closing this issue, since its already possible today

**Comment by christiancadieux** [comment]
tried updating the infrastructure labels : It did not propagate to the service and the envoy-proxy pods.
