### ISSUE TITLE
gateway does not show ADDRESS in multi-namespace install

### ISSUE THREAD

**Issue by christiancadieux** [envoyproxy/gateway#3633]
*Description*:
>in a multi-namespace install, the Gateway is working but does not show ADDRESS

```

$ k get gateway -n tenant1-ns1
NAME   CLASS        ADDRESS   PROGRAMMED   AGE
eg     eg-tenant1             False        38m

$ k get service -n tenant1-eg
NAME                            TYPE           CLUSTER-IP        EXTERNAL-IP     PORT(S)                         AGE
envoy-gateway                   ClusterIP      192.168.200.21    <none>          18000/TCP,18001/TCP,19001/TCP   19h
envoy-gateway-metrics-service   ClusterIP      192.168.230.149   <none>          19001/TCP                       19h
envoy-tenant1-ns1-eg-33b93dd6   LoadBalancer   192.168.206.162   10.X.182.62   8080:9947/TCP                   20h

$ curl --header "Host: www.tenant1.example.com"  http://10.X.182.62:8080/get23
{
 "path": "/get23",
 "host": "www.tenant1.example.com",
 "method": "GET",
 "proto": "HTTP/1.1",
 "headers": {
  "Accept": [
   "*/*"
...

```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by arkodg** [comment]
hey @christiancadieux which verson are you on ?
in which namespace is the controller deployed in ? are you watching for that namespace as well ? thats the namespace where the service is living in (`tenant1-eg`)

**Comment by christiancadieux** [comment]
no. the gateway software  in installed in tenant1-eg and the Gateway&httpRoute is installed in tenant1-ns1 .
but the 
cm:
```
watch:
          namespaces:
          - tenant1-ns1
          - tenant1-ns2
          type: Namespaces
```

**Comment by arkodg** [comment]
adding `tenant1-eg` should fix your issue, this will ensure the controller can watch the generated `Service` and copy the Address from it
