### ISSUE TITLE
docs: Attaching EnvoyProxy to Gateways

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3639]
*Description*:
>Describe the issue.

Support for attaching envoyProxy to Gateways was added in https://github.com/envoyproxy/gateway/pull/3532
https://gateway.envoyproxy.io/v1.0/tasks/operations/customize-envoyproxy/#add-gatewayclass-parametersref 
our docs need to be updated to also highlight support for attaching to Gateway

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
Should note that: `Support attaching EnvoyProxy resource to Gateways if MergeGateways is disabled on GatewayClass`
