### ISSUE TITLE
support ghcr to store envoy-gateway oci helm chart

### ISSUE THREAD

**Issue by networkhermit** [envoyproxy/gateway#3651]
*Description*:

Currently the envoy-gateway oci helm chart is published in [dockerhub](https://registry.hub.docker.com/r/envoyproxy/gateway-helm/tags), this has some shortcomings:

1. dockerhub download is rate limited and could be easily blocked in environments which share a common public ip
3. sadly the dockerhub seems to be indefinitely blocked in China, making users and developers in CN more difficult to promote and adopt envoy-gateway

I think it's possible to publish oci helm chart in both dockerhub and ghcr, so users can benefit from either choice.

[optional *Relevant Links*:]

GHCR is extensively used by other projects such as [prometheus community](https://github.com/orgs/prometheus-community/packages?repo_name=helm-charts).

**Comment by arkodg** [comment]
all envoy projects use shared infra, dockehub for image hosting, and adding another image repo to host will be unmanageable for the team and may result in inconsistent information across repos. 
Closing this one
