### ISSUE TITLE
Support the Backend resource for Ext-Auth

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3665]

**Comment by guydc** [comment]
+1

Curious about the use case: cluster-external service?

**Comment by arkodg** [comment]
same as ext proc, adding the ability to have a sidecar container that can connect over UDS,  but using the ext auth API for legacy reasons

**Comment by zirain** [comment]
@liorokman is this fixed by https://github.com/envoyproxy/gateway/pull/3954?
