### ISSUE TITLE
Support CEL Expressions in Access Logs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3667]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Add the ability to log access logs only when specific conditions are met, mainly to reduce logging costs

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/filters/cel/v3/cel.proto

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by guydc** [comment]
+1. 
Is this just about CEL, or do we want to support additional filters? I think that status code and response flag filters are also pretty useful.

**Comment by arkodg** [comment]
@guydc the status code and the response flag can we represented using CEL `response.code > 500` with the entire supported list in https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#request-attributes

**Comment by guydc** [comment]
Ah, yea, makes sense. Let's keep it CEL for only for now. Thanks!

**Comment by zirain** [comment]
still need doc and e2e for this.
