### ISSUE TITLE
Add Metadata to xDS Resources

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#367]
*Description*:
Similar to https://github.com/envoyproxy/gateway/pull/350 add Metadata to the Xds IR as well as the specific xDS resources https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-metadata  to better map the input Gateway API resource to the output xDS resource

**Comment by NomadXD** [comment]
@danehans Can I work on this one?

**Comment by danehans** [comment]
@NomadXD it's all yours.

**Comment by kanurag94** [comment]
@danehans I would like to take this up if no one else is working actively on this

**Comment by zirain** [comment]
there's no update for a long time, so I think it's ok to reassign to @kanurag94 .

**Comment by arkodg** [comment]
I dont think this issue is required anymore, so closing it for now
@kanurag94 thanks for looking into open issues in the project, [here's a complete list](https://github.com/envoyproxy/gateway/labels/help%20wanted) of issue that have the `help-wanted` labels assigned to them

**Comment by kanurag94** [comment]
thanks @arkodg for the update, I will look into other issues
