### ISSUE TITLE
Add support for monitoring envoy gateway memory and cpu in gateway-addon-chart

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3675]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

https://gateway.envoyproxy.io/latest/tasks/observability/grafana-integration/ adds a dashboard for Envoy Proxy, but not for Envoy Gateway

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
We can add another dashboard called `Envoy Gateway Resources` for monitoring envoy gateway memory and cpu.
