### ISSUE TITLE
Labels or Annotations for Service-to-Gateway Object References

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#368]
https://github.com/envoyproxy/gateway/pull/352 adds gateway owning labels. These labels are applied to the Envoy service and reference the gateway ns/name used to create the service. The Kube provider gateway controller watches services and reconciles the correct gateway, e.g. update `gateway.status.addresses` when the Envoy service is assigned a load-balancer IP. Labels were chosen instead of annotations based on guidance from the [Kubernetes Annotations/Labels docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#:~:text=Labels%20can%20be%20used%20to,characters%20not%20permitted%20by%20labels.):

>Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects. The metadata in an annotation can be small or large, structured or unstructured, and can include characters not permitted by labels.

Should we proceed with Labels or Annotations to solve this problem?

**Comment by youngnick** [comment]
Usually, labels are used when you're _searching_ or _watching for_ things though, so ideally we'd put a label on the _Gateway(s)_ as well, and then take a value from the label on the Service (the controllerName string maybe?) and when reconciling a Service, enqueue updates for all the Gateways that might need it.

That's only because there is (possibly) a many-to-one relationship between Gateways and Service though.

**Comment by zlahham** [comment]
This is interesting as it touches on something we are looking into. We are trying to pass some annotations from the Gateway to the service that are linked to AWS ELB annotations. For example:
```
      service.beta.kubernetes.io/aws-load-balancer-name: setme
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: setme
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-type: external
```

The main issue that we are facing is that this default setup without the annotations would create a classic loadbalancer on AWS and we are trying to create an NLB instead. How would you go about resolving this?

**Comment by danehans** [comment]
@zlahham https://github.com/envoyproxy/gateway/pull/350 added metadata support to the Infra IR and https://github.com/envoyproxy/gateway/pull/352 provides an example implementation of how these labels can be applied to the Envoy Service.

For your use case, I prefer using the [EnvoyProxy API](https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoyproxy_types.go) instead of labeling the Gateway. The driving factor for this recommendation is to avoid Gateway annotation sprawl. Thoughts @arkodg @LukeShu @skriss @youngnick?

**Comment by arkodg** [comment]
> For your use case, I prefer using the [EnvoyProxy API](https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/envoyproxy_types.go) instead of labeling the Gateway. The driving factor for this recommendation is to avoid Gateway annotation sprawl. Thoughts @arkodg @LukeShu @skriss @youngnick?

+1 raised https://github.com/envoyproxy/gateway/issues/377 to track it

**Comment by youngnick** [comment]
Yes, I agree with the approach in #377.

It doesn't really matter where the label lives, I guess, and labels rather than annotations is fine.

**Comment by danehans** [comment]
I'm closing this issue since owning Gateway ns/name labels were added.
