### ISSUE TITLE
Clean up control plane metrics names

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3684]
Original comment on https://github.com/envoyproxy/gateway/pull/3564#discussion_r1649463350

```
There are two different naming styles in EG:

```
xds_snapshot_creation_total
xds_snapshot_creation_failed
xds_snapshot_creation_success
```

```
status_update_total
status_update_failed_total
status_update_success_total
status_update_conflict_total
```

Prefer the first one. We also need to align "failed, failure, error" to a single term.
```

**Comment by shawnh2** [comment]
Like https://prometheus.io/docs/practices/naming/#labels suggest, we can consider various status like `failed, succeed, etc` as a label value, this will reduce redundancy.

**Comment by arkodg** [comment]
thanks for looking into this one @shawnh2, can you revisit the naming for all our control plane metrics and update it based on best practices 
cc @Xunzhuo
