### ISSUE TITLE
Add zipkin in gateway-addons-helm

### ISSUE THREAD

**Issue by shawnh2** [envoyproxy/gateway#3687]
*Description*:

add zipkin in gateway-addons-helm, introduced in https://github.com/envoyproxy/gateway/pull/3668

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
we may not need this, OTel collector has zipkin receiver.

**Comment by shawnh2** [comment]
thanks, good to know!
