### ISSUE TITLE
Most Secure place for storing TLS-certificates and Gateway

### ISSUE THREAD

**Issue by matrix-root** [envoyproxy/gateway#3694]
*Description*: 
If my setup will have only one gateway, is it better to create separate `envoy` namepsace for it and store TLS secrets here or I can store this Gateway with TLS secrets inside `envoy-gateway-system` namespace?

Also by some reason I'm unable to join Slack community - it allows to join only if you have lyft or linuxfoundation email

**Comment by arkodg** [comment]
@matrix-root the TLS certs are usually configured by the platform owner or app owner, so I'd put it in a namespace that they own, and not the `envoy-gateway-system` namespace, access to this ns should be treated with more scrutiny

you can follow theses steps to join the EG slack community https://github.com/envoyproxy/gateway?tab=readme-ov-file#contact
