### ISSUE TITLE
Should Infra Manager Watch Services and Update Status

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#371]
https://github.com/envoyproxy/gateway/pull/352 adds support for managing Gateway `status.addresses`. The approach in this PR adds a Service watch to the Kube provider gateway controller. When a Service is CRUD'd, the controller will reconcile the appropriate Gateway by parsing the "Gateway owning" label(s) from the Service. The appropriate Gateway `status.addresses` are then updated through the reconciliation process.

https://github.com/envoyproxy/gateway/pull/352#discussion_r966399688 suggests an alternative approach:

>something to consider in the future - another way to solve this would have been for the infra manager to publish a GatewayStatus watchable message which would this provider would subscribe to, and update the status when it received a new one

Should we stick with the current approach or shift to the approach from the above comment?

**Comment by danehans** [comment]
From https://github.com/envoyproxy/gateway/pull/352#discussion_r966480558:
> by building the GatewayStatus based on the IR metadata info. We might not need a controller as we start off, just performing a Get post a Create/Update might be good enough

IMO this approach resonates if a Service controller is implemented in the Infra Manager. For example:
- The Service controller reconciles Services that include "Gateway owning" labels.
- The Service controller will publish a `GatewayStatus` message that includes the status ingress address/hostname for each Service that references the owning Gateway.
- Subscribers, e.g. the Kube provider gateway controller, will receive `GatewayStatus` messages and calculate the status for managed Gateways.

**Comment by arkodg** [comment]
closing this issue for now since the Provider layer reconciles the Service resource and updates the Gateway Status, and this approach seems to be working fine.
