### ISSUE TITLE
docs: Steps for migrating to Envoy Gateway

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3742]
*Description*:

Add a doc that can help users who want to migrate to Envoy Gateway

Would be great to highlight the ingress2gateway https://github.com/kubernetes-sigs/ingress2gateway/tree/main tool with an example

**Comment by Manoramsharma** [comment]
@arkodg I am interested in  working on this issue, Can you just tell me in which section of documentation I have to do add this.

**Comment by arkodg** [comment]
thanks for looking into this @Manoramsharma , https://gateway.envoyproxy.io/docs/install/ is a good home for a migration doc
