### ISSUE TITLE
e2e: Cookie based Consistent Hashing

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3744]
*Description*:
>Describe the issue.

Relates to https://github.com/envoyproxy/gateway/issues/2624

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
I will take a look at this, could be done along with https://github.com/envoyproxy/gateway/issues/2153

**Comment by arkodg** [comment]
thanks @shawnh2 !
