### ISSUE TITLE
Configure different access log formats for gateways in the same gateway class

### ISSUE THREAD

**Issue by benediktwerner** [envoyproxy/gateway#3773]
Currently, the access log format can be configured via an `EnvoyProxy` CRD which always applies to a whole gateway class, so it's not possible (at least not without patch policies) to configure different access log formats for different gateways in the same gateway class. In our case, we for example want to log various headers specific to each gateway.

Actually, this also applies to almost all of the other values that can be configured via `EnvoyProxy`, for example gateways managed by different teams may want to send their telemetry to different places or we might want to enable oauth debug logging for a single gateway to debug oauth issues related to its specific OIDC config.

So I wonder if it might even just make sense to somehow allow attaching an `EnvoyProxy` CRD to a single gateway (provided that `mergeGateways` is false for its gateway class, and I guess also disallowing setting `mergeGateway` in that case). In essence, a single (non-merged) gateway after all also just is a single envoy proxy instance, exactly what the `EnvoyProxy` CRD allows configuring.

**Comment by shawnh2** [comment]
hi @benediktwerner, the EnvoyProxy CRD can be attached to gateway now thanks to https://github.com/envoyproxy/gateway/pull/3532.

However, this feature is not documented. Will update documents soon.
