### ISSUE TITLE
Allow configuring TLS settings for OIDC upstream

### ISSUE THREAD

**Issue by benediktwerner** [envoyproxy/gateway#3774]
Our OIDC provider doesn't support Envoy's default ECDH curves so we currently have to configure additional curves via a patch policy.

It looks like EG v1.1 will already add a default `BackendTLSConfig` for the `EnvoyProxy` which seems good enough but at first glance, it looks like it currently isn't applied to the OIDC provider cluster?

**Comment by zhaohuabing** [comment]
Related to https://github.com/envoyproxy/gateway/issues/3622

As discussed in the EG meeting, the provider can be modeled as a `Backend` resource and be associated with a `BackendTLSConfig`.

**Comment by zhaohuabing** [comment]
Closing this as now OIDC provider TLS can be configured with `Backend` and `BackendTLSPolicy`.

Fixed with https://github.com/envoyproxy/gateway/pull/4227
