### ISSUE TITLE
create a release guide

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3814]
*Description*:
>Describe the issue.

Create a release guide listing all the tasks needed to release a new EG version. 

Releasing a new EG version includes a number of tasks scattered in different parts of the repo, for example:
* Create a release branch
* generate a release note
* bump the version in the VERSION file
* ...

It can be useful to create a guide so the next release manager can easily pick up the job.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
https://gateway.envoyproxy.io/contributions/releasing/ may help?

**Comment by zhaohuabing** [comment]
> https://gateway.envoyproxy.io/contributions/releasing/ may help?

Ha, didn't notice that.
