### ISSUE TITLE
Envoy Gateway fails when `EnvoyProxy`is in a different namespace

### ISSUE THREAD

**Issue by mazzy89** [envoyproxy/gateway#3824]
**Description**:
The issue observed is that Envoy Gateway is not functioning correctly when the `EnvoyProxy` resource is created in a different namespace than the `Envoy Gateway`. According to the changelog of version 1.0.2, this setup should be supported, but it currently results in an error.

**Repro steps**:
1. Deploy Envoy Gateway in the `gateway-system` namespace.
2. Create an `EnvoyProxy` resource in a different namespace (e.g., `test`).
3. Observe the error in the logs indicating that the namespace does not match.

**Environment**:
- Envoy Gateway version: 1.0.2
- Kubernetes version: 1.29

**Logs**:
```
2024-07-11T21:47:19.166Z	INFO	provider	kubernetes/controller.go:1272	envoyproxy namespace does not match Envoy Gateway's namespace	{"runner": "provider", "namespace": "test", "name": "test-gateway-proxy-config"}
```

**Comment by zhaohuabing** [comment]
This only exist on 1.0 branch.

**Comment by mazzy89** [comment]
@zhaohuabing how this is going to be released? will be there a patch version to amend `v1.0.2`?
