### ISSUE TITLE
Error when installing Envoy Gateway via GoLang

### ISSUE THREAD

**Issue by BLasan** [envoyproxy/gateway#384]
*Description*:
When installing the envoy gateway according to the [QUICKSTART.md](https://github.com/envoyproxy/gateway/blob/main/docs/user/QUICKSTART.md) via GoLang sequentially, the following error gets produced for the command `kubectl apply -f https://raw.githubusercontent.com/envoyproxy/gateway/v0.2.0-rc1/examples/kubernetes/gatewayclass.yaml`.

```
kubectl apply -f https://raw.githubusercontent.com/envoyproxy/gateway/v0.2.0-rc1/examples/kubernetes/gatewayclass.yaml
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/envoyproxy/gateway/v0.2.0-rc1/examples/kubernetes/gatewayclass.yaml": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s": proxy error from 127.0.0.1:6443 while dialing 10.42.0.145:8443, code 503: 503 Service Unavailable
```

However, this error occurs intermittently. Seems like the GatewayClass waits until `gateway-api-admission-server` gets started. Shouldn't this be properly handled inside the gateway controller itself?

OS: MacOS Moneterey (M1 Pro)
Kubernetes Version: `1.24.4`
K8s Management Tool: Rancher Desktop `1.5.1`

**Comment by danehans** [comment]
@BLasan thanks for reporting the issue and I'm glad to hear it cleared up on its own. I created https://github.com/envoyproxy/gateway/issues/390 to track this issue. Please continue to report any issues you encounter and let us know if you'd like to work on fixing it.
