### ISSUE TITLE
Better management of application images used by e2e test?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3866]
right now there're some applications like [this](https://github.com/envoyproxy/gateway/blob/cd51ad3624d076293e921d02b613f703b6aed809/test/e2e/base/manifests.yaml#L870-L982) in our e2e tests, they're hard to read and mantain. My proposal as following:
- Setup up cluster with local registry https://kind.sigs.k8s.io/docs/user/local-registry/
- Build images and push them to local registry when setup e2e
- Update e2e yaml to use image from local registry.

**Comment by zirain** [comment]
@envoyproxy/gateway-maintainers PTAL, and share your thought on this.

**Comment by arkodg** [comment]
hey @zirain your suggestion is the best long term solution, I haven't felt the pain of reading/editing this code so I'd mark this tech debt as lower priority, but maybe others feel differently

**Comment by zirain** [comment]
@arkodg here is my proposal:

- move all these apps source code under examples(or tools/src)
- add a new make target(make kube-install-examples-image), which build all images and load into kind cluster
- change all related yaml files.

**Comment by arkodg** [comment]
@zirain with this approach, my only concern is resources required for e2e, we are already limited by the GHA runner size, and adding another registry to run will make it harder to run other required things
would like to hear what others think @envoyproxy/gateway-maintainers

**Comment by zirain** [comment]
i didn't add a local registry now, using kind load instead.

**Comment by arkodg** [comment]
> i didn't add a local registry now, using kind load instead.

ah cool, does this work for devs with Mac envs as well ?

**Comment by zirain** [comment]
yes, worked on my m1.
