### ISSUE TITLE
Run `make run-kube-local` failed

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#387]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

make run-kube-local starts EG locally, but failed for couple of reasons:
1. Cannot find EG binary if we did not run make build manually before this:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/48784001/190250033-3cf2a2a8-ee66-44e8-b0bc-0604f9935d8d.png">
2. multicluster kube-config will break the script:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/48784001/190250270-b33457ae-08b3-4e50-bc50-bf1946ba3c89.png">

/assign

**Comment by danehans** [comment]
@Xunzhuo even with https://github.com/envoyproxy/gateway/pull/388, this Make target will fail until https://github.com/envoyproxy/gateway/issues/256 is fixed, PTAL.
