### ISSUE TITLE
Add metrics from the Ratelimiting service in the Grafana dashboard

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3871]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

relates to https://github.com/envoyproxy/gateway/pull/2729

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by MdSahil-oss** [comment]
@arkodg I would like to work on this issue, Can you assign it to me.
