### ISSUE TITLE
default behavior of BackendTrafficPolicy and SecurityPolicy should be Replace

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#3875]
It was fixed by https://github.com/envoyproxy/gateway/issues/2734, but has been reverted somehow.

**Comment by arkodg** [comment]
Is this broken on v1.0 as well ?

**Comment by zhaohuabing** [comment]
This only exists on v1.0.x for corner cases where an empty SecurityPolicy targeting an HTTPRoute overrides a SecurityPolicy targeting a Gateway.

**Comment by zhaohuabing** [comment]
Close as this does not exist in main and v1.1.0. 
This can't be cherry-picked to v1.0.x as the change is significant.
