### ISSUE TITLE
Initial xDS Translator Design and Implementation

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#39]
https://github.com/envoyproxy/gateway/pull/16 specifies the need for an xDS Translator (XT) to translate IR resources to an xDS config. The XT details should be captured in this issue or a linked doc.

**Comment by danehans** [comment]
@skriss I assigned this issue to you based on the 5/24/22 community meeting [notes](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing). Please unassign yourself if that's not the case.

**Comment by skriss** [comment]
> @skriss I assigned this issue to you based on the 5/24/22 community meeting [notes](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing). Please unassign yourself if that's not the case.

Removed my assignment, I'm going to focus on #32 and #38 to start. Happy to circle back to this later though if nobody has picked it up.

**Comment by danehans** [comment]
Fixed by https://github.com/envoyproxy/gateway/pull/123
