### ISSUE TITLE
Check Gateway API Admission Availability

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#390]
EG should check the presence and availability of the [Gateway API bundle](https://gateway-api.sigs.k8s.io/guides/getting-started/#installing-a-gateway-api-bundle), e.g. CRDs, webhook server, etc. resources during startup.

- Check the status of `deploy/gateway-api-admission-server -n gateway-system`.
- Check the status of `svc/gateway-api-admission-server -n gateway-system`.
- Check for Gateway API RBAC
- Check that CRDs are installed with the supported versions. 
- etc.

Should EG periodically check for the presence of these resources too?

**Comment by danehans** [comment]
xref: https://github.com/envoyproxy/gateway/issues/384

cc: @BLasan

**Comment by arkodg** [comment]
@Xunzhuo is this something that can be baked into `helm` ?

**Comment by arkodg** [comment]
closing this issue for now since we no longer install the admission server and webhook
