### ISSUE TITLE
docs: add guide for attaching EnvoyProxy to Gateways

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#3907]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shawnh2** [comment]
dup of https://github.com/envoyproxy/gateway/issues/3639

**Comment by Xunzhuo** [comment]
close in favor of duplicate with #3639
