### ISSUE TITLE
Support for multiple TLS certificates for a single host

### ISSUE THREAD

**Issue by chauhanshubham** [envoyproxy/gateway#393]
*Description*:
LB vendors provide the ability to configure multiple certificates for a single fqdn.
The usecase is to have multiple certificates with different signing algorithms (RSA and/or ECC).
The server, based on the clients' SSL capabilities decides to send the relevant certificate,
preferably ECC signed cert (if configured).
So customers might want to configure two certificates for a single host - one for each algorithm RSA / ECC.

[optional *Relevant Links*:]
> https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate
> https://www.ibm.com/docs/en/i/7.2?topic=ssl-multiple-certificate-selection
> https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#certificate-selection

Came across this - so probably EG needs to not have this limitation, (and additionally some other checks and configs?)
https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/translator.go#L321

**Comment by skriss** [comment]
The Gateway API spec definitely allows this as an implementation-specific behavior (see `certificateRefs` under https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayTLSConfig), so no reason we can't add this to EG. The initial implementation has just been focused on Gateway API's core conformance features, which in this case is 1 TLS cert.

**Comment by danehans** [comment]
@chauhanshubham since the focus of v0.2.0 is Gateway API conformance, I have tagged this issue as `Backlog`.

**Comment by chauhanshubham** [comment]
I can take this up cc: @arkodg
