### ISSUE TITLE
Should validate the filterOrder.After cannot be envoy.filters.http.router

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#3938]
*Description*:
>Describe the issue.

Based on: https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/httpfilters.go#L214, should we validate the filter shouldnt be `envoy.filters.http.router` ?

cc @zhaohuabing 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zhaohuabing** [comment]
@Xunzhuo Good catch! I think we'd better validate at the API level to avoid misconfiguation. Router is a terminate filter and should always be the last one in the filter chain.

**Comment by zhaohuabing** [comment]
@Xunzhuo We already got validation here https://github.com/envoyproxy/gateway/blob/c78f427eb58228da66d64b225a91a2aa3b59515c/api/v1alpha1/envoyproxy_types.go#L156

**Comment by Xunzhuo** [comment]
This validation is weird, cannot we insert filter before router?

**Comment by zhaohuabing** [comment]
Yes, but you should be able to achieve the same with `After` key word.

**Comment by Xunzhuo** [comment]
Thanks, let`s close this one
