### ISSUE TITLE
Find a way to reenable the cherry-picker process

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#3946]
It's removed in https://github.com/envoyproxy/gateway/pull/3831, because it hardly ever worked.
We need find a way to enable it, so that it could reduce the effort for cherrypicking and releasing minor patch.

**Comment by Manoramsharma** [comment]
Hi @zirain I saw the previous attempt to enable cherry-picker workflow using `carloscastrojumo/github-cherry-pick-action` but I think we can also use [Xealth-cherry-picker](https://github.com/marketplace/actions/xealth-cherry-picker#-us) it has a good documentation to follow.

**Comment by zirain** [comment]
the one you shared looks like not in active maintain.

**Comment by Manoramsharma** [comment]
@zirain can you please share any reference or what you are thinking as the way to achieve cherry-picker workflow? Do I have to do something as previous attempt?

**Comment by zirain** [comment]
Once the action work very well, maybe wen write a simple tools which can search the PR with target label(e.g. cherrypick/release-v0.4), and try to cherry pick those to target branch one by one, so that it will be a great help of release manager.

**Comment by Manoramsharma** [comment]
@zirain I have searched a lot about the cherry-picker recently used by organisations, I got this cherry-picker in github marketplace https://github.com/sorenlouv/backport , we can integrate this one.

**Comment by zirain** [comment]
Assign to me for now so no one else can waste their time
