### ISSUE TITLE
homebrew install of egctl doesn't install latest stable version

### ISSUE THREAD

**Issue by eitansuez** [envoyproxy/gateway#3955]
*Description*:

on my mac, when i run `brew install egctl` i end up with version 1.0.2
i expected v1.1.0

**Comment by zirain** [comment]
did you run `brew update`?

**Comment by eitansuez** [comment]
yes i did.

**Comment by zirain** [comment]
let me check, it's bumped from `1.0.1` to `1.0.2`, so I used to think everything is fine.

**Comment by zirain** [comment]
see https://github.com/Homebrew/homebrew-core/pull/178539, we need improve our release notes.

**Comment by zirain** [comment]
this cause by our release notes is too large, brew failed on creating an auto-bump PR.

**Comment by eitansuez** [comment]
i think we can close this issue.  i see that `brew install egctl` now downloads version 1.1.0
