### ISSUE TITLE
how to upgrade from 1.0 to 1.1 ?

### ISSUE THREAD

**Issue by paulo-worry** [envoyproxy/gateway#3981]
*Description*:
[I Install v1.0 with YAML](https://gateway.envoyproxy.io/v1.0/install/install-yaml/)

Currently, I see that version 1.1 is released. I want to upgrade to 1.1, but I can't find any upgrade documents to refer to?

**Comment by arkodg** [comment]
there are steps mentioned under the `v1.1. Upgrade Notes` in https://gateway.envoyproxy.io/docs/tasks/quickstart/ which should probably be moved to the Install Section

**Comment by octonawish-akcodes** [comment]
@arkodg I want to work on this, can you assign it to me?

**Comment by octonawish-akcodes** [comment]
@zirain @arkodg I raised a PR to fix the issue #3988

**Comment by paulo-worry** [comment]
kubectl version
Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b

I got the following error during the upgrade:
`The CustomResourceDefinition "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
`

`kubectl apply -f ./install.yaml 
customresourcedefinition.apiextensions.k8s.io/backendlbpolicies.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/backendtlspolicies.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/gatewayclasses.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/gateways.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/grpcroutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/httproutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/referencegrants.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/tcproutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/tlsroutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/udproutes.gateway.networking.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/backends.gateway.envoyproxy.io created
customresourcedefinition.apiextensions.k8s.io/backendtrafficpolicies.gateway.envoyproxy.io configured
customresourcedefinition.apiextensions.k8s.io/clienttrafficpolicies.gateway.envoyproxy.io configured
customresourcedefinition.apiextensions.k8s.io/envoyextensionpolicies.gateway.envoyproxy.io created
customresourcedefinition.apiextensions.k8s.io/envoypatchpolicies.gateway.envoyproxy.io configured
customresourcedefinition.apiextensions.k8s.io/securitypolicies.gateway.envoyproxy.io configured
namespace/envoy-gateway-system unchanged
serviceaccount/envoy-gateway unchanged
configmap/envoy-gateway-config configured
clusterrole.rbac.authorization.k8s.io/eg-gateway-helm-envoy-gateway-role configured
clusterrolebinding.rbac.authorization.k8s.io/eg-gateway-helm-envoy-gateway-rolebinding unchanged
role.rbac.authorization.k8s.io/eg-gateway-helm-infra-manager configured
role.rbac.authorization.k8s.io/eg-gateway-helm-leader-election-role unchanged
rolebinding.rbac.authorization.k8s.io/eg-gateway-helm-infra-manager unchanged
rolebinding.rbac.authorization.k8s.io/eg-gateway-helm-leader-election-rolebinding unchanged
service/envoy-gateway configured
deployment.apps/envoy-gateway configured
serviceaccount/eg-gateway-helm-certgen unchanged
role.rbac.authorization.k8s.io/eg-gateway-helm-certgen unchanged
rolebinding.rbac.authorization.k8s.io/eg-gateway-helm-certgen unchanged
job.batch/eg-gateway-helm-certgen created
The CustomResourceDefinition "envoyproxies.gateway.envoyproxy.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by arkodg** [comment]
@paulo-worry you need to use `--server-side`
https://gateway.envoyproxy.io/docs/install/install-yaml/
