### ISSUE TITLE
CompatibilityMatrix display supported envoyproxy versions 

### ISSUE THREAD

**Issue by czczycz** [envoyproxy/gateway#3983]
I know how to upgrade my envoyproxy image from this [page](https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/), but I don't know which versions of envoyproxy are compatible with EG.
The [CompatibilityMatrix](https://gateway.envoyproxy.io/news/releases/matrix/) from EG docs shows supported k8s versions, but only one envoyproxy version is associated with each EG version.

**Comment by arkodg** [comment]
@czczycz we can only guarantee 1 envoy version compatibility, others may work, but we cannot guarantee that
