### ISSUE TITLE
Initial xDS Server Design and Implementation

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#40]
https://github.com/envoyproxy/gateway/pull/16 specifies the need for an xDS server to configure managed Envoy instances. The xDS server details should be captured in this issue or a linked doc.

**Comment by arkodg** [comment]
@youngnick raised https://github.com/envoyproxy/gateway/issues/70 so we can track the auth + authz implementation for gRPC communication b/w Envoy proxy and the xDS Server which should ensure that the xDS server can trust different data plane components / envoy proxies deployed by the provisioner allowing the default Envoy Gateway implementation to be based off a single binary (i.e. the Provisioner can deploy unique data planes and the xDS Server can push different xDS resources to different data planes ). A single binary should help simplify installation and operations, which is also something the [Istio community realized](https://docs.google.com/document/d/1v8BxI07u-mby5f5rCruwF7odSXgb9G8-C9W5hQtSIAg/edit#) after running multiple control plane components in a cluster.

**Comment by danehans** [comment]
@LukeShu I assigned this issue to you based on the 5/24/22 community meeting [notes](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing). Please unassign yourself if that's not the case.

**Comment by danehans** [comment]
Per https://github.com/envoyproxy/gateway/issues/60, this issue should use incremental instead of stow xds.

**Comment by youngnick** [comment]
Oops, I didn't do an update here.

I have a prototype branch that implements the xds-server, with a test command for exercising it, that supports both incremental and sotw xDS. I'm in the process of cleaning it up (turns out that go-control-plane expects a specific logging interface which `logr` does not provide, sigh), but expect to have a PR soon.
