### ISSUE TITLE
docs: JSONPath usage in EnvoyPatchPolicy

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#4043]
*Description*:
>Describe the issue.

Support for JSONPath was recently added to EnvoyPatchPolicy to be able to better select elements in a list
More in https://github.com/envoyproxy/gateway/pull/3757

Lets add an example in https://gateway.envoyproxy.io/docs/tasks/extensibility/envoy-patch-policy/ highlighting this use case

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
cc @denniskniep

**Comment by denniskniep** [comment]
@arkodg you can assign me
