### ISSUE TITLE
Improve Provider resource reconciliation

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#407]
*Description*:
We can further improve the performance of the system by ensuring that the provider reconcilers (for GatewayClass, Gateway and HTTPRoute) reconcile only when the resource spec has changed.

Today, when the Status Updater updates the status of a resource, we receive another reconcile notification which also triggers a redundant translation in the the gateway-api layer which triggers another redundant translation in the infra and xds layers.

.

**Comment by youngnick** [comment]
If we were okay with keeping some light state, we could keep the last seen `metadata.generation` for each resource, which would allow us to drop updates that don't change the spec, since `metadata.generation` is autoincremented by the apiserver each time the resource is changed.

**Comment by arkodg** [comment]
> If we were okay with keeping some light state, we could keep the last seen `metadata.generation` for each resource, which would allow us to drop updates that don't change the spec, since `metadata.generation` is autoincremented by the apiserver each time the resource is changed.

ha we should be able to implement this logic, we should have some state in the watchable map !

also in the near future this enhancement will be needed since https://github.com/envoyproxy/gateway/issues/413 will convert everything into a single object and leverage watchable (using `snapshot.Updates` rather than `snapshot.State`) to inform the next layer whether anything changed or not
