### ISSUE TITLE
Add specified headers to JWKS requests

### ISSUE THREAD

**Issue by yerkulees** [envoyproxy/gateway#4098]
*Description*:
Allow request headers to be configured for remoteJWKS with headersToRemoteJWKS similarly to how HTTPExtAuthService has headersToBackend. 

Our IDP requires HTTP headers to be sent to the remoteJWKS uri that Envoy doesn't send. I'd like to be able to configure the request with additional headers.

*Relevant Links*:
https://gateway.envoyproxy.io/docs/api/extension_types/#httpextauthservice
https://gateway.envoyproxy.io/docs/api/extension_types/#remotejwks

**Comment by arkodg** [comment]
@yerkulees the IDP is expecting additional headers when fetching the remote JWKS ?
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-remotejwks

you could add some via https://gateway.envoyproxy.io/latest/tasks/traffic/http-request-headers/#early-header-modification (only available on v0.0.0-latest rn)

**Comment by yerkulees** [comment]
The envoy proxy GitHub was able to help out.
https://github.com/envoyproxy/envoy/issues/35785
But this does look promising. Thanks.

**Comment by arkodg** [comment]
Ah so this should already be a available on v0.0.0-latest and in v1.2.0( end Oct 2024 )
