### ISSUE TITLE
Return 500 when BackendTrafficPolicy translation fails for TCP and UDP routes

### ISSUE THREAD

**Issue by MdSahil-oss** [envoyproxy/gateway#4118]
*Description*:
Return 500 when BackendTrafficPolicy translation fails for TCP and UDP routes

**Comment by MdSahil-oss** [comment]
@arkodg Assign this issue to me I'd like to work on it.

**Comment by arkodg** [comment]
Hey @MdSahil-oss this issue is NA, because there is no status code in the response for TCP and UDP, we would need to not accept connections to implement this, we can close this for now
