### ISSUE TITLE
Is it possible to have 1.2 RC released 

### ISSUE THREAD

**Issue by eshepelyuk** [envoyproxy/gateway#4166]
The latest code has some useful featues like `jsonPath` support in `EnvoyPatchPolicy`, is it possible to have a release of gateway and helm chart for 1.2 RC ?

**Comment by arkodg** [comment]
1.2.0-rc.1 should release in early October
you can use the bleeding edge release tag `v0.0.0-latest` until then to try out the latest unreleased features
https://gateway.envoyproxy.io/latest/install/install-helm/#install-with-helm
