### ISSUE TITLE
Envoy gateway runs oom

### ISSUE THREAD

**Issue by hemenghong** [envoyproxy/gateway#4181]
*Description*:
> The following is an envoy gateway flame diagram. Whether DeepCopy has problems?
<img width="2515" alt="0880c4c80710a29fdf24" src="https://github.com/user-attachments/assets/cfae0431-da04-41d0-8925-dcb073435e92">

*Repro steps*:
> After the EG runs for a period of time, the oom will appear

*Environment*:
>the latest version

**Comment by shawnh2** [comment]
may be releated to https://github.com/envoyproxy/gateway/issues/3698

**Comment by arkodg** [comment]
hey @hemenghong how many relevant resources (xRoutes, Gateway and related Secrets, Services etc) have been  applied ?
the default limits value is `1G`, please consider increasing it in the helm chart

**Comment by hemenghong** [comment]
> hey @hemenghong how many relevant resources (xRoutes, Gateway and related Secrets, Services etc) have been applied ? the default limits value is `1G`, please consider increasing it in the helm chart

eg limit mem has been set to 2G.  
httproute has 90 and node has 100 and secret has 900 and service has 270 and endpointslice has 270.

**Comment by arkodg** [comment]
closing this issue in favor of https://github.com/envoyproxy/gateway/issues/3860
