### ISSUE TITLE
Support host:port host headers

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#4197]
*Description*:

The HTTP RFC defines the `host` header in the following manner:
>  Host = uri-host [ ":" port ] ; Section 4

Users typically define a port-less hostname in their HTTPRoute resources. This can lead to failures for certain clients that set `<host>:<port>` as a `host` header value. Envoy docs suggest to either add `<host>:<port>` to the vhost's domain list or use the HCM `strip_[any|matching]_host_port` option. 

Currently, gateway-api does not allow the ":" character in hostnames, meaning EG users cannot follow the first recommendation on their own. Note that the `strip_matching_host_port` option is not relevant for EG, as the listener port is rarely the same as the external loadbalancer port (e.g. 10443 an 443 respectively). 

Envoy Gateway can mitigate this issue by:
1. support the `strip_any_host_port` in client traffic policy. 
2. generate the xds vhost with additional domains based on the following template <HTTPRoute.Hostname>:<Gateway.Listnener.Port>.

*Relevant Links*:
- https://www.rfc-editor.org/rfc/rfc9110.html#name-host-and-authority
- https://github.com/kubernetes-sigs/gateway-api/blob/92b1154d08d8368e42a803188b1b1df83dab1b2e/apis/v1/shared_types.go#L535. 
- https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_my_route_not_found
- https://github.com/envoyproxy/envoy/pull/10960
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-strip-matching-host-port
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-strip-any-host-port

**Comment by arkodg** [comment]
this has been solved with https://github.com/envoyproxy/gateway/issues/1368

**Comment by guydc** [comment]
> this has been solved with https://github.com/envoyproxy/gateway/issues/1368

My bad! Didn't search the code base correctly for that.

**Comment by guydc** [comment]
@arkodg  Actually, this was reverted a while back due to GW-API conformance issues: https://github.com/envoyproxy/gateway/pull/1512 

Perhaps this should be an opt-in under CTP to work around that.

**Comment by arkodg** [comment]
I believe the issue was fixed with https://github.com/envoyproxy/gateway/pull/1702

**Comment by guydc** [comment]
> I believe the issue was fixed with https://github.com/envoyproxy/gateway/pull/1702

Yes, you're right! We set `ignore_port_in_host_matching: true` for all routes by default.

**Comment by NickNaitik** [comment]
@guydc & @arkodg  - We have 100 of calling system,after doing this changes in envoy proxy, do we need to do regression test or just it will work as OR condition.
