### ISSUE TITLE
Support for enabling Request Response Size statistics

### ISSUE THREAD

**Issue by luvk1412** [envoyproxy/gateway#4234]
I want to have plots of [Request Response Size statistics](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html#request-response-size-statistics) in my eg setup which requires me to enable `request_response_sizes` in [config.cluster.v3.TrackClusterStats](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-trackclusterstats). 

In my knowledge there is currently no api in eg to do so(please correct me if am wrong) nor it is practically feasible to enable this using `EnvoyPatchPolicy` as we have lots of clusters and there is no way to select them all based on regex or something else, and adding for each cluster one by one is not feasible. 

Request to add support for this. `BackendTrafficPolicy` seems a good place to do so to me maybe ?

**Comment by arkodg** [comment]
could we made opt in using https://gateway.envoyproxy.io/docs/api/extension_types/#proxymetrics

**Comment by luvk1412** [comment]
somehow i have missed this api in eg. Thanks @arkodg for pointing this out. 
`ProxyMetrics` does seems like a good place to make this as opt in. When we add it is as field here, it would enable it for all clusters and users won't be able to turn it on for specific clusters right ? I am assuming same is the case for `enablePerEndpointStats` as of today as it is also part of [config.cluster.v3.TrackClusterStats](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-trackclusterstats) , and if mentioned true, it gets enabled for all clusters with no option to enable for specific clusters ? I am fine with this behaviour for at least my use case but just want to clarify.

Also I am a little confused by the `ProxyMetrics` api:
- what does `enableVirtualHostStats` corresponds to in envoy proxy config and what stats it exactly enables ?
- `sinks` are supposed to only have push based sinks ? was thinking why `prometheus` is not part of `sinks` but is outside at first level, hence this came to mind.
- Currently all fields are marked required in the documentation, i am thinking that might not be the case. It would be helpful if you could clarify what all is optional and what is not.


> [OFF TOPIC] 
A side note suggestion for documentation if it seems helpful to you guys: It would be helpful if we start documenting what corresponding field in envoy proxy, does a specific field in eg api corresponds to. This will be really helpful for people who want to deep dive a little or understand it a bit more. I personally have been reffering to eg code to find this out. Most recent example was where i wanted understand what HTTPRoute's timeouts corresponds to as there are two. If this seems reasonable and worth talking about, i can open a separate issue for this as well.

**Comment by luvk1412** [comment]
I can work on this, please assign to me.

Proposed solution:
Add `enableRequestResponseSizesStats` in `ProxyMetrics`, enabling which would enable `request_response_sizes` in [config.cluster.v3.TrackClusterStats](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-trackclusterstats) for all clusters. Please let me know if this looks good.

**Comment by zirain** [comment]
@luvk1412 thanks for picking up this.
