### ISSUE TITLE
Incorrect decoding command in developer guide

### ISSUE THREAD

**Issue by juwon8891** [envoyproxy/gateway#4240]
*Description*:
The developer guide documentation incorrectly states the decoding command. The example for decoding JWT tokens includes an unnecessary "-" in the base64 command. The correct command should omit this extra argument.

For more details, refer to the [developer guide](https://gateway.envoyproxy.io/docs/tasks/traffic/http-routing/).

AS-IS
```go
TOKEN=$(curl https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/with-different-claim.jwt -s) && echo "$TOKEN" | cut -d '.' -f2 - | base64 --decode -
```
TO-BE
```go
TOKEN=$(curl https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/jwt/with-different-claim.jwt -s) && echo "$TOKEN" | cut -d '.' -f2 | base64 --decode
```

**Comment by zirain** [comment]
cc @zhaohuabing
