### ISSUE TITLE
Document content is lagging behind

### ISSUE THREAD

**Issue by yuluo-yx** [envoyproxy/gateway#4242]
![image](https://github.com/user-attachments/assets/645c8b81-ae17-41d0-9419-7b5120f6ee0d)

https://github.com/envoyproxy/gateway/issues/280 is fixed

**Comment by zirain** [comment]
what is the version of the document you're referencing?

**Comment by arkodg** [comment]
this is looking fine on the current version
https://gateway.envoyproxy.io/docs/api/extension_types/#loglevel
