### ISSUE TITLE
Combine OIDC and external auth security policies

### ISSUE THREAD

**Issue by chessman** [envoyproxy/gateway#4275]
*Description*:
I'm trying  to combine OIDC and external auth security polices. The idea is to perform a check using an external service for a forwarded `Authorization` header received in the OAuth2 authentication.

I followed both guides:
https://gateway.envoyproxy.io/docs/tasks/security/oidc/
https://gateway.envoyproxy.io/docs/tasks/security/ext-auth/

They work separately, but when I enable both, the external auth takes precedence, resulting in a 403 error. Is it possible to change the order in which the policies are applied?

**Comment by arkodg** [comment]
@chessman you should be able to do this using the `filterOrder` feature https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/#customize-filter-order

**Comment by chessman** [comment]
@arkodg Thanks for the hint. It started to work with a changed order but there are issues:

* Both policies should have the same target, it doesn't work when one policy targets Gateway and another targets HTTPRoute.
* `headersToBackend` is ignored when OAuth2 filter is enabled before External Authorization.
* The configuration stops working if the OAuth2 filter is recreated (kubectl delete/apply). It is needed to recreated the ext_authz filter to make it work again.

This is what I did: https://gist.github.com/chessman/800b328c484f5ea9ff260537ec8a9ebb

**Comment by arkodg** [comment]
cc @zhaohuabing

**Comment by zhaohuabing** [comment]
> Both policies should have the same target, it doesn't work when one policy targets Gateway and another targets HTTPRoute.

@chessman  One Gateway/HTTPRoue can only be associated with one xPolciy. [If multiple xPolicies of the same type target one Gateway/HTTPRoute, the one with earlier creation time will be applied](https://www.zhaohuabing.com/post/2024-09-22-introducing-envoy-gateways-gateway-api-extensions-en/#policy-attachment-mechanism). 

Could you please try it again with a single SP?

**Comment by chessman** [comment]
@zhaohuabing You are right, I've just tested it, only one security policy can be attached. Isn't it a substantial limitation? Combining authentication and authorization might not be a widely used use case but what about CORS and auth?

**Comment by zhaohuabing** [comment]
> @zhaohuabing You are right, I've just tested it, only one security policy can be attached. Isn't it a substantial limitation? Combining authentication and authorization might not be a widely used use case but what about CORS and auth?

Can't you include these settings in one SP?

**Comment by chessman** [comment]
@zhaohuabing oh, I didn't realize that it is possible. I tried and now everything works. Thank you!
