### ISSUE TITLE
envoy-gateway support multi content-type

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#4283]
support core types by protobuf and envoy-gateway apis by json

**Comment by zirain** [comment]
does GatewayAPI support protobuf?

**Comment by qicz** [comment]
> does GatewayAPI support protobuf?

raised PR https://github.com/kubernetes-sigs/gateway-api/issues/3346

**Comment by zirain** [comment]
I didn't found too much docs for this, how can we achieve this?

**Comment by qicz** [comment]
https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources  @zirain

**Comment by qicz** [comment]
https://github.com/kubernetes/client-go/issues/76

**Comment by zirain** [comment]
> https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources @zirain

I'm asking how to make our api support it? does EG need any code change?

**Comment by qicz** [comment]
> > https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources @zirain
> 
> I'm asking how to make our api support it? does EG need any code change?

add `protobuf` tag in API struct

**Comment by zirain** [comment]
> > > https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources @zirain
> > 
> > 
> > I'm asking how to make our api support it? does EG need any code change?
> 
> add `protobuf` tag in API struct

can you share an existing project that do such things as demo.

**Comment by qicz** [comment]
> > > > https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources @zirain
> > > 
> > > 
> > > I'm asking how to make our api support it? does EG need any code change?
> > 
> > 
> > add `protobuf` tag in API struct
> 
> can you share an existing project that do such things as demo.

client-go and go-controller-panel have more places  using `protobuf`

https://github.com/kubernetes/apimachinery/blob/c98a9e22228d62689a77506ca0252d70f703958b/pkg/apis/meta/v1/types.go#L111-L152

https://github.com/envoyproxy/go-control-plane/blob/ec6977db26e1e30f8fc353a90442112a7f2b00d6/envoy/api/v2/listener.pb.go#L83-L127

**Comment by zirain** [comment]
go-control-plane generated from proto to go struct, so I thinks that's not valid example?

for client-go, I cannot find the tag<protobuf> you said.

**Comment by liorokman** [comment]
In order for the API server to be able to decode protobuf-encoded resources, the protobuf definitions need to be compiled into the API server. 

In Kubernetes, sending the API server protobuf encoded resources only works for core resources, and not for CRDs.

As written [here](https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources):

> Not all API resource types support Protobuf; specifically, Protobuf isn't available for resources that are defined as [CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) or are served via the [aggregation layer](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/).

**Comment by qicz** [comment]
> go-control-plane generated from proto to go struct, so I thinks that's not valid example?
> 
> for client-go, I cannot find the tag `protobuf` you said.

![image](https://github.com/user-attachments/assets/a0579d89-fa4d-4599-a0dc-0064f2653dec)

**Comment by qicz** [comment]
> In order for the API server to be able to decode protobuf-encoded resources, the protobuf definitions need to be compiled into the API server.
> 
> In Kubernetes, sending the API server protobuf encoded resources only works for core resources, and not for CRDs.
> 
> As written [here](https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources):
> 
> > Not all API resource types support Protobuf; specifically, Protobuf isn't available for resources that are defined as [CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) or are served via the [aggregation layer](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/).

yep, just core types support `protobuf`. https://github.com/kubernetes/kubernetes/issues/55541

we can support core types by `protobuf` and crd by `json` with two client instances.  Any other suggestions?

 cc @zirain

**Comment by zirain** [comment]
> we can support core types by protobuf and crd by json with two client instances

sgtm

**Comment by liorokman** [comment]
> 
> we can support core types by `protobuf` and crd by `json` with two client instances. Any other suggestions?
> 
> cc @zirain

`Controller-utils` based clients already uses protobuf for types that support it. 

See https://github.com/kubernetes-sigs/controller-runtime/pull/1149

**Comment by qicz** [comment]
> > we can support core types by `protobuf` and crd by `json` with two client instances. Any other suggestions?
> > cc @zirain
> 
> `Controller-runtime` based clients already uses protobuf for types that support it.
> 
> See [kubernetes-sigs/controller-runtime#1149](https://github.com/kubernetes-sigs/controller-runtime/pull/1149)

Great, we should refactor clients using the informer.

**Comment by liorokman** [comment]
> Great, we should refactor clients using the informer. but the `controller` will refactor too, I think that is impossible, there are too many dependencies.

I can't find places in the codebase where a non `controller-runtime` client is used. Can you provide a link to code that needs to be fixed? The code in `internal/provider/kubernetes` uses controller-runtime to get clients to the provider, as far as I can tell.

**Comment by qicz** [comment]
> > Great, we should refactor clients using the informer. but the `controller` will refactor too, I think that is impossible, there are too many dependencies.
> 
> I can't find places in the codebase where a non `controller-runtime` client is used. Can you provide a link to code that needs to be fixed? The code in `internal/provider/kubernetes` uses controller-runtime to get clients to the provider, as far as I can tell.

yep, the `internal/provider/kubernetes` uses the `controller-runtime`,  for `protobuf` needs call `createRestConfig` and this func invoke in `RESTClientForGVK`.

**Comment by qicz** [comment]
already support multi content-type 
![image](https://github.com/user-attachments/assets/36f040e2-2349-4284-8d3c-4b7e211dcc00)
