### ISSUE TITLE
Dockerhub OCI issues

### ISSUE THREAD

**Issue by mfacenet** [envoyproxy/gateway#4289]
*Description*:
When following the guide to install via helm (slightly modified to run as a helm template command) I get the following error
Error: GET "https://registry-1.docker.io/v2/envoyproxy/gateway-helm/tags/list": unable to retrieve credentials
I believe this to be related to the ongoing issues that dockerhub is experiencing with rate limits and authentication, however, it could also be related to changes that docker is doing to the dockerhub api's (noted other errors when it comes to our mirroring process for the past 3 days).

*Repro steps*:
helm template eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system

*Environment*:
n/a

*Logs*:
n/a

**Comment by mfacenet** [comment]
As a follow on, I'd also like to see the chart in artifcathub.io

**Comment by arkodg** [comment]
@mfacenet I tried
```
helm template eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system --version v1.1.1
```

and I'm not seeing any issues

If you are being rate limited by Docker Hub, I suggest taking necessary approaches to avoid it like moving the image to a private registry so it doesnt disrupt production or pulling using an account that doesnt get rate limited by Docker Hub

**Comment by mfacenet** [comment]
> @mfacenet I tried
> 
> ```
> helm template eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system --version v1.1.1
> ```
> 
> and I'm not seeing any issues
> 
> If you are being rate limited by Docker Hub, I suggest taking necessary approaches to avoid it like moving the image to a private registry so it doesnt disrupt production or pulling using an account that doesnt get rate limited by Docker Hub

not being rate limited, tried this from a personal machine (not vpn'd in to the corp network) as well as a machine in the corporate network and also had another dev try this on their machine, the error seems to be consistent, maybe it's a regional issue?

**Comment by mfacenet** [comment]
Should also mention that while my machine is docker authed (docker login) the corp machine wasn't

**Comment by mfacenet** [comment]
> helm template eg oci://docker.io/envoyproxy/gateway-helm -n envoy-gateway-system --version v1.1.1

ahh I see, you had to supply the tag, that's not really ideal, this is how we check for upgrades (render templates and if there's a delta they get merged after verification) requiring --version seems to go counter to the ideals that helm offers also with the reliance on docker-credential-desktop helper (to auth to the registry) that limits the ability to deploy this anywhere that isn't running docker "docker" i.e. helm on a machine running containerd
