### ISSUE TITLE
Initial Config Manager Design and Implementation

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#43]
The Config Manager is responsible for instantiating and managing the lifecycle of the various system components
in Envoy Gateway based on the Envoy Gateway Bootstrap spec

**Comment by danehans** [comment]
@arkodg I assigned this issue to you based on the 5/24/22 community meeting [notes](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing). Please unassign yourself if that's not the case.

**Comment by danehans** [comment]
Although the initial Config Manager will focus on k8s, it should be designed to support add'l config sources, xref: https://github.com/envoyproxy/gateway/issues/30

**Comment by danehans** [comment]
Fixed by https://github.com/envoyproxy/gateway/pull/146

**Comment by danehans** [comment]
Reopened by https://github.com/envoyproxy/gateway/pull/197

**Comment by danehans** [comment]
@arkodg can this issue be closed?

**Comment by arkodg** [comment]
sure lets close, we seem to be doing fine w/o any sophisticated config manager atm, lets reopen if the need arises.
