### ISSUE TITLE
x-envoy-upstream-service-time is null for 200 response code

### ISSUE THREAD

**Issue by amulya-mallidi** [envoyproxy/gateway#4378]
*Description*:
x-envoy-upstream-service-time is null for 200 response code

We are using the same format for proxy access logs.
Observed https://gateway.envoyproxy.io/latest/tasks/observability/proxy-accesslog/#default-access-log is null for cases where response code is 200
Whereas, when the response is 401 UAEX - (ext_authz_denied), I see the value for this field

https://gateway.envoyproxy.io/latest/tasks/observability/proxy-accesslog/#default-access-log

**Comment by arkodg** [comment]
Envoy Gateway has `x-*` headers disabled by default, and these can be enabled using the [enableEnvoyHeaders field](https://gateway.envoyproxy.io/docs/api/extension_types/#headersettings) in [ClientTrafficPolicy](https://gateway.envoyproxy.io/docs/tasks/traffic/client-traffic-policy/)

Closing this issue for now, feel free to reopen if you hit any issues while configuring this field
