### ISSUE TITLE
Hash the Names of Managed Infra Resources

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#441]
EG currently generates names of managed envoy infra. The names are generally constructed of gateway namespace, gateway name, etc. The names can be long and potentially exceed the allowed length (63 chars) of a Kube name. Instead, and similar to Kube, the name should be generated from a hash.

xref: https://github.com/envoyproxy/gateway/pull/404

**Comment by danehans** [comment]
Added `bug` label due to #434.

**Comment by danehans** [comment]
When using hashed names for managed resources, users will need to use ` --selector` to correlate managed resources to a Gateway. For example:
```

$ kubectl get deploy -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gateway-name=eg,gateway.envoyproxy.io/owning-gateway-namespace=default
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
envoy-default-eg   1/1     1            1           2m14s
```

It might make debugability a bit easier if we had one label that was `namespace/name`. @arkodg @skriss @LukeShu @youngnick thoughts?

**Comment by danehans** [comment]
A similar approach will be needed for the ports of the managed Envoy serivce.

**Comment by arkodg** [comment]
I prefer if we used a hybrid approach in naming - `envoy-<40-50 char namespaced name>-<short-hash>` to improve debug speed.

**Comment by AliceProxy** [comment]
I'll take this one on. Should have some bandwidth in the coming week.
