### ISSUE TITLE
on startup, don't start translation until all resources have been loaded

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#448]
xref #447
xref #413
xref https://github.com/telepresenceio/watchable/pull/6 

On startup/restart, EG should not start translating/sending xDS traffic until all resources have been loaded, to avoid issues with incomplete inputs.

**Comment by danehans** [comment]
Note that this fix is needed to ensure `lastTransitionTime` is not updated when EG is restarted.

**Comment by danehans** [comment]
This issue should be resolved when #413 is fixed.
