### ISSUE TITLE
Reenable Provider Resource Synchronization

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#451]
https://github.com/envoyproxy/gateway/pull/447 removed provider resource sync due. When https://github.com/envoyproxy/gateway/issues/413 is resolved, the sync should be reenabled on the single provider resource map that contains all provider resources, i.e. Gateway, Service, etc..

**Comment by arkodg** [comment]
dup of https://github.com/envoyproxy/gateway/issues/448

**Comment by danehans** [comment]
Closing since this is a dupe.
