### ISSUE TITLE
Envoy Gateway throws 502 if we access it through AWS ALB and works well with NLB

### ISSUE THREAD

**Issue by meektechie** [envoyproxy/gateway#4520]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

I am trying to use AWS ALB on top of envoy-gateway to utilize WAF facility. I did the configuration, while i am testing the DNS request, it throws "502 Bad Gateway" as console output and the log also not having any parameters.

{"start_time":"2024-10-25T01:42:05.023Z","method":"-","x-envoy-origin-path":"-","protocol":"-","response_code":"0","response_flags":"NR","response_code_details":"filter_chain_not_found","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"0","duration":"9","x-envoy-upstream-service-time":"-","x-forwarded-for":"-","user-agent":"-","x-request-id":"-",":authority":"-","upstream_host":"-","upstream_cluster":"-","upstream_local_address":"-","downstream_local_address":"200.0.9.101:10443","downstream_remote_address":"147.185.132.175:65480","requested_server_name":"-","route_name":"-"}

If i try with an NLB, the same request successfully served

"start_time":"2024-10-25T01:32:21.260Z","method":"GET","x-envoy-origin-path":"/","protocol":"HTTP/2","response_code":"200","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"615","duration":"2","x-envoy-upstream-service-time":"-","x-forwarded-for":"18.60.116.227","user-agent":"curl/8.6.0","x-request-id":"77884405-8be7-48a4-bf29-590940440e30",":authority":"ansible-nginx.example.dev","upstream_host":"200.0.6.13:80","upstream_cluster":"httproute/route/dvdemo-http/rule/0","upstream_local_address":"200.0.9.101:43774","downstream_local_address":"200.0.9.101:10443","downstream_remote_address":"18.60.116.227:17930","requested_server_name":"ansible-nginx.example.dev","route_name":"httproute/route/dvdemo-http/rule/0/match/0/ansible-nginx_example_dev"}

I am sure i am missing something. Please gimme some guidelines.

I have tried with X-Forwarded-For header ,Preserve host header,Client port preservation on loadbalancer end and also enabled stickiness in TG as well but it is not working.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
1. Deploy gateway, gatewayclass, envoyproxy using yaml with envoy-gateway helm deployment
2. Create an ALB with ALB ingress controller yaml file and map the envoy-gateway-service with 443 port
3. Map the ALB with the DNS and query

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.
nonprod
*Logs*:
>Include the access logs and the Envoy logs.

ALB AccessLog:
"arn:aws:acm:ap-south-1::certificate/7d825737-5d6f-4cde-9149-dac687624ee8" 1 2024-10-24T10:49:26.282000Z "forward" "-" "-" "200.0.10.88:10443" "-" "-" "-" TID_eaf685a41fa1ca4a8eb2cde621d5c845
h2 2024-10-24T10:49:26.909938Z app/k8s-gateway-testpubl-15d83068bc/5a53f53bcbc22e0c 18.60.210.19:16111 200.0.10.88:10443 -1 -1 -1 502 - 40 192 "GET https://ansible-nginx.example.dev:443/ HTTP/2.0" "curl/8.6.0" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:ap-south-1::targetgroup/k8s-gateway-envoygat-2b0e8bec27/7b41e2689fcce7ed "Root=1-671a2636-7144c63c697b9a7d659274a3" "ansible-nginx.example.dev" "arn:aws:acm:ap-south-1::certificate/7d825737-5d6f-4cde-9149-dac687624ee8" 1 2024-10-24T10:49:26.906000Z "forward" "-" "-" "200.0.10.88:10443" "-" "-" "-" TID_b29dd1a65751ee408837dd8be2c3112f

Envoy gateway log:

{"start_time":"2024-10-25T01:32:26.653Z","method":"-","x-envoy-origin-path":"-","protocol":"-","response_code":"0","response_flags":"NR","response_code_details":"filter_chain_not_found","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"0","duration":"0","x-envoy-upstream-service-time":"-","x-forwarded-for":"-","user-agent":"-","x-request-id":"-",":authority":"-","upstream_host":"-","upstream_cluster":"-","upstream_local_address":"-","downstream_local_address":"200.0.9.101:10443","downstream_remote_address":"171.6.0.17:3658","requested_server_name":"-","route_name":"-"}

**Comment by arkodg** [comment]
can you share the Gateway API config as well as the config in ALB ? 
From this error 'filter_chain_not_found', it looks like there's some hostname mismatch

**Comment by meektechie** [comment]
Thanks for the immediate response.

---
# Source: api-gateway/templates/envoyProxy.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    cert-manager.io/cluster-issuer: letsencrypt-route53
spec:
  gatewayClassName: public-gatewayclass
  listeners:
    - name: https
      hostname: "*.example.dev"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: "mygateway-cert"
            namespace: gateway
---
# Source: api-gateway/templates/envoyProxy.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: public-gatewayclass
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: public-proxy-config
    namespace: gateway
---
# Source: api-gateway/templates/envoyProxy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata: 
  name: public-proxy-config
  namespace: gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 400Mi
      envoyHpa:
        minReplicas: 1
        maxReplicas: 3
        metrics:
          - resource:
              name: cpu
              target:
                averageUtilization: 80
                type: Utilization
            type: Resource
      envoyService:
        externalTrafficPolicy: Local
        type: ClusterIP

---
#ALB config

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1::certificate/7d825737-5d6f-4cde-9149-dac687624ee8
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-path: /ready
    alb.ingress.kubernetes.io/healthcheck-port: "19001"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300,deletion_protection.enabled=false,routing.http2.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=envoy-s3-alb-logs-delete-later,access_logs.s3.prefix=public,routing.http.preserve_host_header.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-09c476fe7b1c23c49
    alb.ingress.kubernetes.io/subnets: subnet-024233077d6d07e5d,subnet-0ac487913e09a7712,subnet-0d7f217616e2e4578
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: Environment=test,Name=test-public-ingress
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  labels:
    app: test-public-restricted-ingress
  name: test-public-restricted-ingress
  namespace: gateway
spec:
  ingressClassName: alb
  rules:
  - host: '*.example.dev'
    http:
      paths:
      - backend:
          service:
            name: envoy-gateway-public-gateway-dd3ef806
            port:
              number: 443
        path: /*
        pathType: ImplementationSpecific

**Comment by arkodg** [comment]
are you trying to do TLS passthrough or (TLS termination + HTTPS) with the ALB ?

**Comment by meektechie** [comment]
Yes TLS Passthrough

**Comment by meektechie** [comment]
Hi Arkodg/ All, shall i get some help over-here. It seems the TLS terminated before reaching Envoy Pods

**Comment by arkodg** [comment]
@meektechie this issue seems related to the ALB configuration - you're trying to enable TLS Passthrough but instead TLS Termination is being implemented, my suggestion would be to ask for help in the ALB related GH repos and slack channels

**Comment by meektechie** [comment]
Hi Arkodg, I wanted to know if anybody using AWS ALB with envoy gateway. If yes, then envoy should run on 443 or 80. ?

**Comment by meektechie** [comment]
@arkodg  This has been resolved after removing `hostname` in gateway. Somehow the the ALB didn't forwarding SNI information to the gateway since the request has been dropped and it was responding "response_code_details":"filter_chain_not_found". Is it mandatory to set up "hostname"?

  listeners:
    - name: https
      hostname: {{ .service.hostname | quote }}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All

**Comment by arkodg** [comment]
@meektechie glad you got it to work
Its not mandatory to set up hostname, a `nil` or empty field is equivalent to `*` / all hostnames, but note that Envoy gateway makes sure the cert provided in the certRefs match the hostname provided in the listener else validation will fail and it will be surfaced as in the resource status

**Comment by samos667** [comment]
Same behavior with [Hetzner cloud LB](https://docs.hetzner.com/cloud/load-balancers/) with HTTPS traffic.

On client side I get:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection`

On envoy proxy:
`{"start_time":"2024-11-10T13:46:45.959Z","method":"-","x-envoy-origin-path":"-","protocol":"-","response_code":"0","response_flags":"NR","response_code_details":"filter_chain_not_found","connection_termination_details":"-","upstream_transport_failure_reason":"-","bytes_received":"0","bytes_sent":"0","duration":"1","x-envoy-upstream-service-time":"-","x-forwarded-for":"-","user-agent":"-","x-request-id":"-",":authority":"-","upstream_host":"-","upstream_cluster":"-","upstream_local_address":"-","downstream_local_address":"<LB_IP>:443","downstream_remote_address":"<client_public_IP>:26895","requested_server_name":"-","route_name":"-"}`

Proxy protocol is enable in LB and ClientTrafficPolicy side.

So if I understand correctly, this is a cloud provider "issue", at least the solution is in their hands, right ?

Unset hostname on listeners fixes this, but breaks the automatic certificate request when deploying the gateway.

**Comment by meektechie** [comment]
Yes
