### ISSUE TITLE
labels on Gateway-owned resources (Envoy service, deployment) should include namespace

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#453]
Currently we set a single label on any resources owned by a Gateway (e.g. the envoy service and deployment) that contains the Gateway's name. This is going to be problematic if you have Gateways in two different namespaces that have the same name. We should either put namespace/name in the label value, or add a second label containing the namespace, to allow differentiating.

A quick look indicates that maybe there's a similar problem with generating names for infra resources, but this needs further investigation.

xref #452 (fixing 452 probably requires addressing this issue as well since otherwise we don't know what the namespace of the Gateway is to enqueue a reconcile request for).

**Comment by skriss** [comment]
I'll work on this and https://github.com/envoyproxy/gateway/issues/452 together.

**Comment by danehans** [comment]
Agree to have a separate label to ID the owning Gateway namespace.
