### ISSUE TITLE
Add route-rule name to xDS route metadata

### ISSUE THREAD

**Issue by Ido-Itz** [envoyproxy/gateway#4551]
*Description*:
With the recent GatewayAPI V1.2 adoption, route rules are now named (https://github.com/kubernetes-sigs/gateway-api/pull/2985).

Currently when Envoy Gateway translates route rules to IR structs (and later to xDS resources), the name of the original HTTP route rule is not persisted to the route's metadata.

It is useful to have this information for runtime awareness of which GatewayAPI route was matched for each request (e.g. in access logging).

This can be achieved by setting the SectionName field on the route resource's metadata, which is currently left empty.

**Comment by Ido-Itz** [comment]
I would be glad to work on this, please assign me if possible

**Comment by arkodg** [comment]
+1 cc @guydc
