### ISSUE TITLE
IPv6 known issues

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#4572]
- [x] FluentBit cannot start https://github.com/envoyproxy/gateway/pull/4525
- [x] Listen on `0.0.0.0` stead of `::1` in IPv6 first cluster https://github.com/envoyproxy/gateway/pull/4573
- [x] xds_cluster dns faield to reslove https://github.com/envoyproxy/gateway/pull/4691
- [x] e2e pod like `grpc-ext-auth` failed to start, may https://github.com/envoyproxy/gateway/issues/3866 help. https://github.com/envoyproxy/gateway/pull/4576
- [x] RateLimit cannot start on IPv6 https://github.com/envoyproxy/ratelimit/pull/774
- [x] `net.SplitHostPort` return `Failed to parse host "[fc00:f853:ccd:e793::ce:80]": address [fc00:f853:ccd:e793::ce:80]: missing port in address`, because `// A literal IPv6 address in hostport must be enclosed in square
// brackets, as in "[::1]:80", "[::1%lo0]:80"`.  https://github.com/envoyproxy/gateway/issues/4597
- [x] https://github.com/envoyproxy/gateway/issues/4761

**Comment by zirain** [comment]
cc @arkodg @juwon8891

**Comment by zirain** [comment]
Another issue:
```console
kubectl logs -n gateway-conformance-infra setup-keycloak-z2rrm
Defaulted container "setup-keycloak" out of: setup-keycloak, wait-for-keycloak (init)
+ /opt/keycloak/bin/kcadm.sh create users -s username=oidcuser -s enabled=true --server http://keycloak --realm master --user admin --password admin
Logging into http://keycloak as user admin of realm master
HTTPS required [invalid_request]
```

cc @zhaohuabing

**Comment by zhaohuabing** [comment]
> Another issue:
> 
> ```
> kubectl logs -n gateway-conformance-infra setup-keycloak-z2rrm
> Defaulted container "setup-keycloak" out of: setup-keycloak, wait-for-keycloak (init)
> + /opt/keycloak/bin/kcadm.sh create users -s username=oidcuser -s enabled=true --server http://keycloak --realm master --user admin --password admin
> Logging into http://keycloak as user admin of realm master
> HTTPS required [invalid_request]
> ```
> 
> cc @zhaohuabing

Fixed in https://github.com/envoyproxy/gateway/pull/4601
