### ISSUE TITLE
Gateway Ready Condition Fluctuates During Conformance Test Run

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#459]
The Gateway 'Ready" condition fluctuates during conformance test runs when it should consistently report `true`.

Reproducer:
- Create a Kube cluster.
- Install EG.
- Run conformance tests.
- Watch the Gateways under test. You will see the `Ready` status condition fluctuate between true/false and status address come and go. The Envoy Deployment is consistently available so the `Ready` condition should not be changing.

**Comment by danehans** [comment]
cc: @arkodg

**Comment by arkodg** [comment]
would like to implement https://github.com/envoyproxy/gateway/issues/407 and see if it helps or not
