### ISSUE TITLE
Cluster_V4_ONLY cause `no healthy upstream` on IPv6 first cluster

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#4605]
xref: https://github.com/envoyproxy/gateway/issues/4572

https://github.com/envoyproxy/gateway/blob/05817fcc42d803caba384d54eee6d9f0c562c1ef/internal/xds/translator/cluster.go#L87

should we change to auto by default?

cc @arkodg @juwon8891

**Comment by juwon8891** [comment]
I think auto should be default when dual stack. And in the ipv6 only environment, ipv6_only

**Comment by arkodg** [comment]
yah + to `AUTO` / `V6_PREFERRED`

**Comment by arkodg** [comment]
@juwon8891 can you help with this one ?

**Comment by zirain** [comment]
> yah + to `AUTO` / `V6_PREFERRED`

Look like `AUTO` didn't work on IPv6 first cluster.

**Comment by juwon8891** [comment]
Can we get the ip address type dynamically when we are not dual stack?

**Comment by zirain** [comment]
```golang
        dnsLookupFamily := clusterv3.Cluster_V4_ONLY
	if net.IsIPv6FirstPod() {
		dnsLookupFamily = clusterv3.Cluster_V6_ONLY
	}
```
