### ISSUE TITLE
The download instructions for Kubectl point to a file for 1.1.3 that doesn’t exist

### ISSUE THREAD

**Issue by softprops** [envoyproxy/gateway#4614]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Install instructions listed on the website for kubectl do not work

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Go to https://gateway.envoyproxy.io/docs/install/install-yaml/#install-with-yaml
Run Kubectl command, currently `kubectl apply --server-side -f https://github.com/envoyproxy/gateway/releases/download/v1.1.3/install.yaml`
Get 404 error

I believe the issue is that there is no release published for 1.1.3 https://github.com/envoyproxy/gateway/releases

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by arkodg** [comment]
hey @softprops raised https://github.com/envoyproxy/gateway/pull/4615 to fix this
