### ISSUE TITLE
HTTP 504 & BackendTrafficPolicy

### ISSUE THREAD

**Issue by ovaldi** [envoyproxy/gateway#4667]
After upgrading to v1.2.0, I got some HTTP 504 errors.

Here is my `BackendTrafficPolicy`:

<img width="475" alt="image" src="https://github.com/user-attachments/assets/02d8608d-4406-4476-8dc3-a10bd790c619">

I noticed that v1.2.0 added a new parameter `requestTimeout`, is it related to this?

**Comment by ovaldi** [comment]
Just downgraded back to v1.1.2, everything works well.

**Comment by arkodg** [comment]
hey @ovaldi do you have a `requestTImeout` set in the `HTTPRoute` ?

**Comment by ovaldi** [comment]
> hey @ovaldi do you have a `requestTImeout` set in the `HTTPRoute` ?

@arkodg  No, I didn't set `timeout` int the `HTTPRoute`

Here is my `HTTPRoute`:

<img width="363" alt="image" src="https://github.com/user-attachments/assets/d50524c1-d5e2-4d5e-b5b8-7c23c5a39d46">

**Comment by arkodg** [comment]
Can you try setting the requestTimeout to a higher value and see if helps ?

**Comment by ovaldi** [comment]
After upgrading to v1.2.1, it seems works well for now.
