### ISSUE TITLE
Does envoy gateway support ingress?

### ISSUE THREAD

**Issue by duxin40** [envoyproxy/gateway#4670]
Does envoy gateway support ingress?

**Comment by zirain** [comment]
EG didn't support and have no plan to support it for now.

**Comment by arkodg** [comment]
yeah as @zirain mentioned, the current plan is not support Ingress which has been deprecated in favor of Gateway API

if you're migrating off Ingress to Envoy Gateway (that supports Gateway API), this doc https://gateway.envoyproxy.io/docs/install/migrating-to-envoy/ will be helpful
