### ISSUE TITLE
Support simple TLS termination

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#471]
*Description*:
Add support for HTTPS/TLS termination
Examples shown here https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#examples

Looks like most of the work is already done in gateway-api translator https://github.com/envoyproxy/gateway/blob/8e1e9815a880236d49df1d21735f1a41fbb9b3d6/internal/gatewayapi/translator.go#L52 and the provider simply needs to reconcile secrets and pass it over.

**Comment by skriss** [comment]
Oof you're right, I was thinking that this was already working end-to-end but yeah the provider is not passing secrets.

**Comment by arkodg** [comment]
this would have been an easy win for 0.2.0 . This can be considered a bug and added to the 0.2.0 milestone cc @danehans

**Comment by arkodg** [comment]
the TLS termination conformance tests should be incorporated once they are added upstream which is being tracked with https://github.com/kubernetes-sigs/gateway-api/issues/1104
