### ISSUE TITLE
Inconsistent default value in ClientTrafficPolicy

### ISSUE THREAD

**Issue by czczycz** [envoyproxy/gateway#4713]
I find two configurations in HCM are different from Envoy's default values. Both set by ClientTrafficPolicy.

### path_with_escaped_slashes_action
The default value from Envoy is `KeepUnchanged`, but the default value in EG is `UnescapeAndRedirect`
Refer to [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#envoy-v3-api-enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-pathwithescapedslashesaction)

### headers_with_underscores_action
The default value from Envoy is `Allow`, but the default value in EG is `RejectRequest`
Refer to [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-enum-config-core-v3-httpprotocoloptions-headerswithunderscoresaction)

**Comment by arkodg** [comment]
these are the recommended edge settings from the envoy proxy documentation, check out https://github.com/envoyproxy/gateway/issues/1048

to change these values, you can configure these in ClientTrafficPolicy https://gateway.envoyproxy.io/docs/api/extension_types/#pathsettings
