### ISSUE TITLE
envoygateway-Owners label propagation to the underline resources (service, deployment)

### ISSUE THREAD

**Issue by meektechie** [envoyproxy/gateway#4741]
*Description*:
I am trying to deploy the envoy gateway custom resources (envoyproxy, gateway, gateway class) via argoCD and it has been deployed but the underline resources (deployment, pods, service) created by these CR are not visible in ArgoCD. To have a better visibility we want the label propagation to the underline resources as well. Kindly suggest if we already have such facility.

>Describe the desired behavior, what scenario it enables and how it
would be used.
It will be use to track the underline resource created by the CustomResources (envoyproxy, gateway)
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
This has already discussed in #3051

**Comment by arkodg** [comment]
hey @meektechie, closing this one in favor of #3051, lets collaborate on that issue
