### ISSUE TITLE
Add `.` to rc pre-release tags

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#477]
*Description*:
Based on https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions pre release tags should be tagged as `major.minor.patch-rc.X` instead of `major.minor.patch-rcX`
Related https://envoyproxy.slack.com/archives/C03E6NHLESV/p1662052422742649

**Comment by Xunzhuo** [comment]
I am thinking this is a standard of release naming, why cover this in ci area? If the release manager tag like v0.3.0-rc.1, I think the generated image and git tag will follow this way.

Need more context of this issue:) cc @arkodg

**Comment by arkodg** [comment]
good point, can be closed since this in incorporated in the release doc
https://github.com/envoyproxy/gateway/blob/main/docs/dev/releasing.md#creating-a-release-candidate
