### ISSUE TITLE
Simplify Kustomization Setup

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#479]
With https://github.com/envoyproxy/gateway/pull/478, EG will have 3 different kustomization files. Look at simplifying the customization setup.

**Comment by skriss** [comment]
My 2c: let's consider whether we even need kustomize. I'm not sure how much value it's adding relative to the complexity it adds.

**Comment by Xunzhuo** [comment]
I think this is related to https://github.com/envoyproxy/gateway/pull/651. If we support helm, we do not need this I think.

**Comment by Xunzhuo** [comment]
cc @danehans

**Comment by arkodg** [comment]
thinking out loud, we might not need kustomize but it would be good to continue uploading the complete `install` yaml as a GH artifcat

**Comment by Xunzhuo** [comment]
> thinking out loud, we might not need kustomize but it would be good to continue uploading the complete default `install` yaml as a GH artifact

This can be done in helm too, just use helm template to generate a install.yaml similar to the previous aritifact. @arkodg

**Comment by Xunzhuo** [comment]
If you guys think it is Okay, I can work on helm support in v0.3.0-rc1 and  remove the previous kustomize way.

**Comment by arkodg** [comment]
@Xunzhuo would prefer if this was a stretch goal instead :)

**Comment by Xunzhuo** [comment]
Agree:)
