### ISSUE TITLE
OIDC "Supported Claims" for SecurityPolicy

### ISSUE THREAD

**Issue by cccsss01** [envoyproxy/gateway#4818]
*Description*:
>I'd like to be able to set my groups, to a supported_claim within the security Policy

[optional *Relevant Links*:]
[>Any extra documentation required to understand the issue.](https://gateway.envoyproxy.io/v1.2/tasks/security/oidc/)

Our SAS OIDC provider doesn't not leverage groups in the traditional sense, but provides, groups via a specific supported claim

setting group to a supported claim would be ideal

Then i'd also like to authN/Z per httproute per returned groups.

Similiar to ingress-nginx lua capabilities.

**Comment by zhaohuabing** [comment]
@cccsss01 As we discussed in slack, EG can utilize any claims extracted from the JWT token for authz. Do you see anything else missing in EG OIDC implementation that might be a blocker for your use case?

**Comment by zhaohuabing** [comment]
Closing this issue as EG can utilize any claims extracted from the JWT token for authz. Feel free to reopen it if you have further questions. @cccsss01
