### ISSUE TITLE
Define a default memory limit for shutdown-manager

### ISSUE THREAD

**Issue by ryanhristovski** [envoyproxy/gateway#4882]
*Description*:
Currently the shutdown-manager sidecar does not have a default memory limit set, this can lead to uncontrolled memory usage, potentially causing node instability or OOMKilled errors. It's best practice to set the memory request equal to the memory limit to ensure consistent resource allocation and avoid unexpected scheduling issues.

I haven't yet benchmarked shutdown-managers memory usage to have a good idea of what to set the request/limit to if anyone has any suggestions.

**Comment by arkodg** [comment]
requests == limit sgtm, wdyt @envoyproxy/gateway-maintainers @envoyproxy/gateway-reviewers

**Comment by zhaohuabing** [comment]
+1 sgtm. The memory usage of the shutdown-manager shouldn't increase over time.
