### ISSUE TITLE
Fix: OSV GHSA-w32m-9786-jp63

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#4951]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

ref: https://osv.dev/vulnerability/GHSA-w32m-9786-jp63
ref: https://osv.dev/vulnerability/GO-2024-3333

*Logs*:
>Include the access logs and the Envoy logs.

https://github.com/envoyproxy/gateway/actions/runs/12408718248/job/34641125634?pr=4949

**Comment by zirain** [comment]
https://github.com/envoyproxy/gateway/pull/4970
