### ISSUE TITLE
Move older Markdown docs into RST docs

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/gateway#497]
All of these need to be dealt with, which might mean translating to RST, moving into a different location, or deleting.

- [ ] `docs/design/CONFIG_API.md`
- [ ] `docs/design/SYSTEM_DESIGN.md`
- [ ] `docs/design/gatewayapi-translator.md`
- [ ] `docs/design/watching.md`

**Comment by danehans** [comment]
Moving the docs to .rst is no longer needed now the .md is supported.
