### ISSUE TITLE
Make `envoy-gateway --version` properly user-facing

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/gateway#498]
After discussion, we've agreed that `envoy-gateway --version` should be a real, user-facing thing. It, uh, needs some work to get there:

- [ ] Include its own version number
- [ ] Use `--version` as a switch (instead of the `version` command), as is the Cobra Way™
- [ ] Figure out Cobra's templating so it's still nice and neat and works with the switch for env-var output

**Comment by danehans** [comment]
Moved to 0.3.0-rc.1 so the group can further discuss implementation details.
