### ISSUE TITLE
Consider RST versions of GOALS.md, etc.

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/gateway#499]
We should decide whether or not to have RST-doc versions of GOALS.md, CONTRIBUTING.md, etc., so that people reading the docs can see them there. We could also just link out to the Markdown versions (which is what the docs currently do), though that's a bit less friendly.

**NOTE**: in any case, we should be **very** careful to separate developer docs from user docs.

**Comment by arkodg** [comment]
markdown docs can be published now with https://github.com/envoyproxy/gateway/pull/571
keeping this issue open to figure out how to separate dev docs from user ones

**Comment by Xunzhuo** [comment]
Hi, can you explain the meaning of dev docs here? The docs under docs/dev? If so, why do we need to separate them, I think user or developer can read them too, need some context on this:)

**Comment by arkodg** [comment]
@Xunzhuo the goal is to get the user to experience EG w/o bogging them down with inner details.
Right now navigation is flat for https://gateway.envoyproxy.io/ , we need to make it tiered (user/examples as well as dev/design) and maybe even default to user

**Comment by Xunzhuo** [comment]
Yep, I see. Thanks for the comments.

**Comment by danehans** [comment]
Now that .md support was added, we just need to link GOALS.md to the Sphinx docs generator.

**Comment by haq204** [comment]
https://github.com/envoyproxy/gateway/pull/932 adds `GOALS.md` and `CODEOWNERS.md` to the sphinx docs directory as symlinks

**Comment by haq204** [comment]
I also agree that there should be clearer separation between dev and user docs. If no one has claim it yet, I can work on a proposal on how to best structure the docs.

**Comment by danehans** [comment]
@haq204 thanks for PR #932.

> If no one has claim it yet, I can work on a proposal on how to best structure the docs.
@haq204 feel free to create a separate issue and a PR to fix.
