### ISSUE TITLE
Define Initial APIs

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#50]
https://github.com/envoyproxy/gateway/pull/16 specifies the need to define APIs, e.g. bootstrap config. To begin developing these APIs, the community should agree on:

1. How these APIs will defined, protos vs Go types. [Emissary](https://github.com/emissary-ingress/emissary) uses protos to define [API types](https://github.com/emissary-ingress/emissary/blob/master/api/agent/director.proto) whereas [Contour](https://github.com/projectcontour/contour) uses Go types.
2. How these APIs will documented.
3. How these APIs will be maintained.
4. Others?

**Comment by danehans** [comment]
@LukeShu per the 5/24/22 meeting notes, please document the rationale for using kube-builder/controller-gen over protobuf.

**Comment by LukeShu** [comment]
Sorry, I didn't get to this on Wednesday, and have been on vacation since then. Will get that documentation up soon.

**Comment by danehans** [comment]
https://github.com/envoyproxy/gateway/issues/51 defines the initial config APIs for control and data planes.
