### ISSUE TITLE
docs: User-facing tutorial examples

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/gateway#501]
We should probably follow https://gateway-api.sigs.k8s.io/guides/getting-started/ here:

- [x] [Simple Gateway](https://gateway-api.sigs.k8s.io/guides/simple-gateway/)
- [x] [HTTP Routing](https://gateway-api.sigs.k8s.io/guides/http-routing/)
- [x] [HTTP Redirects](https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/), but note that we think that rewrites aren't working yet
- [x] [HTTP Traffic Splitting](https://gateway-api.sigs.k8s.io/guides/traffic-splitting/)
- [ ] [Routing Across Namespaces](https://gateway-api.sigs.k8s.io/guides/multiple-ns/)
- [x] [TLS](https://gateway-api.sigs.k8s.io/guides/tls/) may not be supported
- [x] TLS passthrough

Note that [TCP Routing](https://gateway-api.sigs.k8s.io/guides/tls/) is not currently supported, and we should explicitly call that out.

**Comment by danehans** [comment]
All but one of the tasks was completed in v0.2.0... yay!!! Moving to 0.3.0-rc.1 to resolve the last task.
