### ISSUE TITLE
docs: Layout for user docs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#503]
*Description*:
This issue tracks the layout for the user-facing docs. Here is just a suggestion
- [x] What is Envoy Gateway.
- [x] EG Architecture (diagram and docs from existing [design doc](https://github.com/envoyproxy/gateway/blob/main/docs/design/SYSTEM_DESIGN.md)).
- [x] Quickstart
- [x] Installation? EG currently does not support config (EnvoyGateway CRD is not getting mounted to the pod).
- [x] Examples (see Gateway API examples)
- [ ] Deployment Strategies.
- [ ] How Do I (run features). What Gateway API features does EG support/not support.
- [ ] References. No EnvoyGateway CRD ref without adding support.
- [x] Release Notes- xref https://github.com/envoyproxy/gateway/releases (a ## Release Notes section will be created per minor release).

**Comment by arkodg** [comment]
next steps for this issue would be to 
* narrow down the layout 
* create a sample index pages for the layout with Lorem Ipsum text that can be filled in with actual content later

**Comment by danehans** [comment]
We have a good start to docs in v0.2.0. Moved to 0.3.0-rc.1 to resolve the remaining tasks.
