### ISSUE TITLE
Add support for HTTPQueryParamMatch in Gateway API Translator

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#512]
*Description*:
Add support for translating [HTTPQueryParamMatch](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPQueryParamMatch) into the [XDS IR](https://github.com/envoyproxy/gateway/blob/c059da0e582fc39ae49c0f9a9cc5f028f9792675/internal/ir/xds.go#L145) field in the Gateway API translator

**Comment by zhaohuabing** [comment]
@arkodg I would like to take this one if no one else is currently working on it.
