### ISSUE TITLE
Which Gateway API Version Should be Used?

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#52]
v0.4.2 is the latest Gateway AP release. Should this release be used or should the main branch be used until v0.5.0 is released which introduces [release channels](https://gateway-api.sigs.k8s.io/concepts/versioning/#release-channels-eg-experimental-stable)?

cc: @youngnick

**Comment by arkodg** [comment]
the project is using v0.5.0 for the 0.2.0 release 
https://github.com/envoyproxy/gateway/blob/bca9c19ba6205891eade2e66cc0b0ae9f4388802/go.mod#L20
