### ISSUE TITLE
Whitenoise linter is not working well in GA

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#523]
*Description*:

See:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/48784001/194692091-0d0b6e28-b39d-4ad9-8295-e1c593d54d2c.png">

https://github.com/envoyproxy/gateway/actions/runs/3208530844/jobs/5244475038

whitenoise linter is not working well in PR GA.

**Comment by Xunzhuo** [comment]
BWT, do we really need to maintain this linter? How much value does it have?

**Comment by arkodg** [comment]
can you repro this ? seems like its specific to the diff
we could add `set -x` to better understand the issue

**Comment by Xunzhuo** [comment]
I think every PR lint GA will have this error. @arkodg

**Comment by arkodg** [comment]
@Xunzhuo I dont see this issue on main, can this be closed ?

**Comment by Xunzhuo** [comment]
It appears on build and test workflow in pull request, can you help check this too? @arkodg

**Comment by arkodg** [comment]
> It appears on build and test workflow in pull request, can you help check this too? @arkodg

you're right, I see it, looks like its still relevant

**Comment by danehans** [comment]
@shivanshu1333 are you still able to work on this issue?

**Comment by Xunzhuo** [comment]
Hey @shivanshu1333, can you still work on this?
