### ISSUE TITLE
Certs not found when starting EG

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#526]
*Description*:

Cert Job runs after deploying deployment of EG, when starting EG, the secret is not existed.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/48784001/194743923-de4206de-22f2-4f35-880a-23c5ee7cf116.png">

<img width="892" alt="image" src="https://user-images.githubusercontent.com/48784001/194743943-58745b7a-790c-424f-b48c-1eff7424a448.png">

**Comment by danehans** [comment]
Kustomize is used to manage the manifests and handles the [ordering of resources](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/). Even if the cert-gen Job is created before the EG deployment, there is no startup ordering guarantee. As long as the cert-gen Job completes successfully and EG starts, IMHO this is not a bug.

xref: https://github.com/envoyproxy/gateway/issues/479
