### ISSUE TITLE
Fix logic for deleting Services from ProviderResources

### ISSUE THREAD

**Issue by chauhanshubham** [envoyproxy/gateway#536]
*Description*
The current logic attempts to Delete Services from the ProviderResources map when no Routes are found on the cluster, for a given namespace.

https://github.com/envoyproxy/gateway/blob/81eb8178550e7dfe111caf329390e5554c61d0c8/internal/provider/kubernetes/httproute.go#L284

_Snippet_

```
// Delete the Namespace and Service from the resource maps if no other
// routes exist in the namespace.
routeList = &gwapiv1b1.HTTPRouteList{}
if err := r.client.List(ctx, routeList, &client.ListOptions{Namespace: request.Namespace}); err != nil {
	return reconcile.Result{}, fmt.Errorf("error listing httproutes")
}
if len(routeList.Items) == 0 {
	r.resources.Namespaces.Delete(request.Namespace)
	log.Info("deleted namespace from resource map")
	r.resources.Services.Delete(request.NamespacedName)
	log.Info("deleted service from resource map")
}
```

This tries deleting a Service with namespace/name that matches the HTTPRoute which came in to be Reconciled. This will not be the case most of the times.
We must delete the Services which were referred to by the HTTPRoute that has been now deleted.

**Comment by danehans** [comment]
@chauhanshubham thanks for catching this issue. The httproute/tlsroute controllers should get the HTTPRoute from the resource map before deleting it and then iterate through the Service backends, deleting each from the map.

**Comment by danehans** [comment]
xref #539

**Comment by chauhanshubham** [comment]
Does having a separate cache for these mappings make sense? Something like
```
type ProviderCache struct {
   lock
   routeToServiceMappings map[string][]string
   serviceToRouteMappings map[string]string
}
```
Or we'll probably have to iterate through the ProviderResource cache multiple times
once to find out which services were referred by the deleted route
and second time to find whether the services are referred by other routes currently present.
^ both the steps must be performed for every kind of route in the ProviderResources
