### ISSUE TITLE
A ReferenceGrant Should Be Removed From Watchable Map When UnReferenced

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#539]
#471 added initial support for ReferenceGrants by allowing Gateways to reference Secrets in a different namespace. The gateway controller adds the ReferenceGrant and the ReferenceGrant namespace to the provider watchable map when:

1. A Gateway listener references a Secret in a different namespace.
2. A ReferenceGrant in the above namespace exists and permits the Gateways `from` the Gateway's namespace `to` Secrets.

When the Gateway is deleted, the ReferenceGrant and ReferenceGrant namespace should be deleted from the provider's watchable map if no other Gateway references the ReferenceGrant.

**Comment by skriss** [comment]
Note https://github.com/envoyproxy/gateway/pull/580#pullrequestreview-1144310617, when this is fixed the two invalid/missing referencegrant conformance tests should be able to be uncommented.

**Comment by arkodg** [comment]
I prefer if we move this to 0.3.0 . Based on current logic there is no easy way to handle deletes for RefGrants, easier to implement this with https://github.com/envoyproxy/gateway/issues/413 where we dont need to handle deletes, just start from scratch with every reconcile.

**Comment by danehans** [comment]
Being noted in the v0.2.0 release notes and moving to v0.3.0-rc.1.

**Comment by chauhanshubham** [comment]
https://github.com/envoyproxy/gateway/pull/702 fixes this issue and uncomment's the two conformance tests.
