### ISSUE TITLE
finish implementing ReferenceGrant for HTTPRoute -> Service references

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#545]
#519 completed the missing piece of implementing ReferenceGrant for Listener -> Secret references. Something similar needs to be done for HTTPRoute -> Service references. The Gateway API translator already has logic to check cross-namespace references (https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/translator.go#L660-L683), but the provider / HTTPRoute reconciler needs to pass the relevant ReferenceGrants into the translator layer.

May also be simpler to wait for https://github.com/envoyproxy/gateway/issues/413 before doing this.

xref. #411.

**Comment by danehans** [comment]
Wait until https://github.com/envoyproxy/gateway/issues/413 is fixed.
