### ISSUE TITLE
Create Compatibility Matrix

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#55]
A matrix is needed that describes component versions used in EG releases. For example, EG v0.1 = Envoy v1.x, Gateway API v1.y, etc.

**Comment by danehans** [comment]
Items to doc:
- Envoy version
- Gateway API version
- Kube version(s0 (for Kube provider).

The above should be based on the versions used/tested by EG.

**Comment by danehans** [comment]
@flynn has volunteered to take this on. @lizan @mattklein123 @phlax I'm unable to assign @flynn.

**Comment by danehans** [comment]
xref #17

**Comment by arkodg** [comment]
I think we should pin envoy to a specific image to be more deterministic by changing 
https://github.com/envoyproxy/gateway/blob/62bfc55332b0d1e47fad4f77e40713f3e52cb0b8/internal/ir/infra.go#L14
@lizan any advice on which version https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history should we pick for v0.2.0 ?

**Comment by arkodg** [comment]
The Gateway API version currently being used in v0.5.0 https://github.com/envoyproxy/gateway/blob/62bfc55332b0d1e47fad4f77e40713f3e52cb0b8/go.mod#L20

**Comment by lizan** [comment]
Let's use `envoyproxy/proxy:v1.23.1`, or `envoyproxy/proxy:v1.23-latest`.
