### ISSUE TITLE
Allow release-manifests Target to Specify Image

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#550]
Add `$(IMAGE)` to the `release-manifests` target. This will allow e2e testing of a release prior to cutting the actual release. For example, @Xunzhuo created [this](https://github.com/Xunzhuo/gateway/releases/tag/v0.2.0) test v0.2.0 release but the EG deployment manifest uses a non-existent image.

```
$ kubectl get deploy/envoy-gateway -n envoy-gateway-system -o yaml | grep "image: "
        image: envoyproxy/gateway:v0.2.0
```

**Comment by danehans** [comment]
@arkodg thoughts?

**Comment by Xunzhuo** [comment]
OK, ping me if this is needed, I have already implemented this locally.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/48784001/195400782-f796635a-ed78-4ef2-bf78-211ed6609b01.png">

**Comment by arkodg** [comment]
yah this sounds good, thanks for picking this up @Xunzhuo !
