### ISSUE TITLE
HTTPRoute with URL Rewrite Produces Accepted=True HTTPRoute Status Condition

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#562]
## Reproducer
- Install EG and quickstart guide
- Create an HTTPRoute that rewrites the URL:
```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-rewrite
spec:
  parentRefs:
    - name: eg
  hostnames:
    - rewrite.example
  rules:
    - filters:
      - type: URLRewrite
        urlRewrite:
          hostname: www.example.com
      backendRefs:
      - name: httpbin
        port: 80
EOF
```

HTTPRoute status:
```
- apiVersion: gateway.networking.k8s.io/v1beta1
  kind: HTTPRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"http-filter-rewrite","namespace":"default"},"spec":{"hostnames":["rewrite.example"],"parentRefs":[{"name":"eg"}],"rules":[{"backendRefs":[{"name":"httpbin","port":80}],"filters":[{"type":"URLRewrite","urlRewrite":{"hostname":"www.example.com"}}]}]}}
    creationTimestamp: "2022-10-13T19:16:07Z"
    generation: 1
    name: http-filter-rewrite
    namespace: default
    resourceVersion: "49003"
    uid: 45a55677-f725-4e77-9d58-d69e9418b1c6
  spec:
    hostnames:
    - rewrite.example
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: httpbin
        port: 80
        weight: 1
      filters:
      - type: URLRewrite
        urlRewrite:
          hostname: www.example.com
      matches:
      - path:
          type: PathPrefix
          value: /
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2022-10-13T19:16:07Z"
        message: Route is accepted
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: eg
```

The status should be "Accepted=False".

**Comment by danehans** [comment]
A full config dump and httproute config can be found [here](https://gist.github.com/danehans/789e371bcd99deb4f976b69912abeb63).

**Comment by arkodg** [comment]
support for Hostname seems to exist in the xds translator https://github.com/envoyproxy/gateway/blob/2103195e28257a564d3aea674f9cb401cb037032/internal/xds/translator/route.go#L186 
as well as Gateway API Translator 
https://github.com/envoyproxy/gateway/blob/2103195e28257a564d3aea674f9cb401cb037032/internal/gatewayapi/translator.go#L813
next steps would be to print out the IR and ensure xds translator generates the right o/p

**Comment by danehans** [comment]
@arkodg here is the [xds IR](https://gist.githubusercontent.com/danehans/789e371bcd99deb4f976b69912abeb63/raw/6ee32ddc2f95e551899fc37e352132ddccdd0f5e/xds_ir.log). This bug uses the URLRewrite filter and not the RequestRedirect filter. It looks like we're hitting the [default case](https://github.com/envoyproxy/gateway/blob/2103195e28257a564d3aea674f9cb401cb037032/internal/gatewayapi/translator.go#L1028-L1043) and EG configs Envoy to send a direct response.

**Comment by skriss** [comment]
@danehans I'm a little confused by the issue report -- EG doesn't support the URLRewrite filter (it's extended conformance and experimental), and it looks like it's doing the right thing by configuring a direct response for the route that has the unsupported filter. The only problem I see is that the HTTPRoute has an "Accepted: true" condition instead of an "Accepted: false" condition. Could you clarify?

**Comment by AliceProxy** [comment]
> @danehans I'm a little confused by the issue report -- EG doesn't support the URLRewrite filter (it's extended conformance and experimental), and it looks like it's doing the right thing by configuring a direct response for the route that has the unsupported filter. The only problem I see is that the HTTPRoute has an "Accepted: true" condition instead of an "Accepted: false" condition. Could you clarify?

This is what I was refering to in the meeting (maybe last week?) about us not supporting rewriting the prefix of requests since there is no support for the `URLRewrite` filter at this time. I was wanting to add support for it, but the focus has been getting core conformance and bugs fixed instead of adding the extended support sections of gateway API.

I can definitely add it after 0.2.0, or if you think we really need it for 0.2.0 I can try to get it done by Monday. :thinking:

**Comment by danehans** [comment]
> it looks like it's doing the right thing by configuring a direct response for the route that has the unsupported filter.

@skriss thanks for the feedback. The direct response is "Unknown custom filter..." as opposed to "Unsupported filter..".

> The only problem I see is that the HTTPRoute has an "Accepted: true" condition instead of an "Accepted: false" condition. Could you clarify?

Correct, the route should be "Accepted=False" with "Reason: UnsupportedValue". PR https://github.com/envoyproxy/gateway/pull/563 aims to resolve both of the points in this comment.

**Comment by danehans** [comment]
xref: https://github.com/envoyproxy/gateway/issues/564 for adding URLRewrite filter support.
