### ISSUE TITLE
Add Support for HTTPRoute URLRewrite Filter

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#564]
Add support for the HTTPRoute [URLRewrite](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPURLRewriteFilter) filter.

**Comment by danehans** [comment]
cc: @AliceProxy

**Comment by danehans** [comment]
__Note:__ The user guide added by https://github.com/envoyproxy/gateway/pull/565 should be updated when this issue is fixed.

**Comment by Xunzhuo** [comment]
I would like to assign this

**Comment by danehans** [comment]
@Xunzhuo done.

**Comment by Xunzhuo** [comment]
This is planned to be implemented in v0.3.0-rc1, right? Not the v0.2.0 @danehans

**Comment by danehans** [comment]
I didn't include this issue for v0.2.0 since we're running out of time. If you can have a PR submitted by tomorrow, then it can be included in v0.2.0.

**Comment by Xunzhuo** [comment]
Let us do this in v0.3.0-rc1. :)

**Comment by danehans** [comment]
@Xunzhuo this issue is tracked for the v0.3.0-rc.1 milestone. Checking to see if you still plan on fixing this issue.

**Comment by Xunzhuo** [comment]
All implementations are blocked by GWAPI release.

When GWAPI v0.6 released, I can back to implement this.

**Comment by danehans** [comment]
@Xunzhuo now that our Gateway API dep has been bumped to v0.6-rc.1, you should be unblocked. I have confirmed with @youngnick that no breaking changes will occur between v0.6-rc.1 and v0.6.

**Comment by Xunzhuo** [comment]
I am going to work on it this weekend.
