### ISSUE TITLE
Introduce canary release of EG.

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#566]
*Description*:

This proposal is about adding a canary release of EG. This canary version will be pre-released everytime we get PR merged. Take this as an example: https://github.com/fermyon/spin/releases/tag/canary.

We can always get the latest pre-release artifacts, like install.yaml. quickstart.yaml, etc. 

1. This is good for developers who want to try the latest dev version of EG, not the official release(We know that the duration of a release is long, so if people need some features which get merged but not release, it makes them hard to try.)

2. This is good for release-manager who wants to have a pre-release test of a offical release, like what I did in https://github.com/Xunzhuo/gateway/releases/tag/v0.5.0, but in the fork repo, there are many places need to be configured like canceling the coverage uploading / set up github pages / config the personal docker registry.. This is complex. By adding a canary release of EG, it makes everything easy.

**Comment by Xunzhuo** [comment]
See: https://github.com/Xunzhuo/gateway/releases and https://github.com/Xunzhuo/gateway/actions/runs/3247935540.

**Comment by danehans** [comment]
+1 for supporting an EG canary release. @arkodg @youngnick @skriss @LukeShu thoughts?

**Comment by arkodg** [comment]
+1

**Comment by LukeShu** [comment]
Calling this "canary" doesn't quite mesh with my use of the word "canary", but that's not real important.

+1 to doing these builds
