### ISSUE TITLE
TLSRoute Conformance Test

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#577]
https://github.com/envoyproxy/gateway/pull/402 added TLSRoute support. A TLSRoute conformance test should be created [upstream](https://github.com/kubernetes-sigs/gateway-api/) .

**Comment by danehans** [comment]
cc: @chauhanshubham

**Comment by skriss** [comment]
ref. https://github.com/kubernetes-sigs/gateway-api/pull/1587

**Comment by arkodg** [comment]
> ref. [kubernetes-sigs/gateway-api#1587](https://github.com/kubernetes-sigs/gateway-api/pull/1587)

above test has been released as part of v0.6.1 and is enabled by default in our conformance CI
