### ISSUE TITLE
docs-publish failing in GH runs

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#593]
*Description*:
Seeing the `docs-publish` action failing in the GH run
https://github.com/envoyproxy/gateway/actions/runs/3274947957/jobs/5389194301

**Comment by danehans** [comment]
xref https://github.com/envoyproxy/gateway/pull/587. An incorrect CNAME record was initially created but a ticket was created to update the record.

**Comment by arkodg** [comment]
@danehans should we merge #587 then (see its in draft mode) ?

**Comment by danehans** [comment]
No, adding a CNAME to the repo is unneeded when you're deploying GH Pages from an Action. We need CNCF to update the CNAME record in the provider that manages `envoyproxy.io`.

**Comment by danehans** [comment]
The CNAME record has been updated but I'm still unable to hit the docs site:
```
$ dig gateway.envoyproxy.io

; <<>> DiG 9.10.6 <<>> gateway.envoyproxy.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30886
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;gateway.envoyproxy.io.		IN	A

;; ANSWER SECTION:
gateway.envoyproxy.io.	60	IN	CNAME	envoyproxy.github.io.
envoyproxy.github.io.	3600	IN	A	185.199.111.153
envoyproxy.github.io.	3600	IN	A	185.199.108.153
envoyproxy.github.io.	3600	IN	A	185.199.109.153
envoyproxy.github.io.	3600	IN	A	185.199.110.153

;; Query time: 101 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Oct 18 09:22:07 PDT 2022
;; MSG SIZE  rcvd: 146
```

According to the [GH docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain), this is the correct CNAME configuration.
