### ISSUE TITLE
TLS Termination Does Not Work When Listener Hostname Is Unspecified

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#601]
TLS termination does not work on a Gateway that does not specify a hostname. To reproduce:

1. Follow the steps in the draft [secure gateways guide](https://github.com/envoyproxy/gateway/blob/62711dc4341a626b68a689074308a104c6a47cb2/docs/user/secure-gateways.md).
2. Test the HTTPS endpoint:
  ```
$ curl -v -HHost:www.example.com --resolve "www.example.com:8443:${GATEWAY_HOST}" \
--cacert example.com.crt https://www.example.com:8443/get
* Added www.example.com:8443:172.18.255.200 to DNS cache
* Hostname www.example.com was found in DNS cache
*   Trying 172.18.255.200:8443...
* connect to 172.18.255.200 port 8443 failed: Connection refused
* Failed to connect to www.example.com port 8443 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.example.com port 8443 after 0 ms: Connection refused
   ```

EG Logs:
```
2022-10-18T22:07:32.059Z	INFO	cache/logrwrapper.go:24	handling v3 xDS resource request, response_nonce 2, nodeID envoy-default-eg-64656661-8558db7c45-kzt4p, node_version v1.23.2, resource_names_subscribe [], resource_names_unsubscribe [], type_url type.googleapis.com/envoy.config.listener.v3.Listener, errorCode 13, errorMessage Error adding/updating listener(s) default-eg-https: error adding listener '0.0.0.0:8443': partial wildcards are not supported in "server_names"
```

Envoy Logs:
```
[2022-10-18 22:07:32.058][1][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) default-eg-https: error adding listener '0.0.0.0:8443': partial wildcards are not supported in "server_names"
```

[Envoy Config Dump](https://gist.githubusercontent.com/danehans/1e9d9925c646adcd334e0081bbc2bfa9/raw/dba5364d7ad21c1bc9640206f905b410998fd822/envoy_cfg_dump.log)

**Comment by arkodg** [comment]
What's happening - 
Looks like Envoy does not like this specific config
```
       "filter_chains": [
        {
         "filter_chain_match": {
          "server_names": [
           "*"
          ]
```

and errors out with `partial wildcards are not supported in "server_names"`

Why - 
* when the Listener Hostname is unspecified the Gateway API Translator fills in the Hostname field as `*` https://github.com/envoyproxy/gateway/blob/c78103f27480a8fa0308d0fc387ff1f79909aa75/internal/gatewayapi/translator.go#L563
this Hostnames field gets translated into the `server_names` field within the `filter_chain_match`
https://github.com/envoyproxy/gateway/blob/c78103f27480a8fa0308d0fc387ff1f79909aa75/internal/xds/translator/listener.go#L87

Next steps
* @lizan @cpakulski can you help understand why `*` is not supported in `server_names` . The docs https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto.html?highlight=filter_chain_match only mentions partial hostnames, and dont think this is partial, its all :smiles

**Comment by lizan** [comment]
@arkodg if you want to match all server_names, instead of `["*"]` just leave that field empty.

**Comment by arkodg** [comment]
> @arkodg if you want to match all server_names, instead of `["*"]` just leave that field empty.

ha we can def implement this, thanks !
but if this is not supported by envoy does it make sense to enhance the `server_names` docs string ? or should I raise a GH issue within envoyproxy ?

**Comment by lizan** [comment]
@arkodg yeah that sounds good. basically every field in filter chain match has the semantics that "empty matches all".
