### ISSUE TITLE
Add support for regex match type in Gateway API Translator

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#608]
Add support for regex match type in Gateway API Translator for the following HTTPRouteMatch conditions:
* HTTPPathMatch
* HTTPHeaderMatch
* HTTPQueryParamMatch

**Comment by danehans** [comment]
@zhaohuabing can you help me understand why this issue is labeled as a bug and not an enhancement?

**Comment by zhaohuabing** [comment]
@danehans Yes, it should be an enhancement instead of a bug. Could you please help change the label? Thanks.

**Comment by arkodg** [comment]
@zhaohuabing assigning this issue to you, since you volunteered :)

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/676
