### ISSUE TITLE
Split up CRDs and Install YAML

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#613]
*Description*:
I find myself running `make kube-deploy` multiple times so EG initializes properly.

Raising this issue here in case others hit it too, we might need to revert https://github.com/envoyproxy/gateway/pull/510 and go back to a 2 step install process

**Comment by Xunzhuo** [comment]
You mean, you need to run kube-deploy multiple times, otherwise the EG will not start properly?

**Comment by danehans** [comment]
I am not seeing this issue and I have done ~50 installs since #510 merged. Let's continue to keep this open for tracking purposes and we can revert if this becomes more common in the wild.

**Comment by arkodg** [comment]
> You mean, you need to run kube-deploy multiple times, otherwise the EG will not start properly?

yeah EG starts properly, but applying resources doesnt have any affect (no Envoy created), I test locally on Docker Desktop K8s

**Comment by danehans** [comment]
I have used the `install.yaml` and `quickstart.yaml` ~50 times and have not hit this issue.

**Comment by danehans** [comment]
@LukeShu @AliceProxy @Xunzhuo @skriss @youngnick can you please test:

Install EG
```
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml
```

Install the Quickstart:
```
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/latest/quickstart.yaml
```

**Comment by AliceProxy** [comment]
@danehans Anecdotally, it works for me on a GKE cluster first try.

**Comment by Xunzhuo** [comment]
Me too, everything works fine for me 😄

**Comment by thredreams** [comment]
I think it may be that some images failed to pull, which caused some containers to fail to start successfully, or the "job" did not complete. The cause of the error may be the same as #705. Completing #390 may solve the problem.

**Comment by arkodg** [comment]
closing, since this is a non issue and not reproducible anymore
