### ISSUE TITLE
Allow Release Workflow to Support Quickstart Guide Changes

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#629]
Update the release GitHub workflow to accommodate Quickstart guide changes and not result in a failed CI run.

xref: https://github.com/envoyproxy/gateway/actions/runs/3290977504

**Comment by danehans** [comment]
cc: @Xunzhuo

**Comment by Xunzhuo** [comment]
![image](https://user-images.githubusercontent.com/48784001/196998145-1db82fae-d3d0-4a28-8abe-a330213438ef.png)

The build and test release branch pattern is not matched with the release/vxxx. We should update this.
