### ISSUE TITLE
switch to Listener ports 80/443 instead of 8080/8443 for the quickstart & secure Gateway guides

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#644]
Using the standard ports 80 & 443 would be more realistic, and  would simplify various commands that would no longer need to explicitly specify ports. It would also eliminate the need to explicitly specify `Host` headers in curl commands using `--resolve` (that seems to include the port # in the Host header by default if using non-standard ports).

**Comment by kflynn** [comment]
I've verified that this should be a simple YAML change, so I'm just gonna do it.
