### ISSUE TITLE
[Data Plane] Add support for fetching TLS certificates from different certificate management systems (like AWS Certificate Manager)

### ISSUE THREAD

**Issue by bmetzdorf** [envoyproxy/gateway#649]
*Description*:
It would be great to have support for getting TLS certificates via the [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/).  For Envoy Gateway running on EKS, we can allow the envoyproxy gateway pods (as well as the envoy gateway control plane pods) to get their certs from ACM (similar to the `Service` annotation: `service.beta.kubernetes.io/aws-load-balancer-ssl-cert`) instead of plain Kubernetes Secrets.

This could be extended to other use cases (like Vault) and might or might not have to include identity providers (like SPIFFE/SPIRE).

**Comment by danehans** [comment]
> It would be great to have support for getting TLS certificates via the [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/).

@bmetzdorf does ACM Private CA support meet your requirements? Cert-Manager supports an [ACM Private Issuer plugin](https://github.com/cert-manager/aws-privateca-issuer/). We are considering adding support for Cert-Manager to resolve https://github.com/envoyproxy/gateway/issues/81. I prefer having EG support issuers through Cert-Manager instead of natively.

**Comment by danehans** [comment]
@bmetzdorf following-up on my ^ comment. Let me know your thoughts when you have a moment.

**Comment by bmetzdorf** [comment]
@danehans 

I'll have to give this a bit more thought, but right now I think that integration with cert-manager might be enough, yes.  Thanks!

**Comment by arkodg** [comment]
closing this issue, hoping the integration with cert-manger fits your use case, please feel free to open this issue if it doesnt
