### ISSUE TITLE
Initial Gateway API Conformance

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#65]
The community has established Gateway API [conformance](https://gateway-api.sigs.k8s.io/concepts/guidelines/?h=conformance#conformance) as the target of the [0.0.2 release](https://github.com/envoyproxy/gateway/milestone/1). This is a meta issue, in that issues, PRs, etc. that target this goal should be linked to this issue.

**Comment by youngnick** [comment]
Yes, I think we should pick a Gateway API release as our first milestone target, we could choose either v0.4.3, the final v1alpha2 release, or the forthcoming v0.5.0, the first v1beta1 release. I'm inclined toward the latter.

**Comment by danehans** [comment]
@skasisom6 the [v0.2.0](https://github.com/envoyproxy/gateway/milestone/1) goal is for Envoy Gateway to pass Gateway API conformance tests. This means that Envoy Gateway will provide a set of core API Gateway functionality. When you have a moment, please review [Gateway API conformance](https://gateway-api.sigs.k8s.io/geps/gep-917/?h=conforma#what-is-conformance), along with the [conformance tests](https://github.com/kubernetes-sigs/gateway-api/tree/master/conformance/tests) to learn more about conformance. Let us know if these features are not consistent with your requirements for the release.

**Comment by skriss** [comment]
I can work on getting the Gateway API conformance tests running in CI so as soon as we have something integrated, we can start running tests against it. I'll file a specific issue for it.

**Comment by danehans** [comment]
v0.2.0 will focus on httproute conformance, e.g. not tlsroute, tcproute, etc. @kflynn we should make sure the docs state this.

xref https://github.com/envoyproxy/gateway/issues/17

**Comment by skriss** [comment]
Large blockers for getting Gateway API conformance tests to run:
- https://github.com/envoyproxy/gateway/issues/330 (conformance uses the address in Gateway.Status.Addresses to send HTTP requests; we need to set this to the provisioned Service's external IP)
- https://github.com/envoyproxy/gateway/issues/345 (conformance tests won't proceed until a Gateway has a Condition of "Ready: true")
- https://github.com/envoyproxy/gateway/issues/329 (conformance is equally concerned with HTTP requests succeeding and Gateway API resources having the correct statuses; we need to be writing statuses to the apiserver)

Specific "core" conformance features still to be implemented:
- #158 
- #159 
- #162 
- #168 (it's a little fuzzy exactly what's core conformance, but we should probably at least implement TLSMode Terminate)

**Comment by danehans** [comment]
Note that https://github.com/envoyproxy/gateway/issues/168 and https://github.com/envoyproxy/gateway/issues/411 are not required to pass conformance tests.

**Comment by danehans** [comment]
[Outstanding v0.2.0 conformance test issues](https://github.com/envoyproxy/gateway/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fconformance+milestone%3A0.2.0).

**Comment by danehans** [comment]
2 remaining referencegrant tests should pass when #588 is fixed.

**Comment by danehans** [comment]
Closing since all core conformance tests are passing. All but one RefernceGrant test (tracked by https://github.com/envoyproxy/gateway/issues/539) is passing.
