### ISSUE TITLE
support HTTPRequestMirror filter (extended conformance)

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#656]
*Description*:
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter (HTTPRequestMirrorFilter)

There is no upstream conformance test for this yet.

**Comment by arkodg** [comment]
cc @AliceProxy

**Comment by danehans** [comment]
@AliceProxy this issue is tracked for the v0.3.0-rc.1 milestone. Checking to see if you still plan on fixing this issue.

**Comment by AliceProxy** [comment]
@danehans Yep I'm actively working on this now

**Comment by danehans** [comment]
Great. Thanks for the update.

**Comment by arkodg** [comment]
looks like this is needed for [GRPCRoute](https://github.com/kubernetes-sigs/gateway-api/blob/e7260d356a01afc973772610b6223686a971b43e/apis/v1alpha2/grpcroute_types.go#L445) as well

**Comment by arkodg** [comment]
just linking the relevant envoy filter here https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-requestmirrorpolicy
