### ISSUE TITLE
Add Support for HTTPRoute ResponseHeaderModifier Filter

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#657]
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteFilter (responseHeaderModifier)

Note, this one is currently marked experimental, but likely to be promoted soon since it's very similar to the existing requestHeaderModifier filter.

There is a conformance test for this upstream (https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-response-header-modifier.go), though note that an issue was reported with it: https://github.com/kubernetes-sigs/gateway-api/issues/1473

**Comment by danehans** [comment]
@Xunzhuo this issue is tracked for the v0.3.0-rc.1 milestone. Checking to see if you still plan on fixing this issue.

**Comment by Xunzhuo** [comment]
Here too.

All implementations are blocked by GWAPI release.

When GWAPI v0.6 released, I can back to implement this.
