### ISSUE TITLE
enable HTTPRoute method matching conformance test

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#659]
Once Gateway API v0.6.0 has been released and picked up here, we should enable the HTTPRoute method matching test, since it's been implemented in #658.

The test is here: https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-method-matching.go

It also requires adding the SupportedFeature to our suite.Options:
- https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/utils/suite/suite.go#L50-L51
- https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go#L54

**Comment by haq204** [comment]
Hi @skriss I would like to pick up this issue for the v0.3.0-rc.1 Milestone if no one currently working on it.

**Comment by arkodg** [comment]
hey @haq204 go for it !
