### ISSUE TITLE
Support non-versioned Homepages

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#668]
IMO, we miss something like envoy-website and envoy-mobile site, they have the homepages separated with the docs, the homepage contains things which do not need to be versioned like blogs, announcements and etc. As for the the sphinx docs, they are all versioned.

So contents in sphinx docs would be better to be all versioned, we can just add our homepage support after this.

Take what istio has as an example:
non-versioned:

Blogs
Announcements
Get involved
About
Introduction
Case studies
FAQ
....
versioned: Documents.

_Originally posted by @Xunzhuo in https://github.com/envoyproxy/gateway/issues/639#issuecomment-1297494579_

**Comment by arkodg** [comment]
closing as completed
