### ISSUE TITLE
Add Support for Main to use envoy-dev Image

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#672]
#665 updates EG releases to coincide with Envoy (1 week after). This may not be enough time for the community to test and fix potential bugs since `main` tracks a released version of Envoy. Instead, have `main` track [envoy-dev](https://hub.docker.com/r/envoyproxy/envoy-dev/tags).  The Envoy image can then be updated to a released version as part of the release workflow.

xref: https://github.com/envoyproxy/gateway/pull/654

**Comment by arkodg** [comment]
this is a great idea in theory, but it also means that PRs raised in the project might flake or fail due to some intermittent issue in the upstream `main`

**Comment by danehans** [comment]
@arkodg Understood, but that could also benefit us by discovering breaking changes early. As EG matures, I could see the benefits being reciprocated to Envoy. In the future, I could also foresee releasing EG on the same day as Envoy which would be a competitive advantage for the project. Both approaches have tradeoffs. Thoughts @LukeShu @youngnick @skriss @Xunzhuo @AliceProxy?

**Comment by youngnick** [comment]
I'm +1 on this, it makes sense for Gateway dev to be linked to Envoy dev. I think that the risks of having flakes because of Envoy `main` having problems is probably a net win, because we'll be further exercising envoy-dev.

**Comment by Xunzhuo** [comment]
I am +1 on this, dev to dev, make sense in main branch, it makes a good collaboration with EG and upstream Envoy.

**Comment by Xunzhuo** [comment]
Wait for others comments, if most think this is OK to process, I would like to assign this.

**Comment by skriss** [comment]
:+1: I think this makes sense

**Comment by danehans** [comment]
xref https://github.com/envoyproxy/gateway/pull/654 for bumping the envoy image.
