### ISSUE TITLE
Use HTTPRoute hostname as SNI match for HTTPS traffic

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#680]
*Description*:
The current Gateway API Translator logic maps the the [Gateway hostname to the Xds IR Listener](https://github.com/envoyproxy/gateway/blob/0646f946ebb854adbd71b5499704e9bf9c50f1b4/internal/gatewayapi/translator.go#L560) Hostname and uses the Hostnames within the HTTPRoute spec to populate the [Xds IR HeaderMatches](https://github.com/envoyproxy/gateway/blob/0646f946ebb854adbd71b5499704e9bf9c50f1b4/internal/gatewayapi/translator.go#L1176)
field.

The logic can be optimized to use the intersection between the gateway hostname and http route hostnames, [computeHosts](https://github.com/envoyproxy/gateway/blob/3f503723f2a6eedaa20ce8c5200f57087c7be52d/internal/gatewayapi/helpers.go#L165) to populate the Xds IR Hostnames field

Relates to https://github.com/envoyproxy/gateway/pull/662#issuecomment-1297443066

**Comment by shivanshu1333** [comment]
I can try to fix this :) 
/assign

**Comment by danehans** [comment]
@shivanshu1333 thanks for your willingness to take on this issue. Are you still planning to fix this issue for the v0.3.0-rc.1 milestone?

**Comment by oowl** [comment]
Hello, I have seen this issues take a long time and not be fixed, I want to contribute to it. Can I get assigned?

**Comment by arkodg** [comment]
hey @oowl , thinking out loud, we have a simple mapping of 1:1 today
* Listener Hostname maps to Server name match within Filter Chain with a xds Listener
* Route Hostname maps to a `:authority` header match with the VirtualHost with xds Route Configuration object.

Im unsure if this will actually be a perf improvement or not because we use delta xds to push these resources, which will cause EG to update two resources (Listener and RouteConfiguration) instead of just 1, in the data plane, when the hostname in a  HTTPRoute is updated, if we go about making this change.

probably needs more analysis before making the change.

**Comment by arkodg** [comment]
closed as not needed - we use the listener Hostname for SNI matching and route Hostname in virtual host matching
