### ISSUE TITLE
Enable access logging for xds components

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#684]
*Description*:

Update [access logging](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging.html?highlight=access%20logging) to `/dev/stdout` for xds components supporting this feature.

**Comment by arkodg** [comment]
@zirain for this issue, would be great to enable access logging to stdout for xds components (connection manager, tcp proxy etc) for now until we have a full fledged observability solution

**Comment by zirain** [comment]
assign this to me, I will send a temporary solution next week.

**Comment by danehans** [comment]
@arkodg can you assign a priority label to this issue?
