### ISSUE TITLE
Support Multiple Release Versions

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#689]
#639 added support for versioned docs. However, the only versions supported are `latest` and the version specified in `VERSION`. It would be helpful if versioned docs supported every EG release. Possibly update `VERSION` to include `$CURRENT` and `$PREVIOUS` versions that are populated by iterating through `/docs/html`?

**Comment by Xunzhuo** [comment]
Yes, it could generate every history release by iterating folder name in docs/. I will fix this.

**Comment by Xunzhuo** [comment]
Yes, it could generate every history release by iterating folder name in docs/. I will fix this.
