### ISSUE TITLE
Slack link in not working

### ISSUE THREAD

**Issue by krish512** [envoyproxy/gateway#69]
README file has a slack link to join the #gateway-dev which does not work any more

Readme file: https://github.com/envoyproxy/gateway/blob/main/README.md

Slack link: https://envoyproxy.io/slack

**Comment by gyohuangxin** [comment]
@krish512  This link works for me. Maybe you need to sign in at first: https://envoyproxy.slack.com/signin

**Comment by krish512** [comment]
<img width="660" alt="Screenshot 2022-05-19 at 4 48 17 PM" src="https://user-images.githubusercontent.com/6457418/169281382-73060251-5d76-4799-af31-1f38dfe89091.png">

Slack link: https://envoyproxy.io/slack

**Comment by gyohuangxin** [comment]
What if you click "Join with Email", then sign in with your email?
![image](https://user-images.githubusercontent.com/42127654/169283170-b8d3d63d-541f-4287-830b-68d1bb8832bc.png)

**Comment by mattklein123** [comment]
Thanks I will figure out how to fix this.

**Comment by mattklein123** [comment]
Should be fixed soon. Unfortunately this is a limitation of how Slack invites work. https://github.com/envoyproxy/envoy-website/pull/256
