### ISSUE TITLE
Observability: Envoy Gateway

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#700]
*Description*:
This epic tracks the design and implementation for surfacing logs, metrics and traces generated by Envoy Gateway that are relevant to the user managing Envoy Gateway

**Comment by Xunzhuo** [comment]
Sure

**Comment by jcchavezs** [comment]
QQ: what is the current status here?

**Comment by arkodg** [comment]
closing in favor of https://github.com/envoyproxy/gateway/issues/701

**Comment by arkodg** [comment]
hey @Xunzhuo we discussed this issue in the community, would it be possible to prioritize logging over metrics over tracing for control plane telemetry ?

**Comment by arkodg** [comment]
since its unlikely this will make it into v0.5.0, moving this to the v0.6.0 milestone

**Comment by arkodg** [comment]
closing as completed, individual issues have been created to track remaining work

**Comment by arkodg** [comment]
nvm, reopening since we haven't wrapped up `tracing` in EG

**Comment by Xunzhuo** [comment]
close for duplicated with https://github.com/envoyproxy/gateway/issues/701
