### ISSUE TITLE
Observability Design and Implementation of EG

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#701]
*Description*:

This issue tracks the Observability designs and implementations of EG.

EG Observability Design should be two main parts and such subtasks:
+ The Control Plane (CP): Design and Implement the CP Observability of EG (https://github.com/envoyproxy/gateway/issues/700).

   - [ ] Metrics generated by Envoy Gateway
  - [ ] Logging generated by Envoy Gateway
  - [ ] Tracing generated by Envoy Gateway
  
+ The Data Plane (DP): Design and Implement the DP Observability of EG (https://github.com/envoyproxy/gateway/issues/699).

  - [x] Access Logging generated by EnvoyProxy
  - [x] Tracing generated by EnvoyProxy
  - [x] Metrics generated by EnvoyProxy

Welcome to comment your ideas related to Observability here.

**Comment by danehans** [comment]
@Xunzhuo unless you're actively working on this issue, can you unassign yourself and add the help-wanted label?

**Comment by arkodg** [comment]
@zirain since you're interested as well as fairly knowledgable in this area, assigning this issue to you as well, hoping you and @Xunzhuo can tackle this together in the next release 🚀

**Comment by zirain** [comment]
xref: https://github.com/istio/istio/pull/44094 case about grpc stats

**Comment by jcchavezs** [comment]
We should also include observability for filters here even if the work is done upstream.

**Comment by zirain** [comment]
@shawnh2 will work on control plane part.

**Comment by kevintatou** [comment]
how is the support for openetelemtry traces, logs, metrics? I can see it is in design phase on envoyproxies page. Is there anything more being done?

**Comment by zirain** [comment]
> how is the support for openetelemtry traces, logs, metrics? I can see it is in design phase on envoyproxies page. Is there anything more being done?

it's completed, you can try it.

**Comment by kevintatou** [comment]
> > how is the support for openetelemtry traces, logs, metrics? I can see it is in design phase on envoyproxies page. Is there anything more being done?
> 
> it's completed, you can try it.


Is there any example on how to do it in otel with my own collector? I cant seem to find it 🤔

**Comment by zirain** [comment]
I cannot recall if there's a user face doc, but you check the e2e test https://github.com/envoyproxy/gateway/tree/main/test/e2e

**Comment by shawnh2** [comment]
The Metrics of EG CP will be discussed and resolved in #2092

**Comment by kevintatou** [comment]
@shawnh2  so metrics is not implemented yet? Do you know if tracing is?

**Comment by shawnh2** [comment]
> @shawnh2  so metrics is not implemented yet? Do you know if tracing is?

hi @kevintatou, the metrics/tracing/logging for envoy gateway control plane is not implemented yet. But the data plane does (all of them), you can [browse the doc](https://gateway.envoyproxy.io/v1.0.1/tasks/observability/proxy-observability/) to find more.

**Comment by Xunzhuo** [comment]
Let us close this, and track cp metrics progress in https://github.com/envoyproxy/gateway/issues/2092.

**Comment by pkit** [comment]
@zirain any plans on doing otel over http?
writing a grpc service just to get the access log looks like overkill to me...

**Comment by zirain** [comment]
> @zirain any plans on doing otel over http? writing a grpc service just to get the access log looks like overkill to me...

does grpc has better perfmance?

**Comment by pkit** [comment]
It does. Usually.
