### ISSUE TITLE
Github action `build-and-test` fails randomly

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#705]
- fail on `make go.test.coverage`

https://github.com/envoyproxy/gateway/actions/runs/3406968389/jobs/5666166782

- fail on `make conformance` v1.23.6

https://github.com/envoyproxy/gateway/actions/runs/3407232578/jobs/5666696862

- fail on `make conformance` v1.24

https://github.com/envoyproxy/gateway/actions/runs/3407315316/jobs/5666855486

**Comment by zirain** [comment]
```
Error from server (InternalError): error when creating "internal/provider/kubernetes/config/samples/gatewayclass.yaml": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "[https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s](https://gateway-api-admission-server.gateway-system.svc/validate?timeout=10s)": x509: certificate signed by unknown authority
```

**Comment by Xunzhuo** [comment]
> I think we should wait job completed, but not 100%

Probably right, the cert might not be generated, so the auth is failed.
