### ISSUE TITLE
Update to the v0.6.0 Gateway API release 

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#716]

**Comment by arkodg** [comment]
currently blocked on the Gateway API release itself

**Comment by Xunzhuo** [comment]
I am assigning this to bump GWAPI to v0.6.0, since some tasks of extended filters are not covered in v0.5.1.

**Comment by arkodg** [comment]
this is blocking https://github.com/envoyproxy/gateway/pull/717

**Comment by arkodg** [comment]
hey @Xunzhuo looks like https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.6.0-rc1 is released, this tag should unblock us

**Comment by Xunzhuo** [comment]
Let us open this issue for a while, need to bump when v0.6.0 released.

**Comment by arkodg** [comment]
update currently blocked due to the failure of these tests
https://github.com/envoyproxy/gateway/pull/828#issuecomment-1361668873
needs to be triaged
