### ISSUE TITLE
Bump Echoserver Image Tag

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#719]
https://github.com/kubernetes-sigs/gateway-api/pull/1520 bumps the echoserver image version in conformance tests. When https://github.com/envoyproxy/gateway/pull/717 is merged, it should cause Gateway API conformance tests in EG to use the new image tag. The image tag should be bumped to `v20221109-7ee2f3e` in user docs for consistency.

**Comment by Xunzhuo** [comment]
I am going to bump this after https://github.com/kubernetes-sigs/gateway-api/pull/1520 got merged. ResponseHeaderModifier is required this new echo-server to demonstrate response header modifying abilities.

**Comment by danehans** [comment]
> ResponseHeaderModifier Filter needs to use this new echo-server to demonstrate response header modifying abilities

Yes, the image tag for the conformance tests should get bumped as part of bumping Gateway API. This issue targets the image tag used by the user docs that will not get bumped without manual intervention.
