### ISSUE TITLE
Fix Envoy Gateway docs links

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#721]
*Description*:
 
The Enovy Gateway docs link has changed from https://gateway.envoyproxy.io/releases/v0.2.html to https://gateway.envoyproxy.io/v0.2.0/ . Raising this issue to surface this and fix it in any downstream content leveraging these links

**Comment by shivanshu1333** [comment]
I couldn't find any occurrence of https://gateway.envoyproxy.io/releases/v0.2.html in the gateway repo. Can you help me, Where exactly do we need to make this change?

**Comment by arkodg** [comment]
hey @shivanshu1333 , i raised this issue to surface this issue of broken links that we noticed downstream in blog posts and release notes. Ive updated the links in the Release notes, just letting this issue hang out a while longer before we close it out.
Thanks for scanning through the repo searching for its occurrences and making sure it doesnt exist

**Comment by wilsonwu** [comment]
Searched and confirmed that no such link like:https://gateway.envoyproxy.io/releases/v0.2.html in any files.

**Comment by arkodg** [comment]
thanks @wilsonwu @shivanshu1333 , closing this issue for now
