### ISSUE TITLE
Fix stat prefix for xds components

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#727]
*Description*:
Add meaningful stat prefixes for xds components such as [this](https://github.com/envoyproxy/gateway/blob/c1f2585c2de5eca380d21b93a1c3815b1013d65d/internal/xds/translator/listener.go#L67)

**Comment by shivanshu1333** [comment]
I'm new to envoy/gateway. I'm unable to understand what exactly we need to do here; some guidance, please...
thanks!!

**Comment by arkodg** [comment]
hey @shivanshu1333 thanks for volunteering to work on this issue !
the outcome of this issue to fix all the `stat_prefix` logic within the xds translator which gets assigned to the `StatsPrefix` field within structures such as the [http connection manager](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager) and assign sensible string values to it .

**Comment by chauhanshubham** [comment]
Does it make sense for `statPrefix` to be the name of the listener? 
The metrics would look something like this
```
http.default-eg-http.rq_total: 0
http.default-eg-http.rs_too_large: 0
http.default-eg-http.tracing.client_enabled: 0
http.default-eg-http.tracing.health_check: 0
http.default-eg-http.tracing.not_traceable: 0
http.default-eg-http.tracing.random_sampling: 0
http.default-eg-http.tracing.service_forced: 0
```

**Comment by arkodg** [comment]
ptal @zirain

**Comment by arkodg** [comment]
closing as not needed atm
