### ISSUE TITLE
Is there a recommended way to update EG?

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/gateway#729]
There is `install.yaml` which contains CRDs for EG. Is there any recommendation on how to update to a newer version of EG? Can I just update the CRDs?

**Comment by Xunzhuo** [comment]
Currently you can get the latest EG from https://github.com/envoyproxy/gateway/releases/tag/latest.

If you want to set specific version of EG, you can set the image tag of EG in install.yaml.

**Comment by danehans** [comment]
As @Xunzhuo mentions, you can use the `latest` release or when v0.3 is released, you will upgrade using:
```
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/v0.3.0/install.yaml
```
