### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#73]
Linting should be added to the project. Ideally it can be run both locally by developers, via a `make` task, and in GitHub Actions.

Suggested tools:
- [x] `golangci-lint` for Go
- [x] `yamlllint` for YAML
- [x] `codespell` (TODO golangci-lint has `misspell`; is that sufficient?)

**Comment by vince-0202** [comment]
Are we going to use Go 1.18?
There seem to be some unresolved issues regarding golangci-lint support for Go1.18.
https://github.com/golangci/golangci-lint/issues/2649

**Comment by danehans** [comment]
@vince-0202 thanks for making us aware of the golangci-lint issue. We currently plan on using go 1.18.2, so this issue is blocked until https://github.com/golangci/golangci-lint/issues/2649 is fixed or if we decide to use go 1.17.x instead.

xref: https://github.com/envoyproxy/gateway/pull/72/files#diff-868425f4c6dd9927d83974d334ea46b9ec96854cdac9bb15b15f43bc4ad17820R6

**Comment by lianghao208** [comment]
>  so the `golangci-lint` portion of this issue is blocked until [golangci/golangci-lint#2649](https://github.com/golangci/golangci-lint/issues/2649) is fixed or if we decide to use 1.17.x instead.

/assign 

I think we should wait until [golangci/golangci-lint#2649](https://github.com/golangci/golangci-lint/issues/2649) has been fixed.

**Comment by danehans** [comment]
@lianghao208 feel free to assign yourself the issue if you would like to work on it. I suggest using Contour as reference model as I believe it has implemented these linters.

**Comment by lianghao208** [comment]
> @danehans I suggest using Contour as reference model as I believe it has implemented these linters.

Thanks for the suggestion, I've added linters referring to the Contour.

**Comment by danehans** [comment]
Closing as all linters have been added.
