### ISSUE TITLE
Support Authentication Overrides and Defaults

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#731]
#529 allows App Devs to manage request authentication on a per-route rule basis. As a Cluster Admin, I need the ability to:
- Override authentication settings configured by App Dev-managed resources, e.g. HTTPRoutes.
- Apply default authentication settings to App Dev-managed resources, e.g. HTTPRoutes.
- Apply default/override settings to resources I manage, e.g. Gateway, and affect all dependent resources of a specified type, e.g. HTTPRoutes.
- Apply default/override settings to specific subsections of a resource, e.g. HTTPRoute rules 3-5.
- Understand through status, understand what dependent resources are affected by the applied default/override settings (for Cluster Admins and App Devs).

**Comment by danehans** [comment]
__Note__: This issue is backlogged until #529 matures and maintainers understand the pros/cons of the filter approach to implementing request authentication.

**Comment by arkodg** [comment]
closing since this is implemented as part of `SecurityPolicy`
