### ISSUE TITLE
Support `/` style commands to maintain EG Issues and PRs

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#732]
## *Description*

Support `/` style commands to maintain EG Issues and PRs

This is useful for maintainers of Project and contributors from community to mange issues and PRs.

## Status

I have wrote a GitHub Action in my private Repo:

## Available Commands ✨

Commands Usage and Naming follows k8s-ci-bot style, if you are familiar with k8s commands you used in the issues and PRs, you can easily to use them.

### Available Commands in Both Issue and PR ✨

| Command                           | Example                                            | Description                                                                                                  |
| --------------------------------- | -------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| `/[un]assign [[@]...]`            | `/assign`</br>`/unassign`</br>`/assign @Xunzhuo` | Assigns assignee(s) to the PR or issue.                                                                      |
| `/[remove-]milestone [milestone]` | `/milestone v1.0.0`</br>`/remove-milestone`        | Edits the PR or issue milestone. **Milestone need to be created manually in advance.**                       |
| `/[remove-]kind [...]`            | `/kind bug`</br>`/remove-kind doc`                 | Applies or removes the 'kind/*' labels to an PR or issue. **Labels need to be created manually in advance.** |
| `/[remove-]priority`                | `/priority`                                          | Applies or removes the 'priority/*' labels to an PR or issue. **Labels need to be created manually in advance.**                                                                |
| `/area`                         | `/area`                                          | Applies or removes the 'area/*' labels to an PR or issue. **Labels need to be created manually in advance.**                                                                |
| `/hold`                         | `/hold` `/hold cancel`                        | Hold or Unhold the process of Issues and PRs |
| `/[remove-]help`           | `/help`</br>`/remove-help`           | Applies or removes the 'help wanted' labels to an PR or issue.                                               |
| `/[remove-]good-first-issue`      | `/good-first-issue`</br>`/remove-good-first-issue` | Applies or removes the 'good first issue' labels to an PR or issue.                                          |
| `/close`                          | `/close`                                           | Closes an PR or issue.                                                                                       |
| `/reopen`                         | `/reopen`                                          | Reopen an PR or issue.                                                                                       |

### Available Commands Only in PR ✨

| Command                           | Example                                            | Description                                                                                                  |
| --------------------------------- | -------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| `/[un]cc [[@]...]`                | `/cc`</br>`/uncc`</br>`/cc @Xunzhuo`             | Requests a review from the user(s). Must be a Member.                                                        |
| `/[remove-]lgtm`                  | `/lgtm`</br>`/lgtm cancel`                         | Applies or removes the 'lgtm' labels to an PR or issue. **Labels need to be created manually in advance.**   |
| `/[remove-]approve` | `/approve`</br>`/approve cancel` | Applies or removes the 'approve' labels to an PR or issue. **Labels need to be created manually in advance.** |
| `/rebase`                         | `/rebase`                                          | Rebase the this PR to the latest of the branch                                                               |
| `/merge [rebase\|squash]`         | `/merge`</br>`/merge rebase`</br>`/merge squash`   | Merge a PR.                                                                                                  |
| `/retest`                         | `/retest`                                          | Retest all failed test of PR.                                                                                |

### Demo

1. Issues:
![image](https://user-images.githubusercontent.com/48784001/202243239-eabad8f9-3b1e-4ff1-9f6e-22755c65f46d.png)

2. PRs:
![image-1](https://user-images.githubusercontent.com/48784001/202243255-49379d6c-067b-4ca9-8b12-2b17671c1726.png)
![image-2](https://user-images.githubusercontent.com/48784001/202243272-43a673e0-1751-42c5-a36a-2c0b9778d208.png)

**Comment by arkodg** [comment]
ha thanks for building and documenting this out ! will be super useful for this project, would be great if you could add another column mentioning who can perform the action

regarding command names
* prefer `review` over `cc`
* lets not add a `/merge`
* lets pick one between `/approve` and `/lgtm`

**Comment by pydctw** [comment]
I've seen `/lgtm` is used by reviewers (basically anyone) and `/approve` is reserved for maintainers as the final step that triggers automatic merge of the PR in other projects. 

When the community grows, it may be useful to have both `/lgtm` and `/approve` with different privileges. Just a thought.

**Comment by Xunzhuo** [comment]
Thanks @pydctw. Yes and correct l, this is why I use both /lgtm and / approve. /lgtm is for reviewers and /approve is for approvers. 

/merge will merge this PR if we have both /lgtm and /approve, and without /hold

**Comment by danehans** [comment]
> I've seen /lgtm is used by reviewers (basically anyone) and /approve is reserved for maintainers

I agree with this approach.

**Comment by youngnick** [comment]
Note that https://github.com/jpmcb/prow-github-actions also exists and is in use in other repos as well.

I agree with using Prow or a Github-action style replacement if we can.

**Comment by danehans** [comment]
@Xunzhuo the repo now supports this, correct? If not, do you still have time to fix this issue?

**Comment by Xunzhuo** [comment]
Hi @danehans, I plan to work on this in v0.4.0, is it Okay?

**Comment by Xunzhuo** [comment]
FYI: https://github.com/Xunzhuo/kube-prow-bot

**Comment by arkodg** [comment]
@Xunzhuo and others, I have a basic question - can you help me understand the value add for commands like `/lgtm` or `/area` or /`milestone` or `/close` which can be done via clicking the GUI vs typing into the GUI

The ones I find valuable are giving some level of access to a non member / PR owner to kick the CI (`/retest`) or assign a reviewer (`/cc`) to PR or to an issue

**Comment by Xunzhuo** [comment]
close for no plan to work on this anymore
