### ISSUE TITLE
restart gateway ,HandleSubscription  panic

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#734]
*Description*:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1722fb5]

goroutine 842 [running]:
github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).subscribeAndTranslate.func1({{0xc000cce100?, 0xc0009d35e0?}, 0x4e?, 0xc0004021a8?})
	/home/runner/work/gateway/gateway/internal/xds/server/runner/runner.go:131 +0x55
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...](0x0?, 0xc000db9f98?)
	/home/runner/work/gateway/gateway/internal/message/watchutil.go:28 +0xab
github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).subscribeAndTranslate(0xc0016d1e80, {0x1e53990?, 0xc00062fc40?})
	/home/runner/work/gateway/gateway/internal/xds/server/runner/runner.go:121 +0x75
created by github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).Start
	/home/runner/work/gateway/gateway/internal/xds/server/runner/runner.go:73 +0x165

**Comment by Xunzhuo** [comment]
Thanks for raising it, I will take a look later this day.

**Comment by Xunzhuo** [comment]
@zhshw which EG version is used?

**Comment by zhshw** [comment]
> @zhshw which EG version is used?

v0.2.0

**Comment by Xunzhuo** [comment]
Can you provide more context on this? 

Like how to reproduce this, just delete envoy gateway pod and let it recreate one?

@zhshw
