### ISSUE TITLE
Refactory: gateway api translator duplication

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#736]
The gateway API translator has grown too big(nearly 2000 lines now) and has a large amount of duplicated code in it, I'd like to clear it to make it easier to read and maintain.

**Comment by zhaohuabing** [comment]
I would like to take this one.

**Comment by danehans** [comment]
@zhaohuabing Thanks for taking this on. For planning purposes, when do you think you'll be ready to submit a PR?

**Comment by zhaohuabing** [comment]
@danehans I can start to work on this after https://github.com/envoyproxy/gateway/pull/728 has been merged. If everything goes well, I think I can submit a PR for review next week.

**Comment by danehans** [comment]
Sounds great. Thanks for the update.
