### ISSUE TITLE
enforce code coverage thresholds

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#74]
The project should have code coverage reporting and enforce certain levels of code coverage for PRs. https://about.codecov.io/ is a good option that integrates well with GitHub and is free for open-source projects.

**Comment by ethanhanjiahao** [comment]
/accept

I want try to resolve this issue

**Comment by danehans** [comment]
@ethanhanjiahao thanks for your willingness to help. Please assign yourself the issue if you're going to work on it.

**Comment by ethanhanjiahao** [comment]
> @ethanhanjiahao thanks for your willingness to help. Please assign yourself the issue if you're going to work on it.

yeah, but i cannot assign to me. Can you assign the issue to me. I will work on it

**Comment by skriss** [comment]
Still to do: add PR checks that enforce required code coverage #'s.

**Comment by danehans** [comment]
Moving this to backlog since codecov was added but coverage #s are not required.

**Comment by arkodg** [comment]
we are currently at ~60% [code coverage](https://app.codecov.io/gh/envoyproxy/gateway) and this is a decent `threshold` to start off with imho.
based on https://github.com/codecov/codecov-action/issues/554 I'm unsure if `threshold` is supported by the GHA or not. 
Hey @ethanhanjiahao is this something you could further look into and enhance in our CI ?

**Comment by ethanhanjiahao** [comment]
> we are currently at ~60% [code coverage](https://app.codecov.io/gh/envoyproxy/gateway) and this is a decent `threshold` to start off with imho. based on [codecov/codecov-action#554](https://github.com/codecov/codecov-action/issues/554) I'm unsure if `threshold` is supported by the GHA or not. Hey @ethanhanjiahao is this something you could further look into and enhance in our CI ?

yes， i can enhance it

**Comment by danehans** [comment]
@ethanhanjiahao can you please confirm if you can fix this issue by the [v0.2.0 milestone](https://github.com/envoyproxy/gateway/milestone/6)?

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/513

**Comment by arkodg** [comment]
reopening this issue since a drop a coverage didn't manage to fail the CI check (seen https://github.com/envoyproxy/gateway/pull/728#discussion_r1042709751)

**Comment by ethanhanjiahao** [comment]
> reopening this issue since a drop a coverage didn't manage to fail the CI check (seen [#728 (comment)](https://github.com/envoyproxy/gateway/pull/728#discussion_r1042709751))

oddly, fork main to my own repo, it is ok.  I make a test https://github.com/ethanhanjiahao/gateway/pull/2, coverage is down to 36.88%, CI failed.

**Comment by danehans** [comment]
Moving to v0.4 since no one is assigned to this issue and it's not a release blocker.

**Comment by arkodg** [comment]
codecov maintainers suggested that we run the Codecov Github App
https://github.com/codecov/codecov-action/issues/554#issuecomment-1450726667

**Comment by arkodg** [comment]
> codecov maintainers suggested that we run the Codecov Github App
> [codecov/codecov-action#554 (comment)](https://github.com/codecov/codecov-action/issues/554#issuecomment-1450726667)
> @lizan can you help install this ?

@mattklein123 @phlax can you help install the CodeCov Github App for this repository so we can ensure code coverage thresholds kick in, TIA !

**Comment by mattklein123** [comment]
Should be installed now.
