### ISSUE TITLE
Invalid escape character in command line help document

### ISSUE THREAD

**Issue by thredreams** [envoyproxy/gateway#742]
*Description*:
In fact, I don't quite understand why only the Target part is normal when I type `make help`，while the escape characters in the Usage and Options parts are not displayed properly

Correct display: (This is the result of my modification)
![image](https://user-images.githubusercontent.com/44553414/203098632-7940b70e-b04e-4018-900f-d8e187cb31ff.png)
![image](https://user-images.githubusercontent.com/44553414/203098815-19c619fe-38ce-483a-89fe-902d1cb83349.png)

Display in My Terminal

![image](https://user-images.githubusercontent.com/44553414/203098248-4642d445-b016-4c93-b26a-e9da65287875.png)
![image](https://user-images.githubusercontent.com/44553414/203098863-580c4d0d-d8a6-40d6-9ece-b6bf92e4c9f4.png)

*Repro steps*:
This problem exists in both zsh and bash

**Comment by Xunzhuo** [comment]
Thank you @thredreams, can you sign your commit and push it again?

**Comment by thredreams** [comment]
OK, I will sign it tomorrow and push again

**Comment by thredreams** [comment]
`cat /etc/redhat-release`
> "CentOS Linux release 7.9.2009 (Core)"

`cat /proc/version`
> "Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) \#1SMP Mon Oct 19 16:18:59 UTC 2020"

**Comment by Xunzhuo** [comment]
The issue is In different OS, like in darwin(macos), this issue will not appear. And if you add the -e, the log will looks:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/48784001/203215117-3a426fc1-31d2-4b2a-bb94-71b72f8fa33b.png">
There will be an extra -e in the start.

**Comment by Xunzhuo** [comment]
You can just add `SHELL=/bin/bash` at common.mk @thredreams.

This can solve this issue : )
