### ISSUE TITLE
Infra Manager updates Service failed and trigger svc/deployment wrongly

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#746]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Infra Manager updates Service Failed and Wrongly

+ Update Service Failed:
<img width="1078" alt="企业微信截图_ef8a2076-e871-4aa0-8b50-3e17f506b6cf" src="https://user-images.githubusercontent.com/48784001/203260562-90b32fab-570c-479c-9a9b-6396ab618c58.png">

It can be reproduced after update Gateway CR.

+ Update Service Wrongly:

We should not simply use deep copy to compare if svc has changed: https://github.com/envoyproxy/gateway/blob/main/internal/infrastructure/kubernetes/service.go#L95

We should just compare a couple of specific vars. (Some vars in svc spec are fullfiled by k8s itself).

When restarting envoy gateway, without anychanges to gateway CR, it will be updated wrongly.

**Comment by danehans** [comment]
Now that #702 has merged, can you confirm this bug still exists?

**Comment by Xunzhuo** [comment]
Close this since it is not reproduced again.
