### ISSUE TITLE
Latest Install and Quickstart Fails

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#755]
```
$ kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml

error: unable to read URL "https://github.com/envoyproxy/gateway/releases/download/latest/install.yaml", server reported 404 Not Found, status code=404
```

**Comment by Xunzhuo** [comment]
@danehans Can you try it again, to see if this occurs again？

**Comment by danehans** [comment]
@Xunzhuo the install and quickstart now work for me. Was this an issue with GitHub hosting our artifacts?

**Comment by Xunzhuo** [comment]
I am not sure, but I guess is that maybe you apply the latest manifests when latest release workflow is running.

When the latest workflow runs, it will delete the old tag and release, and recreate one.

Maybe you apply the manifests, when the latest release workflow is running and before recreating one. @danehans

**Comment by danehans** [comment]
OK. Something for us to keep an eye out for. Thanks for the feedback.
