### ISSUE TITLE
can't get $NVOY_SERVICE Name

### ISSUE THREAD

**Issue by misstick86** [envoyproxy/gateway#765]
*Description*:
> I can't get $(NVOY_SERVICE) name. this is error. 

```
➜  ~ export ENVOY_SERVICE=$(kubectl get svc -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gateway-namespace=default,gateway.envoyproxy.io/owning-gateway-name=eg -o jsonpath='{.items[0].metadata.name}')
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}
```

*Environment*:
- k8s: minikube k8s-1.24
- version: latest and v0.2

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by Xunzhuo** [comment]
What is the result of `kubectl get svc -n envoy-gateway-system`?

**Comment by danehans** [comment]
@misstick86 ^ means that the Envoy service was not created. If you're following the [v0.2 quickstart](https://gateway.envoyproxy.io/v0.2.0/user/quickstart.html), have you `kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/v0.2.0/quickstart.yaml`? If so, please check the status of the GatewayClass/Gateway resources and EG logs for further analysis.

**Comment by misstick86** [comment]
@danehans get it. but, it's kinda embarrassing.  i reinstall gateway follow document after reinstalled k8s. it's totally ok.

**Comment by danehans** [comment]
Reinstalling EG and/or k8s should not be required but I'm happy you resolved your issue.
