### ISSUE TITLE
Make debug the default tag for the distroless image

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#776]
Use `debug` and replace the tag with `nonroot` when cutting a release (including `latest`).

**Comment by danehans** [comment]
This could help increase developer velocity.

**Comment by arkodg** [comment]
looks like we can achieve the goal of better debuggability using client tools such as egctl that is being worked on right now
changing the image might introduce changes in user expectations as well as might surprise the user due to the image inconsistencies, so prefer if we didn't support this

**Comment by arkodg** [comment]
@danehans can we close this ?
