### ISSUE TITLE
Enable GatewayInvalidRouteKind conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#782]
*Description*:

Seeing this conformance test fail in in https://github.com/envoyproxy/gateway/pull/780

Once fixed it should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by LanceEa** [comment]
@arkodg - Happy to pick this one up if it is still open.

**Comment by arkodg** [comment]
hey @LanceEa thanks for picking this one up !
