### ISSUE TITLE
Enable HTTPRouteInvalidParentRefNotMatchingListenerPort conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#784]
*Description*:
Seeing this conformance test fail in in https://github.com/envoyproxy/gateway/pull/780

Once fixed it should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by sunjayBhatia** [comment]
see https://github.com/kubernetes-sigs/gateway-api/pull/1589

**Comment by arkodg** [comment]
thanks for fixing this upstream @sunjayBhatia ! this issue can hopefully be resolved when the upstream fix is part of the v0.6.0 release and EG bumps its GWAPI dependency to v0.6.0 from v0.6.0-rc1

**Comment by arkodg** [comment]
looks like the issue still exists in v0.6.0-rc2 and is most likely an issue in this project's implementation
hoping someone from the community can further triage this

**Comment by skriss** [comment]
I can take this one.
