### ISSUE TITLE
ir.RouteDestination weight  ?

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#786]
*Description*:

```go
type RouteDestination struct {
	// Host refers to the FQDN or IP address of the backend service.
	Host string
	// Port on the service to forward the request to.
	Port uint32
	// Weight associated with this destination.
	// Note: Weight is not used in UDP route.
	Weight uint32
}
```

In fact, there are 2 cases, 0 and nil
-  Weight 0, which is actually a legal input
-  Weight == nil ，no setting required

**Comment by Pawan-Bishnoi** [comment]
Hi @zhshw 
Could you clarify the issue here? 🤔 
Are you saying 0 and null are being treated the same when they shouldn't be?

**Comment by muyuan0** [comment]
Can the `Weight` be nil? It is an integer.

**Comment by arkodg** [comment]
the issue here is , weight may be optionally set by the caller, so it should ideally be a pointer type,
and if unset by the caller (`nil`), the xDS layer should choose the right default

**Comment by muyuan0** [comment]
I have updated https://github.com/envoyproxy/gateway/pull/1104 to fix this issue.
