### ISSUE TITLE
EDS + endpoint slow start Support

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#787]
*Description*:
There are many types of programs that start slowly and require the flow control of the Pod Endpoint.
envoy supports slow start config feature

**Comment by arkodg** [comment]
@zhshw can you please elaborate on why EDS is needed for the slow start feature ?
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-slowstartconfig

We build static clusters in this project, and when a service endpoint changes, it will be reconciled by the controller, translated into an xds cluster and then, only the updated cluster will be pushed to envoy via delta xds

**Comment by zhshw** [comment]
> 
@arkodg  For example, many Java applications start very slowly, requiring a flow warm-up process.
This is a problem that many people will face when practicing cloud native process, so aws ALb takes the lead in supporting and envoy implements Istio also supports configuration changes
service -> Pod endpoints -> lbEndpoints , envoy lbEndpoint support slow start

**Comment by arkodg** [comment]
there is no strong use case for [EDS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration#eds) yet

but the [slow start](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-slowstartconfig) feature is a valid use case that I believe is separate. It is however blocked by https://github.com/envoyproxy/gateway/issues/35

**Comment by arkodg** [comment]
reopening this issue, as the use case for incorporating EDS is to seamlessly update endpoints without disrupting existing upstream connections associated with the Cluster.

**Comment by zirain** [comment]
FYI, `EDS` will be helpful on case like https://github.com/istio/istio/issues/43575
