### ISSUE TITLE
Add Request Authentication Support

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#790]
- [x] Design user-facing API for authentication requests (#336).
- [x] Add API support to Kube provider.
- [x] Add API support to gatewayapi translator.
- [x] Add API support to IR.
- [x] Add API support to xds translator and server.
- [x] Update user docs with config example.
- [ ] E2E testing.

**Comment by zhshw** [comment]
envoy auth filiter need define request body buffer **MaxRequestBytes**

**Comment by danehans** [comment]
@zhshw does a default value exist for MaxRequestBytes? If not, what is an appropriate default value? We should also consider the min/max values too.

**Comment by arkodg** [comment]
@danehans any idea on how E2E will be implemented for this feature ?

**Comment by danehans** [comment]
@arkodg my thoughts are:
- Use the kind cluster from the conformance tests for running e2e testing.
- Mock a JWKS in our e2e testing package.
- Create an HTTP request that contains a JWT.
- Create a test backend app, Gateway, HTTPRoute, AuthenticationFilter, etc.
- Send the request to the Gateway.

**Comment by danehans** [comment]
This feature is shipping in v0.3 with manual testing (see [authn](https://gateway.envoyproxy.io/latest/user/authn.html) user doc). Moving to v0.4.0-rc.1 to add e2e testing.
