### ISSUE TITLE
proposal new tool named `egctl`

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#794]
tracking for https://github.com/envoyproxy/gateway/pull/749#issuecomment-1343762241, will update details later.

**Comment by danehans** [comment]
@zirain I can move the Milestone to v0.3.0-rc.1 if you expect to have a PR ready in time.

**Comment by zirain** [comment]
@danehans let's get design doc merged first.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/gateway/pull/797
