### ISSUE TITLE
How to Organize API Types

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#809]
Currently, EG API types reside in 2 locations:
- Envoy Gateway and Envoy Proxy configuration: `api/config/v1alpha1`.
- Extended functionality: `api/v1alpha1`.

This makes imports a bit confusing:
```
import (
	egv1a1 "github.com/envoyproxy/gateway/api/v1alpha1"
	egcfgv1a1 "github.com/envoyproxy/gateway/api/config/v1alpha1"
)
```

It's unclear what API types are being imported from `github.com/envoyproxy/gateway/api/v1alpha1`.

**Comment by danehans** [comment]
From the 5/13/22 EG [community call](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing), @youngnick proposes:
> I recommend keeping all the types in the version directory (eg v1alpha1), with validation, helper, or utility code in subdirectories.

**Comment by danehans** [comment]
My recommendation slightly differs from the above. I suggest having separate config and extension API groups. Helper functions, validation, etc. will live within each group for the associated types. This allows versioning the extension types separately from the config types. For example, the EnvoyProxy type can graduate faster than extension API types since they may be more widely used. Additionally, it simplifies transitioning the extension APIs into a separate repo.

Thoughts @youngnick

**Comment by zirain** [comment]
+1 to `egv1 "github.com/envoyproxy/gateway/api/v1alpha1"` or `egv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"`

**Comment by youngnick** [comment]
@danehans, I think that's fine, although I suggest standardizing the import names to make reading the code easier.

**Comment by danehans** [comment]
@arkodg @AliceProxy @Xunzhuo @skriss please comment if you have issue with the approach in https://github.com/envoyproxy/gateway/issues/809#issuecomment-1352277995.

**Comment by arkodg** [comment]
@danehans i think theres a typo in the issue description -  `Extended functionality: api/v1alpha1`
as @zirain suggested I prefer all EG APIs to live under  `api/v1alpha1` under the same group for now so there are lesser groups to revision

**Comment by danehans** [comment]
> i think theres a typo in the issue description

@arkodg thanks for catching this. I updated the description.

> I prefer all EG APIs to live under api/v1alpha1 under the same group for now so there are lesser groups to revision

If our long-term intention is for extensions to live outside of the EG repo, they'll be revisioned separately.

**Comment by arkodg** [comment]
this was discussed in the community meeting today
@AliceProxy and I are in agreement to move the `config.gateway.envoyproxy.io` to `gateway.envoyproxy.io`
https://github.com/envoyproxy/gateway/blob/main/api/config/v1alpha1/groupversion_info.go#L15 in v0.5.0.

This will be a breaking change for users using EnvoyProxy today.

@envoyproxy/gateway-maintainers, would be great if you can 👍 👎  ?

**Comment by kflynn** [comment]
Until we're at 1.0.0, we should not be afraid of breaking changes. Go for it.

**Comment by AliceProxy** [comment]
> Until we're at 1.0.0, we should not be afraid of breaking changes. Go for it.
+1 for callpsing everything into `gateway.envoyproxy.io` and making the breaking change without a deprecation policy or any kind of "migration". Nobody should be running this in production right now.

**Comment by zirain** [comment]
@envoyproxy/gateway-steering-committee @envoyproxy/nighthawk-maintainers we need a certain policy for support and deprecation.

**Comment by arkodg** [comment]
@zirain deprecation policy is being tracked with https://github.com/envoyproxy/gateway/issues/714
