### ISSUE TITLE
Provide a Certificate Management Solution

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#81]
A certificate management solution is needed for users to run EG beyond test/dev. The following are requirements that the cert management should meet:

- Integrate well with Kubernetes.
- Provide a simple process for obtaining, renewing, and using certificates.
- Issue certificates from a variety of sources, e.g. Vault.
- Be well documented.
- Be a well-maintained OSS project with a diverse community of contributors.
- Preferably, integrate with Gateway API to generate certificates for Gateway resources.
- Others?

**Comment by vince-0202** [comment]
cert-manager seems like a good choice.
[cert-manager](https://cert-manager.io/)

**Comment by danehans** [comment]
@vince-0202 agreed.

**Comment by danehans** [comment]
An EG example should be added to the Cert-Manager docs when this issue is resolved.

xref: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/

**Comment by danehans** [comment]
Note that cert-manager now has support for Gateway API: https://gateway-api.sigs.k8s.io/implementations/#cert-manager

**Comment by arkodg** [comment]
cert manager integration docs are in https://gateway.envoyproxy.io/latest/user/tls-cert-manager.html, closing this issue
