### ISSUE TITLE
Remove Bypassing Gateway API Manifest YAML Linting

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#810]
Remove bypassing Gateway API manifest YAML linting when `https://github.com/kubernetes-sigs/gateway-api/issues/1600` is resolved.

xref: https://github.com/envoyproxy/gateway/pull/808

**Comment by arkodg** [comment]
has been fixed upstream with https://github.com/kubernetes-sigs/gateway-api/pull/1749 and these lines https://github.com/envoyproxy/gateway/blob/4adbc2a97065bbb997aaf2850e43224bcdf4ffab/tools/linter/yamllint/.yamllint#L3 should be removed when gateway api v0.7.0 has been brought in
