### ISSUE TITLE
Fix remaining WARNINGs seen while running `make docs`

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#814]
*Description*:
Some WARNINGS are seen while executing `make docs`. Some of these have been fixed with https://github.com/envoyproxy/gateway/pull/806 but some still remain

```
docs/v0.2.0/dev/releasing.md:7: WARNING: duplicate label prerequisites, other instance in  ../v0.2.0/dev/README.md

```

and

```
../docs/v0.2.0/design/config-api.md:19: WARNING: 'myst' reference target not found: #goals

```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```
make docs
```

**Comment by haq204** [comment]
If no one is working on it, I can take this one.
