### ISSUE TITLE
Replace WatchableMap with FIFO Queue as primary synchronous transmission queue

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#815]
*Description*:
>Describe the issue.

when the complexity of the project increases, out of order subscriptions will trigger many incredible bugs。
unfortunately , watchmap does not run in FIFO mode.....

watchmap
- If the consumption is not completed, the same key and vlaue will be overwritten
- disordered consumption process

**Comment by arkodg** [comment]
there are many advantages of using a map here, such as if a user updates the map, but the contents of the map have not changed, the subscriber will not be notified of any update, such a pattern is very useful in terms of performance when this is high churn in the control plane

regarding code complexity, https://github.com/telepresenceio/watchable is used by other projects (such as telepresence) in production so it can be considered stable

**Comment by zhshw** [comment]
@arkog Data subscription should follow the basic principle of first in, first out。
The number of users in this project is not important. The reality is that it is an unordered map

**Comment by zhshw** [comment]
@arkodg  The string of the protobuf message can be used to determine the equality to skip duplicate data. The storage mode of xdscache can be map or other distributed storage, but the transmission queue should follow the basic principles when assembling data synchronously.
