### ISSUE TITLE
Consider disabling stalebot

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#820]
*Description*:
Stalebot was [added](https://github.com/envoyproxy/gateway/pull/130) to periodically close stale issues.
At the time of approving this, I thought this was a good idea, but as a maintainer, I find myself spending cycles either reopening issues closed by `stalebot` that it considers stale, that are not (some GH issues around APIs and design take time, some dont), or rechecking closed issues to see if they're relevant or not.

With or without the presence of `stalebot`, members of this project will need to invest cycles in reviewing **all** GH issues, and will need to accept that we might take time to review all opened GH issues.

For the reasons stated above, I prefer if we disable stalebot.

**Comment by zirain** [comment]
+1 for disable it, because EG still in the early stages

**Comment by arkodg** [comment]
> An alternative may be adding the stale label but not closing.

thanks for the suggestion @mohe2015 , its a good hybrid approach allowing us to quantity the life of a GH issue without losing track of it.

**Comment by danehans** [comment]
> An alternative may be adding the stale label but not closing.

+1
