### ISSUE TITLE
support websocket 

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#836]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
Plz provide more infos, then we can have a deep understanding on the background of this issue.

**Comment by qicz** [comment]
the current eg version cannot support WebSocket requests that are missing upgrade configs for this. just this. @Xunzhuo

**Comment by danehans** [comment]
Moving to the backlog since https://github.com/kubernetes-sigs/gateway-api/issues/205 must be resolved before this feature can be implemented.

**Comment by zhshw** [comment]
@danehans  HTTPRoute add annations ,like this can imp websocket、timeout、retry......
`
 route.Annotations["envoy-gateway/upgrade-websocket"]
`

routeAction setting UpgradeConfig
`
if isWebsocket {
  routeAction.UpgradeConfigs = []*route.RouteAction_UpgradeConfig{{
	  UpgradeType: "websocket",
  }}
}

`

**Comment by arkodg** [comment]
@zhshw annotations lack structure needed to correctly validate intent, we prefer adding support using explicit fields instead

**Comment by zhshw** [comment]
@arkodg 
Explicit fields may not be necessary, but annotations are the simplest and most practical way to be compatible with HTTPRoute.

Backendref serivce can be an associated Envoy route kind. Use the Envoy xds route field as a richer configuration, rather than losing a large number of useful configurations for the translator

**Comment by luofish** [comment]
@arkodg  it's a feature request, maybe we can use anno instead before explicit fields be designed

**Comment by crain-cn** [comment]
@arkodg it's a feature request, maybe we can use anno instead before explicit fields be designed

**Comment by arkodg** [comment]
it looks like envoy allows web socket upgrade https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket which should be easy to achieve using this config in HCM
```          
upgrade_configs:
          - upgrade_type: websocket
```

and it looks like istio enables this by default, so leaning towards enabling this by default for HTTP 1.1 (HTTPRoute), upgrades are disallowed for HTTP 2.0 (GRPCRoute)

**Comment by zhshw** [comment]
@arkodg This is a crude way to violate the semantics that it is an optional value. Most projects are set up on demand。
This default value, istio is not worth learning
