### ISSUE TITLE
support upstream tls

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#837]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
Plz provide more infos, then we can have a deep understanding on the background of this issue.

**Comment by qicz** [comment]
the current eg version can not support upstream HTTPS, when a request  call the upstream with HTTPS the following error occurs
`Client sent an HTTP request to an HTTPS server.`  

@Xunzhuo

**Comment by danehans** [comment]
Moving to the backlog since the dependent upstream issue, kubernetes-sigs/gateway-api#91, is not fixed.

**Comment by arkodg** [comment]
above issue is reg downstream TLS, https://github.com/kubernetes-sigs/gateway-api/issues/1067 tracks upstream TLS from gateway to backend

**Comment by qicz** [comment]
using annotation or labels like `upstream/tls: true` supports upstream tls before gwapi support?

**Comment by arkodg** [comment]
this is being addressed in upstream https://github.com/kubernetes-sigs/gateway-api/pull/1906 right now, lets wait for upstream to define this feature

**Comment by arkodg** [comment]
closing in favor of https://github.com/envoyproxy/gateway/issues/2033
