### ISSUE TITLE
Release Manager Rotation

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#846]
Establish a process for rotating the release manager responsibilities among maintainers.

**Comment by arkodg** [comment]
vote in favor of rotating between all current maintainers, and hoping we can leverage the existing envoy automations in place to help with this.

**Comment by Xunzhuo** [comment]
I`d like to help release v0.3.0, it is the first release of v0.3.0 docs and I am familiar with it, let me check the docs release workflow is working well.

**Comment by danehans** [comment]
@Xunzhuo it would be much appreciated if you can be the v0.3 Release Manager. If so, please submit a PR to add your name and GH ID to https://github.com/envoyproxy/gateway/tree/main/docs/latest/releases.

__Note:__ During yesterday's [community meeting](https://docs.google.com/document/d/1leqwsHX8N-XxNEyTflYjRur462ukFxd19Rnk3Uzy55I/edit?usp=sharing), we decided to push back the [0.3.0-rc.1](https://github.com/envoyproxy/gateway/milestone/7) and [0.3.0](https://github.com/envoyproxy/gateway/milestone/9) releases.
