### ISSUE TITLE
Add YAML directories for YAML linter

### ISSUE THREAD

**Issue by lianghao208** [envoyproxy/gateway#85]
related PR: #79 

We need to add YAML directories for YAML linter after the YAML directories have been determined.

https://github.com/envoyproxy/gateway/pull/79/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R21

**Comment by Plataformaalgoritmica** [comment]
Hello World.

**Comment by daixiang0** [comment]
https://github.com/envoyproxy/gateway/tree/main/tools/yamllint created, I think it can be closed.

**Comment by lianghao208** [comment]
@daixiang0 We need to add YAML directories as args for YAML linter in Makefile:
https://github.com/envoyproxy/gateway/blob/main/Makefile.targets.mk#L58
This issue can be closed after the YAML directories have been determined and the directories args has been added into Makefile.

**Comment by daixiang0** [comment]
Oh, I misunderstand the dir for.

**Comment by danehans** [comment]
@lianghao208 the current yaml dirs are:

https://github.com/envoyproxy/gateway/tree/main/internal/provider/kubernetes/config
https://github.com/envoyproxy/gateway/tree/main/internal/provider/testdata/in
https://github.com/envoyproxy/gateway/tree/main/internal/envoygateway/config/testdata/decoder/in
https://github.com/envoyproxy/gateway/tree/main/internal/gatewayapi/testdata

Are you able to submit a PR to update the yaml linter?

**Comment by lianghao208** [comment]
> @lianghao208 the current yaml dirs are:
> 
> https://github.com/envoyproxy/gateway/tree/main/internal/provider/kubernetes/config https://github.com/envoyproxy/gateway/tree/main/internal/provider/testdata/in https://github.com/envoyproxy/gateway/tree/main/internal/envoygateway/config/testdata/decoder/in https://github.com/envoyproxy/gateway/tree/main/internal/gatewayapi/testdata
> 
> Are you able to submit a PR to update the yaml linter?

Sure, I am working on it, thanks for the reminder.
