### ISSUE TITLE
Ratelimit based on JWT claims

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#851]
*Description*:
Client information is usually stored as JWT Claims.
Add support for ratelimiting clients who can be selected based on JWT claim values
Relates to https://github.com/envoyproxy/gateway/issues/670

**Comment by tmsnan** [comment]
Hi, I can work on this feature, Please assign to me if it is Okay.

**Comment by zirain** [comment]
thanks @tmsnan , anything you need help, please let us know.
