### ISSUE TITLE
Necessary data check of envoy listener

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#854]
*Description*:
data:
-  default-eg listerner

Envoy server listener has some input restrictions. If the data rules are not followed, the data pushed by xds will not take effect。

- unique domain：If multiple httproutes of the same domain name are not checked, it will be triggered bug
- unique route cluster: If the same service exists for multiple rules of httproute，this restriction will be triggered bug。currently the cluster is named by rule index，however there are **duplicate cluster data**。If change the route naming rules, should pay attention to
- all route weight total  > 0:   if multiple backend service weights of an httproute rule all are 0，it will be triggered bug

**Comment by arkodg** [comment]
@zhshw would really help if you could share steps and config to repro the issue, thanks
