### ISSUE TITLE
Enhance go doc comments for RateLimitFilter

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#857]
*Description*:
address follow up comments shared in https://github.com/envoyproxy/gateway/pull/706 for enhancing the documentation for the rate limit API

**Comment by danehans** [comment]
https://github.com/envoyproxy/gateway/commit/4fdbb22e78bcec6c6d17ddeee22868241c29bd3c#r94976226 should be resolved in the PR that fixes this issue.

**Comment by zirain** [comment]
fixed by #922
