### ISSUE TITLE
refactor status conditions logic for Gateway API resources

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#860]
*Description*:
The GatewayClass and Gateway logic for computing status conditions lives here
https://github.com/envoyproxy/gateway/blob/main/internal/status/conditions.go

and the logic for Routes lives here
https://github.com/envoyproxy/gateway/blob/085e6fa5a56066472a52e8c07bc1aefa3ffca5a2/internal/gatewayapi/contexts.go#L89

These should be consolidated to one place for improving code reuse

**Comment by Pawan-Bishnoi** [comment]
Hi @arkodg 
I would like to work on this.
Seems like we would be able to remove duplicate code by changing SetCondition to something like this:

```
func (l *ListenerContext) SetCondition(conditionType v1beta1.ListenerConditionType, status metav1.ConditionStatus, reason v1beta1.ListenerConditionReason, message string) {
	cond := conditions.NewCondition(...)

        l.gateway.Status.Listeners[l.listenerStatusIdx].Conditions = conditions.MergeConditions(l.gateway.Status.Listeners[l.listenerStatusIdx].Conditions, cond)
}
```
Does that sound ok? Any other ideas?

**Comment by Pawan-Bishnoi** [comment]
actually that would cause an import cycle. Let me think about this a bit more tomorrow.
