### ISSUE TITLE
E2E framework for Gateway API Extensions

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#863]
*Description*:
With features such as Authentication and Rate Limiting being supported using Gateway API extensions, we
need to add end to end tests to verify the API and ensure there are no regressions.

Raising this issue to decide which test framework to use, that individual features will need to implement before considering them complete.

**Comment by arkodg** [comment]
related https://github.com/envoyproxy/gateway/issues/790#issuecomment-1382308507

**Comment by danehans** [comment]
Required for AuthenticationFilter and RateLimitFilter.
