### ISSUE TITLE
Finalize EnvoyProxy

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#865]
When https://github.com/envoyproxy/gateway/pull/861 merges, the EnvoyProxy custom resource can be used to customize the managed proxy infrastructure through `gatewayclass.spec.parametersRef`. Deleting the EnvoyProxy referenced by a managed GatewayClass can result in significant unintended consequences. Should EG finalize an EnvoyProxy referenced by a managed GatewayClass to avoid this potential issue?

**Comment by AliceProxy** [comment]
+1 For finalizing the EnvoyProxy resource after startup.

**Comment by cnvergence** [comment]
I would like to take a look at this one :)

**Comment by zirain** [comment]
@cnvergence assign this to you

**Comment by AliceProxy** [comment]
completed via #1534
