### ISSUE TITLE
docs: allow users to configure custom certs for control plane auth

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#866]
*Description*:
https://github.com/envoyproxy/gateway/pull/208 added support for control plane auth in the project, by introducing a job to generate self signed certs and configure them in envoy gateway and envoy proxy.

However users might want to create and plug in their own custom certs for control plane auth (between envoy gateway and envoy proxy)

Relates to https://github.com/envoyproxy/gateway/issues/862

**Comment by zirain** [comment]
what about support [cert-manager](https://cert-manager.io/docs/)?

**Comment by Xunzhuo** [comment]
Should we close this by already adding https://gateway.envoyproxy.io/latest/user/security/tls-cert-manager ?

**Comment by Xunzhuo** [comment]
cc @arkodg

**Comment by arkodg** [comment]
this is control plane certs, we still need a user doc for this
