### ISSUE TITLE
Separate codebases and docs of Envoy Gateway

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#876]
*Description*:

After releasing v0.3.0, I have a worry for doc release. The current logics of doc releasing, cutting off docs in every release, this is a common versioned doc solution same as envoy website. 

But compared with the envoy-website, envoy-website separates envoy codebase and its docs, but eg is not and the docs repeatedly increases and gets larger and larger. It will break the structure of our repo, we repo will contain many docs because we will copy/paste/update it every release.

For a long way, I suggest separate docs with our codebases, like open another separated repo for managing eg docs.

cc @mattklein123

**Comment by mattklein123** [comment]
Sorry I'm having trouble parsing ^. I would do whatever makes sense for the project documentation wise.

**Comment by danehans** [comment]
I'm in favor of separating the docs. I think the question is when to do this and the priority level of the work. The other option is that docs are published only for `latest` and the latest tagged release, e.g. `v0.2.0`. Thoughts?

**Comment by arkodg** [comment]
agree that the split is needed, might make more sense to do it in the future when we have dedicated owners for components (like `docs`), for now keeping it in this repo ensures that the content can be reviewed by the reviewers of this repo

**Comment by danehans** [comment]
@Xunzhuo during today's community meeting, concern was expressed about this issue. I have moved this to the backlog until these concerns are resolved.

**Comment by kflynn** [comment]
I'd vote for leaving the docs and the code in the same repository as long as possible, actually, in line with @arkodg's comment above.

While I was at Ambassador Labs, we wrestled with this quite a lot for various reasons, and even flipped between separate repos and the same repo a couple of times. Overall, my experience has been that having code and docs in the same repo is a huge win for the developers (who benefit tremendously by being able to update code and docs in a single PR), and having them in a separate repo is really only a win if you have a separate (less-comfortable with Git) team working only on documentation.

In the case of Envoy Gateway, I don't see a separate docs-only team happening in the near future, so I'd vote strongly for making the devs' lives easier by keeping everything in the same repo.

**Comment by mattklein123** [comment]
FWIW I'm +1 on @kflynn comment, though I would support whatever the team wants to do.

**Comment by haq204** [comment]
Echoing @kflynn, I'm more in favor with keeping in docs and code in the same repository. In my experience I find it's way easier to keep code and docs in sync when its in the same repo since you can update docs in the same PR as the code change and its something that can be enforced in code review.

**Comment by RRobot-lm** [comment]
Maybe what we need is a new website generator that supports fetching sources from different git branches.

Currently, the generator will iterate all docs directories: https://github.com/envoyproxy/gateway/blob/main/tools/make/docs.mk. That's why the docs from the old releases need to be kept in the main branch.

Another solution is to rewrite the current generator to clone this repo from release branches, so the multiple versions of docs will be just built artifacts.

**Comment by arkodg** [comment]
based on the comments in this GH issue, closing this for now
