### ISSUE TITLE
Support Route timeout And Cluster connect timeout configure

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#877]
*Description*:

Timeout is a user-defined prerequisite。

Each service has different requirements for timeout. In fact, many similar gateway projects support defining timeout through annotations or spec resources.

The default values for different functions of the current code are also inconsistent...

**Comment by danehans** [comment]
Gateway API defines [Policy Attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/#policy-attachment) as a mechanism for exposing these configuration settings. EG would need to define and implement a resource that conforms to the Policy Attachment spec.

**Comment by danehans** [comment]
@zhshw please let us know if you're willing to work on this enhancement.

**Comment by AliceProxy** [comment]
Big plus 1 on addind support for more of the different kinds of timeouts that Envoy allows us to configure. Eventually I'd like to see gatewayAPI add fields for this directly into the CRDs, but as @danehans mentions [Policy Attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/#policy-attachment) is probs the way to go until that day happens.

**Comment by arkodg** [comment]
related upstream issue https://github.com/kubernetes-sigs/gateway-api/issues/1742

**Comment by saurabh-tiket** [comment]
Hi Guys, I'm facing the same issue, my upstream service is taking more than 15 seconds and I am not able to find a way this timeout, can someone help me understand if it is possible to change the upstream HTTPRoute timeout value? I'm stuck on this.

**Comment by zirain** [comment]
Upstream update: https://github.com/kubernetes-sigs/gateway-api/pull/2013

**Comment by arkodg** [comment]
the upstream timeout API has moved to `Experimental` and we should have access to the CRD fields once gateway-api v1.0.0-rc-1 releases https://github.com/kubernetes-sigs/gateway-api/blob/f98e94a5305e3a08cb14f8a03470f8f3bdf6d54c/apis/v1beta1/httproute_types.go#L277

**Comment by arkodg** [comment]
keeping this issue open to track highlighting this feature in our docs
