### ISSUE TITLE
code refactor: support features in xds layer using XdsPatch interface 

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#882]
*Description*:
As we continue to enhance the [xds translator](https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/translator.go) to support more features, the code might become more complex, less readable and harder to maintain. 

One solution to this problem is to create a Patch interface so API Gateway feature libraries can patch in their translations to xds objects (listener, hcm, cluster) so the code is modular and more readable ,

**Comment by zirain** [comment]
are you talking about something like [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/)

**Comment by arkodg** [comment]
no was referring to formalizing this interface call https://github.com/envoyproxy/gateway/blob/fb0c155f629ef72c8f7a7c7ccf9089bdad6680b2/internal/xds/translator/listener.go#L95

**Comment by youngnick** [comment]
So, this is a _developer_ convenience, not a end user feature? If so, sounds good to me.

**Comment by arkodg** [comment]
thanks for moving this in the Backlog, this is a good to have, and is not needed for the 0.3.0 release

**Comment by arkodg** [comment]
completed with https://github.com/envoyproxy/gateway/pull/2210
