### ISSUE TITLE
Enable GatewayClassObservedGenerationBump conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#883]
*Description*:
Seeing this conformance test fail in in https://github.com/envoyproxy/gateway/pull/780

Once fixed it should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by danehans** [comment]
This is the last 0.6.0 conformance test that is failing.

**Comment by Xunzhuo** [comment]
See: https://kubernetes.slack.com/archives/CR0H13KGA/p1673599220709819.

**Comment by danehans** [comment]
Waiting for gw api v0.6.1 to drop.
