### ISSUE TITLE
Add Envoy Gateway as an addon to KubeVela

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#887]
*Description*:

I am working on adding EG as an addon to [KubeVela](https://github.com/kubevela/kubevela), an opensource multi-cluster application platform. With this, people can easily install envoy gateway with one click : )

https://github.com/kubevela/catalog/issues/587

https://github.com/kubevela/catalog/pull/588

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/48784001/211708138-024fb1c9-2d3c-4021-9c30-26b103c9fdaa.png">

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/48784001/211708186-c2f6cc58-0364-4aee-9ec5-216217da1456.png">

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/48784001/211708656-2594e5a5-cfb3-4b76-964e-777cfdf3d79b.png">

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/48784001/211708809-60b014d8-5ab7-46fe-a773-36335acb6c9a.png">

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/48784001/211708912-938676c0-754a-4a11-8aa3-f1494d13d9cd.png">

![FireShot Capture 004 - KubeVela-Make shipping applications more enjoyable  - 43 135 81 164](https://user-images.githubusercontent.com/48784001/211710678-dfa6eeb7-8c44-4499-9aab-101507346d98.png)

**Comment by arkodg** [comment]
great stuff @Xunzhuo , thanks for helping increase adoption, please document/raise issues for any gaps you find in this journey

**Comment by danehans** [comment]
@Xunzhuo should an issue be created to document admin/users on how to use this feature?

**Comment by Xunzhuo** [comment]
It should be, but there are still some prerequisite tasks to be solved, and it is in experiment addon now. I think we can add a doc after this addon promotes to be a formal addon.

**Comment by Xunzhuo** [comment]
I am closing this, since EG has been added as an experiment addon in kubevela.
