### ISSUE TITLE
Ensure Latest Release Assets Exist

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#888]
Per [this](https://envoyproxy.slack.com/archives/C03E6NHLESV/p1673392772362589) Slack conversation, a latest release sometimes is created without the install and QuickStart manifests. A step should be added to the release_latest GitHub workflow to curl the expected URLs of these manifests to ensure they exist.

**Comment by arkodg** [comment]
@danehans @AliceProxy  can you help elaborate on the exact issue ? Was a specific path not working ?
We should consider spending a few cycles to triage which links didn't work and why

**Comment by danehans** [comment]
The links to the quickstart and install manifests for the latest release were not working with a 404. The error was observed because both manifests were not posted to the release even though the logs from the CI job showed no errors in doing so. By added a final step that curls the expected URLs ensures the assets exist.

**Comment by Xunzhuo** [comment]
This is random I think, maybe it is an issue of the release action, and it occurs in a low frequency. For now, I think we can just add a check to it, and make us be aware of its failure and rerun it manually, just like the coverage report upload fails occasionally.

**Comment by zirain** [comment]
action fails when there's nothing updated, cc @Xunzhuo 

https://github.com/envoyproxy/gateway/actions/runs/3944677223
https://github.com/envoyproxy/gateway/actions/runs/3944678931

**Comment by Xunzhuo** [comment]
This is why we add check to the latest release workflow, sometime the uploading will fail for some reason, we can be noticed that there is an error occurred.

I close this issue, since the check latest release job works fine.
