### ISSUE TITLE
How to add http2_protocol_options to cluster config

### ISSUE THREAD

**Issue by HoangTheQuyen** [envoyproxy/gateway#890]
*Description*:
> How to add http2_protocol_options to cluster config to it expose http2
{
     "version_info": "966f10db59b985788b55e52922d71a742dcaf876918025fb764bb648a0817013",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "default-tcp-gateway-hello-tcp-app-2",
      "type": "STATIC",
       "http2_protocol_options": {} // **Here**
      "connect_timeout": "5s",
      "dns_lookup_family": "V4_ONLY",
      "outlier_detection": {},
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "load_assignment": {
       "cluster_name": "default-tcp-gateway-hello-tcp-app-2",
       "endpoints": [
        {
         "locality": {},
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "10.96.254.134",
              "port_value": 50051
             }
            }
           }
          }
         ],
         "load_balancing_weight": 1
        }
       ]
      }
     },
     "last_updated": "2023-01-11T08:45:04.084Z"
    }
   ]
  }

[optional *Relevant Links*:]
>

**Comment by HoangTheQuyen** [comment]
@danehans 
As this PR: https://github.com/envoyproxy/gateway/pull/886.
I see isHTTP2: true to enable http2. Default it is false, but I want it to be true, what should I do?

**Comment by arkodg** [comment]
@HoangTheQuyen https://github.com/envoyproxy/gateway/blob/7f3c9b490ed4a370a6279b15b3d22846d176cc9a/internal/ir/xds.go#L132 is an internal implementation detail that cannot be directly set by the user but is set by the system for GRPCRoute based listeners. You should be able to try out the [GRPCRoute feature](https://github.com/envoyproxy/gateway/issues/642) soon with the v0.3.0 release that is scheduled in early Feb 2023.
