### ISSUE TITLE
Split the router controller into independent deployment

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#926]
For different Gateway , envoy is an independent deployment, but the control plane is not split.

Different Gateway target different application groups. Split the HTTPRoute and other route controllers into independent deployment, which can reduce the processing pressure of busy K8S cluster controllers and the risk of new features, Isolate each other to reduce risks such as crash, Can speed up startup

gateway controller -> gateway[ route controller+XDS, envoy]

**Comment by zirain** [comment]
@zhshw I think you have a lot of toughts about EG arch, it will be better to raise up an design docs, then all the maintainers can discuss it.

**Comment by youngnick** [comment]
I agree, thanks @zirain. @zhshw, I'd love to hear _why_ you find the current design lacking, and a great place to start would be a document explaining the problems you see with the design, why you think they are problems, and _then_ what you think we should do about it.

As I said in a comment on another issue, these designs haven't arisen in a vacuum, there are reasons why things the way they are, which may not be immediately apparent.

**Comment by zhshw** [comment]
@youngnick 


In large-scale K8S clusters, some control surface failures are often seen.

For example, the transition project of ingress-operator is created to solve problems,

One of the design goals of the gateway api is isolation. The data plane is isolated, and the control plane is not isolated. This is a little contrary to the original design intent

Gateway-operator -> route controller + envoyproxy
