### ISSUE TITLE
ci: whitenoise broken

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#928]
===========> Running lint.whitenoise ... 
tools/bin/whitenoise
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

https://github.com/envoyproxy/gateway/actions/runs/3926974423/jobs/6713175184

**Comment by arkodg** [comment]
dup of https://github.com/envoyproxy/gateway/issues/523
