### ISSUE TITLE
Enhance status error messages for RateLimitFilter extension

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#938]
*Description*:

Enhance the error strings to provide more specific feedback to the user (that is presented in the  HTTPRoute `Status`) when the translator is unable to translate the fields within the `RateLimtitFilter` correctly in https://github.com/envoyproxy/gateway/blob/2a03c58a7de443da740f1ab9d86fed87237f637d/internal/gatewayapi/filters.go#L690

**Comment by zirain** [comment]
@arkodg is this fixed?

**Comment by arkodg** [comment]
yah
