### ISSUE TITLE
RateLimit: support more options about ratelimit infra 

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#947]
xref: https://github.com/envoyproxy/gateway/pull/939#discussion_r1090108422

**Comment by arkodg** [comment]
this issue relates to providing a way to change the default Envoy RateLimit image used, this maybe be a good idea for an edge case when this project is unable to keep up with containers releases from https://github.com/envoyproxy/ratelimit but we imho we can address this later if/when this situation arises.

**Comment by zirain** [comment]
users maybe not access dockerhub due to egress policy

**Comment by arkodg** [comment]
https://hub.docker.com/u/envoyproxy is specific, its an OSS account which is not subject to ratelimits
https://www.docker.com/community/open-source/application/

**Comment by zirain** [comment]
I'm not saying docker hub limitation, some users are allowed to use their own docker registry.

**Comment by arkodg** [comment]
ah @zirain that makes sense, thanks for the clarification

**Comment by zirain** [comment]
more thoughts about RateLimit:
1. `EG` already support a [full-managed RLS](https://github.com/envoyproxy/ratelimit) backend
1. should `EG` support user managed RLS?
    1. take care of RLS setting with a hook?
    1. users take care of RLS setting themself
 
cc @arkodg

**Comment by arkodg** [comment]
@zirain can you elaborate on 2 ?
are you referring to user managed envoy RLS deployment+service ?

**Comment by zirain** [comment]
> @zirain can you elaborate on 2 ? are you referring to user managed envoy RLS deployment+service ?

that's one option.
In our cases, there's a self implemented RLS(not build on envoy/ratelimit and redis) in the cluster, and we want reuse it.

![rls](https://user-images.githubusercontent.com/4354057/223886029-6d745432-a4f8-4635-a1ee-0c5e5d8a9052.PNG)

**Comment by arkodg** [comment]
got it, next q - how do you want the end user (using EG) to configure rate limit ?

**Comment by arkodg** [comment]
trying to first understand how RL limits config is provided to EG
1) [via EG RL API ](https://gateway.envoyproxy.io/v0.3.0/user/rate-limit.html)
2) [via some Patch Like API](https://github.com/envoyproxy/gateway/pull/24)
3) [via some Extension API](https://github.com/envoyproxy/gateway/pull/1074)

**Comment by zirain** [comment]
IMO, option2 is not a good idea, we're backing to `EnvoyFilter` way.
yes, option3 is good but heavy, I don't want to take care about listener and filter, `EG` does a good work.

**Comment by zirain** [comment]
> does your RLS respect this contract https://github.com/envoyproxy/go-control-plane/blob/main/ratelimit/config/ratelimit/v3/rls_conf.pb.go ?

they should, otherwise the ratelimit filter will not working, but maybe do not respect the configuration of `envoyproxy/RateLimit`

> hen we could add a managed/unmanaged option in where the unmanaged option configures the RLS server URL and
the RLS config (descriptor/limits) is pushed via xDS

bingo!

**Comment by arkodg** [comment]
@zirain can you elaborate on `they should, otherwise the ratelimit filter will not working, but maybe do not respect the configuration of envoyproxy/RateLimit` ?
The contract that MUST be respected here is https://github.com/envoyproxy/ratelimit#configuration

**Comment by zirain** [comment]
my mistake, they should respect [rls.proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto#envoy-v3-api-file-envoy-service-ratelimit-v3-rls-proto).

[rls_conf.pb.go](https://github.com/envoyproxy/go-control-plane/blob/main/ratelimit/config/ratelimit/v3/rls_conf.pb.go) is suggested, and not constraint. EG can use it when sending hooks request.

**Comment by arkodg** [comment]
> my mistake, they should respect [rls.proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto#envoy-v3-api-file-envoy-service-ratelimit-v3-rls-proto).
> 
> [rls_conf.pb.go](https://github.com/envoyproxy/go-control-plane/blob/main/ratelimit/config/ratelimit/v3/rls_conf.pb.go) is suggested, and not constraint. EG can use it when sending hooks request.

in this case (1) will not work, because EG cannot guarantee decision criteria of RLS, so would have to be implemented using (2) or (3)

**Comment by zirain** [comment]
I will show you with a prototype ASAP.

**Comment by arkodg** [comment]
fixed with https://github.com/envoyproxy/gateway/pull/1297
