### ISSUE TITLE
Add docs for External DNS Integration

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#953]
*Description*:
>Describe the issue.

Add docs for integrating External DNS and Gateway API resources
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gateway-api.md
under https://github.com/envoyproxy/gateway/tree/main/docs/latest/user
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment]
cc @ericgoode

**Comment by HoangTheQuyen** [comment]
What is the progressing current and upcoming status of this issue?

**Comment by arkodg** [comment]
@HoangTheQuyen needs help from the community to volunteer and drive it to completion

**Comment by arkodg** [comment]
addressed with https://github.com/envoyproxy/gateway/pull/1461
