### ISSUE TITLE
Edge Proxy Best Practices

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#96]
How should EG support best practices for running Envoy as an edge proxy?

xref: https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge

**Comment by youngnick** [comment]
I think that we should implement all of those best practices. We've done a lot of them in Contour (the page has been updated since I last looked), but they're all extremely good recommendations.

**Comment by zirain** [comment]
@danehans this need a  `help wanted`?

**Comment by arkodg** [comment]
closing in favor of https://github.com/envoyproxy/gateway/issues/1048 since @Xunzhuo already assigned himself to it
