### ISSUE TITLE
latest-release-check job is failing for latest commit

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#978]
*Description*:
Seeing the job failing in this CI workflow https://github.com/envoyproxy/gateway/actions/runs/4086874092/jobs/7046696271#step:7:1
when merging https://github.com/envoyproxy/gateway/pull/974
```
make[1]: *** [tools/make/lint.mk:87: latest-release-check] Error 1
[27](https://github.com/envoyproxy/gateway/actions/runs/4086874092/jobs/7046696271#step:7:28)
Latest install.yaml of eg is published with failures.
[28](https://github.com/envoyproxy/gateway/actions/runs/4086874092/jobs/7046696271#step:7:29)
make[1]: Leaving directory '/home/runner/work/gateway/gateway'
[29](https://github.com/envoyproxy/gateway/actions/runs/4086874092/jobs/7046696271#step:7:30)
make: *** [Makefile:18: _run] Error 2
[30](https://github.com/envoyproxy/gateway/actions/runs/4086874092/jobs/7046696271#step:7:31)
Error: Process completed with exit code 2.
```

**Comment by arkodg** [comment]
cc @Xunzhuo

**Comment by Xunzhuo** [comment]
I think this is normal like coverage reports uploading failed sometimes, When creating latest release, uploading latest artifacts will use GitHub APIs and they are not always working well, so the job fails sometimes. I think we should be aware of it by the checking latest release job, and retrigger it. And it may always solve this problem by re-run this job.

**Comment by arkodg** [comment]
@Xunzhuo I keep seeing the check to fail multiple times (~10-20%) , seen again here https://github.com/envoyproxy/gateway/actions/runs/4106358295/jobs/7084480277, should we just rm the check ?

**Comment by Xunzhuo** [comment]
IMHO, if we remove this but the uploading failed, we might not be aware of it. So before the next commit gets merged or latest release workflow runs, the latest release link might be broken. But if we keep this, we might just need to rerun the latest release workflow.

**Comment by danehans** [comment]
@Xunzhuo can you PTAL at this issue after v0.3.0. The recreate latest release job has been flaky due to the assets (install/quickstart.yaml) not being posted.

**Comment by arkodg** [comment]
errors out 2/5 times
<img width="1599" alt="Screenshot 2023-02-07 at 5 53 01 PM" src="https://user-images.githubusercontent.com/9469142/217408586-e4e236f1-acd1-42b1-90ea-dbf96ed5769d.png">

**Comment by Xunzhuo** [comment]
Thanks @arkodg, I will take a deep look after v0.3.0 :)

**Comment by AliceProxy** [comment]
Looks like this action is passing for all commits other than non-code updates (such as docs updates)

Green: https://github.com/envoyproxy/gateway/actions/runs/4376814980
Red: https://github.com/envoyproxy/gateway/actions/runs/4367565345

@Xunzhuo Are you still able to work on this one for 0.4.0? :slightly_smiling_face:

**Comment by Xunzhuo** [comment]
Not sure if it is related to non-code changes. Let me take a look after some higher priority issues.

**Comment by Xunzhuo** [comment]
May be fixed by https://github.com/envoyproxy/gateway/pull/1161

/close
