### ISSUE TITLE
Refactor authn and ratelimit features to reuse buildXdsCluster

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#979]
*Description*:
The ratelimit feature creates an xds cluster using https://github.com/envoyproxy/gateway/blob/4a04915e3f8b95ac54baeed6d42503324fb7af9b/internal/xds/translator/ratelimit.go#L267 and the authn feature creates an xds cluster using https://github.com/envoyproxy/gateway/blob/4a04915e3f8b95ac54baeed6d42503324fb7af9b/internal/xds/translator/authentication.go#L413

These features should instead be using the existing method to build an xds cluster defined here
https://github.com/envoyproxy/gateway/blob/4a04915e3f8b95ac54baeed6d42503324fb7af9b/internal/xds/translator/cluster.go#L22 so its easier to manage the intended cluster field values

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by sbko** [comment]
I'm going to work on this. Could you assign it to me?
