### ISSUE TITLE
Enable HTTPRouteRedirectPath conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#993]
*Description*:
Seeing this fail in https://github.com/envoyproxy/gateway/pull/780

Once fixed they should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by arkodg** [comment]
cc @AliceProxy

**Comment by arkodg** [comment]
tried to repro this locally, here are the error logs
```
=== CONT  TestGatewayAPIConformance/HTTPRouteRedirectPath/4_request_to_'/full-path-and-host'_should_receive_a_302
    http.go:186: Response expectation failed for request: {{http   127.0.0.1:80 /full-path-and-host  false false   }  HTTP GET map[X-Echo-Set-Header:[]] true [] [] }  not ready yet: expected redirected port to be 80, got  (after 28.075232404s)
Sending Request:
< GET /full-path-and-host HTTP/1.1
< Host: 127.0.0.1:80
< User-Agent: Go-http-client/1.1
< X-Echo-Set-Header: 
< Accept-Encoding: gzip
< 
< 

Sending Request:
< GET /path-and-host HTTP/1.1
< Host: 127.0.0.1:80
< User-Agent: Go-http-client/1.1
< X-Echo-Set-Header: 
< Accept-Encoding: gzip
< 
< 

Received Response:
< HTTP/1.1 302 Found
< Date: Thu, 09 Feb 2023 03:51:30 GMT
< Location: http://example.org/replacement-prefix
< Server: envoy
< Content-Length: 0
< 
< 
```

the issue seems to be with the way the conformance test is written, the `hostname` in the Filter is set to `example.org`
https://github.com/kubernetes-sigs/gateway-api/blob/e36b374652a6bcc56af5f9fa405c00e7bc478cc7/conformance/tests/httproute-redirect-path.yaml#L59
without explicitly setting the port in the hostname or setting a port redirect
but the conformance tests is basing the expectedPort off the input URL https://github.com/kubernetes-sigs/gateway-api/blob/e36b374652a6bcc56af5f9fa405c00e7bc478cc7/conformance/utils/http/http.go#L348

**Comment by arkodg** [comment]
also Gateway API defines the field as `hostname` (no port) https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRequestRedirectFilter but envoy defines the redirect API in terms of `host` https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-redirectaction

**Comment by arkodg** [comment]
might require enhancement in upstream https://github.com/envoyproxy/envoy/issues/17318#issuecomment-1424855021

**Comment by AliceProxy** [comment]
https://github.com/envoyproxy/gateway/issues/992#issuecomment-1462483018
