### ISSUE TITLE
Enable HTTPRouteMatching conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#995]
*Description*:
Seeing this fail in https://github.com/envoyproxy/gateway/pull/780

Once fixed they should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by danehans** [comment]
I see this test pass with GW API v0.6.0 when run locally.

**Comment by danehans** [comment]
I see this test fail in v0.6.1 due to these test [changes](https://github.com/kubernetes-sigs/gateway-api/commit/070a6b65bcdc6fbc85f69b4882de2569c9e477b7) upstream.
